remix-run/react-router

docs/api/components/Route.md
=> Add documentation for <Route ignoreScrollBehavior>

modules/__tests__/Router-test.js, modules/utils/createRouter.js
=> failing test for willTransitionFrom

docs/guides/overview.md
Explicit source of Router, Route, DefaultRoute in overview.md
I've only see one person run into this on StackOverflow, but it doesn't hurt to be explicit (we are dealing with react users, right?).
=> explicit source of variables in overview.md

docs/guides/overview.md
As I followed the overview instruction, I found the `require(...)` is not complete. Therefore, I added the corresponding dependencies in the docs.
=> Add missing dependencies in docs/overview.md.

.gitignore
this makes contributing easier imo
=> [added] node_modules to gitignore

docs/guides/overview.md
For readability and maintenance, I suggest composing like this. :)
=> change way of composing for readability and maintenance

docs/api/mixins/Navigation.md
=> Doc update Navigation example

docs/guides/overview.md
=> Added documentation for skipping dynamic segment transition optimization

modules/Navigation.js
Upgrade path: The goBack function now returns true (on successful back) or false (no react-router history to navigate back to), previously the return from goBack was always undefined.
=> [changed] Change Navigation to return the result of goBack()

examples/auth-flow/app.js
* Communicate the next transition
to the login form using query params
instead of statics.
* This style is more like server side
routing.
=> Use query params instead of statics to communicate the next transition

docs/api/components/DefaultRoute.md
This update simply removes the `<Routes/>` from here.
=> [fixed] Docs Update

docs/guides/overview.md
This PR fixes a very small typo in the overview guide.
=> small docs typo

docs/api/RouterContext.md, examples/animations/app.js, examples/auth-flow/app.js, examples/data-flow/app.js, examples/dynamic-segments/app.js, examples/master-detail/app.js, examples/query-params/app.js, examples/rx/app.js, examples/simple-master-detail/app.js, examples/transitions/app.js
Hey.
I assumed showing git diffs wasn't your point here so I removed them and also changed a few `func.isRequired` you missed into `func`.
=> Remove diffs in docs and update contexts in examples

modules/PropTypes.js
=> clarify warning message

docs/guides/overview.md
Document the `<Link params={user} />` functionality added in #231
=> Document Link param functionality

docs/guides/overview.md
Tiny swap to bring docs up to date.
Hey, it's something!
=> [changed] Update overview.md

docs/guides/flux.md
Not sure if I am missing some syntax here or get/set methods on a different version of node, but my impl required this tweak.
=> updated readme for flux action creator workarounds

README.md
the last one's size is not the same with others's
=> fix camo's size in README.md

website/styles.css
The documentation website is a pain to navigate on iOS otherwise
=> Adding momentum scrolling for iOS on Main div in website

examples/pinterest/app.js
based in the example it seems like this should be `RootRoute.indexRoute` instead of `RootRoute.defaultRoute`.
=> change to RootRoute.indexRoute

README.md
I'm presuming that's supposed to be 'really'.
=> Fix tiny spelling error in readme

.npmignore
=> remove babelrc from npm package

doc/00 Guides/0 Overview.md
Fixed semi-colon typo in docs example code
=> Fixed typo

doc/00 Guides/0 Overview.md
Branching on state instead of props.
=> Update 0 Overview.md

doc/00 Guides/0 Overview.md, examples/async-data/app.js, examples/huge-apps/app.js
Just so the examples are more consistent in that regard.
=> Removed parentheses after `new Hashhistory`

README.md
As per comment from @devknoll in https://github.com/rackt/react-router/issues/1362
=> Removed reference to indexComponent in README.md

UPGRADE_GUIDE.md, doc/00 Guides/Advanced Usage.md, doc/00 Guides/Server Rendering.md, doc/02 Components/Route Component.md, doc/03 History/MemoryHistory.md
=> It's, its', its.

package.json
includes https://github.com/r3dm/warning/pull/2 for browserify builds
=> update to warning@^2.0.0

examples/auth-flow/app.js
Fixes  'this' is not allowed before super() error when running examples
=> Add missing super() call

modules/index.js
Pretty self-explanatory.
Btw, almost done with the rewrite for Redux React Router based on the changes in latest beta and it's working great :)
=> Export RoutingContext

modules/__tests__/isActive-test.js, modules/isActive.js
this fixes #1561 
@ryanflorence could you give some feedback on this diff? is that the behaviour we want?
=> fix isActive, makes the root URL active only if it is a parent route

package.json
Updates `karma` to 0.13.9. Resolves Issue #1855.
=> Upgrade karma to 0.13.9 in the 0.13.x branch

docs/README.md
=> Docs: fix broken Server Rendering page link

UPGRADE_GUIDE.md
Just some minor grammar fixes. This is an absolutely fantastic upgrade guide, thanks for all your hard work!
**Edit**: Looks like the "Thanks" fix is in the other open PR, but the rest are new.
=> Grammar fixes in upgrade guide

README.md, UPGRADE_GUIDE.md, docs/introduction/README.md
Woops, looks like I accidentally re-inserted the semicolons in the code snippets that MJ had already removed earlier today. My bad.
=> Removing semicolons

UPGRADE_GUIDE.md, docs/basics/Histories.md
These two things caught me out with the upgrade path so I thought I would send through a PR. You will likely want to add more context but adding both of these to your documentation would help someone trying to convert everything over/set up a new project.
=> Update Documentation to make migration easier.

UPGRADE_GUIDE.md
Hello, I think this is component instead of handler, or maybe I misunterstood something. :O
=> Fix typo in upgrade guide

examples/index.html, examples/nested-animations/app.css, examples/nested-animations/app.js, examples/nested-animations/index.html
Based on https://github.com/rackt/react-router/pull/1226.
I've updated the code to use the latest API / code style, it should be good to go now :rocket:
=> Add an example of animating both parent and nested routes – Rewritten for 1.0

examples/huge-apps/app.js
I love the huge-apps example. It gives a good idea about building applications larger than the standard todo list. The recursive directory call was easy to understand but I got a lot more value from unrolling the loop to see just what this looks like all put together.
=> add comment showing the unrolled loop of the huge-apps Router

docs/advanced/DynamicRouting.md
Have updated the documentation to reference the correct method arguments for getComponents in DynamicRouting
=> 1.0.0-rc1 Documentation for DynamicRouting incorrect #1927

webpack.config.js
=> remove repeated "loose=all"

README.md, doc/README.md, docs/guides/README.md
Related to doc updates in #1959.
=> Add link to guides w/ table of contents

examples/auth-flow/app.js
removed the boolean typecasting to dry up the code since the parameter passed will be a booelan
=> dry up auth-flow example code

modules/__tests__/IndexLink-test.js
no fix yet, just a failing test
=> failing test case

docs/Introduction.md
=> Fix typo: <Links>s to <Link>s

modules/Link.js
"active" class is not default anymore. doc should state that.
=> update activeClassName definition

docs/guides/basics/RouteMatching.md
Reverts rackt/react-router#2214
=> Revert "[Docs] Add path syntax example"

package.json
* Set `history` peer dep to minor version needed by react-router core
See also: https://github.com/rackt/react-router/pull/2258#issuecomment-147937726
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/rackt/react-router/2268)
=> Update `history` peer dep to `^1.12.0`

examples/animations/app.js, examples/nested-animations/app.js, package.json
Just fixed the animation examples to reference the correct dependency.
=> fixed deps for animation and nested animation examples

README.md
=> Link to the full examples in README

README.md
Fixes https://github.com/rackt/react-router/issues/2300
=> Added a UMD example

UPGRADE_GUIDE.md
Discussion here: https://github.com/rackt/react-router/issues/2324#issuecomment-149710600
=> Add note re: propTypes + React.cloneElement in upgrade guide

examples/auth-with-shared-root/app.js, examples/auth-with-shared-root/components/About.js, examples/auth-with-shared-root/components/App.js, examples/auth-with-shared-root/components/Dashboard.js, examples/auth-with-shared-root/components/Landing.js, examples/auth-with-shared-root/components/Login.js, examples/auth-with-shared-root/components/Logout.js, examples/auth-with-shared-root/components/PageOne.js, examples/auth-with-shared-root/components/PageTwo.js, examples/auth-with-shared-root/components/User.js, examples/auth-with-shared-root/config/routes.js, examples/auth-with-shared-root/index.html, examples/auth-with-shared-root/utils/auth.js, examples/index.html
Demonstrates partial/lazy loading with auth and dynamic routes
See PR #1947
=> Add auth-with-shared-root example

docs/Introduction.md
It took me some time to understand what happens, and I updated the page so the explanation is more clear (at least for me). Feedback is welcome :)
=> Introduction change to explain nesting using JSX.

modules/RoutingContext.js, modules/__tests__/RouteComponent-test.js
=> [added] params on RoutingContext child context

modules/__tests__/.eslintrc, modules/__tests__/History-test.js, modules/__tests__/IndexLink-test.js, modules/__tests__/IndexRedirect-test.js, modules/__tests__/IndexRoute-test.js, modules/__tests__/Link-test.js, modules/__tests__/PatternUtils-test.js, modules/__tests__/Redirect-test.js, modules/__tests__/RouteComponent-test.js, modules/__tests__/Router-test.js, modules/__tests__/createRoutesFromReactChildren-test.js, modules/__tests__/formatPattern-test.js, modules/__tests__/getParamNames-test.js, modules/__tests__/getParams-test.js, modules/__tests__/isActive-test.js, modules/__tests__/matchRoutes-test.js, modules/__tests__/pushState-test.js, modules/__tests__/serverRendering-test.js, modules/__tests__/transitionHooks-test.js
wdyt?
Seems a pain to have to define those ESLint overrides for every test module.
=> Consolidate test ESLint overrides

docs/guides/advanced/ServerRendering.md
See http://expressjs.com/4x/api.html for more info.
=> Fix Express deprecated usage warning

README.md
=> Point users away from issue tracker for support

modules/__tests__/transitionHooks-test.js, modules/computeChangedRoutes.js
=> [changed] Query changes aren't route changes

docs/guides/advanced/ComponentLifecycle.md
Use code blocks in tables for Lifecycle Hooks
=> Update ComponentLifecycle docs

.babelrc, package.json
50434 -> 49406 bytes on minified bundle
=> Use dev-expression Babel plugin

modules/Link.js, modules/__tests__/AsyncUtils-test.js, modules/__tests__/Router-test.js
=> Improve coverage

README.md, karma.conf.babel.js
- Build status usually goes before npm version (see e.g. https://github.com/facebook/react)
- There is virtually no activity on IRC and it feels wrong to direct people there
=> Update badges on README

UPGRADE_GUIDE.md
Okay fine I also threw in an unrelated copy-editing change a few lines up. Sorry!
=> Point to scroll-behavior for scroll behaviors

docs/API.md
=> explain what `this` refers to in `onEnter` hooks

README.md, docs/README.md
=> Fix upgrade guide links

index.html
Reverts rackt/react-router#2529
=> Revert "Point to v1.0.0 docs instead of master docs"

CHANGES.md, docs/API.md, modules/Router.js, modules/__tests__/Router-test.js
Reverts rackt/react-router#2507
=> Revert "Pass route state to onUpdate callback"

modules/__tests__/Router-test.js
Follow-up to https://github.com/rackt/react-router/pull/2540
=> Fix using this before super

docs/API.md
=> Clarify getIndexRoute example

docs/API.md
Doc notes around scroll position management not being currently handled by react-router.
Closes #2605
=> Hash documentation update concerning scroll management.

package.json
ESLint fails sporadically with the old babel-eslint
=> Update babel-eslint dependency

modules/Link.js, modules/__tests__/Link-test.js
Re-made from https://github.com/rackt/react-router/pull/2658.
Tests will fail until https://github.com/rackt/history/pull/173 is merged and released.
Codemod: https://github.com/rackt/rackt-codemod/pull/5.
I'm still using `context.history` here - we could potentially merge this and release it before the API changes to get rid of the deprecation warnings for users, per https://github.com/rackt/history/issues/172#issuecomment-162336396.
I'm going to be extremely busy over the next week and a half or so, and someone else might have to shepherd this to release (docs, changelog, &c.), which is why this branch is on the main repo instead of my personal fork.
=> Update <Link> to just call push

docs/guides/advanced/ComponentLifecycle.md
=> update lifecycle doc

modules/History.js, modules/Lifecycle.js, modules/Link.js, modules/RouteContext.js, modules/Router.js, modules/RouterContext.js, modules/RouterUtils.js, modules/RoutingContext.js, modules/createTransitionManager.js
These are editable, so we can avoid breakage if there are edits to the upgrade guide in the future.
=> Update links to tiny.cc

examples/pinterest/app.js
The `state` prop is deprecated in v2.
=> Update pinterest example

modules/useRouterHistory.js
=> add warning for new replaceState location param

package.json
=> Update history dependency

.travis.yml, karma.conf.js
Firefox and Chrome were really old and auto-update now.
Also, iOS 9 and 8 distribution is high, so they should be tested too. Also bumped up Safari and used Windows 10 where possible.
=> Update our tested browsers

modules/Link.js, modules/__tests__/Link-test.js
=> Fix handling of Link location descriptors

docs/Troubleshooting.md
This is a common occurrence. Reordering the routes fixes this issue.
I made it a little more verbose for clarity sake. Happy to adjust based on feedback.
Part of #2933 
/cc @timdorr
=> docs: Add unreachable routes troubleshooting

docs/Troubleshooting.md
=> Troubleshooting information about this.context.router

modules/createTransitionManager.js, modules/match.js, package.json
Fixes https://github.com/rackt/react-router/issues/2859
The tests won't pass until https://github.com/rackt/history/pull/200 is merged and released.
=> Use history.createLocation where possible

docs/guides/advanced/ServerRendering.md, upgrade-guides/v2.0.0.md
Hopefully this improves on #2992. Suggestions welcome!
Thanks for keeping an eye on this kind of stuff, @ryanflorence!
=> Add back singleton example and add a blurb about them in SSR docs.

docs/API.md
=> Fix Index Routes guide urls

docs/guides/RouteConfiguration.md
I know we show, that in the example above but maybe it's hard to find while searching the repo or docs.
=> [docs] add explicit example on how to redirect using plain routes

docs/API.md, docs/guides/IndexRoutes.md, docs/guides/RouteConfiguration.md
This includes proper `<IndexRedirect>` documentation.
=> Improve redirect docs

modules/Link.js, modules/RouteUtils.js, modules/RouterContext.js, modules/createTransitionManager.js, modules/getRouteParams.js, modules/isActive.js, modules/matchRoutes.js
=> Fix calls to hasOwnProperty

package.json
For folks that need to use the UMD build, it would be nice if there was a build that included the warnings that folks could use during development.
=> Add UMD module with developer warnings

docs/API.md, docs/guides/Histories.md
- Add information about included enhancers
- Improve example to make it clear the factory comes from the history
package
- Document usage of useRouterHistory on histories page, with examples
regarding usage with options and other enhancers
=> Improve docs for useRouterHistory

upgrade-guides/v2.0.0.md
Since use of [scroll-behavior](https://github.com/taion/scroll-behavior) is so popular, maybe show an example of how to upgrade it in the v2.0.0 upgrade guide.
=> Show Scroll Behavior upgrade example.

.travis.yml, karma.conf.js, modules/__tests__/_bc-History-test.js, modules/__tests__/_bc-Link-test.js, modules/__tests__/_bc-Router-test.js, modules/__tests__/_bc-isActive-test.js, modules/__tests__/_bc-serverRendering-test.js, modules/__tests__/_bc-transitionHooks-test.js, modules/__tests__/matchRoutes-test.js, modules/__tests__/shouldWarn.js, modules/__tests__/transitionHooks-test.js, tests.webpack.js
Easier all around just to have one test run that includes backward compat and just asserts what warnings should be there.
=> Assert on specific warnings in tests

examples/huge-apps/components/App.js, examples/huge-apps/components/Dashboard.js, examples/huge-apps/components/GlobalNav.js, examples/huge-apps/routes/Calendar/components/Calendar.js, examples/huge-apps/routes/Course/components/Course.js, examples/huge-apps/routes/Course/components/Dashboard.js, examples/huge-apps/routes/Course/components/Nav.js, examples/huge-apps/routes/Course/routes/Announcements/components/Announcements.js, examples/huge-apps/routes/Course/routes/Announcements/components/Sidebar.js, examples/huge-apps/routes/Course/routes/Announcements/routes/Announcement/components/Announcement.js, examples/huge-apps/routes/Course/routes/Assignments/components/Assignments.js, examples/huge-apps/routes/Course/routes/Assignments/components/Sidebar.js, examples/huge-apps/routes/Course/routes/Assignments/routes/Assignment/components/Assignment.js, examples/huge-apps/routes/Course/routes/Grades/components/Grades.js, examples/huge-apps/routes/Messages/components/Messages.js, examples/huge-apps/routes/Profile/components/Profile.js
Replaced React.component with component.
=> Picky fix on ES6 syntax

modules/PatternUtils.js, modules/__tests__/_bc-Link-test.js, modules/__tests__/_bc-isActive-test.js, modules/__tests__/isActive-test.js, modules/__tests__/matchPattern-test.js, modules/__tests__/serverRendering-test.js, modules/isActive.js, modules/matchRoutes.js
This is a redo of #3158, with taion/rrtr#8 applied as well.
=> Support trailing slashes, not extraneous ones

CHANGES.md, modules/__tests__/Router-test.js, modules/getComponents.js
=> Fix this in getComponent and getComponents

scripts/release.sh
This is finally fixed on npm 3.8.7 and higher
=> Remove workaround for npm bug with history

package.json
=> Set up peer dependency on React

.babelrc
This doesn't do anything right now, but might avoid problems later.
=> stage-0 belongs after es2015

docs/API.md
Documentation change for API.md
=> Documentation change

package.json
=> Make scripts runnable on Windows

examples/index.html
No functional changes, just better html.
=> Fix html structure for examples index.html

docs/guides/ConfirmingNavigation.md
I had to search the repo to find information about this. A link would've been nice!
=> Add link to withRouter HoC in ConfirmingNavigation docs

modules/__tests__/shouldWarn.js, tests.webpack.js
This doesn't change any behavior. It just syncs up the logic to the
latest that I have elsewhere.
=> Update helpers for warning messages

modules/components/Link.js
I figure why not... I dunno. I like not seeing test warnings before publishing. ¯\\\_(ツ)_/¯
I'm just going to merge this because it's the old dead branch and who cares.
=> Fix extra props on <Link> in 0.13 branch

CODE_OF_CONDUCT.md
Whatever our thoughts on the contributor convenant, we should at least update to the latest version.
=> Update CoC version

docs/guides/NavigatingOutsideOfComponents.md
I have been searching in the tutorials and guides but unable to find the instruction on how to navigate back to the previous page. I hope this addition will help more users.
=> Add instruction on navigating back to previous page

docs/API.md
Aside: I do everything except for changelog updates in PRs on all my repos out of habit. If PRing trivial stuff like this is too spammy, I'll stop.
I'm going to merge this once CI passes and ship alpha.3.
=> Add docs for function to on <Link>

tools/es2015Preset.js
=> Make code work on Node 4

docs/API.md, docs/Glossary.md
=> Fix broken link to location descriptor reference

docs/API.md, docs/Glossary.md, docs/Introduction.md, docs/Troubleshooting.md, docs/guides/ComponentLifecycle.md, docs/guides/ConfirmingNavigation.md, docs/guides/DynamicRouting.md, docs/guides/Histories.md, docs/guides/IndexRoutes.md, docs/guides/MinimizingBundleSize.md, docs/guides/NavigatingOutsideOfComponents.md, docs/guides/RouteConfiguration.md, docs/guides/RouteMatching.md, docs/guides/ServerRendering.md, docs/guides/Testing.md, upgrade-guides/v1.0.0.md, upgrade-guides/v2.0.0.md, upgrade-guides/v2.2.0.md, upgrade-guides/v2.4.0.md, upgrade-guides/v2.5.0.md
=> Improve syntax highlighting in docs

docs/guides/ServerRendering.md
fix a missing replacement in commit https://github.com/reactjs/react-router/commit/759b4b1543de9e912c3188519fb20ad656b5feae
=> Replace jsx with js to correctly highlight code

modules/createTransitionManager.js, modules/match.js
Only need to create the location in match.
Fixes #3807
=> Fix redirects

website/pages/quick-start.md
This example imports the render method, not reactDOM
=> Update to use render()

website/pages/quick-start.md
Using #root because that is what create-react-app gives by default
=> Add dom element to render App to

website/pages/quick-start.md
I'm pretty sure this was the intended phrasing.
=> Small phrasing change

modules/index.js
Does this need to be added to the docs too?
=> Add propTypes export (#3898)

docs/index.html
https://react-router-website-xvufzcovng.now.sh/ redirects to https://react-router.now.sh/
=> docs(website): updated the website address

modules/ServerRouter.js, website/api/ServerRouter.md
Adds the `basename` as a documented prop of the `<ServerRouter>`
=> ServerRouter basename prop

modules/__tests__/LocationUtils-test.js
Basic tests for the `createRouterLocation` and `createRouterPath` functions.
=> LocationUtils tests

website/examples/Miss.js, website/examples/Sidebar.js
Remove some code that is no longer necessary
=> v4 Cleanup examples

modules/BrowserRouter.js
This one is a no-brainer. I couldn't pass `getUserConfirmation` down, found this typo.
=> fix createBrowserHistory API call

modules/Link.js
These don't appear to be supported any more
=> Remove references to Link hash/query/state props

README.md
=> [v4] Update README.md api and example doc links

packages/react-router/package.json
=> Fix missing StaticRouter

packages/react-router-dom/modules/NavLink.js
I try use NavLink and found `isActive` error that `history` is undefined.
I think may NavLink is not public yet. 
If this PR is unnecessary, please close it.
=> Fix NavLink location variable

packages/react-router-dom/modules/__tests__/NavLink-test.js
Verifies that `activeStyle` and `activeClassName` work.
=> NavLink tests

README.md
Not sure if you guys want this in README, but thought it is a good idea to reference npm installation instructions
=> Add installation refference

lerna.json, package.json, packages/react-router-native/package.json, packages/react-router-website/package.json
=> Hoist devDeps with Lerna

README.md
I hope a PR for this is alright. :)
=> Tiny grammar/spelling fix in v4 readme

.gitignore
=> add npm-debug.log to .gitignore

packages/react-router-dom/modules/__tests__/NavLink-test.js
Added tests to ensure that the `exact` and `strict` props style active as expected.
Also simplified the `isActive` tests.
=> NavLink exact & strict tests

packages/react-router-website/modules/api/Installation.md
Everything is in this PR title - colons were missing in the installation docs
=> Add missing commas in imports in installation docs

packages/react-router/modules/Switch.js, packages/react-router/modules/__tests__/Switch-test.js
First commit is a test that fails if you check out that SHA. Next commit will be a fix that comes with a behavior change.
Fixes #4578
=> Reuse components in Switch

README.md
fixes https://github.com/ReactTraining/react-router/issues/4613
=> Note v2, v3 api docs

packages/react-router/docs/blocked-updates.md
Add a guide to explain why components are not updating after navigation.
A rough draft, but I think that it conveys the idea well.
=> Add guide for dealing with sCU

CHANGES.md, packages/react-router-dom/docs/api/NavLink.md, packages/react-router-dom/modules/__tests__/NavLink-test.js, packages/react-router/docs/guides/blocked-updates.md
Related to https://github.com/ReactTraining/react-router/pull/4623
=> Update docs, tests, changes with NavLink's default activeClassName

packages/react-router/docs/guides/blocked-updates.md
A little bit of rewording and also mention `PureComponent`.
=> Tweak blocked updates guide

packages/react-router/docs/api/history.md
Just noticed the lack of space here :smile:
=> space in history docs

packages/react-router-redux/package.json
5.0.0-alpha.2 (react-router-redux)
Not sure how to test an npm pack
1. ` npm install react-router-redux@next`
2. include in project
Run without breaking
ERROR in ./~/react-router-redux/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./actions in /Users/joshfurie/hero.client/node_modules/react-router-redux
@ ./~/react-router-redux/index.js 21:15-35
ERROR in ./~/react-router-redux/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./middleware in /Users/joshfurie/hero.client/node_modules/react-router-redux
@ ./~/react-router-redux/index.js 70:18-41
=> missing files in package.json

packages/react-router/docs/api/withRouter.md
Pinging off of #4676, this PR improves documentation and directly links the post that was mentioned by @pshrmn. It also includes some example code to help new users understand the issue and mitigate blocking updates.
=> Adding documentation to explain blocking updates using withRouter

packages/react-router/docs/api/StaticRouter.md
Make it a little bit clearer what `<StaticRouter context>` is for and link to the server rendering guide.
=> Expand on <StaticRouter context> documentation

packages/react-router-dom/modules/NavLink.js, packages/react-router-dom/modules/__tests__/NavLink-test.js
=> Add location property to NavLink

packages/react-router-native/Link.js
=> [native] <Link> doesn't pass own props to child component

README.md
react-router alt on logo was.... babel, just fixed it :)
=> Fix react-router alt text

packages/react-router/docs/guides/migrating.md
This is very basic, but hopefully can provide some footing for a developer before they begin to migrate an application.
I'll probably add a couple more commits to this with some more details, but ideally other people could expand on this as well.
=> Basic migration guide

packages/react-router/docs/guides/blocked-updates.md
BlockerAvoider -> BlockAvoider
=> small typo fix

packages/react-router-redux/README.md
documentation missing npm install --save history
=> added npm install history package

packages/react-router-dom/docs/api/NavLink.md, packages/react-router/docs/api/Route.md, packages/react-router/docs/api/Switch.md
=> Updates documentation of Switch, NavLink, Route

FAQ.md
I haven't seen this question lately, but it comes up occasionally, so it might be useful to add to the FAQ.
=> [FAQ] Pass props to component rendered by <Route>

FAQ.md
This is another usage question that pops up in issues fairly frequently.
=> [FAQ] How to access history outside of components

packages/react-router/docs/guides/migrating.md
May be helpful for some, I didn't really find it too apparent offhand without searching the issues first on how to do it.
=> Add notes on how to migrate from using IndexRedirect

packages/react-router/docs/api/location.md
Adjust the `Switch` link target.
=> docs(location): fix switch link

packages/react-router/README.md
Add a note for those that are unaware.
=> Add install note to react-router README

packages/react-router/package.json
Change log
https://github.com/mridgway/hoist-non-react-statics/releases/tag/v2.0.0
=> Bump hoist-non-react-statics

packages/react-router/docs/guides/migrating.md
=> Reveal lack of empty to prop in v4 Link in migration guide

packages/react-router-dom/docs/api/Link.md, packages/react-router-native/docs/api/Link.md
Fixes #5372. I also tweaked the description of the string version.
=> Correct Link location property description in docs

packages/react-router/docs/api/Router.md
=> Fix memory and static router links on website

packages/react-router/docs/api/Route.md
use `prop` instead of `attribute` in route component
=> use `prop` instead of `attribute`

packages/react-router/docs/api/Route.md
precedence has been written incorrectly.
=> there is a typo

packages/react-router-redux/README.md
=> Update react-router-redux readme to reflect versioning situation.

website/modules/docs/Web.js
=> fix: wrong path of require

website/package-lock.json
I'm not sure why/how, but #5516 (my own PR :man_facepalming:) broke the `package-lock.json` for the website by including a missed merge conflict.
=> Fixes bad package-lock file

packages/react-router/docs/api/Redirect.md
=> Add 'exact' & 'strict' props to redirect api doc.

packages/react-router-redux/modules/ConnectedRouter.js
make 'history' the required prop of ConnectedRouter
=> react-router-redux: update propTypes

packages/react-router-redux/modules/ConnectedRouter.js, packages/react-router-redux/modules/__tests__/ConnectedRouter-test.js
I'm afraid that an important number of bugs where introduced by #5203.
I got hit hard by one of those, this PR adds a test reproducing my issue and what I think it's the best solution to fix it.
=> [FIX]: Redirect on mount issue

website/modules/examples/Params.js
Related to https://github.com/ReactTraining/react-router/issues/391 and this example https://github.com/ReactTraining/react-router/issues/391#issuecomment-294237556
=> Example with regex in path

LICENSE
Update copyright year to include 2018
=> Update Copyright Year

packages/react-router/docs/guides/migrating.md
=> Document v3 <Redirect> query string behavior

packages/react-router-dom/docs/api/BrowserRouter.md, packages/react-router-dom/docs/api/HashRouter.md, packages/react-router-dom/docs/api/Link.md, packages/react-router-dom/docs/api/NavLink.md, packages/react-router-dom/docs/guides/basic-components.md, packages/react-router-dom/docs/guides/code-splitting.md, packages/react-router-dom/docs/guides/server-rendering.md, packages/react-router-native/docs/api/BackButton.md, packages/react-router-native/docs/api/DeepLinking.md, packages/react-router-native/docs/api/Link.md, packages/react-router-native/docs/api/NativeRouter.md, packages/react-router-native/docs/guides/animation.md, packages/react-router-redux/README.md, packages/react-router/docs/api/MemoryRouter.md, packages/react-router/docs/api/Prompt.md, packages/react-router/docs/api/Redirect.md, packages/react-router/docs/api/Route.md, packages/react-router/docs/api/Router.md, packages/react-router/docs/api/StaticRouter.md, packages/react-router/docs/api/Switch.md, packages/react-router/docs/api/history.md, packages/react-router/docs/api/withRouter.md, packages/react-router/docs/guides/blocked-updates.md, packages/react-router/docs/guides/migrating.md, packages/react-router/docs/guides/testing.md
```jsx
<Because this="looks better than" />
```
```js
<This does />
```
=> Markup JSX in docs

packages/react-router/docs/api/Router.md
Reverts ReactTraining/react-router#5911
=> Revert "Fix non-functional links to routers"

packages/react-router/docs/api/Redirect.md
this was hard to use without this extra note
=> Note on accessing location.state in Redirect docs

website/modules/examples/RouteConfig.js
the `Main`  component is not used
=> remove component not used

packages/react-router/docs/guides/blocked-updates.md
=> Correct the false `UpdateBlocker` in docs

packages/react-router-dom/modules/Link.js
if target is _self act as target is falsy
=> Link should work with target="_self"

package-lock.json, package.json, packages/react-router-config/rollup.config.js, packages/react-router-dom/.size-snapshot.json, packages/react-router-dom/rollup.config.js, packages/react-router/.size-snapshot.json, packages/react-router/rollup.config.js
Ref https://github.com/ReactTraining/react-router/issues/6393
=> Reduce bundle size by making dependencies external

packages/react-router/docs/api/matchPath.md
Was going through the docs and found this misalignment.
=> Align properties

packages/react-router/modules/StaticRouter.js, website/modules/components/FakeBrowser.js
Refactor ...props to ...rest StaticRouter and FakeBrowser for consistency over code.
=> Refactor variables naming  

packages/react-router/docs/api/generatePath.md, website/modules/docs/Core.js
I've created PR. Let me know if something should be changed.
Any comments are appreciated. 👨‍💻
=> Document generatePath function

packages/react-router-native/examples/Ambiguous.js, packages/react-router-native/examples/Auth.js, packages/react-router-native/examples/NoMatch.js, packages/react-router-native/examples/Recursive.js, packages/react-router-native/examples/RouteConfig.js
files:
Ambiguous.js
Auth.js
NoMatch.js
Recursive.js
RouteConfig.js
=> Remove unused import (example directory)

website/modules/base.css
I cleaned up the commit in my previous PR #6448
=> fixed glitch in doc #6426

CONTRIBUTING.md
Removes outdated "hacking" section. Fixes #6460.
=> Remove "hacking" section from CONTRIBUTING.md

packages/react-router-native/docs/guides/animation.md
First off, thanks for the in-depth docs! Saw this while reading the bit on animations 👍
=> Fix typo in animation snippet

website/modules/base.css
=> Fixes offset for sample code

packages/react-router-dom/modules/Link.js
Hello @pshrmn 👋 quick fix for the tests
=> Adds missing "const" keyword to Element

packages/react-router-dom/modules/__tests__/Link-test.js
Added unit tests for the onClick handler of ```Link```.
I noticed that there was no test for that at all when I looked at the coverage report.
=> Wrote event handling tests for Link.

packages/react-router/docs/api/matchPath.md
I've added 2 simple examples of the matchPatch return values. It was not clear what to expect.
=> Update matchPath docs

.huskyrc.js, package-lock.json, package.json
keeps `package.json` light ...
=> use huskyrc file

.github/support.yml
=> Added on to the support comment.

packages/react-router/docs/api/Route.md
=> Fix a description mistake in the `Route.md`

packages/react-router-dom/modules/NavLink.js, packages/react-router-dom/modules/__tests__/NavLink-test.js
This is a fix for (#6862). I also added a test so this issue doesn't happen again.
=> NavLink - pass currentLocation to isActive prop (#6862)

packages/react-router-config/README.md
and I just added `getDerivedStateFromProps` to `react-router-config/README.md`, based on this [blog post at reactjs.org](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data-when-props-change) 😉
=> use getDerivedStateFromProps instead of componentWillReceiveProps

website/modules/examples/Recursive.js
params.id comes back as string when you navigate
=> Fix recursive example

packages/react-router/docs/api/hooks.md
This resolves the issue from https://github.com/ReactTraining/react-router/issues/6974
=> Updated examples to fix breaking layout

packages/react-router/docs/api/Route.md
wanted to clarify the behavior seen here: https://codesandbox.io/s/sleepy-hopper-bgntr
=> explain same component in multiple routes

website/modules/base.css
fix style bug that mentioned #7003.
for review you should first build be the website.( build fix #7025 )
=> fix(#7003): style collapse on 1350px view

packages/react-router-dom/docs/guides/quick-start.md
As suggested in [CRA Readme](https://github.com/facebook/create-react-app#quick-overview) and to avoid [warnings related](https://stackoverflow.com/questions/59188624/template-not-provided-using-create-react-app)
=> Replace npm -g with npx

package.json, scripts/builds/react-router-dom.js, scripts/builds/react-router-native.js, scripts/builds/react-router.js, yarn.lock
Updates filesize tracker and closure compiler plugins to latest version.
=> Re-enable closure compiler

packages/react-router-dom/modules/__tests__/static-link-test.js, packages/react-router-dom/modules/server.js
=> Fix a crash when <Link /> was used within <StaticRouter />

docs/advanced-guides/migrating-5-to-6.md
=> Document v5 to v6 migration from go/goBack/goForward

packages/react-router-dom/docs/api/Link.md
Documented the existence of the `component` prop and gave an example illustrating how to use it
=> Add documentation for component prop

packages/react-router/docs/guides/testing.md
=> [docs] Missing tag

docs/advanced-guides/migrating-5-to-6.md
https://twitter.com/garand/status/1256333598338150401
=> Update install snippet to reference @next

docs/advanced-guides/migrating-5-to-6.md
=> Add documentation for moving the `basename`

packages/react-router-dom/modules/BrowserRouter.js, packages/react-router-dom/modules/HashRouter.js, packages/react-router-native/BackButton.js, packages/react-router-native/DeepLinking.js, packages/react-router-native/Link.js, packages/react-router-native/experimental/StackRoute.js, packages/react-router-native/experimental/TabRoutes.js, packages/react-router-native/index.android.js, packages/react-router/modules/Lifecycle.js, packages/react-router/modules/MemoryRouter.js, packages/react-router/modules/Route.js, packages/react-router/modules/Router.js, packages/react-router/modules/StaticRouter.js, packages/react-router/modules/Switch.js
Reverts ReactTraining/react-router#7258
=> Revert "perf: Use PureComponent to avoid useless re-renders (fixes #7248)"

packages/react-router-native/experimental/StackRoute.js, packages/react-router/modules/__tests__/Route-test.js
Reverts ReactTraining/react-router#7259
=> Revert "chore: Replace deprecated "componentWillMount" with "componentDidMount""

packages/react-router/index.tsx
This PR adds the usage of the ts type record to make the types more concise.
=> Use ts record type

packages/react-router/modules/index.js
the test has passed the rollup packaging mechanism!
=> unified module export style

packages/react-router/modules/Route.js, packages/react-router/modules/Router.js, packages/react-router/modules/hooks.js
minor changes to the Route.js and Router.js files
=> minor changes to the Route.js and Router.js files

packages/react-router/modules/Router.js
=> Fix a low miss from f20cd62

website/modules/base.css
Minor h2 header alignment issue fixed.
Actual:
After fix (local screenshot):
=> fix for issue #7472: minor header alignment issue in the website

packages/react-router-dom/examples/Auth.js
Problem:
In the original example, `AuthButton` component always shows `<p>You are not logged in.</p>` regardless of auth state.
Solution:
Add auth provider so all components are aware of auth state and rerender when auth state changes.
Big thanks Gabe Ragland (https://usehooks.com/useAuth/) for `useAuth` hook example and awesome detailed article. 
Code sandbox with changes in this PR: https://codesandbox.io/s/react-router-redirects-auth-2u39q
=> chore(docs): fixes bugs with auth example

packages/react-router/docs/api/Redirect.md
Use double quotes instead of single quotes to make it the same style as other exmaple code blocks.
=> Update example code style

packages/react-router-dom/docs/api/BrowserRouter.md, packages/react-router/docs/api/MemoryRouter.md, packages/react-router/docs/api/StaticRouter.md
=> Added React.Fragment into BrowserRouter.md, MemoryRouter.md and StaticRouter.md.

packages/react-router/__tests__/useParams-test.js, packages/react-router/index.tsx
=> Do not replace + with ' '

docs/advanced-guides/migrating-5-to-6.md, docs/advanced-guides/migrating-reach-to-6.md, docs/advanced-guides/testing/README.md, docs/advanced-guides/working-with-the-search-string.md, docs/api-reference.md, docs/faq.md, docs/installation/add-to-a-website.md, docs/installation/getting-started.md, package.json, packages/react-router/__tests__/utils/renderStrict.tsx, packages/react-router/index.tsx, scripts/rollup/index.js, scripts/rollup/react-router-dom.js, scripts/rollup/react-router-native.js, scripts/rollup/react-router.js, yarn.lock
- ESLint and all related dependencies updated
- Prettier updated
- Ran `prettier . --write` to reduce potential formatting issues in later commits
Unless I commented on a change, it came from `prettier . --write`.
=> Update ESLint + Prettier

packages/react-router-dom/examples/Animation/index.js
=> Fix animated transition example bug

packages/react-router-native/__tests__/deep-linking-test.tsx, packages/react-router/__tests__/navigate-test.tsx, packages/react-router/__tests__/useResolvedPath-test.tsx, packages/react-router/index.tsx
=> Normalize search + hash strings in `resolvePath`

packages/react-router-dom/__tests__/link-href-test.tsx, packages/react-router/index.tsx
=> fix: Absolute paths in nested routes

docs/advanced-guides/migrating-5-to-6.md, docs/api-reference.md, packages/react-router/__tests__/useRoutes-test.tsx, packages/react-router/index.tsx
Thanks @MeiKatz for the great suggestion!
=> Update  `useRoutes` API to accept an object as second param

packages/react-router/__tests__/navigate-test.tsx, packages/react-router/index.tsx
=> Fix relative `to` resolution

packages/react-router-dom/index.tsx
don't want that thing causing re-renders in every component that uses it.
=> useCallback around useLinkClick handler

examples/basic/package.json, examples/basic/vite.config.ts
this plugin enables react-refresh and a few other optimizations
=> chore: use `@vitejs/plugin-react`

examples/custom-filter-link/.gitignore, examples/custom-filter-link/.stackblitzrc, examples/custom-filter-link/README.md, examples/custom-filter-link/index.html, examples/custom-filter-link/package.json, examples/custom-filter-link/src/App.tsx, examples/custom-filter-link/src/index.css, examples/custom-filter-link/src/main.tsx, examples/custom-filter-link/src/snkrs.ts, examples/custom-filter-link/src/vite-env.d.ts, examples/custom-filter-link/tsconfig.json, examples/custom-filter-link/vite.config.ts
I guess the main things to note here is that these came from [snkrs.mcan.sh](https://github.com/mcansh/snkrs) with slightly different data types, and the images are hosted in a Cloudinary bucket with a Cloudflare worker in front for caching 🤓... so we'll see how that all holds up...
=> add custom filter link example

packages/react-router/__tests__/matchRoutes-test.tsx, packages/react-router/index.tsx
See https://github.com/remix-run/react-router/issues/8143
=> feat: compute score now takes into account index

packages/react-router/__tests__/useRoutes-test.tsx, packages/react-router/index.tsx
See https://github.com/remix-run/react-router/issues/8145
=> feat: warn for leaf routes with no element

packages/react-router/index.tsx
Simply updates all references to the new docs sites. I did click through all of these individually to test as well :joy:
=> Docblock updates: Update all @see references to new links

docs/upgrading/v5.md
I think the ending quote was left off by mistake.
Excited for v6!
=> Minor doc change: fixing active styling example

docs/getting-started/overview.md
Should I keep it this way or change it to `yarn add` ?
=> Fix typo: `npm add` -> `npm install`

docs/getting-started/overview.md
Missing imports in the overview example.
=> [docs] import Routes + Route in the overview.md

docs/getting-started/concepts.md
=> Fix a typo in concepts.md

.github/workflows/website.yml
when an example's README file changes, we should update the db
=> chore(ci): trigger update for example md files

docs/api.md
Remove `createRoutesFromArray` in document
=> Remove `createRoutesFromArray`

packages/react-router/index.tsx
=> Fix `RouteProps` type

contributors.yml, docs/faq.md
Fix broken link of `advantages of route element` in faq.md
=> docs: Fix broken link in faq.md

docs/api.md
Add the `useOutletContext` hook import to example to align with other hook examples.
=> Update api.md - Add the `useOutletContext` hook import to example to align with other hook examples.

contributors.yml, docs/getting-started/tutorial.md
- Import `useLocation`
- Fix diff indicator to include `useLocation` and the whole `<p>` tag:
=> docs: Fix example in "Navigating Programmatically"

.github/workflows/format.yml, contributors.yml
`FORMAT_TOKEN` -> `FORMAT_PAT`
=> ci: update format workflow token name

contributors.yml, docs/upgrading/v5.md
=> Add Backwards Compatibility info to v5 Migration Doc

contributors.yml, docs/getting-started/concepts.md
=> Docs: Fix typo in getting-started > concepts

contributors.yml, docs/components/route.md, docs/components/routes.md
change outdated "location" navlink to /utils/location
=> docs: Update route.md and routes.md

contributors.yml, docs/components/route.md
use-routes instead of use-route
=> docs: Update route.md

docs/hooks/use-fetcher.md
[Preview docs](https://beta.reactrouter.com/en/brophdawg11-docs-update/hooks/use-fetcher)
=> docs: Update fetcher docs

.changeset/chilled-beers-sell.md, .changeset/strange-terms-pretend.md
Add missing changesets for `6.4.0-pre.8`
=> Add missing changesets

.changeset/sixty-otters-teach.md, packages/react-router-dom/__tests__/DataBrowserRouter-test.tsx, packages/react-router-dom/index.tsx, packages/react-router/__tests__/DataMemoryRouter-test.tsx, packages/react-router/lib/components.tsx, packages/router/__tests__/router-test.ts, packages/router/router.ts
Adds `basename` prop to `Data*` routers
=> feat: add support for basename in data routers

packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/index.tsx
Same fix as https://github.com/remix-run/remix/pull/4000
=> fix: avoid duplicating ?index param on repeated actionless form submissions

docs/getting-started/tutorial.md
The getContact import was added in a previous step and thus, should be reflected here.
=> Fix 6.4 tutorial import

contributors.yml, docs/start/overview.md
Removed duplicated attribute in the JSX example
=> docs: remove duplicate example attribute

contributors.yml, packages/react-router-dom/package.json
=> fix: [Bug]: react-router-dom does not list dependency @remix-run/router (#9243)

contributors.yml, docs/start/tutorial.md
I know it's very very minor but just thought If I could correct it
=> Correcting "Voila" spelling

contributors.yml, docs/start/tutorial.md
First of all, thank you all for the library.  Found that those codes are not in use and removed.
=> remove unused codes from docs/start/tutorial.md

contributors.yml, docs/start/tutorial.md
Using native English term instead of a term borrowed from French to explain "Data Writes + HTML Forms" section, to make it easier to understand for reader who don't know "a la" meaning in English.
Can check following dictionary for more information:
https://www.dictionary.com/e/slang/a-la/#:~:text=Borrowed%20from%20French%2C%20%C3%A0%20la,as%20traditionally%20cooked%20in%20Provence).
=> Using native English term for an explanation in tutorial.md

packages/router/__tests__/router-test.ts, packages/router/router.ts
Updates to `unstable_createStaticHandler` to better handle thrown values during `queryRoute`
=> feat: better handle throws in queryRoute

contributors.yml, docs/start/overview.md
I was reading through the feature overview and found what appears to be a grammatical mistake, so I figured I'd point it out. Thanks for React-router!
=> Grammar fix

contributors.yml, docs/start/tutorial.md
=> Fix tiny typo in tutorial

contributors.yml, docs/routers/picking-a-router.md
Includes `createRoutesFromElements` and `Route` in the imports of the code snippet.
=> Improve picking-a-router.md code snippet

contributors.yml, docs/components/form.md
=> docs(components/form): fix typo

contributors.yml, packages/react-router-dom/index.tsx
=> fix: correct FormImpl's displayName

.github/workflows/format.yml, .github/workflows/no-response.yml, .github/workflows/release-experimental.yml, .github/workflows/test.yml
Update Action dependencies + bring in line with the ones from https://github.com/remix-run/remix/tree/main/.github/workflows
=> chore: update workflows

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, docs/start/tutorial.md, packages/react-router-dom/CHANGELOG.md, packages/react-router-dom/index.tsx, packages/react-router/CHANGELOG.md, packages/react-router/lib/components.tsx, packages/react-router/lib/hooks.tsx, packages/router/CHANGELOG.md, packages/router/utils.ts
=> chore: update docs links

contributors.yml, docs/hooks/use-fetchers.md
Fixes for few minor issues in the exemplary code from the useFetchers documentation - the two parts of the example where not in sync.
=> fix exemplary code in useFetchers docs

contributors.yml, docs/start/tutorial.md
This example does not import `Route`
=> docs(start/tutorial.md): remove unused import

.changeset/polite-coins-tap.md, examples/ssr-data-router/README.md, examples/ssr-data-router/src/entry.server.tsx, packages/react-router-dom/__tests__/data-static-router-test.tsx, packages/react-router-dom/server.tsx, packages/router/__tests__/router-test.ts, packages/router/router.ts
Stabilize these API's now that we've got them wired up in Remix
=> Stabilize SSR data router APIs

docs/start/tutorial.md
This pull request fixes issue #9744
=> docs(start/tutorial.md): fix filename

contributors.yml, docs/start/tutorial.md
=> docs(start/tutorial.md): fix 404 example code highlight

scripts/release/github.ts
=> ci(comment): update package check

decisions/0001-use-blocker.md, decisions/template.md
[Preview](https://github.com/remix-run/react-router/blob/brophdawg11/blocker-decision-doc/decisions/0001-use-blocker.md)
=> Add decisions/ directory and useBlocker decision doc

docs/components/link.md
=> docs(components/link): Update for Link types and add replace/state props sections

.changeset/spotty-cheetahs-live.md, packages/router/utils.ts
=> Remove abort controller for defer with only critical data

contributors.yml, docs/route/route.md
Layout Route example was TODO, so I add the example
=> Add Layout Route Example

.github/workflows/release.yml, scripts/release/find-release-from-changeset.js
something something `SnaKE_CasE` being the root of all evil
=> ci: uppercase ENV, changesets output is camelCase

contributors.yml, docs/start/tutorial.md
=> fix demo error 

docs/start/tutorial.md
Reverts #10093
---
See https://github.com/remix-run/react-router/pull/10093#issuecomment-1429321902
=> Revert "docs(start/tutorial): remove unnecessary dependency"

contributors.yml, docs/start/tutorial.md
Fixing the below highlighting:
=> docs(start/tutorial): fix highlighting in "URL Params in Loaders" step

packages/react-router/__tests__/data-memory-router-test.tsx
These tests were using a `DataMemoryRouter` wrapper from when that was the original API.  Rewrite to use `createMemoryRouter`/`RouterProvider`
=> Convert data-memory-router-tests to use createMemoryRouter directly

.changeset/disallow-return-undefined-type.md, packages/router/utils.ts
=> Disallow undefined as a return value from LoaderFunction/ActionFunction

.github/ISSUE_TEMPLATE/bug_report.yml, examples/basic-data-router/.gitignore, examples/basic-data-router/.stackblitzrc, examples/basic-data-router/README.md, examples/basic-data-router/index.html, examples/basic-data-router/package-lock.json, examples/basic-data-router/package.json, examples/basic-data-router/src/app.tsx, examples/basic-data-router/src/index.css, examples/basic-data-router/src/main.tsx, examples/basic-data-router/src/vite-env.d.ts, examples/basic-data-router/tsconfig.json, examples/basic-data-router/vite.config.ts
=> Add basic data router example

contributors.yml, docs/guides/api-development-strategy.md
This fixes the markdown for the Current Future Flags table
=> fix(react-router): "Current Future Flags" table

LICENSE.md
See https://github.com/remix-run/remix/pull/6089
=> chore: update `LICENSE.md`

docs/routers/create-browser-router.md
=> docs(routers/create-browser-router): fix Future Flags link

package.json, packages/react-router-dom/__tests__/exports-test.tsx, packages/react-router-dom/server.tsx, packages/react-router-native/__tests__/exports-test.tsx, packages/react-router/index.ts, packages/react-router/lib/components.tsx
🤦  Forgot to handle `StaticRouterProvider` in https://github.com/remix-run/react-router/pull/10389
=> refactor(react-router): Fix useRoutesImpl for SSR

contributors.yml, packages/react-router/lib/components.tsx
Avoids unsubscribing/subscribing every time `state` changes
=> Avoid unnecessary router subscribes

.changeset/set-search-params-type.md, packages/react-router-dom/index.tsx, packages/react-router-native/index.tsx
=> feat: export `SetURLSearchParams` type

.changeset/start-transition-support.md, package.json, packages/react-router-dom/__tests__/components/LazyComponent.tsx, packages/react-router-dom/__tests__/concurrent-mode-navigations-test.tsx, packages/react-router-dom/index.tsx, packages/react-router/__tests__/navigate-test.tsx, packages/react-router/lib/components.tsx
Closes https://github.com/remix-run/remix/issues/5763
=> Wrap internal router state updates with React.startTransition

.changeset/smart-pots-repair.md, package.json, yarn.lock
This gives us the latest dom types, along with other goodies
=> chore: upgrade typescript

.github/workflows/deduplicate-yarn.yml
This way we don't need to do #10582 manually anymore
Thanks to @mcansh for the idea (https://github.com/remix-run/remix/pull/6109 & https://github.com/remix-run/examples/pull/248)! 🙏
=> chore: add `deduplicate-yarn` workflow

contributors.yml, docs/routers/picking-a-router.md
I think the intention here is `history.pushState`
=> Fixing typo

examples/auth-router-provider/.gitignore, examples/auth-router-provider/.stackblitzrc, examples/auth-router-provider/README.md, examples/auth-router-provider/index.html, examples/auth-router-provider/package-lock.json, examples/auth-router-provider/package.json, examples/auth-router-provider/src/App.tsx, examples/auth-router-provider/src/auth.ts, examples/auth-router-provider/src/index.css, examples/auth-router-provider/src/main.tsx, examples/auth-router-provider/src/vite-env.d.ts, examples/auth-router-provider/tsconfig.json, examples/auth-router-provider/vite.config.ts
This is a long time overdue, but duplicated `examples/auth` to show how to do it with a `RouterProvider`./.
=> Add auth example using RouterProvider

.changeset/fix-query-route-response.md, contributors.yml, packages/router/__tests__/router-test.ts, packages/router/router.ts
Continuation of https://github.com/remix-run/react-router/pull/10703
=> Fix isQueryRouteResponse boolean logic

docs/hooks/use-navigate.md
* Aligned with the summary/details type declarations used elsewhere
* Added `preventScrollReset` to type declaration
* Added docs for each `options`flag
=> Update docs for useNavigate()

packages/router/__tests__/router-test.ts
Pulled some flaky playwright tests over here since they're testing router logic more than Remix logic.
=> Add some redirect unit tests from Remix

contributors.yml, docs/hooks/use-location.md
tried to add some more context on useLocation in the docs folder in file use-location.md
=> Update on file use-location.md

contributors.yml, docs/hooks/use-navigate.md
Replacement for https://github.com/remix-run/react-router/pull/10754
=> Update useNavigate docs for state property

.changeset/unmounted-fetcher-revalidate.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/router/router.ts
=> Do not revalidate unmounted fetchers when v7_persistFetcher is enabled

contributors.yml, docs/hooks/use-navigation.md
issue: #11036 
Hello!
I'm submitting a Pull Request to enhance the documentation. 
Please review the changes at your earliest convenience, and feel free to provide feedback or let me know if any further adjustments are needed.
=> Add usenavigation formAction, formMethod, formEncType doc

packages/react-router/__tests__/useResolvedPath-test.tsx
This unit tests has an unexpected splat (not impacting text behavior though)
=> Fix unit test

.github/workflows/format.yml
Same as https://github.com/remix-run/remix/pull/8410
=> Sort contributors.yml as part of the format workflow

contributors.yml, docs/start/faq.md
fixed typo in last line of document from rending to rendering
=> fix typo in faq.md

contributors.yml, docs/components/link.md
=> [Docs] Update link.md

packages/remix-dev/vite/plugin.ts
Replay of https://github.com/remix-run/remix/pull/9287.
=> Remove `@react-router/node` from `optimizeDeps.include`

CHANGELOG.md, contributors.yml, docs/components/form.md, docs/hooks/use-navigate.md
=> docs: fix typos

.github/workflows/release-nightly.yml
Perform nightly releases from `v7` for now, we'll change it to `dev` after we get that merged down
=> Add nightly release workflow

contributors.yml, docs/routers/create-browser-router.md
I believe there should be a `=` sign at this code snippet
=> doc: Update create-browser-router.md example snippet

integration/helpers/vite-template/package.json, pnpm-lock.yaml
Bringing https://github.com/remix-run/remix/pull/9218 over to the v7 branch
=> Remove unused node-fetch dependency

contributors.yml, docs/start/tutorial.md
First, thanks for the great tutorial ! Impressive work :-)
This pull request contains two commits.
The first one replaces **placekitten.com** with **robohash.org** (not as cute but gender neutral) because placekitten.com seems to be down. This commit also displays the robohash avatar in case nothing is set (nicer when creating fake contacts while learning).
The second pull request is about using `const` instead of `let` in two places where `let` does not seem optimal.
Cheers !
PS: this pull request is only about documentation, so it is done against **main** as advised.
=> Small typos and fixes to the tutorial

contributors.yml, docs/utils/create-routes-from-elements.md
Adds the missing Route import in createRoutesFromElements docs
=> docs: add Route import in createRoutesFromElements docs

.changeset/early-beds-obey.md, examples/view-transitions/src/main.tsx, packages/react-router-dom/index.ts, packages/react-router/__tests__/dom/concurrent-mode-navigations-test.tsx, packages/react-router/__tests__/dom/flush-sync-navigations-test.tsx, packages/react-router/__tests__/navigate-test.tsx, packages/react-router/__tests__/router/fetchers-test.ts, packages/react-router/__tests__/router/utils/data-router-setup.ts, packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/context.ts, packages/react-router/lib/dom/lib.tsx, packages/react-router/lib/dom/server.tsx, packages/react-router/lib/dom/ssr/browser.tsx
=> Remove future.v7_startTransition flag

.changeset/flat-seals-hunt.md, packages/react-router-dom/index.tsx
=> Remove polyfil.io reference from warning message

.changeset/rich-bees-invent.md, package.json, packages/router/__tests__/lazy-discovery-test.ts, packages/router/router.ts
=> Fix initial matching in fog of war when a splat route matches

.changeset/wicked-ducks-heal.md, packages/router/__tests__/lazy-discovery-test.ts, packages/router/router.ts
Closes https://github.com/remix-run/remix/issues/9721
=> Fix fog of war hydration in SSR apps that matched a splat route

packages/react-router-architect/server.ts, packages/react-router-cloudflare/worker.ts, packages/react-router/lib/dom/ssr/routeModules.ts, packages/react-router/lib/dom/ssr/single-fetch.tsx
See: https://github.com/remix-run/remix/compare/remix@2.10.2...remix@2.10.3
=> Bring over changes from Remix 2.10.3

.changeset/hip-poets-provide.md, packages/router/__tests__/fetchers-test.ts, packages/router/router.ts
Closes https://github.com/remix-run/react-router/issues/11723
=> Fix fetcher interruption cleanup logic after fetcher submissions

.github/workflows/integration-pr-windows-macos.yml
Follow up to https://github.com/remix-run/react-router/pull/11848 to ensure changes like this trigger the Windows tests.
=> Run Windows tests on deps change

packages/react-router/__tests__/dom/ssr/components-test.tsx, packages/react-router/lib/dom-export/hydrated-router.tsx, packages/react-router/lib/dom/global.ts, packages/react-router/lib/server-runtime/server.ts, packages/react-router/lib/server-runtime/serverHandoff.ts
See https://github.com/remix-run/remix/blob/main/CHANGELOG.md#v2111
=> Copy over Remix v2.11.1 changes

packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/context.ts, packages/react-router/lib/dom/lib.tsx, packages/react-router/lib/dom/ssr/fog-of-war.ts, packages/react-router/lib/router/utils.ts
v7 sibling of https://github.com/remix-run/react-router/pull/11967
=> Fix types for PatchRoutesOnNavigationFunction

packages/react-router/__tests__/router/lazy-discovery-test.ts, packages/react-router/lib/router/router.ts
v7 sibling of https://github.com/remix-run/react-router/pull/11977
=> Remove internal discoverRoutes queue and make patch idempotent

.changeset/chatty-impalas-pump.md, packages/router/__tests__/scroll-restoration-test.ts, packages/router/router.ts
Closes [#8991](https://github.com/remix-run/remix/issues/8991)
=> Fix bug with preventScrollReset when using concurrent redirecting fetchers

packages/react-router/__tests__/router/lazy-discovery-test.ts, packages/react-router/lib/router/router.ts
v7 sibling for https://github.com/remix-run/react-router/pull/12013
=> Fix idempotent patchRoutes for sibling pathless layout routes

packages/react-router-dev/vite/route-chunks-test.ts, packages/react-router-dev/vite/route-chunks.ts
Updates core chunking logic to handle destructured exports like `export const { foo, bar } = ...`.
=> Route chunks: Handle destructured exports

packages/react-router-dev/vite/route-chunks-test.ts, packages/react-router-dev/vite/route-chunks.ts
This PR adds a lot more tests for dependency analysis which helped catch a number of issues that are now fixed. The dependency analysis is now a lot more comprehensive.
=> Route chunks: Improve dependency analysis

packages/react-router/lib/router/router.ts
=> Avoid unnecessary console error on fetcher abort due to back-to-back revalidation calls

contributors.yml, docs/start/routing.md
- Fix the variable name in the code example (data -> loaderData)
- Replace semicolons with commas at line ends for array elements in route definitions
- Add the missing `export` statement to the loader function in the code example
=> docs: fix minor issues in docs/start/routing.md

.changeset/wet-actors-act.md, packages/react-router/lib/server-runtime/cookies.ts, packages/react-router/lib/server-runtime/sessions.ts, packages/react-router/package.json, pnpm-lock.yaml
=> Update cookie dependency to 1.0

integration/typegen-test.ts, packages/react-router-dev/package.json, packages/react-router-dev/typegen/generate.ts, packages/react-router/__tests__/path-matching-test.tsx, packages/react-router/lib/router/utils.ts, packages/react-router/lib/test-types.ts, packages/react-router/lib/types.ts
=> typegen: dynamic segments with dot

contributors.yml, docs/components/link.md
Noticed a slightly incorrect link in the docs
=> Fix incorrect link

.github/workflows/deduplicate-lock-file.yml, .github/workflows/format.yml, .github/workflows/no-response.yml, .github/workflows/release-experimental.yml, .github/workflows/release-nightly.yml, .github/workflows/release.yml, .github/workflows/shared-build.yml, .github/workflows/shared-integration.yml, .github/workflows/test.yml, contributors.yml
update github actions 'uses' to latest version
updated items:
* pnpm/action-setup
* actions/stale
=> chore(.github/workflows): update github actions 'uses' to latest version

packages/react-router-dev/config/config.ts, packages/react-router-dev/vite/plugin.ts
For parity with Remix v2 (see https://github.com/remix-run/remix/pull/9927)
=> future flag: unstable_optimizeDeps

docs/explanation/special-files.md, packages/react-router-dev/typedoc.json
[Preview](https://github-md.com/remix-run/react-router/blob/dbfbfa3bf0d9f711b52a880047836f4792c75b27/docs/explanation/special-files.md)
=> docs: special files

contributors.yml, docs/how-to/file-route-conventions.md
- corrected sentence structure / verb tense
=> docs(how-to/file-route-conventions): fix typo

contributors.yml, docs/upgrading/component-routes.md
- reference the correct config file to update (i.e. not the vite config)
=> docs(upgrading/component-routes): fix filename

.changeset/red-eagles-stare.md, integration/typegen-test.ts, packages/react-router-dev/typegen/generate.ts, packages/react-router/lib/types/route-module.ts
=> typegen: matches and params for child routes

.changeset/slow-birds-fetch.md, packages/react-router/lib/deprecations.ts
=> allow users to opt out of deprecation warnings by setting flags to false

contributors.yml, docs/explanation/special-files.md
I had a [conversation ](https://bsky.app/profile/pierophp.bsky.social/post/3lco2fpgbhk2h)with @brookslybrand on Bluesky, and I'm adding the Remix .server modules [documentation](https://remix.run/docs/en/main/file-conventions/-server#server-modules) to [React Router](https://reactrouter.com/explanation/special-files).
Thank you
=> [Docs] .server modules and .client modules

packages/react-router-dev/vite/plugin.ts, packages/react-router-dev/vite/virtual-module.ts, packages/react-router-dev/vite/vmod.ts, packages/react-router-dev/vite/with-props.ts
- namespace plugins with package name (`react-router:` prefix)
- pre-compute virtual module ID,resolved ID, and URL
=> refactor vite plugin

packages/react-router-dev/vite/plugin.ts
See https://github.com/remix-run/remix/pull/9395
=> Remove client route virtual modules in development

contributors.yml, docs/how-to/suspense.md
The promises in the suspense docs are not using resolve - this PR fixes the issue
=> Resolve promises in suspense docs

docs/explanation/sessions-and-cookies.md
Add a combined sessions and cookies doc
=> docs: sessions and cookies

contributors.yml, docs/explanation/special-files.md, packages/react-router-dev/config/defaults/entry.server.node.tsx
I bumped into a few typos while upgrading our app to RR v7 😅
=> fix typos in timeout comments

.changeset/twenty-llamas-lick.md, packages/react-router-dev/vite/plugin.ts
=> Fix prerendering when using a custom server

.changeset/big-lamps-remain.md, contributors.yml, packages/react-router/lib/deprecations.ts
https://github.com/remix-run/react-router/pull/12509 + changeset
=> Suppress v7 warnings in production build

integration/bug-report-test.ts
=> Update bug report inline docs

.changeset/rich-pans-fail.md, .vscode/settings.json, integration/headers-test.ts, packages/react-router/lib/router/router.ts, packages/react-router/lib/server-runtime/headers.ts
v7 version of https://github.com/remix-run/remix/pull/10424
=> Fix bugs with thrown data headers and duplicated set-cookie headers

docs/explanation/progressive-enhancement.md, docs/explanation/state-management.md
These docs were originally in Remix docs and apply here now
Closes #12815 (Progressive Enhancement)
- [rendered doc](https://github.com/remix-run/react-router/blob/brooks/pe-doc/docs/explanation/progressive-enhancement.md)
- [remix doc](https://remix.run/docs/en/main/discussion/progressive-enhancement)
Closes #12816 (State Management)
- [rendered doc](https://github.com/remix-run/react-router/blob/brooks/pe-doc/docs/explanation/state-management.md)
- [remix doc](https://remix.run/docs/en/main/discussion/state-management)
=> docs: add progress-enhancement and state-management docs

contributors.yml, docs/explanation/type-safety.md, docs/how-to/route-module-type-safety.md
Added information on how to define the `AppLoadContext` to the type-safety doc
=> (Docs) Update type safety for AppLoadContext

docs/how-to/route-module-type-safety.md
=> (Docs) fix typo from #12861

.changeset/honest-socks-fail.md, packages/router/__tests__/lazy-discovery-test.ts, packages/router/router.ts
Closes https://github.com/remix-run/react-router/issues/12896
=> Strip search params from FOW path parameter

packages/react-router-dev/vite/plugin.ts
=> Add route module chunk suffix to build output

packages/react-router-dev/vite/plugin.ts
If a user defines config for the SSR environment, this should also apply to all server bundle environments.
=> Extend server bundle env from user SSR env

contributors.yml, docs/how-to/pre-rendering.md
Minor https://github.com/remix-run/react-router/pull/13005 followup:
* fixing a typo, and
* improving the readability of an SSR sentence
=> docs: fix pre-rendering typo

.changeset/thick-meals-shout.md, contributors.yml, integration/vite-prerender-test.ts, packages/react-router-dev/vite/plugin.ts
=> fix: prerendering binary files

.changeset/witty-birds-fetch.md, packages/router/__tests__/navigation-test.ts, packages/router/router.ts
v6 version of https://github.com/remix-run/react-router/pull/12927
=> Fix hash issue for matchRoutes optimization

.changeset/cool-pillows-sing.md, packages/react-router/__tests__/server-runtime/handler-test.ts, packages/react-router/__tests__/server-runtime/server-test.ts, packages/react-router/__tests__/server-runtime/utils.ts, packages/react-router/lib/server-runtime/server.ts
Closes https://github.com/remix-run/react-router/issues/13072
=> Skip resource route flow in dev mode when SPA  mode is enabled

contributors.yml, docs/start/library/routing.md
=> fix: component in routing.md to element

contributors.yml, docs/community/contributing.md
* Indent code block within setup ordered list item
* Update **Think You Found a Bug?** section to match issue template, notably replacing CodeSandbox with StackBlitz
* Leverage `<docs-error>` element to emphasize test requirement
=> docs: refresh contributing bug section

contributors.yml, docs/start/modes.md
=> docs(start/modes): fix links

.changeset/orange-sloths-tease.md, integration/vite-prerender-test.ts, packages/react-router/lib/dom/ssr/routes.tsx, packages/react-router/lib/router/utils.ts
=> Revalidate prerendered paths when param values change

packages/react-router/lib/dom-export/hydrated-router.tsx, packages/react-router/lib/dom/ssr/single-fetch.tsx
Replaces https://github.com/remix-run/react-router/pull/13304
=> Refactor dataStrategy for better use with RSC

contributors.yml, docs/start/data/data-loading.md, docs/start/data/route-object.md, docs/start/declarative/navigating.md, docs/start/declarative/routing.md
fixes for documentation links + added new
=> docs(start): fix links

contributors.yml, docs/api/components/Routes.md
=> Update Routes.md - Correct typo in code sample

.changeset/smooth-donuts-bake.md, integration/client-data-test.ts, packages/react-router/lib/dom/ssr/single-fetch.tsx
Closes https://github.com/remix-run/react-router/issues/13420
=> Handle redirects from hydrating clientLoaders

.changeset/curvy-queens-hug.md, integration/single-fetch-test.ts, packages/react-router/__tests__/router/router-test.ts, packages/react-router/lib/router/router.ts
=> Avoid hydration error if a server loader returned undefined

.changeset/purple-gifts-bake.md, build.utils.d.ts, packages/react-router/lib/deprecations.ts
Closes https://github.com/remix-run/react-router/issues/13006
=> Prevent invalid warning for v7_relativeSplatPath

contributors.yml, docs/start/data/routing.md
The link is wrong, it currently 404.
=> Fix broken link in routing.md

contributors.yml, packages/create-react-router/__tests__/github-mocks.ts, packages/create-react-router/__tests__/msw.ts, packages/create-react-router/package.json, pnpm-lock.yaml
Cherry-picked from https://github.com/remix-run/react-router/pull/12351
=> Update MSW to v2

.changeset/healthy-readers-kick.md, packages/react-router/__tests__/use-revalidator-test.tsx, packages/react-router/lib/hooks.tsx
Changeset and a test for https://github.com/remix-run/react-router/pull/13511
=> feat(react-router): stabilize `useRevalidator`'s `revalidate`

docs/start/data/testing.md
The link is borked. Fixing it.
=> Doc: Fix link in data/testing.md

contributors.yml, docs/how-to/fetchers.md
Previous step defines a loader, not an action so changing the import.
=> docs(how-to/fetchers): fix import

.changeset/curvy-pears-yawn.md, packages/create-react-router/package.json, pnpm-lock.yaml
Fixes https://github.com/advisories/GHSA-pq67-2wwv-3xjx
=> fix(create-react-router): update `tar-fs`

.github/ISSUE_TEMPLATE/bug_report.yml, GOVERNANCE.md
The Remix team is adjusting our approach to the governance of React Router.
> This document will outline the process in which React Router will continue to evolve, and how new features will make their way into the codebase. This is an evergreen document and will be updated as-needed to reflect future changes in the process.
The team is very excited about how this change in governance will enable us to continue improving React Router for the numerous developers and projects that rely on it.
Full credit goes to @brophdawg11 for authoring this document. I'm just the copy-and-paster.
=> Add GOVERNANCE.md

.github/ISSUE_TEMPLATE/bug_report.yml, GOVERNANCE.md
=> docs(GOVERNANCE): fix typos + grammar

packages/react-router/lib/rsc/browser.tsx, packages/react-router/lib/rsc/server.rsc.ts
fix: clone request if we have to read the body
=> fix: flushSync support

packages/react-router/__tests__/server-runtime/utils.ts
I'm sure people from the wider @e18e ecosystem cleanup (like @43081j & @outslept) will be very happy to see these kind of changes as well
=> chore(react-router): remove unused code

packages/react-router-node/__tests__/utils.ts
I'm sure people from the wider @e18e ecosystem cleanup (like @43081j & @outslept) will be very happy to see these kind of changes as well
=> chore(node): remove unused file

docs/tutorials/address-book.md
=> Remove reference to a screenshot that doesn't exist

docs/api/components/Await.md, docs/api/components/Link.md, docs/api/hooks/useLoaderData.md, docs/api/hooks/useNavigate.md, docs/api/hooks/useResolvedPath.md, docs/api/hooks/useRouteError.md
=> docs: fix broken links to API docs

contributors.yml, docs/start/framework/route-module.md, packages/react-router/__tests__/server-runtime/cookies-test.ts
Description:  
This pull request corrects minor typos in the codebase:
- Updates the word "preferrable" to "preferable" in the documentation (`route-module.md`).
- Fixes the spelling of "different" in a test comment (`cookies-test.ts`).
=> Fix Typos in Documentation and Test Comments

website/modules/components/Example.js
Pins versions of `react` and `react-dom` to fix codesandbox examples
Fixes #13426
=> Add pinned React deps to codebox examples

.github/workflows/deduplicate-lock-file.yml
=> chore(CI): make dedupe workflow a bit cleaner

contributors.yml, docs/api/hooks/useLocation.md
=> Update `Location` link at `useLocation.md`

integration/client-data-test.ts, integration/helpers/create-fixture.ts, integration/helpers/rsc-parcel-framework/start.js, integration/package.json, packages/react-router/lib/rsc/browser.tsx, packages/react-router/lib/rsc/server.rsc.ts, packages/react-router/lib/rsc/server.ssr.tsx, pnpm-lock.yaml
Note this also required changing the way RSC fixtures are run due to this issue: https://github.com/markdalgleish/parcel-rsc-multiple-apps-issue.
=> fix(rsc): test client data, apply minor fixes

.changeset/fuzzy-bottles-itch.md, packages/react-router/lib/rsc/browser.tsx
Retain transition through form submission to allow useOptimistic to play correctly with pending states.
=> fix: retain transition through form submission

contributors.yml, docs/api/hooks/useOutletContext.md
well the documentation page was empty for this hook
=> Update useOutletContext.md with detailed information and example

.eslintrc, .github/workflows/docs.yml, packages/react-router/lib/components.tsx
Follow up to https://github.com/remix-run/react-router/pull/14002
=> Auto-generate docs for components

.changeset/thin-tables-reply.md, integration/middleware-test.ts, packages/react-router/__tests__/router/context-middleware-test.ts, packages/react-router/lib/router/router.ts
See https://github.com/remix-run/react-router/discussions/12950#discussioncomment-13952082 for details
=> Run clientMiddleware on client navs if no loaders exist

.changeset/olive-bugs-sing.md, docs/how-to/middleware.md, integration/middleware-test.ts, packages/react-router/__tests__/router/context-middleware-test.ts, packages/react-router/lib/dom/ssr/single-fetch.tsx, packages/react-router/lib/router/router.ts, packages/react-router/lib/router/utils.ts, playground/middleware/server.ts
=> Bubble middleware errors back up the ancestor chain

.changeset/bright-bats-wave.md, packages/react-router/__tests__/path-matching-test.tsx, packages/react-router/lib/router/utils.ts
Closes https://github.com/remix-run/react-router/issues/9925
=> Add support for optional segments in nested absolute routes

.changeset/rotten-parents-care.md, packages/react-router-dev/config/defaults/entry.server.node.tsx
Fixes https://github.com/remix-run/react-router/pull/13416.
=> fix: memory leak in entry.server
