modules/__tests__/Router-test.js
modules/utils/createRouter.js

Currently, the dispatchHandler doesn't distinguish between stale (superseded) async transitions and the current (pending) ones. This works fine in most cases since a new transition will cause a cancellation of the current one. So when the old transition is finished, the router will call the abort handler which will simply ignore it.
However, I found two problems with this:
1. Besides executing the no-op abort handler, finishDispatch also sets pendingTransition to null.  This can be a problem if a stale transition ends while another async one is in progress. If a third transition occurs, the router tries to cancel the ongoing one as usual, but its reference was removed after the completion of the first transition. As a result, that transition will go through once it is complete.
2. If an …

Ignore stale transitions

---

modules/utils/createRouter.js

Supersedes #606, that's the only missing piece. Let me know if you want tests for this; I'm not sure where to put them because there are not tests for `addRoutes` either. But this has been working for me for a few weeks so I don't think it's problematic.

[added] router.replaceRoutes(children)

---

modules/utils/Path.js
modules/utils/__tests__/Path-test.js

Hi there,
`Path.withQuery` did not strip off the query once it became empty. Here's a fix + test. :smiley: 
Cheers,
Max

[fixed] Path.withQuery strips query if query is empty

---

modules/utils/Path.js
modules/utils/__tests__/Path-test.js

Reverts rackt/react-router#599
This test is failing. :(

Revert "[fixed] Path.withQuery strips query if query is empty"

---

examples/async-data/app.js

On new installs the examples don't compile. That's because when.js had been removed as a dependency in #654. This PR fixes it by replacing the use of when.js with promises.

Replace when.js with promises in example app

---

tests/Router-test.js
utils/createRoutesFromChildren.js

I just tried to do something like this:
```jsx
<Route name="app" path="/" handler={Application}>
<Route name="job" path="job/:job_id/?" handler={JobLayout}>
<Route name="report" handler={Report} />
{__DEBUG__ && <Route name="debug" handler={Debug} />}
<DefaultRoute handler={JobForm} />
</Route>
</Route>
```
Where the `__DEBUG__` var is injected via webpack at compile time. This works fine during development, but in production, the line becomes equivalent to `{undefined}`. This pattern for conditionally rendering nodes is fairly common in React. I thought it might make sense to allow this here by skipping over falsy values in the `createRoutesFromChildren` function.

[fixed] Ignore falsy routes

---

docs/api/run.md

Fixed typo `req.send` -> `res.send`.

Fixed typo in server rendering example

---

webpack.config.js

Since [webpack 1.5](http://webpack.github.io/docs/changelog.html#1-5) the casing of `buffer` has been changed to `Buffer` (because it refers to the global `Buffer` variable)

Capitalize `node.buffer`-option

---

modules/createRouter.js

We can't reliably restore scroll position on Forward due to browser differences and incompatibilities.
Instead, we will only restore previous scroll position when user presses Back, and scroll to top on Forward.
Fixes #707.

[changed] Don't restore scroll position on Forward

---

docs/guides/overview.md

nother tiny s/its/it's change

---

README.md

(edits while snooping through the docs)

tiny fixes for readme

---

modules/RouteHandlerMixin.js

See #778
This commit ensures that we don't leak references to a component if the route depth decreases when navigating to a new route.

[fixed] Clean up mounted route component on unmount so we don't leak references

---

modules/Routing.js

With the current implementation `<NotFoundRoute {...props}>{[]}</NotFoundRoute>` fails, but clearly there are no children. This uses a more accurate check to determine whether there are actually component children.

[fixed] Use more correct children invariant

---

docs/api/components/Link.md
modules/components/Link.js
modules/components/__tests__/Link-test.js

If you are styling components in the component itself (not using external CSS), then active styling is not possible at the moment. This PR adds an optional `activeStyle` property to Link to allow for this scenario.
Super simple example:
```js
var style = {
color: 'white',
fontSize: 12,
textDecoration: 'none'
};
var activeStyle = assign({}, style, {
color: 'red'
});
<Link style={style} activeStyle={activeStyle} to="route">Link</Link>
```

[added] Link activeStyle property

---

modules/createRouter.js

Converting from `String` → `StaticLocation` up front allows this.
Discovered this while testing server-side rendering of #828, where a `StaticLocation` must be passed to provide a payload.

[fixed] allow a StaticLocation to be passed directly when creating a router

---

modules/utils/Path.js
modules/utils/__tests__/Path-test.js

Previously, special characters in query were left as is, potentially overwriting other query parameters and causing ambiguity.
Now, they are properly escaped.
Fixes #804.

[fixed] Allow special characters in query

---

modules/components/Link.js
modules/createRouter.js

This pull request fixes two things:
* When changing routes, `Router.dispatch` gets correctly called and does not throw an error. (An issue I raised in #638 )
* Link click handlers are not correctly bound and don't throw an error when called
I haven't touched the rest and there are still some tests that are failing.

Improve React 0.13 compatibility

---

examples/master-detail/app.js

It is immediately assigned from getParams() and so clearly is an unused argument. Moreover other functions do not call it with an argument.

Minor fix in example: remove unused argument

---

docs/api/RouterContext.md

Tried using the context methods based on the documentation, and they didn't appear to be defined.
Looked at the implementation of the now-deprecated State mixin (thanks for the high quality warnings!) to see what context methods correspond to the older mixin methods:
https://github.com/rackt/react-router/blob/master/modules/State.js
These updated method names seem to work in my app.
Thanks!
Jonathan

Correct method names in RouterContext docs

---

modules/PathUtils.js
modules/__tests__/Router-test.js

`/` and `/?a` route to the same place, but `/?` won't match any route and will trigger not found. This issue is not experienced with `HistoryLocation` in the browser because when the URL ends with `?` then `window.location.search == ""` thereby dropping the question mark; however when using `req.url` in Node.js the `?` is not automatically dropped.
I've fixed the issue via a tweak to the regex, and added a relevant test.
I'm not sure if we need to change `extractQuery` in PathUtils to return false if `match[1].length === 0`?

Empty query string ("/?") causes route match to fail

---

modules/index.js

A small fix for https://github.com/rackt/react-router/issues/789

Added TestLocation to the list of exports

---

modules/locations/HashLocation.js

This commit fixes https://github.com/rackt/react-router/issues/958 
Using HashLocation, the _actionType was lost on **transition.redirect** due to multiple async onHashChange calls for push and replace, which made the redirect wrongly trigger a **pop** state.
regards,
mario

fix transition.redirect() with Router.HashLocation

---

examples/animations/app.css

This is a tiny little patch to clean up the CSS on the animation example. It adds `px` to width and height properties so that the values are actually applied to the HTML display, and removes a duplicate class declaration for `.Image` which was being overridden.

Cleanup CSS in Animation Example

---

docs/guides/testing.md

Hello,
If you want to test an element with `<RouteHandler />` component in it, you need in additional the `routeDepth` into `stubRouterContext`.
I don't know the side effects but this was proposed by @taurose in the issue I have created: https://github.com/rackt/react-router/issues/1055
Best.

add `routeDepth` into `stubRouterContext` method

---

README.md

The new location is https://github.com/react-bootstrap/react-router-bootstrap

Change react-router-bootstrap to its new location

---

website/styles.css

Fixes #1218 - Docs font-family declaration misspelling of monospace.

Fixes #1218 - font-family declaration misspelling

---

examples/master-detail/app.js

https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html
https://facebook.github.io/react/docs/component-api.html#getdomnode

getDOMNode() has been deprecated. Use React.findDOMNode() instead.

---

doc/03 History/BrowserHistory.md
doc/03 History/HashHistory.md
modules/BrowserHistory.js
modules/HashHistory.js
modules/__tests__/BrowserHistory-test.js
modules/__tests__/HashHistory-test.js
modules/__tests__/scrollManagement-test.js

This commit normalizes the way we export history classes. Instead of automatically creating a new Browser/HashHistory for people when they require the module, we just export the class like we do with History and MemoryHistory.
This gives us a few things:
- We don't have to explain to people that they need to `import { HashHistory }` in order to create their own HashHistory.
- We don't require people using CommonJS to `var HashHistory = require('react-router/lib/HashHistory').default`, which sucks

[changed] Export history classes

---

doc/00 Guides/0 Overview.md

`<Link>` is used but never imported.

Docs: Add Link import to first example

---

modules/BrowserHistory.js
modules/HashHistory.js

IE8 gives an error:
> Object doesn't support this property or method
It is fixed by the use of `detachEvent`.

Use detachEvent in old IE

---

doc/00 Guides/0 Overview.md

`history={HashHistory}` should be `history = {new HashHistory()}`

fix docs history={HashHistory}

---

examples/passing-props-to-children/app.js

Added the missing new keyword to HashHistory

Quick fix to Passing Props to Children example

---

doc/02 Components/Link.md
examples/auth-flow/app.js
modules/Link.js

Looks like replacing `location.query` with `location.state` was incomplete.
Also fixed `Link`'s property name in docs (`s/href/to`) and examples in its doc comments.

Fixed incomplete edits

---

tags/v0.13.3.html

I'm always annoyed when clicking these links and the route to:
http://rackt.github.io/react-router/#TODO
.... so I fixed them.

fixed dead links

---

modules/Link.js
modules/__tests__/Link-test.js

It renders differently on the server because the url on server is stripped by nginx and it is not an active route.

[fixed] Link module adds an extra space to className

---

README.md
doc/00 Guides/0 Overview.md
doc/03 History/0 Histories.md
doc/03 History/BrowserHistory.md
doc/03 History/HashHistory.md
examples/animations/app.js
examples/async-data/app.js
examples/auth-flow/app.js
examples/dynamic-segments/app.js
examples/huge-apps/app.js
examples/master-detail/app.js
examples/passing-props-to-children/app.js
examples/pinterest/app.js
examples/query-params/app.js
examples/shared-root/app.js
examples/sidebar/app.js
examples/transitions/app.js
modules/BrowserHistory.js
modules/DOMHistory.js
modules/HashHistory.js
modules/__tests__/BrowserHistory-test.js
modules/__tests__/HashHistory-test.js
modules/__tests__/MemoryHistory-test.js

Instead of just updating the docs, this is an implementation for what @ryanflorence said on #1339 and @mjackson on #1426.
this PR lets you use a history singleton with `BrowserHistory` and `HashHistory`:
```js
var { history } = require('react-router/lib/HashHistory');
React.render(<Router history={ history } ... />, ...);
```

History singletons

---

README.md

Old link, https://github.com/mtscout6/react-router-bootstrap, points to the new repository.

Update link to new official repository for React-Router Bootstrap

---

docs/guides/overview.md

This link is broken. I updated it to point to the website, but you might prefer that I...
1. point it somewhere else
2. remove it entirely
just lmk.

Fix broken link to API docs.

---

modules/Link.js
modules/__tests__/Link-test.js

* subscribe to history changes
* don't use the context to pass data
* works with parents that implement shouldComponentUpdate
* solves #470, #1772

Link: listen to history for active state changes

---

modules/PropTypes.js

```
// react-router/modules/index.js
export PropTypes from './PropTypes';
```
This line will get a `undefined` value as `PropTypes`.
We should export whole PropTypes as default or just `export { * as PropTypes } from './PropTypes';`

fix import PropTypes got undefined bug

---

doc/01 Route Configuration/Redirect.md

Clarify that the `<Redirect/>` component does not support relative paths in the `to` property. (Iss #1658)

Clarify relative redirects

---

modules/index.js

Otherwise third-party tools end up having to re-implement this logic, including `isReactChildren()`.

Export createRoutes instead of createRoutesFromReactChildren

---

modules/__tests__/getParams-test.js

Referencing issue #1264, this issue is fixed in the current master branch.  This pull request adds a test to show this is the case.

Add test verifying multiple URL encoded characters are decoded successfully

---

modules/PathUtils.js
modules/__tests__/PathUtils-test.js

Fixes the regex for trailing slashes in PathUtils to not match /? if it
is at the beginning of a url's query params

[fixed] #1148 regex for detecting trailing slashes

---

modules/__tests__/matchRoutes-test.js

Hash links don't seem to work, as far as I can tell. The router attempts to navigate to a route that includes the hash at the end of it, resulting in a route not found error. Attached are a couple of failing tests for the issue.
Related issue: #394

Add failing tests for route matching with hash

---

modules/__tests__/Router-test.js

This is following #1574. The test you added was passing in beta3 so I added a test case which fails. Note that it's now passing against master (which is nice)! It's just to make sure we cover all cases.
This is against beta3
And this is against current master
---
If you want to test against beta3 the code needs to be adapted a bit
```jsx
describe('at a route with special characters', function () {
it('does not double escape', function(done) {
// https://github.com/rackt/react-router/issues/1574
let MyComponent = React.createClass({
render () { return <div>{this.props.params.some_token}</div> }
})
React.render((
<Router history={new MemoryHistory('/point/aaa%2Bbbb')}>
<Route path="point/:some_token" component={MyComponent} />
</Router>
), div, function () { …
```

added a test for nested routes

---

docs/advanced/DynamicRouting.md
docs/api/Route.md

Docs didn't match the recent api changes to the getComponents and getComponent functions from beta4 to rc1
```javascript
// changed from
getComponents(callback)
// to
getComponents(location, callback)
```

Docs update on getComponents

---

docs/Glossary.md

Wasted a few minutes trying to figure out why my `onEnter` hooks weren't firing properly :smile:

Correct RedirectFunction signature in Glossary

---

examples/auth-flow/app.js

Fix usage of onEnter function from the auth-flow example.
Was giving this error:
```
Uncaught TypeError: Cannot read property 'indexOf' of null
```

Fix error in auth-flow example

---

README.md
doc/README.md

- Removes the link to the old github.io site (currently redirected to the repo's master/1.0.x docs)
- Adds a link to the 0.13.x branch's docs
- Adds a README w/ a table of contents for the 0.13.x docs

Create table of contents for 0.13.x docs

---

docs/api/Link.md

Updates Link's activeClassName docs to reflect v1.0 behavior: activeClassName is now opt-in and no longer defaults to "active".

Update activeClassName docs

---

docs/README.md

The Recipes page was removed by @mjackson in 59aadc29f, but it was still
linked to from the readme.

Remove dead "Recipes" link from docs/README.md

---

package.json

QueryUtils depends on qs, but it's not in package.json
line 9 
```
var _qs = require('qs');
```

add qs to package.json

---

modules/QueryUtils.js
package.json

The QueryUtils module is the only one with a dependency on the `qs` module (as raised in #1985), but it isn't in use anywhere in the library. We can remove both it and its `qs` dependency.

Remove unused QueryUtils

---

docs/guides/basics/RouteConfiguration.md

Noticed that the link to the documentation section for routes didn't span the entire word.

Fixed typo in link.

---

UPGRADE_GUIDE.md

I just went through the process of upgrading from `0.13.x` to `1.0` as per the upgrade guide and made a few changes that should hopefully make things a little easier:
- Added a link to the [`history` package](https://github.com/rackt/history); not everyone will necessarily be familiar with it and there is no harm in being a little more explicit to avoid confusion with any other package that deals with history
- It wasn't clear that `DefaultRoute` was gone, so I explicitly added a note - this is in line with saying explicitly that `RouteHandler` is gone in the following section
- Fixed a really minor grammatical error - it just caught my attention, I couldn't help myself!
Let me know what you think, hopefully these are helpful changes for everyone and not just myself - feedback/suggestions …

Upgrade guide

---

modules/__tests__/matchRoutes-test.js
modules/__tests__/serverRendering-test.js
modules/useRoutes.js
package.json

#2169 was just a docs tweak. This has some real meat. You shouldn't get some upstream deprecation warnings from `history` with this.
The build is still failing on isActive because of be371966. The internal state isn't being populated initially by `useRoutes` when using `match`. I'll see if I can get to that one too.

Update for history createLocation deprecation

---

docs/guides/advanced/ServerRendering.md

`createLocation` is [now deprecated](https://github.com/rackt/history/pull/79) and so are these docs :smile:

Update server rendering docs

---

modules/__tests__/transitionHooks-test.js
modules/computeChangedRoutes.js

Fixes #2122 
Any time the query params change, onLeave and onEnter hooks will both be called. 
If comparing `state.location.query` instead of `state.location.search` would be more appropriate, let me know and I can adjust the PR–`state.location.search` was just easiest since it's a simple string comparison.

Call transition hooks when query changes for useQueries

---

modules/Redirect.js
modules/__tests__/Redirect-test.js

This is a rough implementation that can be cleaned up further, but I wanted to request for comments on the approach first before cleaning the implementation.
It adds `patterns` to `nextState`/`match` (State) in order to find the parent's matched pattern before appending to it. It can instead traverse parent routes and prepend the paths until it finds the first route that contains `/`. That adds more logic to Redirect but I'm happy to do that as well.
Resolves #1905

[added] Support <Redirect to="relative/path">

---

README.md

Just installed react-router via the previously given command (which installs v0.13) and spent an hour figuring out why I get errors when just following the tutorial code. Turns out the tutorial code assumes you installed v1. This is really confusing.

Update README.md to help new users install v1

---

UPGRADE_GUIDE.md

I thought it would make the upgrade process easier for other users by making it clearer which props must be passed via props and which can still be passed via context.
As far as I can make out, only history and location are available via context.

Clarify available State information in context

---

docs/guides/advanced/ServerRendering.md

Reverts rackt/react-router#2192
[Using `createLocation` statically is deprecated](https://github.com/rackt/history/commit/21f8dbdeaec458538882f72a4c5a5c2fad2b34da) and this code will generate warnings (and eventually errors) with recent versions of `history`.

Revert "Update ServerRendering.md"

---

modules/Link.js

This pull request adds the ability to open links in new windows or tabs (or frames or browsing contexts in HTML5), using the `target` attribute of the `<a>` tag. Basically, if `target` is set, we let the browser handle the transition itself (similarly to when we middle-click on a link to open it in a new tab).
See #1510 and #2188 for more discussions about this requirement.

Ability to open links in new window/tab, using target="_blank"

---

docs/guides/basics/RouteMatching.md

Yesterday I spent a lot of time to figure out how to do this. In fact, I found like 4-5 search results regarding the same issue. There is no place that actually tells you that you can do something like "/:user?/brands/:brand?/home" using this syntax.

[Docs] Add path syntax example

---

modules/Link.js
modules/__tests__/Link-test.js

Fix the hash prop on Links

---

modules/__tests__/IndexLink-test.js
modules/isActive.js

This mirrors the logic in matchRouteDeep.
Ran into this bug earlier just now. This is just a tactical fix for now to get the logic in sync with the route matching logic.

[fixed] Don't match empty routes for isActive

---

README.md
modules/__tests__/Link-test.js
package.json

Since we don't plan on making any breaking changes in the history package without a major version bump, we should be able to just have a peer dep on history `~1`. Please review and merge if it looks good to you, @taion.
Fixes #2211
Fixes #2252

[added] Peer dependency on history package

---

docs/guides/testing.md

I put together some updated testing docs for React-router 1.x.
There wasn't much to write as testing should "just work" with react-router 1.x but mainly this doc helps those upgrading from prior testing setups.
As I do more testing and run into issues, I can add more to the docs.
Re issue #2149

Updated testing docs for 1.x

---

docs/API.md
docs/guides/advanced/DynamicRouting.md

Add documentation for `getIndexRoute`. Fixes #2283

Document getIndexRoute

---

UPGRADE_GUIDE.md
docs/API.md
modules/Link.js
modules/__tests__/Link-test.js

For consistency with React v0.14, don't prevent the transition if the onClick handler returns false.
Closes #2219 
I added a basic test case to cover the default being prevented. Also reworded the IndexLink part of the upgrade guide slightly because it was a bit confusing - can split that out into a separate PR if desired though.

[changed] Preventing transition from onClick

---

UPGRADE_GUIDE.md

I was having difficulty figuring out what happened to `getQueryParams` – I think this note in the upgrade guide is worthwhile.

Add getQueryParams() -> location.query to upgrade guide

---

modules/__tests__/IndexRoute-test.js
modules/matchRoutes.js

This test is related to #1939 which was closed, but not fixed.

handle nested IndexRoute in path-less route

---

docs/guides/advanced/DynamicRouting.md

getIndexRoute expects a route, whereas the example was sending a component.

Fix getIndexRoute example in DynamicRouting.md

---

examples/breadcrumbs/app.css
examples/breadcrumbs/app.js
examples/breadcrumbs/index.html
examples/index.html

@knowbody a couple of concerns:
- not super happy with the static properties, although I needed to set up `path` as well to make `links` from breadcrumbs working. 
- it won't work with any HOC's, so use case is pretty limited. In my custom project, I was using a HOC called `@RouterPage(title)` that was the top-most HOC assigning these static properties for use with router and with DocumentTitle. Quite verbose, but it was working efficiently.
And generally it feels like styling and breadcrumbs component can be (and should) be extracted to a separate component, but just wanted to check if we are heading in the same direction first ;)
Commits to be squashed into one later.

Breadcrumbs example

---

modules/RoutingContext.js
modules/__tests__/RouteComponent-test.js

Per https://github.com/rackt/react-router/pull/2336#commitcomment-13933868.
I'm not entirely comfortable with this - in a vacuum I'd prefer we not have `location` on child context either, but I mostly agree with the point that getting rid of it is not worth making another breaking change.
Might want to consider somehow deprecating it anyway, though.

[removed] params from RoutingContext child context

---

docs/guides/advanced/ConfirmingNavigation.md

Closes #2364 
Here's one way to let users easily use `Lifecycle` when using ES6 classes. Zero LoC change on our end!
I think this is a bit cleaner than implementing on our wrapper - it'd essentially just be duplicating code from a perfectly good library that's already there.

Document confirming navigation with ES6 classes

---

docs/guides/basics/RouteMatching.md
modules/PatternUtils.js
modules/__tests__/PatternUtils-test.js
modules/__tests__/formatPattern-test.js
modules/__tests__/getParams-test.js
modules/__tests__/matchRoutes-test.js

As discussed #2284, this pull request add support to greedy splat `**`.
Example of matching:
```
/*/c matches /you/are/okay/c
/*/c does not match /you/are/cool/c
/**/c matches /you/are/cool/c
```
Fix #2284

[added] Greedy splat (**)

---

docs/API.md
modules/__tests__/isActive-test.js
modules/isActive.js

Right now there's no way in `isActive` to require that a given query key is missing in the currently active query.
This makes `null` values on the specified query match absent or otherwise `null`-y values on the active query.

[added] Handle undefined query values in isActive

---

docs/guides/basics/RouteMatching.md

Changing the file extension in 
```js
<Route path="/files/*.*">           // matches /files/hello.jpg and /files/path/to/hello.jpg
```
to
`// matches /files/hello.jpg and /files/path/to/hello.html`
So we can make it clear that this path takes any file extension. As opposed to the next example that only accepts `jpg`.

Change file extension in example

---

modules/PatternUtils.js
modules/isActive.js
modules/matchRoutes.js

Fixes https://github.com/rackt/react-router/issues/2355
This is mostly straightforward, except for adding some special-casing to check that we only match at path boundaries.

[fixed] Match routes piece-by-piece

---

UPGRADE_GUIDE.md

I've been bitten by this before and subsequently seen it as a source of questions on Stack Overflow and Reactiflux.
It's especially tricksy because `Router` is commonly used when importing 0.13.x.

Add an "Importing" section to the upgrade guide

---

modules/Route.js

Fixes https://github.com/rackt/react-router/issues/2438
Unless I'm missing some reason that we need to keep this around. This is out last chance to delete it before semver means we can't do so without cutting a 2.x.

[removed] Remove deprecated handler prop on Route

---

examples/animations/app.js
examples/nested-animations/app.js
package.json

Fix animations examples

---

modules/Router.js
modules/__tests__/Router-test.js

Closes #2088 
Another attempt at #2376. The tests illustrate the intended usage. I think this is a much less gross API on the React Router side.

[added] Support custom RoutingContext on Router

---

modules/PatternUtils.js
modules/PropTypes.js
modules/__tests__/isActive-test.js
modules/__tests__/matchRoutes-test.js
modules/isActive.js
modules/matchRoutes.js

This fixes the behavior referenced https://github.com/rackt/react-router/pull/2421#issuecomment-152698992, per https://github.com/rackt/react-router/pull/2425#issuecomment-152625621.
I add the check in `matchRoutes` to ensure that index routes actually don't have paths set (since you might not hit the prop type check if you're using plain route objects).
I've also added a couple of extra test cases to cover more routing and matching.
@mjackson Can you take a look when you have a chance? If we don't want to ignore extraneous slashes between path elements (analogous to what we do at the end of a path), then the previous implementation of "active on index" is probably better.

[fixed] Index routes with extraneous slashes

---

CHANGELOG.md

Closes #2463
This at least updates the v0.13.x branch and fixes the changelog present there. Can't do anything about the v0.13.5 tag that's already set.

Fix v0.13.5 changelog

---

modules/IndexRoute.js
modules/Route.js

Fix prop types on route components

---

.npmignore
package.json

We currently have a bunch of random stuff like `coverage/` and `.travis.yml` in our distributed tarball. IMO it's easier to keep track of things when whitelisting rather than blacklisting from `package.json`, and easier to tell what we're doing.
This does drop `modules/` from the tarball, though - I do feel that it's pretty standard to exclude the pre-transpiled ES6 sources from most builds (React does this, for example), but - Chesterton's fence and all.

Use whitelist instead of blacklist for packaging

---

CHANGES.md
docs/API.md
modules/Router.js
modules/__tests__/Router-test.js

I'd really love for the route state to be passed into the `onUpdate` callback `<Router />` prop. In particular, I'm working on some ReactRouter based integration for another project and found maintaining the scope of `onUpdate` in the callback to be troublesome.
This is a follow up to https://github.com/rackt/react-router/issues/1539. Things got a little quiet there so I thought I'd just send a PR to get the conversation going again.
Really, I suppose it's more a shame that state isn't provided to the callback inside of `ReactComponent::setState`. But here we are :smile:.
Also: awesome work on the 1.0 API. This is really top notch.

Pass route state to onUpdate callback

---

index.html

Now that we have a v1.0.0, the docs page should probably point there for now as a stopgap.
The goal is to limit the risk of confusing users by showing them documentation for features on master that aren't yet in the stable release.

Point to v1.0.0 docs instead of master docs

---

.travis.yml
package.json
tests.webpack.js

This is the rest of #2517, &c. Largely no-op but we should merge to clean/freshen these.

Fix build configs

---

.babelrc
modules/IndexRedirect.js
modules/IndexRoute.js
modules/Link.js
modules/Redirect.js
modules/Route.js
modules/Router.js
modules/RoutingContext.js
modules/__tests__/RouteComponent-test.js
modules/__tests__/Router-test.js

By removing usages of [class-properties](https://babeljs.io/docs/plugins/transform-class-properties/) which are still experimental, ie8 is fully supported. We also protect against it happening in the future with a blacklist of that feature in babel.

Remove static properties for ie8 compatibility

---

package.json
tests.node.js

Closes https://github.com/rackt/react-router/issues/2538
Just the SSR test for now - we can add more later if we want, but this is the one we really care about.
Not generating coverage for this right now, since we're not merging coverage data across platforms.

Run the server rendering test against Node

---

.gitignore
CHANGES.md
README.md
package.json

Closes https://github.com/rackt/react-router/issues/2524. Replaces #2523.
~~Don't merge this, it's just a strawman to show what we'd have to change.~~

Add ES6 module build

---

examples/huge-apps/app.js
examples/huge-apps/components/App.js
examples/huge-apps/routes/Calendar/components/Calendar.js
examples/huge-apps/routes/Course/components/Course.js
examples/huge-apps/routes/Course/routes/Announcements/components/Announcements.js
examples/huge-apps/routes/Course/routes/Announcements/components/Sidebar.js
examples/huge-apps/routes/Course/routes/Announcements/routes/Announcement/components/Announcement.js
examples/huge-apps/routes/Course/routes/Assignments/components/Assignments.js
examples/huge-apps/routes/Course/routes/Assignments/components/Sidebar.js
examples/huge-apps/routes/Course/routes/Assignments/routes/Assignment/components/Assignment.js
examples/huge-apps/routes/Course/routes/Grades/components/Grades.js
examples/huge-apps/routes/Grades/components/Grades.js
examples/huge-apps/routes/Messages/components/Messages.js
examples/huge-apps/routes/Profile/components/Profile.js

Fixes https://github.com/rackt/react-router/issues/2588
This is all just bit shoving. This example is a bit structurally outdated, though - it really ought to be using `indexRoute`s, IMO.

Update huge-apps example

---

CHANGES.md

In version 13 there was no `getQueryParams()`. `getQuery` returns the object.
https://github.com/rackt/react-router/blob/0.13.x/doc/06%20Mixins/State.md

Remove getQueryParams()

---

.eslintrc
CHANGES.md
docs/API.md
modules/History.js
modules/Lifecycle.js
modules/RouteContext.js
modules/RoutingContext.js
modules/__tests__/RoutingContext-test.js
modules/deprecateObjectProperties.js

Peep the commit message.
- I could use some help updating all the stuff in `/docs`. Don't worry about CHANGES.md. The changes coming down the pipe after this will require a more cohesive explanation of how to update your code than we can do with each individual commit that changes API.
- could use help updating all of OUR code to the new API (particularly in `Link` and in our tests), but that should maybe be a separate pull request just to "prove" that the old API still works (afaict it does, tests pass anyway!).

1.1 context.router

---

CHANGES.md
docs/API.md
modules/Router.js
modules/RoutingContext.js
modules/__tests__/Router-test.js
modules/__tests__/RoutingContext-test.js

We shouldn't need to deprecate <Router RoutingContext> since I don't think we ever actually documented it.
As was the case w #2647, we shouldn't need to update CHANGES.md just yet. We'll need to update it more comprehensively when everything lands.

Add <Router render> prop, remove <Router RoutingContext>

---

CHANGES.md
docs/API.md
docs/guides/advanced/ServerRendering.md
modules/Router.js
modules/RouterContext.js
modules/RoutingContext.js
modules/__tests__/RouterContext-test.js
modules/__tests__/serverRendering-test.js
modules/index.js

We only export `router` to context now and would
like to start a precedent that components that
export a context are named after what they export
closes #2650

Rename RoutingContext -> RouterContext

---

modules/__tests__/isActive-test.js
package.json

query-string serializes arrays differently from qs

Fix isActive-test

---

.babelrc

Since we're not using ES6 classes, this isn't a problem anymore. Future usage will break IE8, but that's only if we switch back to classes or explicitly want to drop IE8 support (which it seems like we might at some point anyways).

Don't blacklist es7 class properties

---

docs/guides/advanced/NavigatingOutsideOfComponents.md

This example confused one of my students as it shows a `Router` without the required children/routes. I added routes to make it valid, without making the actual point of the example less obvious (I hope).

tweaked example in NavigatingOutsideOfComponents

---

modules/__tests__/serverRendering-test.js

During the rename to RouterContext, the server_Rendering-test.js was only partially updated. It should be importing RouterContext not RoutingContext.

RoutingContext should be RouterContext in server test

---

modules/RouterContext.js
modules/__tests__/RouterContext-test.js

Also rewrite how `router` is formed to keep it concise.

Add more functions from history to context.router

---

examples/active-links/app.js

I find that when it match the route "/users/ryan", it should show the user's id, but it won't.
I think the "Users" should render its children node, so I add some code to achieve this.

Render user information when under user route

---

docs/API.md

The Tab example was really helpful to address what I think is a very common case (following bootstrap's navigation markup). Since it's likely that the developer would also need to use IndexLink, I just added a couple tweaks here to allow for it. Also, I believe it's preferable to use `const` over `let` when a variable is not meant to change. So I switched a couple of declarations.

Updates tab example to allow for IndexLink as appropriate.

---

docs/API.md

We can avoid the use of <IndexLink/> entirely, since it's just a simple wrapper around <Link/> that adds a single prop.
See some discussion in #2692.

simplify the Tab example a bit

---

README.md

Changed all docs and examples links in the README to reference latest, to help with #2713

Reference `latest` branch in docs and example links in README

---

.travis.yml
modules/__tests__/Link-test.js
modules/__tests__/isActive-test.js
package.json

This should be published as `1.0.3`. Should fix both the warnings from `history` (removed in `1.16.0`) and any errors about unmet peerDependencies.
Also, note this is on the `1.0.x` branch.

Switch back to a caret range for history

---

examples/index.html

It doesn't link to anything,
`Cannot GET /shared-root`

Remove shared root example

---

scripts/release.sh

No longer needed with any reasonably recent npm.

Remove history npm workaround

---

scripts/release.sh

Reverts rackt/react-router#2756
fml
npm3 vendored in the file from fstream-npm, so the release notes about how this was fixed on npm3 were just wrong. Sorry.

Revert "Remove history npm workaround"

---

modules/index.js

[`createMemoryHistory` is documented](https://github.com/rackt/react-router/blob/54ec6a81d759bb78b17687d6b0689b0fc6e49873/docs/guides/basics/Histories.md#creatememoryhistory) as being importable from the React Router package but isn't being exported in 2.0.0-rc3

Export createMemoryHistory

---

modules/deprecateObjectProperties.js

This avoids spurious deprecation warnings in dev tools.

Make deprecated properties non-enumerable

---

upgrade-guides/v2.0.0.md

Since `hashHistory` is a singleton and not a function, it can't be used with `useRouterHistory`.
I've updated the guide to a working guide, but maybe `createHashHistory` should also be exported by `react-router`, so the user doesn't need `history` as an explicit dependency for this case? Or even better: the exported `createHashHistory` could be used without `useRouterHistory` …

Upgrade Guide Correction for Custom Histories

---

examples/transitions/app.js

Added contextTypes(router) to the Form component of the transitions example and also change this.props.router to this.context.router to get the setRouteLeaveHook working.

Small fix for the transitions example for 2.0

---

modules/__tests__/serverRendering-test.js
modules/match.js

Will make redux-simple-router integration more clear.

Add passing custom histories to match

---

upgrade-guides/v1.0.0.md

Noticed this while reading through the docs.  I think it just needed a leading slash.
Test Plan:
- Previewed and opened the link, seemed to work.

Fix "Confirming Navigation" link

---

docs/API.md

The generated ID is `contextrouter`: https://github.com/rackt/react-router/blob/master/docs/API.md#contextrouter

Fix link to context.router in API documentation

---

docs/guides/advanced/ServerRendering.md

Just some documentation per https://github.com/rackt/react-router/issues/2834#issuecomment-168576182.

Give some guidance for 404 with catch-all routes

---

upgrade-guides/v2.0.0.md

Small update to the V2 upgrade guid.  In V2, custom query parsing needs to be done via custom histories:  https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md#using-custom-histories
Fixes #2842

Updates docs for custom query parsing in V2

---

docs/guides/advanced/ConfirmingNavigation.md

I think in rc4 the API is `setRouteLeaveHook` instead of `setLeaveHook` ?

setRouteLeaveHook over setLeaveHook

---

docs/guides/basics/RouteConfiguration.md
examples/auth-flow/app.js
examples/auth-with-shared-root/config/routes.js
modules/Redirect.js
modules/TransitionUtils.js
modules/__tests__/serverRendering-test.js
modules/__tests__/transitionHooks-test.js
modules/createTransitionManager.js
upgrade-guides/v2.0.0.md

Use location descriptor in onEnter redirect

---

modules/Router.js
modules/__tests__/_bc-serverRendering-test.js
modules/__tests__/serverRendering-test.js

Improve support for server rendering async routes

---

docs/guides/testing.md

"Lastly, anywhere you have the following, needs to be replaced with this: [...] with this:" doesn't make sense.

Clarify updating testing setup from 0.x to 1.x

---

modules/AsyncUtils.js
modules/matchRoutes.js

Unwind recursion in loopAsync when possible

---

docs/guides/advanced/ServerRendering.md
modules/Router.js
modules/__tests__/serverRendering-test.js
modules/createTransitionManager.js
modules/match.js

Fixes https://github.com/rackt/react-router/issues/2935
https://github.com/rackt/react-router/pull/2883 was actually busted and had a test that didn't cover what it was supposed to.
~~In an ideal world we'd just use the same `history` and `transitionManager` for `match()` and `<Router>` on the client side, but the deprecation wrapping API messes with that too much, so this might be the best we can do for now.~~

Fix initial routing state after match

---

upgrade-guides/v2.0.0.md

Per discussion in #2991, the second example is a fragile pattern. As @taion mentioned:
> I don't think we really guarantee that you can just split out push like that, instead of calling it via router.push.
`browserHistory` is undefined in non-browser environments, so accessing `browserHistory.push` throws. It also relies on using the same history passed to `Router`, which may (conditionally) change.
Let me know if you'd prefer adding a warning over removing the example entirely.

Remove misleading example from upgrade guide

---

docs/guides/advanced/NavigatingOutsideOfComponents.md

This should import from the base module.

docs(example): fix module name

---

upgrade-guides/v2.0.0.md

The documentation previously said the hook for a customized query stringification was `stringifyQueryString` but key should actually be `stringifyQuery` which can be seen in the History module here:
https://github.com/rackt/history/blob/master/modules/useQueries.js#L32

Update v2.0.0 Upgrade Documentation - stringifyQueryString -> stringifyQuery

---

modules/__tests__/useRouterHistory-test.js

When using `basename` and hitting a redirect, the `basename` gets swallowed. I'm not sure if this is the correct place for the failing test, but it illustrates the issue.
After hitting `/redirect-to-inbox`, the basenames array should contain `[ '/foo', '/foo', '/foo' ]`. The last element however is empty: `[ '/foo', '/foo', '' ]`. This results in a wrong path: instead of `/foo/inbox` we get `/inbox`.
I've no idea how to fix this, but I hope the failing test helps!

Transition hooks swallow basename (failing test)

---

modules/__tests__/serverRendering-test.js
modules/createMemoryHistory.js

Fixes #3003
Looks like we broke this inadvertently back in #2743. Specifically, we did so here: https://github.com/rackt/react-router/pull/2743#discussion_r48084686 
Users should use a custom history from now on, but this maintains BC with 1.0.

Add back basename support in match()

---

docs/API.md
docs/Introduction.md
docs/guides/DynamicRouting.md
upgrade-guides/v1.0.0.md

The folder `basics` doesn't exist anywhere

Fix broken links in documentation

---

modules/__tests__/transitionHooks-test.js
modules/createTransitionManager.js

~~Needs test cases.~~
Fixes #3106
There will be some edge cases (e.g. if the parent applies a key when rendering the child route) that this will mess up, but it's the best we can do for now.

Don't tear down leave hooks when not leaving

---

docs/API.md

The examples linked to in the API doc for `IndexRedirect` show no example of it being used and aren't actually that relevant to it. I have removed that link and added an example.

Improved IndexRedirect documentation

---

docs/guides/ServerRendering.md

https://github.com/reactjs/react-router/blob/master/docs/API.md#match-routes-location-history-options--cb exists, the previous link didn't!

Fixed bad link in docs

---

CHANGES.md
modules/__tests__/transitionHooks-test.js
modules/computeChangedRoutes.js

/users/123/assignments/456
/users/789/assignments/456
The transition hooks were called on assignments, but not users, now it calls them on both.
If a parent route is left/entered, we should leave and enter all the children regardless of their params. Imagine this exact example when you've got a data loading lib that depends on the leaving/entering routes. You'd see user 123's assignment and not user 789's.

Transition bug

---

docs/guides/IndexRoutes.md
docs/guides/RouteConfiguration.md

It looks like we're reaching consensus on https://github.com/reactjs/react-router/issues/3172, so let's update the guide to follow the new recommended pattern.

Update decoupling UI from URL pattern

---

docs/API.md

The `<Link>` API has been updated in 2.0 ([see this](https://github.com/reactjs/react-router/blob/master/upgrade-guides/v2.0.0.md#link-to-onenter-and-isactive-use-location-descriptors)).
The library informs the user via console messages when deprecated attributes are used: ![console](https://cloud.githubusercontent.com/assets/767959/13775417/a8fd2284-eaa4-11e5-8317-0827c0be35b0.jpg)
This PR updates the API docs for `<Link>` to reflect these changes.

Update API docs for Link#to

---

docs/API.md

Add list of exported PropTypes.
Specified the behavior of the falsy PropType

Docs: add list of exported PropTypes

---

modules/TransitionUtils.js
modules/__tests__/transitionHooks-test.js
modules/computeChangedRoutes.js
modules/createTransitionManager.js

closes #2547
Adds an onChange hook for Routes, which allows routes to respond to non leave/enter changes.
I changed up the signature a bit, which may be more self serving than anything else, but I also think it nicely mirrors the React hooks. In particular onChange is called with `prevState` along with `nextState` and `replace`. Which just makes checking for the particular change you are interested in easier. It also allows for not doing any work in the case of a location not changing in a way that is relevant to the particular route. Let me know tho if I'm off base there. The diff is a bit noiser then it might otherwise be if I left that out

[added] onChange route hook

---

modules/PatternUtils.js
modules/__tests__/getParams-test.js

Fixes https://github.com/reactjs/react-router/issues/3215

Speed up pattern matching

---

package.json

This was previously present to support installing from source.

Don't need to include source in distribution

---

modules/PatternUtils.js
modules/__tests__/_bc-Link-test.js
modules/__tests__/_bc-isActive-test.js
modules/__tests__/isActive-test.js
modules/__tests__/matchPattern-test.js

On further thought, the current behavior, despite being tested, is clearly just buggy. This will make life easier and opens the door to having a much simpler algorithm for checking isActive in the indexOnly sense.

Support trailing slashes, not extraneous ones

---

docs/guides/testing.md

Really tiny update to the testing tutorial - changed `jest.dontMock` to `jest.unmock`, removed the bit about es6 module syntax not being compatible with `jest.dontMock` and added jest to the list of dependencies.

Updated jest example in testing.md

---

docs/API.md

New users assume Link tags are basically equivalent to A tags. It is a rude awakening to discover relative links do not work.

Document lack of support for relative links

---

examples/active-links/app.js
examples/animations/app.js
examples/breadcrumbs/app.js
examples/dynamic-segments/app.js
examples/nested-animations/app.js
examples/query-params/app.js
examples/sidebar/app.js

Added Component to import statement to save some space. We have two choices.
Either to do React.Component with all other than huge-apps, for
huge-apps to be an example. Or we could use Component rather than
React.Component in the all of the examples.

Final Picky fix with ES6

---

docs/guides/Histories.md

This commit simply adds a preceeding forward slash to the basename example. In my testing (using `v2.0.1`) this is necessary for the basename routing to be applied correctly and adding this to the documentation may provide a bit more clarity for others using the basename option.

Update basename example

---

docs/guides/ComponentLifecycle.md

Add order hints to lifecycle hook docs

---

modules/PatternUtils.js
modules/__tests__/_bc-Link-test.js
modules/__tests__/_bc-isActive-test.js
modules/__tests__/isActive-test.js
modules/__tests__/matchPattern-test.js

Breaking change from #3158. Let's re-revert this back into master after a 2.1.1 can be cut.

Revert "Support trailing slashes, not extraneous ones"

---

examples/index.html
examples/route-no-match/app.js
examples/route-no-match/index.html

* Hope I have done is correct! This example will help to show "page not found" implementation on client side. Refs my comments on https://github.com/reactjs/react-router/issues/458
* If its correct then I would like to update the doc too for Page not found on client side. It might help in https://github.com/reactjs/react-router/issues/2933 fix "Document how to make a client-side "not found" route (i.e. with <Route path="*" component={NotFound} />)" under Potential Improvements

Adds example to show "page not found" implementation

---

docs/Troubleshooting.md
docs/guides/ConfirmingNavigation.md
modules/PropTypes.js
modules/__tests__/RouterContext-test.js
modules/__tests__/transitionHooks-test.js
upgrade-guides/v2.0.0.md

Depending on how #3205 shakes out, this provides updated and correct PropTypes.

Updated PropTypes

---

examples/auth-flow-async-with-query-params/app.js
examples/auth-flow-async-with-query-params/index.html
examples/index.html

Simple workflow that uses querystring parameters to determine if a user can look at a page or not. Parameters can come from a form submission, or from an url with those parameters in.
While I understand this is definitely not the best way to do any sort of authentication, I was recently working on an [app](http://contentful.github.io/discovery-app-react/) where this was desirable.
I extracted this flow out of that small app where the usage workflow can be something like:
- new user comes in and uses the form to authenticate
- user can then share the url with the auth parameters in the querystring if desired
If this is too much for an example I can try and slim it down to an async onEnter example, as that is my main reasoning for adding this. As far as I can tell there is currently no …

Add example for async auth with querystring params

---

modules/Link.js
modules/__tests__/Link-test.js

`<Link />` always adds the `class=""` attribute even when it's not defined or is active. When you do server rendering you don't want unnecessary attributes.

Removed unnecessary className on Link

---

.gitignore
package.json

This makes us consistent with Redux

Move ES module build to es/

---

docs/API.md
docs/guides/DynamicRouting.md
examples/auth-with-shared-root/config/routes.js
examples/huge-apps/routes/Calendar/index.js
examples/huge-apps/routes/Course/index.js
examples/huge-apps/routes/Course/routes/Announcements/index.js
examples/huge-apps/routes/Course/routes/Announcements/routes/Announcement/index.js
examples/huge-apps/routes/Course/routes/Assignments/index.js
examples/huge-apps/routes/Course/routes/Assignments/routes/Assignment/index.js
examples/huge-apps/routes/Course/routes/Grades/index.js
examples/huge-apps/routes/Grades/index.js
examples/huge-apps/routes/Messages/index.js
examples/huge-apps/routes/Profile/index.js
modules/__tests__/Router-test.js
modules/deprecateObjectProperties.js
modules/getComponents.js
upgrade-guides/v2.2.0.md

Fixes https://github.com/reactjs/react-router/issues/3262

Call getComponent with nextState instead of location

---

modules/__tests__/matchRoutes-test.js
modules/matchRoutes.js

Properly continue match after pathless routes

---

modules/__tests__/isActive-test.js
modules/isActive.js

Now that we've finally landed #3158 (hopefully for good), we can optimize `isActive` a bit.
Paths are fully canonical now except for possibly the trailing slash.
Thus, for checking `indexOnly` active state, we only need to verify that the paths are the same, net of leading/trailing slash normalization. This ought to be a lot faster than actually running the path match.
Additionally, this condition is also sufficient (but not necessary) for a route match in the general case.

Check for exact path match before checking routes

---

modules/getComponents.js

Don't use Object.assign

---

CHANGES.md
modules/__tests__/applyRouterMiddleware-test.js
modules/applyRouterMiddleware.js
modules/index.js

I'll add some docs in @knowbody's new docs site thing, but here's the quick version:
```js
// end users put the middleware in the `render` prop
<Router render={applyRouterMiddleware(useFoo())}/>
// a middleware returns an object w/ two methods
const useFoo = () => ({
// this will wrap `RouterContext` to participate in rendering at the top level of
// the Router rendering tree
renderRouterContext: (child, renderProps) => (
<FooRootContainer>{child}</FooRootContainer>
),
// this will wrap the route components when RouterContext renders them
renderRouteComponent: (child, routeComponentProps) => (
<FooContainer>{child}</FooContainer>
)
})
// typically these things just add something to context
const FooRootContainer = React.createClass({
propTypes: { children: React.PropTypes.node.isRequired …
```

added applyRouterMiddleware

---

docs/guides/MinimizingBundleSize.md

This is the more correct way of addressing #3333. webpack 2 users should configure webpack to look at jsnext:main instead of importing from react-router/es6, which is not intended to be supported.

Improve instructions for users of ES modules

---

.gitignore
package.json

Fixes #3333
Revert "Move ES module build to es/ (#3295)"
This reverts commit d4f8d3cad70fb0a79629221b5cf47efb552a97d1.

Move ES module build back to es6/

---

docs/API.md

Explain usage of `context.router` for:
* Components created with `React.createClass`
* Components created with ES classes extending `React.Component`
* Components created as stateless functions

Expanded API docs for `context.router`

---

docs/Glossary.md

#2933 is the larger goal
#3359 raises my case for why this specific doc update should be prioritized

Update glossary to properly document greedy string matching

---

docs/API.md
docs/Troubleshooting.md
docs/guides/ConfirmingNavigation.md
docs/guides/NavigatingOutsideOfComponents.md
examples/auth-flow-async-with-query-params/app.js
examples/auth-flow/app.js
examples/auth-with-shared-root/components/Login.js
examples/confirming-navigation/app.js
examples/master-detail/app.js
examples/passing-props-to-children/app.js
modules/__tests__/withRouter-test.js
modules/index.js
modules/withRouter.js
package.json
upgrade-guides/v2.0.0.md
upgrade-guides/v2.4.0.md

Closes #3350.
This is a little funky because we have to set a static on the composed component. I was originally just going to set `Component.contextTypes` and call it a day, but that creates a side effect. Is there any downside or error in the proposed solution? `hoist-non-react-statics` is nice to keep from running into unintended surprises (especially if the component is wrapped multiple times).

Add withRouter HoC

---

upgrade-guides/v2.4.0.md

No Login component has been defined, i guess "Page" was meant

Fix example for withRouter

---

modules/Link.js

When checking to see if target was supported on the Link module, I first checked props and noticed it wasn't there, but then noticed it was used below in the code. This might help other developers quickly determine that target is a supported prop.

Add "target" as an optional prop to Link module

---

docs/Troubleshooting.md

This solution is an improvement over the `createElement` method in that it passes eslint-plugin-react problem https://github.com/yannickcr/eslint-plugin-react/issues/512, and that conceptually, I think a middleware is the place to do these kind of manipulations.

Add additional props passing method

---

docs/guides/MinimizingBundleSize.md

In practice, tree-shaking does not currently allow for the kind bundle size reduction achievable using direct module imports, so shouldn't encourage it as an option for minimizing bundle size.
@Rich-Harris explains it here: https://github.com/reactjs/redux/pull/1369#issuecomment-210853615.
Specifically, because of the way we set up the singleton histories, those will not tree-shaken out, as noted by @tomduncalf in https://github.com/reactjs/react-router/issues/3387#issuecomment-215051101.
The best approach then is to import from the ES module directory, but I don't think we should encourage people to import from `react-router/es6/*` when we want to move that to `react-router/es/*`. Maybe we should maintain an ES module build in both `/es` and `/es6`.

Remove section about ES modules and tree-shaking

---

docs/API.md
upgrade-guides/v2.0.0.md
upgrade-guides/v2.4.0.md

I don't want to anachronistically update the v2.x upgrade guide to reference libraries that didn't exist at the time, but it's worth noting that the API to scroll-behavior has in fact changed.

Add version caveats for scroll-behavior docs

---

modules/ContextUtils.js
modules/Link.js
modules/RouterContext.js
modules/__tests__/Link-test.js

The second attempt to fix #470, thereby unbreaking every project that uses React Redux with React Router. (The first attempt was #3429.)
I’m mostly using the snippets @taion wrote in https://github.com/reactjs/react-router/pull/3429#issuecomment-217048841 and https://github.com/reactjs/react-router/issues/470#issuecomment-217046400 as they work great, with minor tweaks to accommodate the overall project code style. I tested this on a few example projects I have, and they seem to work (even with React Redux `connect()` optimizations which was the goal.)
All existing tests are passing.
@taion expressed a desire for this to be separated from the router code. I don’t disagree but I personally just won’t have the time to maintain it, so I’m not ready to do this. I’m also not 100% sure that …

Make <Link> work with static containers (take two)

---

modules/ContextUtils.js

- Use separate context object
- Use correct subscribe method
I'm putting this PR here ahead of pulling this out into a separate library just for the sake of visibility. This fixes a couple of my bugs in the original ContextSubscriber implementation. After this, I'll pull this out into a separate library.

Fixes to ContextSubscriber

---

modules/ContextUtils.js
modules/Link.js
modules/RouterContext.js

As discussed in https://github.com/reactjs/react-router/issues/3439, these are implementation details and are better implemented as mixins so that it’s easier to kill them later. They don’t leak into public API, and React mixin merging behavior comes in handy here.
This way the hierarchy stays flat but we work around https://github.com/facebook/react/issues/2517.

Implement ContextUtils as mixins

---

modules/Router.js
modules/RouterUtils.js
modules/__tests__/Router-test.js
modules/__tests__/RouterContext-test.js
modules/__tests__/serverRendering-test.js
modules/match.js

Not sure if this is a great way to do it but let’s start here. Partially fixes #3325—at least for my use cases.
I’m not sure how to put `route` there because it depends on how deep you are. So I just limited it to `params` and `location`.

Attach current location and params to context.router

---

modules/ContextUtils.js
modules/Router.js
modules/__tests__/withRouter-test.js
modules/withRouter.js
package.json

Make withRouter() update inside static containers

---

docs/API.md
modules/__tests__/withRouter-test.js
modules/withRouter.js

Fixes #3439 for good as discussed in https://github.com/reactjs/react-router/pull/3443#issuecomment-217972967.

Pass params and location as props in withRouter()

---

modules/Router.js
modules/RouterUtils.js
modules/__tests__/withRouter-test.js
modules/withRouter.js
package.json

This will address the last checkbox on #3445 
It will also shut me up about this comment https://github.com/reactjs/react-router/issues/3445#issuecomment-218000037 😄

Update router state properties directly

---

README.md

For us poor suckers still stuck using 0.13.x, https://github.com/reactjs/react-router/tree/0.13.x/doc is a lot more useful than https://github.com/reactjs/react-router/tree/0.13.x/docs/guides (and for a long time I just assumed there was no API documentation because of this link in the readme).

fix 0.13.x docs link

---

modules/PatternUtils.js
modules/__tests__/Router-test.js
modules/__tests__/getParams-test.js
modules/matchRoutes.js

Replace decodeURIComponent with _tryDecodeURIComponent to ignore crash "URIError: malformed URI sequence".

Don't crash on invalid uri query parameters.

---

docs/API.md
docs/Glossary.md
modules/createTransitionManager.js

Basically the text for API docs is copied from `createTransitionManager`, looks like it is good, though didn't had chance to dig into router's internals.
Removed last line _Returns a function that may be used to unbind the listener._, as react-router manages this itself.
Let me know what you think. Hope got it right.
Fixes #3488

Fix setRouteLeaveHook references in docs

---

docs/API.md
modules/RouterContext.js
modules/__tests__/RouterContext-test.js

Per discussion in #3325. It's a bit awkward to have to opt in to context or wrap route components in `withRouter` in order to do things like `router.push` considering all the other routing concerns already injected into route components.
If this can go in 2.x I can retarget there. I think the issue title threw me :confused:

Add router to props for route components

---

examples/active-links/app.js
examples/animations/app.js
examples/breadcrumbs/app.js
examples/dynamic-segments/app.js
examples/nested-animations/app.js
examples/query-params/app.js
examples/sidebar/app.js

For stateless components (also called presentational/dumb components), Facebook introduced a much simpler syntax than ES6 classes.
Stateless functional components simply take props as an argument and return the element you want to render.

Define presentational components as stateless functional components

---

package.json

Hey hey,
_(formal bug report below, without as much context on my solution)_
> TL;DR; Like `react`, use `loose-envify` dependency / browserify transform to prevent browserify users from shipping development code in production.
> (Warning: big file) L248 of https://github.com/ThibWeb/react-router-browserify-build/blob/master/bundle.js#L248.
When using `browserify` to bundle a project that uses `react-router`, the default configuration of browserify transforms causes around 3kb of minified/gzipped warning messages to end up in the production bundles.
The source of the problem is that by default browserify transforms do not run on packages in `node_modules`. Configuring those to run on the whole bundle is simple, but I believe [this is counter-intuitive to the common "best …

Browserify production build is not optimized by default

---

docs/API.md
docs/guides/DynamicRouting.md
examples/huge-apps/routes/Course/index.js
examples/huge-apps/routes/Course/routes/Announcements/index.js
examples/huge-apps/routes/Course/routes/Assignments/index.js
modules/__tests__/matchRoutes-test.js
modules/deprecateLocationProperties.js
modules/getComponents.js
modules/matchRoutes.js

As it says on the label, this is an initial POC of making `params` and `remainingPathname` available to `getChildRoutes` providers. This was instigated primarily via a discussion with @taion and a another minor discussion with @timdorr.
**Use Case**
The use case this is intended to help with is in cases where the child route to be returned by `getChildRoutes` is dependent on the `params` that have been evaluated so far. For instance, if I have `:country` as the path for the current route being matched, in the `getChildRoutes` function for that route, I want to be able to access the `country` param so that I can decide which child route should be returned for that country (it can be different in different cases). Additionally, I have other cases where I want to "read forward" into …

Make `params` available to getChildRoutes providers

---

examples/auth-flow/app.js
examples/nested-animations/app.js

Just a small change to use more es2015 in two of the examples.

use es2015 object shorthand in examples

---

modules/Link.js

I foolishly moved my Link component outside of the Router. I managed to figure it out pretty quickly but the error wasn't terribly helpful. See #3225. Thoughts?

Add warning to link.js

---

modules/RouteUtils.js

We are adding a warning to React that warns when you call `PropTypes` validation functions by yourself. This is going to be unsupported as we want to make them behave more like black boxes so people stop calling them, and it would become safe for us to make them no-ops in production, saving some code size.
I tried the [new code](https://github.com/facebook/react/pull/7132) on some projects, and it appears that React Router calls propTypes directly generating the warnings: https://github.com/facebook/react/pull/7132#issuecomment-229534202.
I’m not sure how valuable that check was so I just removed it. If it’s super valuable, we can replace it with `React.createElement` call that would make React check the prop types, but in this case I’d need to have a test case verifying the behavior you …

Don't check propTypes ahead of time

---

docs/API.md
docs/Glossary.md
modules/TransitionUtils.js
modules/__tests__/transitionHooks-test.js
modules/createTransitionManager.js

Fixes #3612
Make sure this lands in `react-router@next` too.

Add prevState to onLeave hooks

---

karma.conf.js
modules/PropTypes.js
modules/Route.js
modules/__tests__/Router-test.js
modules/__tests__/Routing-test.js
modules/__tests__/State-test.js
modules/components/ActiveHandler.js
modules/components/Link.js
modules/components/RouteHandler.js
modules/components/__tests__/DefaultRoute-test.js
modules/components/__tests__/Link-test.js
modules/components/__tests__/NotFoundRoute-test.js
modules/components/__tests__/Redirect-test.js
modules/components/__tests__/Route-test.js
modules/components/__tests__/RouteHandler-test.js
modules/createRoutesFromReactChildren.js
package.json
webpack.config.js

I was going through cleaning up old branches, and realized I still had this one sitting around.
Might as well check it in? I think it works.
From https://github.com/reactjs/react-router/issues/3281, but looks like nobody's desperately in need of a release or anything.

Support React v15 on legacy v0.13 branch

---

modules/Router.js
modules/__tests__/serverRendering-test.js
modules/__tests__/useRouterHistory-test.js
modules/createTransitionManager.js
modules/match.js
package.json

This code isn't going to win any beauty awards. I'd like to clean this up structurally before v3.0.0 final if I have time, but it's not going to involve any major API changes (just internal refactoring).
I figure it's okay to take out the invariant on `history.getCurrentLocation` because anybody attempting to use a v2 history will just hit an exception when `history.getCurrentLocation` fails due to not existing. If it comes up, it'd be easy enough to add back the inverse of the removed invariant to assert a non-v3 history.

Support history v3

---

README.md

Hi! I was looking to point one of our designers to the 0.13.x docs only to find that the links were dead :( (As per https://github.com/reactjs/react-router/pull/3607)
This is a small update to the README to make those links valid again. Happy to update any other legacy doc stuff as needed! 
(Also, there were no code changes so I opted to not add anything to `changes.md`. Happy to do otherwise)

Updates links to old docs in README

---

docs/API.md

This change adds an example to the documentation on how to use the onEnter callback to redirect a user to another page.

Add an example on how to use the onEnter callback

---

package.json

This is what webpack 2 prefers. Ideally Rollup will follow along as well.

Add module entry point for webpack 2

---

modules/Link.js
modules/__tests__/Link-test.js

Closes https://github.com/reactjs/react-router/issues/3657
I'm not absolutely sure this is entirely correct – the "nice" way to use this requires creating a throwaway function in render. But `<Link>` isn't a pure component right now anyway.

Add support for function to

---

docs/guides/NavigatingOutsideOfComponents.md

Just a minor copyediting fix for the docs PR. Just adding a PR to have something we can refer to.

Tweak goBack docs a bit

---

karma.conf.js

After https://github.com/ReactTraining/history/commit/b7152a4c6da99a150dd3e2b9011c85fb2d18e6bd.

Fix BrowserStack config

---

modules/PatternUtils.js
modules/__tests__/getParamNames-test.js
modules/__tests__/matchPattern-test.js

Fixes #3679.
Includes #3678 (needed for CI to pass).
`PatternUtils` is sort of a mess, incidentally. There's no reason to export `compilePattern`, and there's no real reason that `getParams` should still exist (nothing calls it). I also don't know why `getRouteParams` is completely separate module, either.
I want to fix/deprecate, but it's not that compelling right now.

Fix handling of patterns that are method names

---

docs/API.md

While developing a widget which is meant to be embedded into websites
via an iframe, we noticed `history` taking over the parent page’s
back/forward button (not a bug, just the way browser history works). We
were able to isolate the routing to the widget by using
`memoryHistory`.
This PR just adds a tiny note that `createMemoryHistory` can be useful
for a case like that.

add note about possible use case for memoryHistory

---

README.md

When I read React Router's versioning explanation, I thought the statement "We follow the same versioning as React.js itself" meant that I could use React Router 0.14.8 with React 0.14.8 (which is what React does with addons and ReactDOM packages in npm). I didn't realize that it was just the versioning /scheme/ which was consistent, not the version numbers themselves. I updated the language just slightly to reflect that.
Feel free to discard or merge as you see fit!

Update README.md to clarify versioning scheme vs versions

---

docs/API.md

Just getting started with React-Router, but thought it was a little unclear that the root URL isn't specified in the `Route` that renders the `App` component. While `/groups` and `/users` will still render correctly, navigating to the root URL '/' will give an error.

Readme: Add root path to Route component

---

modules/PromiseUtils.js
modules/__tests__/Router-test.js
modules/__tests__/matchRoutes-test.js
modules/getComponents.js
modules/matchRoutes.js
package.json
tests.webpack.js

First pass at #3606. Not 100% happy with it right now. It would be easier to architect if we had guaranteed Promise availability, but alas... 
I've got some practical things in there for Babel's `default` exports. And we can't just accept a Promise instead of a function, since `System.import` won't code split in that case. That's probably the most ugly part of it.
But this works:
```jsx
<Route path='/' getComponent={() => System.import('./app')} />
```

Add Promise support to async route functions

---

modules/__tests__/applyRouterMiddleware-test.js
modules/applyRouterMiddleware.js

Right now, if you pass in a value with properties that is not a valid React Router middleware, we just silently ignore it. This leads to really confusing things happening like https://github.com/relay-tools/react-router-relay/issues/189.
I don't think anybody's intentionally passing in empty objects to `applyRouterMiddleware`, so this should be a nice DX convenience.

Warn on invalid middlewares

---

modules/__tests__/withRouter-test.js
modules/withRouter.js

withRouter should allow a router prop specified on a wrapped component
to be used instead of the router in context; this pattern is more
flexible, avoids overwriting explicitly set props, and makes testing
components wrapped by withRouter more simple.

Allow a router prop to take priority over context prop.

---

modules/__tests__/withRouter-test.js
modules/withRouter.js

Following up on conversation from [this](https://github.com/reactjs/react-router/issues/3652) bug. Adding the ability to specify an withRef option to be passed to withRouter. The signature has changed from `withRouter(MyComponent)` to `withRouter()(MyComponent)` except now you can do this `withRouter({withRef:true})(MyComponent)` and later `instanceOfMyComponent.getWrappedInstance()` returning the component instance wrapped by withRouter. This feature is also demonstrated in react-redux in [code](https://github.com/reactjs/react-redux/blob/master/src/components/connect.js#L265) and is [documented](https://github.com/reactjs/react-redux/blob/master/docs/api.md#getwrappedinstance-reactcomponent). If given the thumbs up I will update the documentation, and write a codemod script.

Adding support to get the component instance that withRouter HOC wraps

---

examples/auth-with-shared-root/components/About.js
examples/auth-with-shared-root/components/App.js
examples/auth-with-shared-root/components/Dashboard.js
examples/auth-with-shared-root/components/Landing.js
examples/auth-with-shared-root/components/Login.js
examples/auth-with-shared-root/components/Logout.js
examples/auth-with-shared-root/components/PageOne.js
examples/auth-with-shared-root/components/PageTwo.js
examples/auth-with-shared-root/components/User.js

Fix for the changed default export behavior in babel 6. The default export now needs to be explicitly required(). See also http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default.
Had a look at the other examples, they're all ok.

Fix auth-with-shared-route example

---

modules/__tests__/withRouter-test.js
modules/withRouter.js

Cleans up code style, variable naming, and tests

Fix the withRef mess

---

docs/API.md

The [history](https://github.com/mjackson/history) Location doc [was removed](https://github.com/mjackson/history/commit/fc46b329ba58289e447d3fe8997a9d6e1ccc962e).

Remove broken link in API doc

---

modules/createTransitionManager.js

This just reduces the surface area of history that we use.

Use replace instead of transitionTo for redirects

---

docs/API.md

The actual type of this.props.params.portfolioId will be a string as opposed to a number.

Corrected misleading routeParams docs comment.

---

website/components/bricks.js

This might fix the new docs in Firefox. I was able to fix it in the developer tools, and I think this is the right place to apply it. Honestly, I find Firefox's flexbox implementation to be closer to the spec usually, so Firefox's behavior may be correct and you need this.
I can't figure out how to run the site, so I don't know if this works. Opening this PR to at least point you in the right direction.

Add overflow in docs to tell Firefox to constrain to parent's size (v4)

---

website/pages/quick-start.md

Line 57 refers to a `NoMatch` component that is not defined elsewhere. These docs are looking great, good job!

rename `Miss` inline component to `NoMatch`

---

modules/index.js

This adds `createServerRenderContext` to the main exports file, allowing it to be accessed exactly as it is in the v4 docs website.

Explicitly export createServerRenderContext

---

modules/ServerRouter.js

The destructuring assignment should include location, otherwise Node throws *location is not defined* ReferenceError.

Fix ReferenceError in ServerRouter

---

website/api/Match.md

Fixing 2 small typos in the documentation

fixing pathame->pathname typo in docs

---

modules/MatchProvider.js
modules/__tests__/Match-test.js

Add failing test.
`renders deep match` test works, but
`should render deep match on path change` not.
I think that the problem is because [this.parent](https://github.com/ReactTraining/react-router/blob/v4/modules/MatchProvider.js#L22) does not updated on route change.

this.parent does not updated on match change at MatchProvider.

---

website/examples/Basic.js

`Miss` and `Redirect` are not actually used in this example.

Remove unused imports in example

---

website/pages/quick-start.md

Solves #3837 problem
Before: `A valid React element (or null) must be returned`.
After: everything renders ok.

Add Router content wrapper

---

modules/Link.js
modules/__tests__/Link-test.js
website/api/Link.md
website/examples/CustomLinkComponent.js
website/routes.js

Please refer to #3874
Feel free to purpose different name for children function parameters! I am not good at naming things. :(
This should also allow creating Link on react-native, not tested yet, I don't have the infra to test it right now!
```javascript
const RNLink = ({to, ...props}) => <Link to={to}>{
({isActive, transition}) => <Text onPress={transition} {...props} />
}</Link>
```

feat: make Link accept function as children

---

modules/BrowserRouter.js
modules/HashRouter.js
modules/StaticRouter.js
modules/__tests__/StaticRouter-test.js

Fixes #3839
Uses @chentsulin's code from #3843
Basenames are handled by the history, but not by the stuff that actually displays URLs. This fixes things so rendered hrefs include the basename.
Note: This is broken as-is, as we need to strip the basename from the location pushed to history too.

Fix basename support

---

modules/Router.js

`history.getCurrentLocation`  was [removed](https://github.com/mjackson/history/compare/v4.0.0-1...v4.0.0-2#diff-04c6e90faac2675aa89e2176d2eec7d8L51) on history `v4.0.0-2` so I thought this check could be updated.
I also took a look to the check on [v3](https://github.com/ReactTraining/react-router/blob/v3/modules/Router.js#L79), it seems that it will catch correctly(besides wording) histories created with history versions `>=4.0.0-2` but no versions `4.0.0` and `4.0.0-1`, I could also make a PR for that if you think is ok.

update history version check

---

website/examples/Auth.js

Attempting to visit the /login route directly results in a "this.props.location.state is null" error which breaks the example.  This fix tells the login component to redirect back to the root route on login if the login route was accessed directly.

Fix auth sample login route

---

modules/PatternUtils.js
modules/__tests__/formatPattern-test.js

Working on a URL generator based on a route path.  Using `formatPattern` gets close, but fails when we have routes like `search(/collection/:collectionId)`.  This PR takes care of that case.

Discard optional paren history based on params evaluation

---

docs/API.md
docs/guides/Histories.md

Change link urls from master branch to v2.x branch. This also changes links from ReactTraining/history to mjackson/history
[fixes #3971]

Fix doc links to history

---

modules/MatchProvider.js
modules/__tests__/integration-test.js

Miss would not render in ambiguous match example after navigating away and returning to ambiguous path
closes #3957

Fix ambiguous Miss component not rendering (#3957)

---

modules/__tests__/Miss-test.js
modules/matchPattern.js

Provide fix and tests for #3938 
Applied the same fix as in #3939, but added a couple tests to prove the case

fix: <Match exactly> takes parent into account

---

modules/StaticRouter.js
modules/__tests__/StaticRouter-test.js

I use `<Router basename="/foo">`. If I call `transitionTo('/')`, I end up at `http://host/foo/` but I expect to land on `http://host/foo`. I also tried passing `{pathname:null}` but that doesn't help either.

don't incude a trailing slash in the href for pathname='/' if the basename is not empty

---

modules/__tests__/Match-test.js
modules/matchPattern.js

To fix the bug for #3970 
`<Match>` needs to call `decodeURIComponent` to properly pass parameters to its component.

decode path params

---

modules/__tests__/Match-test.js
modules/matchPattern.js

Currently, in the v4 branch, `<Match pattern="/foo/" component={Foo} />` fails to match at `/foo/bar/`, because the URL is truncated to `/foo/bar` instead of `/foo/` prior to being matched.

Fix non-exact match of pattern with trailing slash.

---

modules/Link.js
modules/Redirect.js
modules/__tests__/integration-test.js
website/api/Link.md
website/api/Redirect.md

These props allow selecting pushState and replaceState for navigating to
the next state.
Fix #3903.

Add <Link replace> and <Redirect push>

---

modules/Link.js

The new `replace` prop on `Link` introduced in v4 yesterday (eac82172a04287501b5c4a2668fcfdbe7059f227) was being passed down to the `<a>` tag during rendering. This was causing a warning from React:
> Warning: Unknown prop `replace` on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
in a (created by Subscriber)
in Subscriber (created by LocationSubscriber)
in LocationSubscriber (created by Link)

Prevent replace prop from being passed to <a ... />

---

modules/MatcherCache.js
modules/__tests__/MatcherCache-test.js
modules/matchPattern.js

Cache matchers by key of `pattern` up to a maximum of **50** matchers. (arbitrary number).
If anyone has a better idea of what number to use for the cache max, let me know.
Relates to issue #3875

feat: cache matchers with simple cache

---

.eslintignore
package.json
scripts/clean.js

- Convert clean task into node script to work cross-env
- Remove quotes from build-lib task, so tests folder isn't transpiled
- Add watch task for better local dev

Fix scripts on windows

---

modules/HashRouter.js
modules/__tests__/HashRouter-test.js

I added an extra function since the link looks different when using `hashType` `hashbang`.
This is a fix for #4022. I hope I'm doing it the right way, since this is more or less my first PR.
Help appreciated, especially if it needs tests  :)

provided HashRouter with own createHref implementation

---

modules/Link.js
modules/__tests__/Link-test.js

When a `<Link>` doesn't need to know about the current location, its `<a>` does not need to be wrapped with a `<LocationSubscriber>`.
#3985

Links apathetic to active don't subscribe (#3985)

---

modules/StaticRouter.js
modules/__tests__/StaticRouter-test.js

The `blockTransitions` function on the `router` prop passed down from `<StaticRouter />` was not returning a function to tear down the blocking prompt.
This PR changes the `blockTransitions` function to return its result, which should be the teardown function returned from calling `history.block()`.

Fix blockTransitions not returning teardown function

---

scripts/clean.js

Clean task failed if files didn't exist (my fault), so now it fails silently if a file doesn't exist or an error occurs.

Clean task fails silently

---

modules/Link.js
modules/__tests__/Link-test.js

Issue:
`onClick={() => null} to="test">` => Clicking this link with v4-alpha5 causes a page refresh in the browser. That is because the internal onClick was overwritten by the this.props.onClick due to first applying the own props and then applying the ...rest props.
Alternative: Strip out onClick and all other properties that should not be overridden.

Fix Link {...rest} overwriting used properties like onClick

---

modules/TransitionUtils.js
modules/__tests__/transitionHooks-test.js
package.json

Fix for #3220.
- Transition manager keeps track of pending **async** (or sync) hooks (for `onEnter` and `onChange`).
- When new transition starts, redirects from pending async hooks are ignored, fixing the unexpected behaviour in #3220 
- When the hook completes, it is removed from the pending list
This prevents a redirect from *old* transitions happening. If a new transition occurs **after** an async hook with a redirect starts, the *new* location should take precedence, so the redirect is ignored.
See new tests for situations where this might occur
> Also fixed npm tasks on windows again whilst I was there :smile:

feat: cancel pending enter/change hooks on location change

---

modules/__tests__/Match-test.js
modules/matchPattern.js

`decodeURIComponent(undefined)` is `"undefined"`

Don't pass `'undefined'` for missing optional parameters

---

modules/TransitionUtils.js
modules/__tests__/transitionHooks-test.js

I've reported #4114 but nobody responded.
eventually, I fixed it myself. 😂 
Hope you guys are happy with this. 🙏

Pass transition hook's arguments correctly

---

modules/__tests__/matchRoutes-test.js
modules/matchRoutes.js

Fixes #3852. The problem was that `getIndexRoute` didn't consider async `getChildRoutes` when looking for pathless child routes.

Fix index routes inside async pathless routes

---

website/api/Match.md

Since `exactly` should be a boolean value, I think `true` and `false` on example would look more clear.
What do you think?

Improve explanation about `exactly` prop

---

website/components/FakeBrowser/index.js

Right now jsxstyle requires to write `<Inline component="input" props={{onClick}} />` instead of `<Inline component="input" onClick={onClick} />`.
There is a upcoming patch in jsxstyle that will change this API: https://github.com/smyte/jsxstyle/issues/32

v4 Fix FakeBrowser address bar (was broken due to jsxstyle)

---

modules/__tests__/withRouter-test.js
modules/withRouter.js

withRouter() return wrapped Component if router is not present ([#4292])

bugfix #4292 

---

docs/guides/RouteMatching.md
modules/PatternUtils.js
modules/__tests__/formatPattern-test.js
modules/__tests__/getParams-test.js

For our latest project we need to escape parenthesis since they occur in the URLs (which is uncommon but valid). This PR is based on this old one (https://github.com/ReactTraining/react-router/pull/2533 by @Zoxive) which has been closed since at some point in time you wanted to refactor the URL matching into a separate module - unfortunately that has not happened yet so it would be very nice if the PR would make it this time.

Add support for escaped parentheses in <Route path>

---

website/api/Route.md

In the current implementation, Route's children prop gets passed `history` and `match`, not `matched`. I'm not sure if it should get passed `matched` or if the docs were just outdated.

Update Route's children docs

---

modules/Router.js

React-router uses a check on the existence of history.getCurrentLocation to determine the current version of the history object. [(seen here)](https://github.com/ReactTraining/react-router/blob/master/modules/Router.js#L79)  If there is no history.getCurrentLocation it assumes that version 2.x or lower is being used and throws an error.
As of version [4.0.0-2](https://github.com/ReactTraining/react-router/blob/master/modules/Router.js#L79) `history' no longer uses `history.getCurrentLocation`, so this error will also trigger as a result of history's version being too high (4.x)
I've updated the wording in the error message to make it clearer that the error may be a result of having `history` that is v4.x as well as 2.x or lower.

Updated History Error Message

---

packages/react-router-native/NativeRouter.js

Fix #4413
Need help with tests here, as this is not something I'm familiar with at the moment (yep 😔)

Allow initialIndex, initialIndex in NativeRouter

---

packages/react-router/modules/Route.js
packages/react-router/modules/__tests__/Route-test.js

Duplicate of #4402, I added in a test. 
I didn't have write access to @developit's branch so I made a fork. 
Not sure if there is a different/better way to approach this test, but it seemed right to me.

Preact support: Check for empty array children 

---

packages/react-router-dom/.gitignore
packages/react-router-dom/modules/.babelrc
packages/react-router-dom/modules/BrowserRouter.js
packages/react-router-dom/modules/HashRouter.js
packages/react-router-dom/modules/MemoryRouter.js
packages/react-router-dom/modules/NavLink.js
packages/react-router-dom/modules/Prompt.js
packages/react-router-dom/modules/Redirect.js
packages/react-router-dom/modules/Route.js
packages/react-router-dom/modules/Router.js
packages/react-router-dom/modules/StaticRouter.js
packages/react-router-dom/modules/Switch.js
packages/react-router-dom/modules/matchPath.js
packages/react-router-dom/modules/withRouter.js
packages/react-router-dom/package.json
packages/react-router-dom/scripts/build.js
packages/react-router-dom/tools/es2015Preset.js
packages/react-router/.gitignore
packages/react-router/modules/.babelrc
packages/react-router/package.json
packages/react-router/scripts/build.js
packages/react-router/tools/es2015Preset.js

This creates an ES build (still transpiled, but with ES2015 import/exports left in tact to enable tree-shaking) inside `es/`, updates the relevant gitignores & npm inclusions, and adds a "module" entry point to package.json of react-router and react-router-dom.
Please see https://github.com/ReactTraining/react-router/issues/4425#issuecomment-276717662 before merging, as this also updates the react-router imports from react-router-dom to be top-level rather than cherry-picked (necessary to enable descendent tree-shaking). As-is, this increases the bundle size of cherry-picked CJS imports from react-router-dom, since they now include the entire react-router package.
IMO, this is fine -- if people care about bundle size, they should be using a tree-shaking bundler -- but if you disagree, I …

Add ES build to react-router and react-router-dom (#4425)

---

packages/react-router/modules/__tests__/matchPath-test.js
packages/react-router/modules/matchPath.js

Previously, the cache keys for compiled `path-to-regexp` patterns was being computed using:
```js
const cacheKey = options.end + options.strict
```
However, this meant that `{ end: true, strict: false }` created the same key as `{ end: false, strict: true }`.

Use boolean strings for cache keys

---

packages/react-router-dom/scripts/build.js
packages/react-router/scripts/build.js

ES build was being placed in the root directory of the package. This was causing errors "unexpected token import" errors when trying to run the tests.

build es modules in es directory

---

packages/react-router/modules/Router.js
packages/react-router/modules/__tests__/Router-test.js

As per issue #4444, this PR adds an invariant which provides a nicer
error message from `Router` if it is given multiple children.
Any feedback on the approach, etc, is very welcome! I hope it's OK :)

Warn when `Router` is given >1 children

---

packages/react-router/modules/Route.js
packages/react-router/modules/__tests__/Route-test.js

#4423 added Preact support by making `children` null if its length is zero.
[`Function.length`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) indicates how many arguments the function takes, so a function that takes no arguments has a length of 0.
```js
<Route path='/okay' children={() => <div>What?</div>} /> // this would set children to null
```
This PR will make sure that `children` is an array before setting it to `null` when it is empty.
I also took the liberty of adding some basic `<Route>` tests for its `component`, `render`, and `children` props.

Only nullify empty children array

---

packages/react-router-website/modules/api/Route.md

This adds tables showing how the different combinations of a `<Route>`'s `exact` and `strict` props match a `path` against `location.pathname`.
I also removed the tables that were previously included under the `strict` and `exact` props because they were now redundant (and in the case of `strict`, not completely accurate).
closes #4441

Update description of strict

---

packages/react-router/modules/StaticRouter.js
packages/react-router/modules/__tests__/StaticRouter-test.js

Fixes #4480 Add a leading slash after concatenating `this.props.basename` and `createURL(path)`.
```js
// before
addLeadingSlash('') + '/my-path' = '//my-path'
// after
addLeadingSlash('' + '/my-path') = '/my-path'
```

Remove extra StaticRouter createHref leading slash

---

packages/react-router-dom/webpack.config.js

Remove the `react-router` external from `react-router-dom`'s `webpack.config.js`. This was preventing `react-router`'s modules from being bundled into the UMD builds.
I used the `react-router-dom.js` and `react-router-dom.min.js` files in a mini project and the modules from `react-router` imported as expected. The file sizes are also similar to the beta 4 build, so it appears that everything is being included as expected.

Remove react-router as webpack external

---

packages/react-router-dom/modules/Link.js

`to` is currently implicitly required. Might as well make it throw when it's not included.

Require to prop on Link

---

packages/react-router-website/modules/api/NavLink.md
packages/react-router-website/modules/components/APIDocs.js

Adds documentation of the `<NavLink>` component to the API section of the website.

Add NavLink to docs

---

docs/API.md

There is no mention of the following in the Injected Props docs at present:
The registered routes.
Although when I'm debugging react-router 3.0.2 I can certainly see it there (and have been using with react-router 2.0 and 3.0).  So I've added it - hope that's helpful.

Update API.md to mention routes as part of injected props

---

packages/react-router-website/modules/api/Switch.md

Update docs to state that the elements passed to a `<Switch>` should be `<Route>`s. I used "should" instead of "must" because technically any component with the correct props will work.

Switch children should only be Routes

---

modules/Router.js

Related to https://github.com/ReactTraining/react-router/issues/4493.
This [test](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/tree/master/test/fixtures/es-class-assign-property-variable) should ensure us it's working correctly.
cc @timdorr

move propTypes declaration

---

packages/react-router-website/modules/api/Router.md

Update v4 docs so that the function call for `createBrowserHistory()` lines up with the import of `createBrowserHistory`.

Fix createBrowserHistory in documentation.

---

packages/react-router/modules/StaticRouter.js
packages/react-router/modules/__tests__/StaticRouter-test.js

The `<StaticRouter>`'s history object is missing the `block` method. Fixes #4543.

Add block to StaticRouter's history

---

packages/react-router-website/modules/examples/NoMatch.js
packages/react-router/modules/__tests__/Switch-test.js
packages/react-router/modules/matchPath.js

* `<Redirect>` already worked because it doesn't have a `path` and it gets rendered :)
* Add `from` as an alias for `path` in `matchPath` so you can write `<Redirect from="/old" to="/new"/>`
Fixes #4541

Support <Redirect> in <Switch>

---

packages/react-router/docs/Redirect.md
packages/react-router/docs/Switch.md

Let it be known.
Side note: A number of links in the API section of the website are non-functional right now. There are duplicate ids for props that have the same name/type in multiple components.

Document <Redirect> in a <Switch>

---

packages/react-router/modules/Route.js
packages/react-router/modules/__tests__/StaticRouter-test.js

Some little fixes for things that were causing warning errors in the Travis builds.
No idea who could have missed adding a `<Prompt message>` :innocent:

Remove some warnings emitted during tests

---

packages/react-router/modules/Route.js
packages/react-router/modules/Switch.js
packages/react-router/package.json

Adds `warning` dependency and imports `warning` in `<Switch>` and `<Route>` (missing from 143db65).

Import warning

---

packages/react-router-native/NativeRouter.js

This still does not block anyone to actually do it, as the developer can actually take care of persisting the history and then passing it as `initialEntries` and `initialIndex` props, but I don't know of any app actually doing it.

do not persist location after the app restart

---

packages/react-router/modules/Router.js
packages/react-router/modules/__tests__/Router-test.js

**Edited** :scissors:
Right now, a component that is rendered within a `<Route>` has a `context.router.match` object that it can use to determine "where" it is. A photo album link may be in `{ url: '/albums' }` while a photo link may be in `{ url: '/albums/123' }`. This is great for resolving relative paths.
The exception is components that are rendered inside of a `<Router>` but not within a `<Route>`. The `context.router` object created by a `<Router>` provides no initial `match` object, so if one of these components wants to know "where" it is, is has to use default values. A root match would allow those components to know "where" they are without resorting to default values.
```js
const url = match && match.url  ? match.url : '/'
```
This isn't the only situation where `match` is …

Add root match to context.router

---

packages/react-router-website/modules/components/Examples.js
packages/react-router-website/modules/components/FakeBrowser/index.js
packages/react-router-website/modules/examples/Auth.js
packages/react-router-website/modules/examples/ModalGallery.js
packages/react-router/modules/Route.js
packages/react-router/modules/Router.js
packages/react-router/modules/Switch.js
packages/react-router/modules/__tests__/Route-test.js
packages/react-router/modules/__tests__/Router-test.js
packages/react-router/modules/__tests__/Switch-test.js

When a `<Switch>` or a `<Route>` has a `location` prop, its children should match using that `location` instead of the current `history.location`.
This also adds a modal example since the PR changes enable it and that seems to be a popular request.

Add context.route.location

---

packages/react-router/modules/Route.js
packages/react-router/modules/Switch.js
packages/react-router/modules/__tests__/matchPath-test.js
packages/react-router/modules/__tests__/withRouter-test.js
packages/react-router/modules/matchPath.js

Add a parent match object as the third argument to `matchPath`.
```js
matchPath(pathname, options, parent)
```
When the `path` is undefined, `matchPath` will return the parent match instead of creating a new object. Previously, an undefined `path` would create a new match object. This meant that attempting to access the current `match` within a pathless `<Route>` would give you incorrect values.
```js
// location = { pathname: '/arizona/phoenix' }
// before
<Route path='/:state' render={({ match }) => (
// match = { url: '/arizona', params: { state: 'arizona' }, ... }
<Route render={({ match }) => (
// match = { url: '/arizona/phoenix', params: {}, ... }
)}/>
)}/>
// after
<Route path='/:state' render={({ match }) => (
// match = { url: '/arizona', params: { state: 'arizona' }, ... } …
```

Pathless <Route> inherits parent match

---

packages/react-router-website/modules/docs/Web.js

This was not transferred to the data in `Web.js` during the website overhaul.

Add modal gallery to list of examples

---

packages/react-router-dom/modules/NavLink.js

Since most of users provide the same class, it would be great to have it as a default one so we don't need to define it every time or make a wrapper component for this.
The other users, who need another class will pass another activeClassName, same as they have to do in current version.

Add default activeClassName to NavLink

---

packages/react-router-dom/modules/Link.js
packages/react-router-dom/modules/__tests__/BrowserRouter-test.js
packages/react-router-dom/modules/__tests__/HashRouter-test.js
packages/react-router-native/AndroidBackButton.js
packages/react-router-native/DeepLinking.js
packages/react-router-native/Link.js
packages/react-router/modules/Prompt.js
packages/react-router/modules/Redirect.js
packages/react-router/modules/Route.js
packages/react-router/modules/Router.js
packages/react-router/modules/StaticRouter.js
packages/react-router/modules/Switch.js
packages/react-router/modules/__tests__/MemoryRouter-test.js
packages/react-router/modules/__tests__/Route-test.js
packages/react-router/modules/__tests__/Router-test.js
packages/react-router/modules/__tests__/StaticRouter-test.js

Per #4650. This is mostly self-explanatory. I didn't look through the docs, but I am sure there are a few small changes that will need to be made with them.
@ryanflorence I updated the context references that I saw in `react-router-native`. There aren't any tests there to verify nothing is breaking, but everything looks right to me.
@mjackson I changed how `staticContext` gets placed on `context.router` to make `<Router>`'s implementation slightly simpler. I can revert it, but then `<Router>` would need to check its parent context.

Group context under context.router

---

packages/react-router-website/modules/components/WebExample.js

Currently, the `location` object that `<FakeBrowser>` uses as its key is `window.location`, which does not have a `key` property.
This PR just renders a `<Route>` around the `<FakeBrowser>` so that it can access the current `location` object. This will reset the active example when the link to it in the sidebar is clicked.
Alternatively, the `example.slug` could be used as a key. If that is the case, then clicking the sidebar link of the active example will have no effect.
I am not certain which of those is preferable.

Provide location object to <FakeBrowser>

---

packages/react-router/modules/Route.js

I'm not sure if these were intentionally or accidentally removed in 45649fd. I have seen a few people having issues that would be easier to debug with these warnings.

Bring back <Route> render prop warnings

---

README.md

Just noticed the incorrect URL in the README. This updates it to the right one.

Provide the correct URL to react-router-redux in the README.md

---

README.md

While we're all super excited for the release of react router 4, there are still allot of users who still use 2.x so there should be easy access to these documentation pages until they upgrade.

Add links to 2.x and 3.x documentation versions

---

packages/react-router-dom/docs/guides/code-splitting.md

Code-splitting documentation for `react-router-dom` has an import for the loadDashboard module, but references the same loadAbout module that precedes it.
Changes the import filename to reflect the import name.

Fixes duplicate loadAbout import within code splitting docs.

---

packages/react-router-redux/modules/ConnectedRouter.js
packages/react-router-redux/modules/__tests__/ConnectedRouter-test.js
packages/react-router-redux/modules/__tests__/__snapshots__/ConnectedRouter-test.js.snap
packages/react-router-redux/package.json

This PR will add support for the ConnectedRouter to render Preact components without the help of `preact-compat` alias. As seen in this repo [developit/react-router-4-test](https://github.com/developit/react-router-4-test), it will work out of the box with the normal Router component.
I'm not sure what other kind of tests you would like to see aside from a snapshot. This shows that it doesn't break the current implementation, but not sure a way to prove in tests, that it does in fact work with Preact.

Support Preact in react-router-redux/ConnectedRouter

---

packages/react-router-redux/modules/ConnectedRouter.js
packages/react-router-redux/modules/__tests__/ConnectedRouter-test.js
packages/react-router-redux/modules/__tests__/__snapshots__/ConnectedRouter-test.js.snap

This allows us to use `ConnectedRouter` without any children:
```
<Provider store={store}>
<ConnectedRouter history={history} routes={routes} />
</Provider>
```

ConnectedRouter can render without children.

---

packages/react-router-website/modules/components/Guide.js

I found GUIDE docs scroll management is tiny broken.
And append `<ScrollToDoc>`.
|before|after|
|--|--|
|![kapture 2017-03-13 at 23 01 12](https://cloud.githubusercontent.com/assets/13282103/23857522/fa5814d0-0840-11e7-9355-76f6207f5860.gif) | ![kapture 2017-03-13 at 23 02 49](https://cloud.githubusercontent.com/assets/13282103/23857597/2efd85f8-0841-11e7-82ed-e7e8fc0f18c4.gif) |

Fix guide docs scrolling

---

packages/react-router-dom/docs/guides/code-splitting.md

I got a warning in my webpack console and see they have update their docs now this is no more `import loadSomething from 'bundle?lazy!./Something'` but `import loadSomething from 'bundle-loader?lazy!./Something'` :)

Update babel for babel-loader

---

packages/react-router/modules/Switch.js
packages/react-router/modules/__tests__/Switch-test.js

Fixes #4725
Makes `&&` booleans easier inside of Switch.

Handle non-element Switch children

---

packages/react-router-dom/docs/api/BrowserRouter.md
packages/react-router-dom/docs/api/HashRouter.md
packages/react-router/docs/api/StaticRouter.md

History will do some work to fix malformed basenames, but it is still helpful to state that there is a correct format.

Specify proper basename format in docs

---

packages/react-router-native/AndroidBackButton.js

Without this change I get:
```js
AndroidBackButton.render(): A valid React element (or null) must be returned.
```
When used as shown in docs:
```js
<NativeRouter>
<View style={{flex: 1}}>
<AndroidBackButton />
</View>
</NativeRouter>
```

Return null if this.props.children is undefined

---

packages/react-router-website/modules/docs/Core.js
packages/react-router-website/modules/docs/Native.js
packages/react-router-website/modules/docs/Web.js
packages/react-router/docs/guides/blocked-updates.md

Hopefully people will have an easier time finding this when it is on the site.

Add blocked updates guide to website

---

packages/react-router-dom/docs/guides/server-rendering.md

This was fixed in static-routes.md in 38a0f5709, but the change wasn't carried over to this page when making the fix.

Fix link to React Router Config

---

packages/react-router-config/modules/__tests__/integration-test.js
packages/react-router-config/modules/__tests__/renderRoutes-test.js
packages/react-router-config/modules/renderRoutes.js

My attempt at writing tests for #4728

Add exact and strict support to renderRoutes

---

CONTRIBUTING.md

Closed the un-closed `<a>` tags in `CONTRIBUTING.md`. They were preventing markdown headers from rendering.

Fix headers in contributing.md

---

packages/react-router/docs/api/Redirect.md
packages/react-router/docs/api/Switch.md

There seems to be some confusion around this.
I think that the link will work (it works within GitHub), but at least for me, none of the single-dot relative paths work when running the documentation site locally.

More specific <Redirect from> description

---

modules/createRouterHistory.js

Fixes an issue identified in #4855. Occurs when webpack tries to parse an anonymous function without expression brackets wrapping the function.
Looks like simply giving the function a name fixes this issue (hopefully). It at least worked when I tested it locally.

Fix webpack-related anonymous function issue

---

packages/react-router/docs/api/match.md

On this page: https://reacttraining.com/react-router/web/api/match
The `matchPath` link is pointing to `withRouter`.

Fix wrong URL for `matchPath`

---

packages/react-router-config/README.md

Cleaning up the example to use a controlled Route (#4589) instead of manually overwriting context. I can't say for that this is 100% equivalent, since it's all just pseudo code and I didn't test it.

Use <Route location> in react-router-config example

---

packages/react-router/docs/api/Route.md

This hopefully makes it a little clearer why code like
```js
<Route component={(props) => <MyComponent {...props} />} />
```
should be avoided.

Expand on why not to use inline <Route component>

---

packages/react-router-native/docs/guides/quick-start.md

The guide doesn't work because the variable `App` is registered at the bottom, but doesn't exist. Solved by renaming `nativeRouterExamples` to `App`.

Fix typo in quick-start guide

---

ISSUE_TEMPLATE.md

This is the "React Router Template" from codepen.com/ReactJSTraining. This shouldn't actually be merged until that template is updated to `v4.0.0` (it is currently at `v4.0.0-beta.3`). It appears this hasn't been updated in a while since the old test case actually pointed to `v2.0.0` :laughing:

Provide 4.0 test case in ISSUE_TEMPLATE.md

---

modules/TransitionUtils.js
modules/__tests__/AsyncHooksServer-test.js
modules/createTransitionManager.js

**Issue:** When having async hooks (onEnter, getComponent) on routes, server side parallel request fails a lot of time.
**Reason:** Because pending hooks of onEnter and onChange are defined globally (https://github.com/ReactTraining/react-router/blob/v3/modules/TransitionUtils.js#L11), it can cause hooks collision between parallel request. And enterHooks.clear() can cause clearing other request hooks. 
**Fix:** Provide a scope for pending hooks instance and utility methods, so for each request hooks are maintained separately.  
Added test case which fails on the current version and passes with the patch on this PR. Let me know if any change required on PR.

Fix server side async hooks

---

CHANGES.md
packages/react-router/docs/api/withRouter.md
packages/react-router/modules/__tests__/withRouter-test.js
packages/react-router/modules/withRouter.js
packages/react-router/package.json

This brings the current `withRouter` more in line with what we had in v3.
1. WrappedComponent: Lets people access the original component as a static property. Useful for unit testing the component without the router (might help with #4795). It's also what react-redux does.
2. wrappedComponentRef prop: Passed as `ref` to the original component. v3 and react-redux use a different API based on `options: { withRef: true }` and `getWrappedInstance()`, but this way seems more comfortable to me to use with ref functions, and we don't need to change the signature to something like `options => Component => Component` or `(Component, options) => Component`. It's also suggested in the  [react docs](https://facebook.github.io/react/docs/higher-order-components.html#refs-arent-passed-through).
3. …

Improve withRouter

---

packages/react-router/docs/api/withRouter.md

withRouter(connect(...)(MyComponent)->
withRouter(connect(...)(MyComponent))

Updates documentation of withRouter, missing ')'

---

docs/API.md

previously implied that only `router` was injected, but `location`,
`params` and `routes` are also injected.

updates `withRouter` docs to describe all injected props.

---

upgrade-guides/v2.4.0.md

I couldn't figure out why the `setRouteLeaveHook()` callback wasn't being called when I navigated to a child route, and in doing some searching, I'm not the only person who had this problem.

Clarify setRouteLeaveHook() and child routes

---

packages/react-router-website/modules/examples/Animation.js
packages/react-router-website/package.json

This PR updates the website example to use the new package.
The old one will stop working with React 16.

TransitionGroup has moved into another package

---

packages/react-router-dom/docs/guides/scroll-restoration.md

Added a note in the docs to make it clearer that the `<ScrollToTop />` component needs to be wrapped in `withRouter`.
#5031

Added note on use of withRouter in Scroll Restoration doc

---

packages/react-router-native/experimental/StackRoute.js

This PR changes old route.replace to route.history.replace. Fixes pan control errors.

switch to new api

---

README.md

My eye was drawn to the individual packages, then I had to come back to this page before realising this link was the primary documentation link.

Make the Docs link stand out a little bit more

---

packages/react-router-dom/docs/guides/code-splitting.md

Add missing opening parenthesis

[docs] Fix typo in code-splitting example

---

packages/react-router-native/AndroidBackButton.js
packages/react-router-native/package.json

As of React Native 0.44 the BackAndroid API is deprecated in favor of BackHandler.

Change BackAndroid to BackHandler

---

packages/react-router-dom/modules/NavLink.js

* append `activeClassName` at end of class attribute ( only for aesthetic purpose  )
* css tip: active-class should be declared after default-class ( css specificity )

NavLink className update

---

packages/react-router-dom/docs/guides/code-splitting.md

Fixes "loadDashboard" typo in code snippet for `react-router/web/guides/code-splitting` #5179

fix typo in loadDashboard #5179

---

packages/react-router-website/modules/examples/ModalGallery.js

Code uses `img` for routes but comments use `images` for them.

Fix typos in ModalGallery example comments

---

packages/react-router/docs/api/Route.md

https://reacttraining.com/react-router/core/api/Route/component-func should be https://reacttraining.com/react-router/core/api/Route/component

Fix link to route component in docs

---

packages/react-router/docs/api/Route.md

URL:s are case sensitive, and fixes another instance of the link to `component-func`.

Fix links in API documentation

---

packages/react-router-redux/modules/ConnectedRouter.js

Moved history subscription from componentWillMount to componentDidMount to avoid memory leaks during server side rendering.

Updated history subscription in ConnectedRouter

---

packages/react-router-website/modules/docs/Web.js
packages/react-router-website/modules/examples/StaticRouter.js

This is the JS port of the example added to the TypeScript definitions for StaticRouter and staticContext in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16812 as requested by @tkrotoff

Add example for StaticRouter (sync from DefinitelyTyped)

---

packages/react-router-config/README.md

Updates API language and removes some ambiguity that confused me/kept me away from this library last time I looked at it (I thought `matchRoutes` could only look at one route, no subroutes, at a time).

Update matchRoutes API description

---

packages/react-router/docs/api/Switch.md

This was broken in https://github.com/ReactTraining/react-router/pull/5136
Basically, only `<h1>` (`#`) and `<h2>` (`##`) headings get converted into links for the documentation website, so we need to make the prop headings `<h2>` s.

Fix <Switch> documentation

---

packages/react-router-dom/modules/BrowserRouter.js
packages/react-router-dom/modules/HashRouter.js
packages/react-router-dom/modules/__tests__/BrowserRouter-test.js
packages/react-router-dom/modules/__tests__/HashRouter-test.js
packages/react-router/modules/MemoryRouter.js
packages/react-router/modules/StaticRouter.js
packages/react-router/modules/__tests__/MemoryRouter-test.js
packages/react-router/modules/__tests__/StaticRouter-test.js

Adding a warning as suggested in issue #5114.

Issue #5114 warn about history prop in Router-derived components

---

packages/react-router-native/DeepLinking.js

Solves a problem similar to #4818 related to `DeepLinking`

DeepLinking - Return null if this.props.children is undefined

---

docs/API.md
docs/README.md

This is sort of a weird pull-request, but it's sort of an experiment. Currently, when i google search for "react router 3 docs" i get
but neither the 'api' or 'docs' links there are actually correct. 
My pet theory is that by aggressively adding the words 'react router 3' in choice locations google will know to point to this documentation more easily (fingers crossed). But in any case, it can't hurt even just from a descriptive point of view (i have a separate commit which would also change the readme in master to point to "react router 3.x docs" instead of "3.x docs" but this one should probably get merged first if it gets merged at all.
thoughts?

Makes RR3 documentation headings and links more descriptive

---

packages/react-router-dom/docs/api/Link.md
packages/react-router-dom/modules/Link.js
packages/react-router-dom/modules/__tests__/Link-test.js

Use case: [`react-measure`](https://github.com/souporserious/react-measure):
I'd like to show a tooltip above a Link. For this I need to know the underlying DOM node's position. Proxying the `ref` via an `innerRef`-prop would allow to do this. (I stole the naming from [`glamorous`](https://github.com/paypal/glamorous#innerref))
This would allow to extract the position like this:
```jsx
<Measure bounds>{({measureRef, contentRect}) => 
<Link to="..." innerRef={measureRef}/>
}</Measure>
```
But I'm optimistic that other use-cases might benefit from accessing the inner ref as well!
Happy to adapt docs (and tests) in this PR if you think this is worthwhile 🙂

Accessing <Link>'s underlying node via `innerRef`

---

packages/react-router-dom/modules/NavLink.js

Line 32 has to be `aria-current` instead of `ariaCurrent`, otherwise React will strip it out.

aria-current in NavLink #4707

---

packages/react-router-native/Link.js
packages/react-router-native/__tests__/Link-test.js
packages/react-router-native/package.json

This change adds the following behavior to the react-router-native/Link component:
- `onPress` handler can now be passed to Link
- `onPress` event can now be cancelled using `preventDefault()`
---
An example illustrating the new behavior
```jsx
import React, { Component } from 'react'
import { Link } from 'react-router-native'
class Example extends Component {
onPress(event) { // this function is now called
event.preventDefault() // this stops react-router from navigating
}
render() {
return <Link to='/' onPress={this.onPress.bind(this)} />
}
}
```
Fixes #4811
---
Notes: The react-native init included tests are failing. There is not an eslint config in react-router-native, so I tried to match the style of the other packages.

react-router-native/Link improvements

---

packages/react-router-website/webpack/markdown-loader.js

This PR makes it so that all subsection headers (a `##` that creates an `<h2>`) use lowercase letters. There is a little bit of discussion about this in #5197, but I'll explain everything below.
The way that GitHub adds `id`s to headers [converts all of the letters to lowercase](https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb#L39). The current way that the React Router website adds `id`s to headers is to convert to lowercase unless the header is from the `api` section, in which case it preserves the case for all letters.
For example, on GitHub, the documentation for the section on a `<Route>`'s render methods has the id [`route-render-methods`](https://github.com/ReactTraining/react-router/blob/v4.1.1/packages/react-router/docs/api/Route.md#route-render-met …

Make header links work on site & github

---

packages/react-router/docs/guides/migrating.md

PatternUtils.formatPattern was something I used pretty extensively on several projects, sharing the patterns in routing config and on links (and in action creators) so that if the pattern changed I didn't have to update paths everywhere. It took some time to figure out I could use the compile option on pathToRegexp so I thought it worth documenting here.
While I was at it it seemed worth adding a blurb about the other major util in PatternUtils and linking to matchPath

Added a migration section on PatternUtils

---

packages/react-router-config/package.json
packages/react-router-dom/package.json
packages/react-router/package.json

Missed removing these when switching to Rollup.

Remove babel-loader devDeps

---

packages/react-router/docs/api/withRouter.md

The docs make it sound like `withRouter` updates its wrapped component on every router transition (e.g. via listening to history).
> withRouter will re-render its component every time the route changes
Update clarifies that rerenders are only triggered by parent rerenders.
see [this issue](https://github.com/ReactTraining/react-router/issues/5356).

clarify docs about conditions when withRouter updates

---

packages/react-router-dom/docs/api/Link.md
packages/react-router-native/docs/api/Link.md

Add missing description for Link component `to` object in react-router-dom and react-router-native.

Update Link API docs

---

packages/react-router-dom/modules/BrowserRouter.js
packages/react-router-dom/modules/HashRouter.js
packages/react-router-dom/modules/MemoryRouter.js
packages/react-router-dom/modules/NavLink.js
packages/react-router-dom/modules/Prompt.js
packages/react-router-dom/modules/Redirect.js
packages/react-router-dom/modules/Route.js
packages/react-router-dom/modules/Router.js
packages/react-router-dom/modules/StaticRouter.js
packages/react-router-dom/modules/Switch.js
packages/react-router-dom/modules/matchPath.js
packages/react-router-dom/modules/withRouter.js
packages/react-router-dom/package.json
packages/react-router-dom/tools/babel-preset.js

Use direct import to react-router.

---

packages/react-router/modules/Route.js
packages/react-router/modules/Switch.js
packages/react-router/modules/__tests__/matchPath-test.js
packages/react-router/modules/matchPath.js

For this enhancement: https://github.com/ReactTraining/react-router/issues/5435

Case sensitive routes

---

packages/react-router-dom/docs/guides/code-splitting.md

Addresses #5418.
I attempted to convert the site to use `react-loadable` which to use properly would require upgrading webpack. I got that updated but I think `lazy-loader` is unhappy. The nav links start to get populated but the guides are just arrays of `undefined`, i.e., the equivalent of the following:
```jsx
{[undefined, undefined, undefined, ...].map(.map((item, i) => (
<Block key={i} marginBottom="10px">
<NavLink
key={i}
to={`/${environment}/api/${item.title.slug}`}
triangleColor="white"
children={item.title.text}
/>
))}
```

Update code splitting docs to use react-loadable.

---

packages/react-router-config/README.md
packages/react-router-config/modules/__tests__/renderRoutes-test.js
packages/react-router-config/modules/renderRoutes.js
packages/react-router-config/package.json

Prevents remount component on routes with the same component.
This issue was described and fixed for `react-router` here: https://github.com/ReactTraining/react-router/issues/4578 , but for `react-router-config` this bug occurs again due different `key` value on `<Route>` component.
Since `<Switch>` renders only one component there is no need to use unique `key` prop for `<Route>`.
Not sure if this is right fix, but it works.

Prevent remount component on routes with the same component

---

packages/react-router-config/package-lock.json
packages/react-router-config/package.json
packages/react-router-config/rollup.config.js
packages/react-router-dom/package-lock.json
packages/react-router-dom/package.json
packages/react-router-dom/rollup.config.js
packages/react-router/package-lock.json
packages/react-router/package.json
packages/react-router/rollup.config.js

I went ahead and updated all of the outdated Rollup dependencies, although my main reason for doing this is that [my PR to `rollup-plugin-commonjs`](https://github.com/rollup/rollup-plugin-commonjs/pull/208) was just merged and it makes the UMD builds a lot more readable. Instead of there being lots of `index$1`, `index$2`, etc. variable names (because they come from` index.js` files), those variables are now named using their parent directory.
Previous:
```js
var index$6 = Array.isArray || function (arr) {
return Object.prototype.toString.call(arr) == '[object Array]';
};
if (!index$6(keys)) {
options = /** @type {!Object} */ (keys || options);
keys = [];
}
```
Now:
```js
var isarray = Array.isArray || function (arr) {
return Object.prototype.toString.call(arr) == '[object Array]';
};
if …
```

Update rollup config/deps

---

packages/react-router/modules/Redirect.js
packages/react-router/modules/__tests__/Switch-test.js

Fixes https://github.com/ReactTraining/react-router/issues/5003
~~Is it ok I've added `is-equal` dependency? It's used by `expect` already.~~
I needed it because checking if we are redirecting to the same route is not so trivial.  
`to` can be a String or an Object, and the Object variant can have `pathname`, `search` and `state`, each of which could be a valid new route to redirect to.
e.g. I might want to redirect to my own route with a different `search` string or `state` data.
- I'd really like the warning to be better, telling the user where that last <Redirect> originated or something that will help him realize where the issue is, any ideas?
- How do I test if the usage of `warning`?  
In this case if we try to redirect to the same route we call `warning` to notify the user.

Redirect on props update (#5003)

---

docs/Glossary.md

there are definitely more in these docs that don't match the code, but here are a few fixes:
* `EnterHook` needs to use function intersection instead of an optional `callback` parameter
* some props in `LocationDescriptorObject` are optional
* `RedirectFunction` seems to take just a `LocationDescriptor` object as far as I can tell from the source code

fix various types in glossary

---

packages/react-router-dom/modules/Link.js

`button` 0 is the left mouse button, but there is more than one other kind of button: https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button#Return_value

Fixing misleading comment

---

packages/react-router-dom/docs/guides/quick-start.md

[The API docs for `match`](https://github.com/ReactTraining/react-router/blob/0b9917e02391809f6ef12c10a29c75ee0e20efe5/packages/react-router/docs/api/match.md) distinguishes between `match.url` and `match.path`, recommending that `.url` be used for **building nested `<Link>s`** and `.path` for **building nested `<Route>s.`**
The example code in the _Quick Start_ guide uses `match.url` for links, however, it also uses `match.url` for routes. This change is to use `match.path` for routes, to ensure uniformity.

Use `match.path` for nested routes.

---

packages/react-router-redux/modules/__tests__/selectors-test.js
packages/react-router-redux/modules/index.js
packages/react-router-redux/modules/selectors.js

Add a couple functions to the react-router-redux API
Simply retrieve the location object stored in the store
This function will create a memoized selector that will match the current location to the given path, if the match turns out to be different than before it will return the new match, otherwise it will keep returning the previous one.
Usage:
```js
import { createMatchSelector } from 'react-router-redux';
const usersMatchSelector = createMatchSelector({ path: '/users' });
// this will effectively update your component when the user enters or leaves the /users route.
// it wont update the component if the users goes from /users/one to /users/two because
// the pattern doesn't have the `exact: true` flag.
const mapStateToProps = (state) => ({
match: usersMatchSelector(state);
});
```

react-router-redux useful selectors

---

package.json
yarn.lock

`react-redux` is now using v2.3.1 of `hoist-non-react-statics` and causing a duplicate dependancy within my webpack builds for different versions.
Upgraded single package to the latest version all tests complete.

Upgrade hoist-non-react-statics

---

.travis.yml
package.json
scripts/build.js
scripts/postinstall.js

Don't build the website in CI or install any of its dependencies. This was suggested by both @timdorr in https://github.com/ReactTraining/react-router/pull/5527#issuecomment-329872051 and @pshrmn in https://github.com/ReactTraining/react-router/issues/4362#issuecomment-328163751. But @ryanflorence seems opposed to the idea (see https://github.com/ReactTraining/react-router/pull/5527#issuecomment-329874880).
Anyway, just wanted to put up this PR real quick so we have a place to discuss. I personally don't think it's a huge deal either way. It doesn't take a terrible amount of time to build the website in CI, but it is annoying. I also don't think building the site is a very valuable test of what's working and what's not. ¯\_(ツ)_/¯

Ignore the website in CI

---

packages/react-router/docs/api/Redirect.md
packages/react-router/modules/Redirect.js
packages/react-router/modules/__tests__/generatePath-test.js
packages/react-router/modules/generatePath.js

This pull request adds back a feature from v3 where the `to` URL pathnames of `<Redirect>` could contain parameters.
Currently, parameters in `from` are already matched by `<Switch>` and then passed into `<Redirect>` as `computedMatch` prop just like `<Route>` children. However, `<Redirect>` does not do anything with that information yet.
I implemented a new `generatePath(pattern, params)` function that creates a new pathname using [path-to-regexp's `compile` function](https://github.com/pillarjs/path-to-regexp#compile-reverse-path-to-regexp). This guarantees that patterns are processed in the same way as they are parsed in `matchPath`. This function is used to put the params from `computedMatch` into the respective slots of the `to` prop, which may from now include named parameters as …

Added Redirect with parameters

---

packages/react-router-dom/docs/guides/basic-components.md
website/modules/docs/Web.js

While the quick start guide provides a working example, I think that for some people it can be a little bit much to learn React Router by having to parse through a file to figure out what is going on.
This covers the basic components that should be known by a user in order to create a `react-router-dom` application. It could be adapted pretty easily for `react-router-native`, but that isn't my wheelhouse.

Add a basic components guide

---

packages/react-router/docs/guides/blocked-updates.md

I read this doc like four times until I decided to click on the breadcrumbs for other guides.  Lo and behold, I found and solved my problem within 30 seconds.  This PR helps others avoid my situation because it indicates that they should also read the other Redux guide if they are experiencing blocked updates.

Adds a note & link to Redux blocked updates

---

packages/react-router-redux/examples/AuthExample.js
packages/react-router-redux/examples/BasicExample.js

I'm adding these examples in order to improve our docs and help to understand the API's usage, just like it's currently done on <a href="https://github.com/ReactTraining/react-router/tree/master/packages/react-router-native/examples">React Router Native</a> .
I would like some help to improve these docs in the future as **React Router Redux** is being developed because right now it's quite simple.

Add basic working examples to react-router-redux

---

packages/react-router-dom/modules/Link.js
packages/react-router-dom/modules/__tests__/Link-test.js

New implementation will parse the string to create an actual location object. This also means that a to string with no pathname will resolve using the current location.
The `href` value is also now stored in state, only recalculating it when the `to` prop changes.
**Edit:** If anyone is looking at this, but hasn't read through #5488, the reason for this PR is that when a user renders a `<Link>` whose string `to` does not include a pathname, the rendered anchor's `href` does not include a pathname (`<Link to='?test=ing'>Test</Link>` -> `<a href='?test=ing'>Test</a>`). This results in conflicts with the output of the `<StaticRouter>` since that explicitly makes `href`s absolute paths by enforcing that the string begins with a forward slash. Since React Router works with location's whose …

Fix <Link to="string">

---

packages/react-router-config/README.md

I thought this might help clarify the parameters of `matchRoutes`.

update readme to clarify pathname

---

packages/react-router/docs/api/Route.md

Document the new `sensitive` option of the `Route` component.
The feature is implemented in https://github.com/ReactTraining/react-router/pull/5438

Document Route sensitive option

---

packages/react-router-dom/modules/NavLink.js
packages/react-router-dom/modules/__tests__/NavLink-test.js

The `to` prop passed to NavLink needs to have special characters escaped when passed to the Route component.  This change allows NavLink to be used for urls with any characters.
Example routes that will be taken literally:
- /pizza (1)
- /:pizza*
- /(.*)

Escape NavLink path to allow special characters in path.  Fixes #5584

---

packages/react-router-redux/package.json

fixes #5637 where requireing index.js would fail.
Reproduction steps:
```
> require('react-router-redux');
Error: Cannot find module './selectors'
at Function.Module._resolveFilename (module.js:527:15)
at Function.Module._load (module.js:476:23)
at Module.require (module.js:568:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/halkeye/git/sauce/billing/node_modules/react-router-redux/index.js:6:18)
at Module._compile (module.js:624:30)
at Object.Module._extensions..js (module.js:635:10)
at Module.load (module.js:545:32)
at tryModuleLoad (module.js:508:12)
at Function.Module._load (module.js:500:3)
```

Add selectors to files

---

packages/react-router-redux/modules/__tests__/selectors-test.js
packages/react-router-redux/modules/selectors.js

If one uses the `createMatchSelector` selector function provided by this library (presumbly using `connect`) in a component that could potentially be in an uninitialized state where the `router` property has not yet been initialized by redux (i.e. the root `<Router>` component of your route hierarchy), the line at https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/modules/selectors.js#L9 causes the selector to throw an error by destructuring on the `undefined` return value of `getLocation(state)`.

react-router-redux/createMatchSelector: handle null case when router state is not yet initialized

---

packages/react-router/docs/api/Switch.md

The `./` there is important to give the correct link when rendered.
Note that this is not related to #5259
Also note that this breaks not the link when browsing github repo, but for the [website](https://reacttraining.com/react-router/web/api/Switch/Switch-props) - the hyperlink points to `/react-router/location.md` instead of `/react-router/web/api/location.md`

Fix link to location.md in <Switch> documentation

---

package.json

After upgrading to React 16 the react-router v3 throws a peerDependency warning.
This fix it to stop this warning and allow downstream modules to build without peerDependency failures.

Version 3: Added peerDependency support for React 16.0.0

---

website/modules/examples/Animation.js
website/package.json

For beginners like me it would be nice if you would use the latest version from react-transition-group in your Animations example. In v2 of react-transition-group the implementation for CSS Transitions changed slightly.

Updated react-transition-group and changed Animation.js example

---

packages/react-router-redux/examples/AuthExample.js
packages/react-router-redux/examples/BasicExample.js

I made some general improvements to things I noticed in the examples:
- Removed duplicated imports;
- Removed semicolons; 
- Changed indentation style;
- Fixed `authReducer` which was removing any props other than `isAuthenticated` because of the spread operator and also triggering an update on default case;

Improvements to react-router-redux examples

---

packages/react-router-dom/modules/BrowserRouter.js
packages/react-router-dom/modules/HashRouter.js
packages/react-router/modules/MemoryRouter.js
packages/react-router/modules/StaticRouter.js
packages/react-router/modules/__tests__/Route-test.js
packages/react-router/modules/__tests__/Router-test.js
packages/react-router/modules/__tests__/SwitchMount-test.js

Fixes https://github.com/ReactTraining/react-router/issues/5576
The issue is when we have something like 
`import createBrowserHistory from  'history/createBrowserHistory'`
you get file included into the result dist:
` node_modules/history/createBrowserHistory.js`
And then when you import something like
`import {smth} from 'history'`
and your webpack or other build tool is configured to read packages.json>module property then it includes node_modules/history/es/index.js and then node_modules/history/es/createBrowserHistory.js
So both files are included:
```
node_modules/history/createBrowserHistory.js
node_modules/history/es/createBrowserHistory.js
```

Use named import of 'history' module to fix #5576.

---

packages/react-router/docs/api/history.md

Correct me if I'm wrong, but I believe `history.location.state` is an `object` and not a `string`?

Change `history.location.state` to `object`

---

packages/react-router/docs/guides/philosophy.md

`API's` is possessive, `APIs` is the plural of `API` (I think. If I'm wrong I'm about to learn some grammar!)

Grammar fix on philosophy page

---

packages/react-router-redux/modules/__tests__/selectors-test.js
packages/react-router-redux/modules/selectors.js

Hi and thanks a lot for this package,
I've notice a pretty annoying bug with the `createMatchSelector`. In this PR I've added a test to reproduce the bug and a fix.
Basically what happens is that the selector doesn't update the `match` object if what have change is the `isExact` property.
For instance, if I have a "matchSelector" for the path "/sushi" and the user navigates from "/sushi" to "/sushi/dynamite", despite of the fact that the `match` object is different (before it was an exact match and now it it's not) the previously memoized match is the one that is returned.
It's an easy fix.
Thanks,
Josep

[BUG-FIX]: createMatchSelector isExact

---

packages/react-router-config/README.md
packages/react-router-config/modules/__tests__/renderRoutes-test.js
packages/react-router-config/modules/renderRoutes.js

In order to render routes in a `modal` using `renderRoutes` (https://reacttraining.com/react-router/web/example/modal-gallery), `renderRoutes` receives an optional `location` argument to set on the `Switch` component.

Add Switch location argument to renderRoutes

---

packages/react-router-redux/modules/ConnectedRouter.js
packages/react-router-redux/modules/__tests__/ConnectedRouter-test.js

A followup PR of [this discussion](https://github.com/ReactTraining/react-router/pull/5786#issuecomment-351220936).
cc @ericp96

[FIX]: Allow other middlewares to dispatch routerActions on init

---

packages/react-router-dom/docs/api/Link.md

In v3 the docs [clearly indicated](https://github.com/ReactTraining/react-router/blob/07d6b50ab9a9b6d1940d67abe530044be7f7dc99/docs/API.md#others) that `<Link>` takes DOM props to be put on `<a>`.
In v4 docs this information [is missing](https://reacttraining.com/react-router/web/api/Link).
Nevertheless, the functionality [is still here](https://github.com/ReactTraining/react-router/blob/96410c69be1ca32e294bf83e7d1321c39ecd286b/packages/react-router-dom/modules/Link.js#L76).
The contributors [refer to it](https://github.com/ReactTraining/react-router/issues/5760#issuecomment-347979291) as expected, public functionality.
The [`activeClassName` prop on `NavLink`](https://reacttraining.com/react-router/web/api/NavLink/activeClassName-string) clearly suggests that a regular `className` is …

Bring back documentation on Link DOM props

---

packages/react-router-dom/modules/Link.js
packages/react-router-dom/modules/__tests__/Link-test.js

First off - thanks for creating this. Me, myself and my team - and thousands of other developers across the world - are building incredibly successful apps thanks to your hard work and sexy brains. I hugely appreciate your efforts.
Now, to business.
Whenever you forget to set the `to` property on a `<Link />` component, You get the following error message:
If I scroll long enough up the error log, you'll see the error from prop types telling me I forgot to set the required `to` prop - but it usually takes me a minute to figure it out. With the rising of `create-react-app` - many people will probably not find it for a bit, because they are busy looking through the stack traces in the error overlay (like I was in my screen shot above).
**This PR adds an invariant check** (I'm very open to …

Add invariant for missing "to" property

---

packages/react-router/docs/guides/migrating.md

Hiya, thanks for all the fab work on these packages. So it wasn't until I was pretty far through the upgrade to react-router v4 that I found [these issues](https://github.com/ReactTraining/react-router/pull/4717) with react-router-redux and React DevTools. Obviously it will take time for the tooling etc to catch up with new releases of popular packages, but would it be possible to publicise this issue a little more?

Warn of possible tooling loss on upgrade

---

package-lock.json
package.json

This PR adds [`pretty-quick`](https://github.com/azz/pretty-quick) to automatically run `prettier` on staged files before committing. There are [two choices listed on the prettier site](https://prettier.io/docs/en/precommit.html), `pretty-quick` and [`lint-staged`](https://github.com/okonet/lint-staged), but I went with `pretty-quick` because its config is simpler and I don't think RR needs any other pre-commit linting.

Run prettier on commit

---

packages/react-router/docs/api/matchPath.md

URL's with query strings don't get matched correctly when using `req.url`. `req.path` is required instead. This PR simply updates the documentation.
https://github.com/ReactTraining/react-router/issues/5285

Update `req.url` to be `req.path`

---

package-lock.json
package.json

There was an issue with the previous `pretty-quick` release that added all edited files (not just staged ones) when committing, which is fixed in this release.

pretty-quick v1.2.2

---

packages/react-router/docs/api/Router.md

The previous relative links introduced in #5441 only works in the repo-view in GitHub. When published on the home page they don't resolve to an existing route. This aligns the markup for the non-working links with those that do work.
Verifying:
1. Check todays [site](https://reacttraining.com/react-router/web/api/Router)
2. Press the static or memory router links
3. See that you are being redirected to the root page, not the subsection
Also, just check the links directly:
- Non working link: https://reacttraining.com/react-router/StaticRouter.md
- A working link on the actual header element: https://reacttraining.com/react-router/web/api/StaticRouter

Fix non-functional links to routers

---

packages/react-router/docs/api/Prompt.md

`true` to allow the transition was not yet shown, do you think it's a useful addition to the documentation ?

Prompt doc: add example message returns true

---

packages/react-router/docs/api/Route.md

The old example was wrong: with path=`/One`, location.pathname=`/one` and sensitive=`false`, the Route will match

Fix documentation for Route's sensitive attribute

---

ISSUE_TEMPLATE.md

Even when the issue template is used, this value seems to be ignored. If the user doesn't update the string we can probably assume that they are on the latest release, but hopefully the bold text will encourage people opening issues to set the correct version.

Don't hard-code version in ISSUE_TEMPLATE

---

packages/react-router/docs/api/match.md
packages/react-router/modules/Route.js
packages/react-router/modules/Switch.js
packages/react-router/modules/__tests__/Route-test.js
packages/react-router/modules/__tests__/matchPath-test.js
packages/react-router/modules/__tests__/withRouter-test.js
packages/react-router/modules/matchPath.js
packages/react-router/modules/withRouter.js

Recreating #4704 under a branch on the main repo. 
Original PR post:
This moves the logic for getting the match object for a pathless `<Route>` `matchPath`. When automatic path resolving is added, `matchPath` will need access to the parent `match`, so we will need to pass that argument to `matchPath` eventually anyways.
When a parent `match` is `null`, a match object with default values is returned by `matchPath`. This match object should not be relied upon for resolving paths, but it will allow a `<Route>` that uses the `component` or `render` prop to render.
Fixes #4695

Fix pathless route's match when parent is null 

---

packages/react-router-dom/modules/__tests__/NavLink-test.js

Further to PR #5142 and subsequent fix in #5964, reimplementing the original unit tests I wrote

Reimplement tests from #5142

---

packages/react-router/modules/StaticRouter.js
packages/react-router/modules/__tests__/StaticRouter-test.js

Currently, there is an inconsistency between the pseudo-history used by the `<StaticRouter>` and the histories created by the `history` package because the `history` package creates locations with decoded pathnames, while the pseudo-history does not. This PR updates the `<StaticRouter>` to use the `createLocation` function from the `history` package to ensure consistent decoding between `<StaticRouter>` and the other routers.
Fixes #5296. #5359 is also partially fixed by this, but that also includes `matchPath` tests which are outside the scope of this PR.

Use history.createLocation in <StaticRouter>

---

packages/react-router-redux/modules/ConnectedRouter.js
packages/react-router-redux/modules/__tests__/ConnectedRouter-test.js
packages/react-router-redux/modules/__tests__/reducer-test.js
packages/react-router-redux/modules/__tests__/selectors-test.js
packages/react-router-redux/modules/index.js
packages/react-router-redux/modules/reducer.js
packages/react-router-redux/modules/selectors.js

It seems like react-router-redux assumes the action property is in the location object provided by the history module. So I've added the action property back into the store and added a selector. I've also updated the tests and added a test for this change.
We're interested in the action used to cause the route change, to react to `POP`s and `PUSH`s
The `location` object doesn't seem to have an `action` property when using `history/createBrowserHistory`
The createLocation function is missing the action property https://github.com/ReactTraining/history/blob/master/modules/LocationUtils.js#L5

Fix history api changes in react-router-redux

---

packages/react-router-config/package.json
packages/react-router-dom/package.json
packages/react-router-native/package.json
packages/react-router-redux/package.json
packages/react-router/package.json

Webpack 4.0 introduced support for a `sideEffects` flag in a project's `package.json`: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free. This is awesome because we can now get Webpack's tree shaking to work as intended for most, if not all projects. 🎉 
I've noticed that in my projects where I've used `react-router-dom`, the recommended import syntax (eg. `import { Route } from 'react-router-dom'`) still pulls in the entire library. While react-router-dom and it's associated packages aren't _that_ large, I'm a bit of a performance junkie 😃. All this PR does is add the `sideEffects: false` flag to the `react-router-dom` package. I created a simple test repo to demo the effects of this flag: https://github.com/taylorc93/react-router-test. I'm noticing ~20KB of …

Add sideEffects: false to react-router-dom package.json

---

website/modules/base.css

Fixes #6052
Prevents large code blocks from being wrapped at sub 1266px widths.

Embiggen the large breakpoint

---

packages/react-router/docs/api/Redirect.md
packages/react-router/docs/api/Route.md
packages/react-router/docs/guides/migrating.md

The most recent `path-to-regexp` versions are backward incompatible:
https://github.com/pillarjs/path-to-regexp#compatibility-with-express--4x
https://github.com/pillarjs/path-to-regexp/blob/master/History.md#200--2017-08-23
Just so people don't waste their time reading the wrong documentation.

Change `path-to-regexp` references to ^1.7.0

---

packages/react-router/modules/__tests__/generatePath-test.js
packages/react-router/modules/generatePath.js

this is a failing test to reproduce issue #6171 
not sure how to fix it yet

test(core): add failing test to generatePath, see #6171

---

packages/react-router/docs/guides/migrating.md

Added:
- optional parameters
- routeParams
- query - gone, only unparsed search
- getParamNames

Updated migrating doc from v2/v3 to v4

---

packages/react-router-native/docs/api/Link.md

otherwise it throws Invariant Violation: React.Children.only expected to receive a single React element child.

wrap text in a Link with a Text element

---

packages/react-router-config/modules/__tests__/renderRoutes-test.js
packages/react-router-config/modules/renderRoutes.js

This PR allows to use render as valid callback in the `react-router-config` configuration tree.
It tries to resolve the #4962 issue and it's implemented based on this idea:
https://github.com/ReactTraining/react-router/issues/4962#issuecomment-376567551
For example:
```
{
{
path: "/restricted-area",
render: (props) => isUserLoggedIn() ? <RestrictedArea/> : <Redirect to="/login"/>
},
{
path: "/login",
component: Login
}
}
```

Added support for render method in react-router-config

---

packages/react-router/modules/Redirect.js

See https://github.com/ReactTraining/react-router/pull/6278#issuecomment-412213622 for rationale. In short, the change merged in #6278 will actually _increase_ bundle size for ESM builds if other parts of react-router are used which include other parts of the history module.
Instead, please consider merging ReactTraining/history#597 and releasing a new version of the history module, which would allow webpack to more aggressively tree-shake react-router's use of history, providing equivalent bundle size savings regardless of how much of react-router is used.

Revert namespaced history import

---

packages/react-router-config/modules/matchRoutes.js
packages/react-router-config/modules/renderRoutes.js

I was recently doing some bundle size analysis using source-map-explorer
and noticed that we had a little bit of duplication of react-router
code. It seems as though our import of react-router-config was bringing
in modules from react-router/Foo, while our named imports from
react-router was bringing in modules from react-router/es/Foo.
As a workaround, I've set up a webpack alias to avoid the duplication,
but I think this should be solved in this package so that everyone can
benefit.
I believe this is similar to:
- https://github.com/ReactTraining/react-router/pull/5589

Used named imports for react-router in react-router-config

---

packages/react-router-dom/docs/guides/code-splitting.md

Babel has updated its core name to @babel/core and the same naming convention is now applied to plugins too. 
The plugin `babel-plugin-syntax-dynamic-import` is now available as `@babel/plugin-syntax-dynamic-import`. 
The old version is also available but that will not work with Babel v7+
Cheers

Update Babel plugin name

---

website/modules/examples/Basic.js

Although match.url works in this basic example, match.path should be used for nested routes.

Change match.url to match.path for nested routes

---

packages/react-router-native/docs/guides/quick-start.md
website/modules/examples/Basic.js

Although match.url works in this basic example, match.path should be used for nested routes.

 Update react-router-native Quickstart Guide

---

packages/react-router/docs/api/Route.md
packages/react-router/docs/api/matchPath.md
packages/react-router/modules/Route.js
packages/react-router/modules/__tests__/Route-test.js
packages/react-router/modules/__tests__/matchPath-test.js
packages/react-router/modules/matchPath.js

I piggybacked off of the tests written for `matchPath()` by @Shervanator at #5393, and I'm tackling the issue described by @mjackson at #5866.
- Added support for arrays of paths to `<Route>` and `matchPath()`
- Added a test case to demonstrate that `match.path` is a string
- Added a test case to demonstrate that the component doesn't remount on switches between two matching paths
I'm happy to add docs and examples if everybody is satisfied with the behavior. Let me know if you think any changes are in order as well.

add support for an array of paths in <Route> and matchPath

---

website/modules/components/FakeBrowser.js
website/modules/docs/Web.js
website/modules/examples/QueryParams.js
website/package.json

Issue #5789 requested an example/guide for working with url parameters in `react-router`. I implemented this as an example since they allow for a functioning example that a visitor the docs can interact with and see it in action.
Almost all (if not all) of the code was gathered from that issue and formatted to work with the docs.
At the top of the example, I put a short bit of copy about the fact that url params are implemented using an external library. I just took a stab at this so please feel free to let me know if there are any additional changes that need to made to this copy or the code for the example.

Add example to docs for working with url parameters.

---

packages/react-router-dom/modules/Link.js

rename ...props on Link.js to ...rest - same naming convention used on NavLink.js. renaming for consistency.
also refactored   proptypes.

Refactor - Link.js -  {...props} to {...rest}

---

packages/react-router-config/package.json

There is a missing file in the `react-router-config` package (`warnAboutDeprecatedCJSRequire.js`). This PR adds it in package.json so that it's included when publishing a new version on npm.

Added warnAboutDeprecatedCJSRequire.js in package.json

---

packages/react-router-dom/docs/guides/quick-start.md
packages/react-router/docs/guides/philosophy.md
website/modules/docs/Native.js
website/modules/docs/Web.js

Hi y'all, thanks to everyone for all the work that's gone into this library!!! 👍 
Here's a summary of my progress so far:
RE: #6409

Improve Initial Docs Experience

---

website/modules/components/Home/Header.js

While watching newcomers try navigate the Home Page, I think I've found a point of confusion. 
The presence of a button labelled "Anywhere" seems to throw them off. 
It sounds like a safe catch-all. Yet most people likely want to see usage examples for either "Web" or "Native"
I'd leave the "Core" section in the docs for now:

Removed the "Anywhere" button from Home Page

---

packages/react-router-dom/.size-snapshot.json
packages/react-router-dom/modules/Link.js
packages/react-router-dom/modules/NavLink.js
packages/react-router-dom/package-lock.json
packages/react-router-dom/rollup.config.js

Ref https://github.com/ReactTraining/react-router/issues/6464
Here's the problem. Babel transpiles static class properties outside of class iife which blocks uglify/terser from this iife.
`defaultProps` will become a bad pattern soon since it's blocks treeshakability. For functions the problem is even more aggressive since it's not solvable these days.
I think the best we may do is use defaults in destructuring
```js
const Component = ({ prop1 = 'a', prop2 = 'b' }) => {
}
```
With classes this is harder because defaults can't be propagated in all methods.

 Make react-router-dom treeshakable

---

packages/react-router-native/docs/guides/animation.md

Typo fix: `renered`=> `rendered`

Docs improvement

---

packages/react-router/modules/__tests__/withRouter-test.js
packages/react-router/package-lock.json
packages/react-router/package.json

The fix was just a major bump of `hoist-non-react-statics` to include mridgway/hoist-non-react-statics#55. The breaking change was the hard dependency on `react-is` which is already included in `react-router`. Therefore this change is not breaking. As a side effect this will also prevent hoisting of [`contextType`].(https://reactjs.org/docs/context.html#classcontexttype)
The added test case will cover the change required for #6056.

 Fix withRouter components being considered forwardRef types

---

packages/react-router-dom/.size-snapshot.json
packages/react-router-dom/modules/NavLink.js

Since `NavLink` returns a wrapped `Link` component and passed all of its props to the `Link`, this should also be reflected in `NavLink.propTypes`.

NavLink.propTypes should extend Link.propTypes

---

packages/react-router-dom/docs/guides/code-splitting.md

As far as I can tell `@babel/react` isn't a thing
Seems like `@babel/preset-react` was what was intended
Might be good to change this to use React.lazy or @loadable/component instead?
`react-loadable` is [no longer maintained](https://www.smooth-code.com/open-source/loadable-components/docs/loadable-vs-react-lazy/#note-about-react-loadable)

Changes referenced preset to @babel/preset-react

---

packages/react-router-dom/docs/guides/code-splitting.md

[loadable-components](https://github.com/smooth-code/loadable-components) is the officially recommended way to do code splitting with dynamic imports in React: https://reactjs.org/docs/code-splitting.html#reactlazy
react-loadable does not accept issues and is starting to look like an unmaintained project. As React Training was one of the first guides that came up when I was googling how to do dynamic loading in react it seems sensible to change the docs to avoid other people wasting time going down the (in my opinion) wrong path
Many thanks

Replace react-loadable with loadable-components

---

CHANGES.md
packages/react-router-dom/.size-snapshot.json
packages/react-router-dom/docs/api/Link.md
packages/react-router-dom/modules/Link.js
packages/react-router-dom/modules/__tests__/Link-test.js

When using [`React.createRef()`](https://reactjs.org/docs/react-api.html#reactcreateref) with the `innerRef` prop of a `Link`, a false positive prop-types error appears. But it works perfectly.
This PR adds the shape of a `RefObject` (name for `React.createRef()` return type) as a valid prop type for `Link`'s `innerRef`.

Added RefObject as valid Link innerRef

---

packages/react-router-dom/docs/api/NavLink.md

Based on this line of code, we need either update the code or the doc.
https://github.com/ReactTraining/react-router/blob/4dc6e16b447191aedcac557a81ac26c307a0d9c7/packages/react-router-dom/modules/NavLink.js#L15
I updated the document, since all **aria-*** HTML attributes are fully supported in JSX based on
https://reactjs.org/docs/accessibility.html#wai-aria

change from ariaCurrent to aria-current

---

packages/react-router-dom/modules/Link.js

Polyfill Element for Node

---

packages/react-router/docs/api/Router.md

The example showing how to use a custom history object is referencing an outdated import path. Change it to a supported one.
Also see https://github.com/ReactTraining/history/blob/465288b91859244d401103c079c058c0a2be5cb0/createBrowserHistory.js#L2

Example references deprecated API

---

packages/react-router/docs/api/Redirect.md

I checked the docs for the other pull-request and noticed that ```sensitive``` was absent.

Document Redirect sensitive prop.

---

packages/react-router/modules/RouterContext.js

I wasn't seeing these named correctly in DevTools. Looking at https://github.com/facebook/react-devtools/pull/1031#issuecomment-423288506 this seems to be the way to do it. Thanks!

fix: set DisplayName correctly for Named Context

---

packages/react-router/package-lock.json
packages/react-router/package.json

`0.2.2` uses the [MIT license](https://unpkg.com/create-react-context@0.2.2/LICENSE) while `0.2.3` uses a  [custom license](https://unpkg.com/create-react-context@0.2.3/LICENSE).

Pin create-react-context to 0.2.2

---

packages/react-router/modules/Redirect.js
packages/react-router/modules/__tests__/Redirect-test.js

Fixes #6673
Basically, "to" can be a string or a location object. But only the case for objects was covered, hence the infinite loop in cases where the <Redirect/> is still being rendered after the location change.

Fixed maximum update depth exceeded caused by Redirect.

---

packages/react-router-dom/.size-snapshot.json
packages/react-router/.size-snapshot.json
packages/react-router/modules/withRouter.js

Currently, withRouter(Foo) would render with 5 levels:
```jsx
<withRouter(Foo)>
<Route>
<ContextConsumer>
<ContextProvider>
<Foo/>
</ContextProvider>
</ContextConsumer>
</Route>
</withRouter(Foo)>
```
With this PR, it's only 3 levels:
```jsx 
<withRouter(Foo)>
<ContextConsumer>
<Foo/>
</ContextConsumer>
</withRouter(Foo)>
```
I also took the opportunity to clarify the warning. Previously, using withRouter(Foo) would have yielded ```"You should not use <Route> outside a <Router>"```. I've ran into that warning a couple of times myself and it's particularly unhelpful.

withRouter: Directly use RouterContext instead of Route.

---

packages/react-router/modules/Redirect.js
packages/react-router/modules/__tests__/Redirect-test.js

Piggybacking off https://github.com/ReactTraining/react-router/pull/6674 to also handle object.
Resolves https://github.com/ReactTraining/react-router/issues/6689

call createLocation on 'to' regardless of type

---

packages/react-router-dom/.size-snapshot.json
packages/react-router/.size-snapshot.json
packages/react-router/modules/RouterContext.js
packages/react-router/package-lock.json
packages/react-router/package.json

I forked create-router-context because I saw that the package didn't see much activity anymore and had some obvious tweaks to be made.
| | original | mini
|---|---|---|
| bundled sized | [1.4kB minzip](https://bundlephobia.com/result?p=create-react-context@0.2.3) | [1.2kB minzip](https://bundlephobia.com/result?p=mini-create-react-context@0.3.0)
| install size | [**2.45 mB**](https://packagephobia.now.sh/result?p=create-react-context)  | [32kB](https://packagephobia.now.sh/result?p=mini-create-react-context)
See also the [install-size of RR.](https://packagephobia.now.sh/result?p=react-router-dom) and how it's gone *way* up with 5.0

Switch to mini-create-router-context

---

packages/react-router/modules/StaticRouter.js

If you instantiate StaticRouter without providing a context object and attempt to render e.g. a Redirect, an error is thrown because context will be undefined.

Add a default value for context in StaticRouter.navigateTo

---

packages/react-router/modules/__tests__/matchPath-test.js
packages/react-router/modules/matchPath.js

matchPath: Fixed exception thrown if `path` is undefined

---

packages/react-router-dom/.size-snapshot.json
packages/react-router-dom/modules/Link.js
packages/react-router-dom/modules/__tests__/Link-test.js
packages/react-router/.size-snapshot.json

Solves: https://github.com/ReactTraining/react-router/issues/6709
1. catch exception of onClick
2. prevent default event handler
3. re-throw exception

prevent reload of page if an error occurs in onClick event handler

---

packages/react-router-config/rollup.config.js
packages/react-router-dom/.size-snapshot.json
packages/react-router-dom/rollup.config.js
packages/react-router/.size-snapshot.json
packages/react-router/rollup.config.js
website/package-lock.json
website/package.json

Fixes #6622 and hopefully allows more people to contribute.
The fix is relatively straightforward:
* In the rollup configs, I changed the check from starting at root ("/") to check if the <package>/modules path is referenced.
* I changed the `NODE_ENV=production webpack -p` command for building the website with to a cross-plattform way of setting the enviroment variable.
This should be just a one-time effort and not result in any additional maintenance overhead.

Fix build on windows.

---

packages/react-router/modules/withRouter.js

Doesn't warn about `createRef` or `useRef` values in `wrappedComponentRef`

fix(react-router): Allow string and object refs in withRouter

---

packages/react-router-dom/.size-snapshot.json
packages/react-router-dom/modules/NavLink.js
packages/react-router-dom/modules/__tests__/NavLink-test.js
packages/react-router/.size-snapshot.json

See comments [here.](https://github.com/ReactTraining/react-router/issues/6613#issuecomment-472109397)
I added some unit tests in NavLink-test and also removed the location override as a precaution for other interactions.

Don't override path in NavLink component. Fixes #6613

---

packages/react-router-config/rollup.config.js
packages/react-router-dom/rollup.config.js
packages/react-router/rollup.config.js

As suggested from previous PR, any client exclusively using react-router-dom package via CommonJS modules will run into this problem:
```
TypeError: Cannot assign to read only property '__esModule' of object '[object Object]'
at node_modules/react-router-dom/cjs/react-router-dom.js:288:64
at Array.forEach (<anonymous>)
at Object.<anonymous> (node_modules/react-router-dom/cjs/react-router-dom.js:288:26)
at Object.<anonymous> (node_modules/react-router-dom/index.js:6:20)
```
Changing rollup config to omit `Object.defineProperty(exports, '__esModule', { value: true });` will fix this, however my suggestion in https://github.com/ReactTraining/react-router/pull/6757 seems less heavy handed in that it doesn't break interop https://stackoverflow.com/a/55687758

esModule: false fix read only TypeError in exports

---

packages/react-router-dom/docs/guides/scroll-restoration.md

While using the scroll restoration example I rewrote it using hooks and I thought it'd be useful to add it to the docs, as I'm sure others will want to as well and it'll save everyone time.

add hooks option to scroll restoration docs

---

packages/react-router-dom/.size-snapshot.json
packages/react-router-dom/docs/api/Link.md
packages/react-router-dom/modules/Link.js
packages/react-router-dom/modules/NavLink.js
packages/react-router-dom/modules/__tests__/Link-test.js
packages/react-router-dom/modules/__tests__/NavLink-test.js
packages/react-router-dom/modules/utils/locationUtils.js

closes https://github.com/ReactTraining/react-router/issues/5331

Make Link and NavLink components accept "to" property as a function

---

packages/react-router-dom/.size-snapshot.json
packages/react-router-dom/modules/Link.js
packages/react-router-dom/modules/__tests__/Link-test.js

This PR adds a `<Link component>` prop that links can use to render a custom component instead of an `<a>`.
This has been an oft-requested feature over the years that we've traditionally not wanted to add because all links on the web should be `<a>` tags for accessibility reasons. However, this limitation means that we have different APIs between `react-router-dom`'s `<Link>` and `react-router-native`'s `<Link>`, which makes it difficult to reuse code across native and web.
For previous discussion, see #4625 and #5437
/cc @necolas @lazyelephant

Add <Link component> prop

---

website/modules/basename.js
website/modules/components/App.js
website/modules/components/DelegateMarkdownLinks.js

Currently, the "internal links" (the ones in markdown) manually push themselves. However, the URLs that the push include the `/react-router` basename. history doesn't do any basename removal with its `push`/`replace` methods, so the basename ends up in the location object that it emits to its listeners This, in turn, causes issues with the router which fails to match a location that begins with `/react-router` and forces a redirect to the home page.
I've tested that the replace function works and that the site runs locally, but I don't have a convenient way to test the site running with the basename.
Hopefully at some point the documentation will switch to something like MDX so that all of these markdown hacks can go away :smile:.

Remove basename before pushing internal links

---

packages/react-router-dom/docs/guides/scroll-restoration.md

In the example, use cases of `ScrollToTop` are presented with both a component with a children and a self-closing one. The component however did not handle the self-closing (childless) use case.

docs: update scroll-restoration code example

---

packages/react-router-dom/.size-snapshot.json
packages/react-router/.size-snapshot.json
packages/react-router/docs/api/matchPath.md
packages/react-router/modules/__tests__/matchPath-test.js
packages/react-router/modules/matchPath.js

Currently `matchPath()` accepts a string as 2nd argument as shortcut for `{ path }`. Since path could also be an array, I recommend a shortcut for this too.
```javascript
matchPath("/foobar", [ "/foobar", "/hello-world" ])
```

matchPath() accepts an array of paths as 2nd argument

---

packages/react-router-config/package.json
packages/react-router-config/rollup.config.js
packages/react-router-dom/package.json
packages/react-router-dom/rollup.config.js
packages/react-router/package.json
packages/react-router/rollup.config.js

Unless your idea of fun is mentally un-transpiling ES5 code into ES6 and JSX, you'll like this PR. It makes debugging easier by adding sourcemaps for the react-router, react-router-dom, and react-router-config packages.  The following build-time config changes are included: 
1. Add `sourceMaps: true` to babel config for each package 
2. Make a similar change to rollup `output` config, except it's called `sourcemap: true` here because, uh, diversity is good? ;-)
3. Added the source files in the `modules` folder to the `files` whitelist in each package's package.json, so that the original source will be installed by npm or yarn so that the sourcemaps have original source to point to.
4. Unlike the other module formats, UMD bundles all dependencies and therefore its sourcemaps include …

build: add sourcemaps

---

packages/react-router-dom/docs/api/BrowserRouter.md
packages/react-router-dom/docs/api/HashRouter.md
packages/react-router-native/docs/api/NativeRouter.md
packages/react-router/docs/api/MemoryRouter.md
packages/react-router/docs/api/Router.md
packages/react-router/docs/api/StaticRouter.md

Hi!
The correct link to the `React.Children.only` API doc is `https://facebook.github.io/react/docs/react-api.html#reactchildrenonly`, not `https://facebook.github.io/react/docs/react-api.html#react.children.only`. This PR fixes that.
Cheers!

docs: Fix links to reactjs docs

---

packages/react-router-config/modules/__tests__/utils/renderToStringStrict.js

This fixes issue #6854 because you were using es6 import to find the default export, but in renderToStringStrict.js you were still using the old export

export default renderToStringStrict

---

packages/react-router/docs/api/matchPath.md

Hi,
I have noticed that there are small styling problems for [matchPath returns](https://reacttraining.com/react-router/web/api/matchPath/returns) documentation.
Small PR for updating the markdown readme with _JS code blocks_ and splitting **object** and **null** return examples.

Improve documentation readability for matchPath

---

packages/react-router/docs/api/location.md

Noticed this when I copied and pasted the location structure into REPL to test some code.

docs: Fix missing comma in docs/api/location.md

---

packages/react-router-dom/modules/Link.js
packages/react-router-dom/modules/NavLink.js
packages/react-router-dom/modules/__tests__/Link-test.js
packages/react-router-dom/modules/__tests__/NavLink-test.js

This allows components like @reach/menu-button to manage focus or do anything else they need to with the underlying DOM element.
This prefers the forwarded ref, but `innerRef` will still work too.
Related: reach/reach-ui#54

Use forwardRef on Link, NavLink

---

packages/react-router/docs/api/Redirect.md

I spent a while wondering why my `<Redirect>` was not behaving as expected as can be seen [here](https://github.com/ReactTraining/react-router/issues/6911).
This simple clarification would have saved me from the misunderstanding.

Clarifying documentation <Redirect> exact & strict

---

packages/react-router/docs/api/location.md

Incorrect usage "its"; "it's" is correct here, a contraction for "it is"

Fix typo in docs for location API

---

packages/react-router/docs/guides/testing.md

The creation of a custom navigation-specific testing harness seems a bit too purpose-built for most people. Change to an integration test that leverage JSDOM's browser globals to use BrowserRouter directly.
cc @kentcdodds for 👀

remove clever example in testing guide

---

packages/react-router/modules/__tests__/useParams-test.js
packages/react-router/modules/hooks.js

fixed by returning empty object if route not mounted
Closes #6938

fix(useParams): fix issue with useParams reading from null object

---

packages/react-router/modules/__tests__/matchPath-test.js
packages/react-router/modules/matchPath.js

fixes https://github.com/ReactTraining/react-router/issues/6941
related https://github.com/ReactTraining/react-router/pull/6715

fix regression to allow for empty-string paths

---

packages/react-router-dom/docs/guides/quick-start.md

You need to use `component={xxx}` syntax, otherwise match will be `undefined`.

Fix documentation for nested routing

---

packages/react-router/docs/guides/testing.md

Fix a duplicated variable definition and missing one in a testing guide code example.

Fix code example in testing guide

---

modules/ContextUtils.js
modules/Router.js

The existing version detection was broken because `parseFloat('16.10.1')` results in `16.1`. Solution borrowed from https://github.com/reduxjs/react-redux/pull/1407
We still have several dozen apps using `react-router@3` and this fix would be useful for us. Thanks!

v3: fix React version detection for lifecycle renaming

---

packages/react-router-dom/docs/guides/quick-start.md

I think `useRouterMatch` should be `useRouteMatch` here.
(Which would explains why I wasn't finding many results for useRouterMatch 😂)

fix typo in examples: change useRouterMatch to useRouteMatch

---

packages/react-router-dom/modules/index.js
packages/react-router-native/main.js

Instead of using `export * from "react-router"` in react-router-dom and react-router-native, this PR changes it so we export everything explicitly, which makes it easier for static code analysis tools to know which names are actually exported from that module.

Make react-router exports explicit

---

packages/react-router/docs/api/hooks.md

I found the [blog post introducing the react router hooks](https://reacttraining.com/blog/react-router-v5-1) to have a bit more [information on `useRouteMatch`](https://reacttraining.com/blog/react-router-v5-1/#useroutematch) than the [website's documentation](https://reacttraining.com/react-router/web/api/Hooks/useroutematch).
I just added a little bit about how you can also pass in an object, not just a string and used the example from the blog post.
I actually ran into an issue getting the website to run locally, so I couldn't exactly test it. I thought about raising a new issue, but it looks like #5830 was closed saying you don't support running the website.

add more detail to useRouteMatch hook documentation

---

docs/advanced-guides/migrating-5-to-6.md

Stringify argument of `navigate` because
`history.go` is called if the argument is a number.
<https://github.com/ReactTraining/react-router/blob/92502f2f6769dbf5ce4c7b154b1f6e1d27af6d07/packages/react-router/index.js#L398-L399>
Demo: <https://stackblitz.com/edit/react-router-fix-migrating-5-to-6-code-example>

[dev] Fix code example in the guide for migrating 5 to 6

---

package.json
yarn.lock

We have several (in the hundreds) of apps still using `react-router` v3 and have recently run into issues related to `withRouter` hoisting statics that it shouldn't. We have our own internal solution and are not blocked but I wanted to make this PR in case anybody else has these issues. 
My solution here is to upgrade `hoist-non-react-statics` and `react-is`. Thanks much!

[v3] upgrade hoist-non-react-statics/react-is

---

scripts/builds/react-router-dom.js

This is just the remaining tweaks for #7168, without the erroneous `prop-types` fix.

Slightly smaller modern output for react-router-dom

---

packages/react-router/docs/api/match.md

Since the addition of `useRouteMatch`, there’s a new way to access a _match_ object 😄

Update docs to reference useRouteMatch

---

packages/react-router/docs/api/history.md

Wasn't sure about the "properties" link so I just pointed it to the main docs page. Alternatively, it could point to ["Misc"](https://github.com/ReactTraining/history/blob/master/docs/Misc.md)?

Update links to history docs

---

packages/react-router-dom/modules/NavLink.js
packages/react-router-dom/modules/__tests__/NavLink-test.js

Seems to me like this was probably just left out as an oversight and not for a specific reason.

Support `sensitive` matchPath option in NavLink

---

packages/react-router-dom/docs/api/BrowserRouter.md

Updated the docs of BroswerRouter to change the example code of basename case in which BroswerRouter for self-closing so as per the issue #7197 it should be defined with a closing tag.

update the docs for browserrouter in the example of basename.

---

packages/react-router-native/Link.js

The `Link` component in `react-router-native` always throws a warning regarding the type of its `component` prop when it is not explicitly passed a function. This is because by default `component` is set to `TouchableOpacity`, which always fails the propType test in development mode since `component: PropTypes.func`. Changing the type test to  `component: PropTypes.oneOfType([PropTypes.func, PropTypes.instanceOf(React.Component)])` preserves the intended behavior and doesn't throw a warning by default.

Fixed Link component prop type check

---

packages/react-router/docs/api/Prompt.md

Just spent a long time trying to solve a problem which this change would've helped me solve faster.
Another reason: The [@DefinitelyTyped type def for Prompt.message is wrong](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-router/index.d.ts#L51) and I'm opening a PR there to fix it too. Would love an `react-router` maintainer to give a 👍 over here to fix the type def too!
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44133

Clearly describe API of callback in code

---

packages/react-router/package.json

Update to latest version, as it doesn't depend anymore on the `gud` package, a package that has a problematic license file (missing copyright).
The API seems to be the same, so there shouldn't be any issues with this update.

chore(package): update mini-create-react-context to v0.4.0

---

packages/react-router-dom/index.tsx

This types the return as const to correctly infer the items within the array. Previously, the return array was (searchParams|setSearchParams)[], instead of [searchParams , setSearchParams], which made the usage impossible with correct typings.
Also setSearchParams parameters are now typed instead of just being any.

Improve useSearchParams types

---

packages/react-router/index.tsx

Fixes #7237
An empty string falls through the `||`, so this makes our check more explicit around `undefined/null`.
(I know I have no tests. I'm using the web editor...)

[v6] Allow generatePath to use empty string params

---

packages/react-router/index.tsx

There's two different signatures.
Options cannot be provided when using a delta number.

Split navigate function signature

---

packages/react-router-dom/modules/Link.js
packages/react-router-native/BackButton.js
packages/react-router-native/DeepLinking.js
packages/react-router-native/Link.js
packages/react-router/modules/HistoryContext.js
packages/react-router/modules/Router.js
packages/react-router/modules/createNameContext.js
packages/react-router/modules/hooks.js
packages/react-router/modules/index.js

Reference #6999 
As a suggestion from @MeiKatz . I added a new context for history object only to be used for useHistory hook and prevent the hooks from getting update triggerred by the original context.
The original context still has all the same properties without any change, the history object is also in the original context.
Tested with my project and it reduced rerendering greatly.

Separate history object to its own context

---

packages/react-router-dom/index.tsx

The `useSearchParams` hook actually takes an *optional* argument, according to how it interacts with `createSearchParams`.
The original declaration indicated that the return type is `(URLSearchParams | ((nextInit: any, navigateOpts: any) => void))[]`, meaning array whose every elements can be either `URLSearchParams` or a function, which is obviously not correct.
I strongly suggest a `NavigateOption` interface with generic `State`.

[v6] Fix definition for useSearchParams arguments and return type

---

packages/react-router/index.tsx

By providing a fallback value (here string), the type of that parameter will already be cast to string, so its unnecessary.

Unnecessary type declaration

---

packages/react-router/index.tsx

This PR adds a generic to readOnly to return the passed in object type.

Correctly infer the read only type

---

packages/react-router/docs/guides/testing.md

This PR fixes a bug with the testing documentation.
Currently it states you can call the same 'let' and replace it inside the render callback. This is not valid javascript and will not assign anything to the top level let. Therefore you need to call it something else rather then the destructed name eg testLocation and testHistory.

Fixed location test documentation

---

docs/api-reference.md

refs #7414 
I think there should be a prominent mention of the `end` prop and why you would use it, so I've added a note and code sample to the API Reference.
(I hope my description is accurate, but maybe "descendant paths" is incorrect?)

[v6] Added documentation for NavLink `end` prop

---

packages/react-router/docs/api/hooks.md

On one of my projects I needed to access the match object in a component and after searching in react-router code I found that `useRouteMatch` had an undocumented behaviour which is that it returns the Route context match when it is provided with no argument (see [here in the code](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/hooks.js#L44)).
The purpose of this PR is to document this.

Document useRouteMatch empty case

---

packages/react-router/docs/guides/testing.md

jsx code visually breaks because there are 2 pre blocks one after another
https://reactrouter.com/web/guides/testing

fix broken markup on testing page

---

packages/react-router/docs/api/history.md

Fixed the link to the history "blocking transitions" documentation.

Update link to history "blocking transitions" docs

---

website/index.html.ejs

Currently, Logo is not displayed at Twitter card.
`og:image` is url, not path.
https://ogp.me/

Fix og:image

---

packages/react-router-dom/docs/api/NavLink.md
packages/react-router-dom/modules/NavLink.js

In the [spec](https://www.w3.org/TR/wai-aria-1.1/#aria-current) the default value is "false" and currently there is an error that comes up when trying to set the value to false. The use case for this would be if there are multiple links on a page with `aria-current="page"` then the screen reader would alert the user multiple times about what the current page is.
I considered allowing for `false` as a boolean but that would be a larger change and "false" is already an option in the spec.
There are no tests currently enforcing what values are passed into `aria-current`, only that the expected output is returned, so I didn't need to update any tests for this PR.

Allow for "false" value for aria-current NavLink attribute

---

website/webpack/markdown-loader.js
yarn.lock

After fix in f20b6fe8beb839bafb71bbc08c320521db9f68c8 
when start website local dev exist a lot of errors
`ERROR in ../packages/react-router-dom/docs/guides/quick-start.md
Module build failed (from ./webpack/markdown-loader.js):
TypeError: Cannot read property 'basename' of null
at Object.module.exports (/mnt/c/code/react-router/website/webpack/markdown-loader.js:153:28)
@ ./modules/docs/Web.js (./node_modules/babel-loader/lib!./modules/docs/Web.js) 77:11-83
@ ./node_modules/bundle-loader?lazy!./modules/docs/Web.js
@ ./modules/components/Environment.js
@ ./modules/components/App.js
@ ./modules/index.js
`

Fix markdown loader

---

README.md

Right now the link is broken, fixed the URL

[v6] Fix 'getting started' link

---

packages/react-router-dom/examples/QueryParams.js

This PR changes the **QueryParams docs**. Change `useQuery` to memoize the `URLSearchParams` instance, creating a new instance only if **search** changes.
_I suggest this 'cause I was using `useQuery` and my app keeps reloading a lot, I found it interesting to share the solution I found._

Improve QueryParams docs

---

package.json
packages/react-router-config/package.json
packages/react-router-dom/package.json
packages/react-router/package.json
yarn.lock

Refs: https://github.com/babel/babel/pull/12693
As this repo uses loose transforms, Babel < 7.12.13 produces code that hits `__proto__` and doesn't work in hardened environments where it has been disabled.
Updating to ^7.12.13 fixes this issue.
Al alternative solution would be to disable loose mode (but that would generate bigger code).

Update babel to 7.12.13 to fix __proto__

---

packages/react-router/docs/guides/testing.md

"navigates home when you click the logo" fails because of minor issues
* the path to the route with the link was wrong
* the id for the link was wrong
* the text on the target page was wrong
* providing an argument to the anonymous function makes the timeout waiting for completion callback

Fix mistakes that make test fail

---

packages/react-router-dom/docs/api/Link.md

When passing a custom component to Link, you will get a warning if you pass all the props through to the anchor element. The `navigate` prop must be removed before passing through.
https://github.com/ReactTraining/react-router/issues/6962

Update Link example

---

packages/react-router/index.tsx

Split navigator from location context

---

packages/react-router-dom/__tests__/link-href-test.js
packages/react-router/index.tsx

Fixes #7216 
Adds test for correct link behaviour under basename

[v6] Fix Link and navigate for absolute paths with basename

---

packages/react-router/__tests__/path-matching-test.js
packages/react-router/index.tsx

Fix greedy trailing * bug

---

packages/react-router/__tests__/Routes-test.tsx
packages/react-router/__tests__/useRoutes-test.tsx
packages/react-router/index.tsx

After discussing this more with @mjackson, we believe the `location` prop on `Switch` in v5 is still the wrong API. The primary use case as far as we can tell is for Route animations. Michael is going to open a new issue for a deeper discussion about this, and we'll likely introduce some even better solutions in a new beta scheduled for next week.

Remove location prop from `Routes` and `useRoutes`

---

packages/react-router-dom/docs/guides/quick-start.md

The latest version of `create-react-app` uses Yarn as the package manager, not NPM (even though it's invoked with `npx`). Because of this, specifying `npm install` as [step 2 of the quick start](https://reactrouter.com/web/guides/quick-start/installation) will likely cause confusion for new learners.
This changes `npm install` to `yarn add` in the quick start guide. I don't know if there are any other installation guides in the docs; I took a look and didn't see any but it's possible I missed something.

Replace NPM with Yarn in quick start guide

---

package.json
packages/react-router/__tests__/useParams-test.tsx
packages/react-router/index.tsx

If I read this right, I believe this solves the problem captured in #7960!

Make all params available to nested routes + parents

---

packages/react-router-dom/index.tsx

Before the `beta.1` release we removed `propTypes` and `displayName` from the dev build. This PR adds `displayName` back for `forwardRef` components to help with debugging and make some Jest tests a bit more predictable (re: #7958)

Add `displayName` to `forwardRef` components

---

packages/react-router-dom/docs/api/NavLink.md
packages/react-router-dom/modules/NavLink.js
packages/react-router-dom/modules/__tests__/NavLink-test.js

This is an alternative API that will provide a low level solution to the problem described in https://github.com/remix-run/react-router/issues/7194
In RR v6, we plan to drop support for `activeClassName` and `activeStyle` and use the function solution as a singular API for either styled or un-styled links. Consumers can always add these props back by abstracting `NavLink` if they prefer the old API, but this will allow us to simplify the code and API surface level internally while providing a more powerful lower-level solution.

`NavLink`: Add support for `className` and `style` props as functions given the active state

---

docs/advanced-guides/migrating-5-to-6.md
docs/api-reference.md
packages/react-router-dom/__tests__/nav-link-active-test.tsx
packages/react-router-dom/index.tsx

See #7983 for context.
This change will remove the `activeClassName` and `activeStyle` props from `NavLink` and replace them by allowing either `style` or `className` to accept functions with the active state. Updated tests and documentation to support the change!

[v6] `NavLink`: replace `activeClassName` + `activeStyle` props

---

packages/react-router/__tests__/navigate-test.tsx
packages/react-router/index.tsx

In #7880 it looks like `useSearchParams`, when called from a higher level route that renders an outlet, potentially directs to the wrong pathname when `setSearchParams` is called and a user is actually at a nested route.
This is actually a problem with `useNavigate`, I believe. When the resulting `navigate` function is called without an explicit pathname, we should stick with the current pathname returned by `useLocation` instead of the pathname constructed in the `RouteContext`. This ensures that `navigate` always directs users to a location with the same pathname they are currently on while only modifying either the hash or search depending on what is passed to `navigate`. Because `setSearchParams` abstracts `navigate`, this should fix #7880 and make `useNavigate` more stable in …

`useNavigate`: Get `pathname` from `useLocation` instead of `RouteContext`

---

packages/react-router/__tests__/Routes-location-test.tsx
packages/react-router/index.tsx

Added the posibility to override the location in the Routes component, like it was possible in Switch in V5.
Useful for implementing logic like in the example: 
https://reactrouter.com/web/example/modal-gallery
Specific test added

Added location param override to Routes

---

packages/react-router/__tests__/useRoutes-test.tsx
packages/react-router/index.tsx

This tweaks the implementation a bit for a custom `location` prop on `Routes` and adds support for the same location override with `useRoutes`.

`useRoutes`: add support for `location` override

---

docs/api-reference.md
packages/react-router/__tests__/useParams-test.tsx
packages/react-router/index.tsx

The `Params` type and functions that consume it should be generic to allow simpler static typing for query params.
```tsx
// before
let { valid, invalid, literallyAnything } = useParams();
let match = useMatch("profile/:userId");
let userId = match?.params.user; // wrong param, but TS doesn't know that!
// after:
// Property 'invalid' does not exist on type 'Params<"valid" | "key">'
let { valid, invalid } = useParams<"valid" | "key">();
let match = useMatch<"userId">("profile/:userId");
// Property 'user' does not exist on type 'Params<"userId">'
let userId = match?.params.user;
```
Note, the generic type defaults to `string` so this doesn't break anyone's existing code, but it will enhance it for those looking for added type awareness.
Resolves #7978

Make `Params` and related functions generic

---

packages/react-router-dom/jest.config.js
packages/react-router-native/jest.config.js
packages/react-router/jest.config.js
scripts/test.js

closes REM-250
This PR adds the ability for you to not need to rebuild react-router before running the tests
This PR also adds `jest --watchAll` so jest will auto rerun the tests on file changes
https://user-images.githubusercontent.com/11698668/134251774-36c251fe-6349-4b6b-890c-a9e4a0212a4e.mp4

test: rerun tests without rebuilding / add support for --watchAll

---

package.json
packages/react-router-dom/__tests__/link-href-test.tsx
packages/react-router/__tests__/useHref-test.tsx
packages/react-router/__tests__/useResolvedPath-test.tsx
packages/react-router/index.tsx

Fixes relative `<Link to>` values so that `..` traverses up by route instead of by URL segment.
Fixes #8086

Fix relative <Link to>

---

README.md

Looks like the README links weren't changed when the /docs directory was re-arranged. Similar to #8177 merged a few days ago :)

fix: correct README link to migration docs

---

docs/getting-started/concepts.md
docs/getting-started/tutorial.md

Noticed this small [typo](https://en.wiktionary.org/wiki/programatically) while going through the v6 docs. The new website looks great, congrats y’all!

Fix “programmatically” typo in the docs

---

docs/getting-started/overview.md

The prior version seemed to indicate the opposite of the desired behavior will occur.

Fix typo in overview docs

---

docs/getting-started/overview.md

I noticed a minor mismatch in the docs. I think this example is listing an incorrect route for the dynamic `:invoiceId` example. 
Thanks for all of the great work!

Minor doc change: fixing routes for example

---

packages/react-router-dom/package.json
packages/react-router-native/package.json
packages/react-router/package.json

Check;
https://github.com/remix-run/react-router/blob/4ae8f4662592080c089454ab274c230d8e169aaf/packages/react-router-dom/server.tsx#L2
Currently not able to bundle react-rotuer-dom, as there is no dep on `history` in the file tree.
Worth noting seems to be only if pnpm is used, maybe just different linking strategy between it and yarn/npm.

history was missed as a peer dep

---

docs/upgrading/v5.md

The section is about replacing one hook with another, so it makes sense that the title reflects that.

Improve title of `useNavigate` section in v5 -> v6 migration docs

---

website/modules/base.css

Fixes #8208 
Updated the paragraph width inside markdown for Desktop view of screen width more than 1270px
So the alignment of code snippets in right half of the page in now fixed.
Now the documentation layout is correct for all the resolutions.

Fixed layout of documentation for desktop view

---

packages/react-router/__tests__/Routes-test.tsx
packages/react-router/index.tsx

Warn Against Non-<Route> children of <Routes>

---

docs/getting-started/tutorial.md

Just some typos I noticed while I read through the tutorial.
Thanks for your hard work on RR6! Looks great 👍🏽

fix typos in tutorial.md

---

docs/getting-started/concepts.md

Found a typo while reading the docs.

style: fix typo in docs (layotus -> layouts)

---

packages/react-router-dom/index.tsx
packages/react-router-native/index.tsx

Minor spelling fix from `compoments` -> `components`

Fix spelling for components

---

docs/upgrading/v5.md

Our v5 migration docs do not mention that we replaced `useRouteMatch` with `useMatch` (thanks to @eps1lon for pointing that out in [#7133](https://github.com/remix-run/react-router/issues/7133#issuecomment-963017207)).
This change begins to address it, though we should probably add a few code examples to make refactoring much simpler. I'm actually not 100% sure how to capture the nuance in a few situations, but I think this is better than nothing for now. Will circle back to that later after discussing with the team.

Docs: Add `useMatch` section in upgrade docs

---

docs/index.md

There's a broken docs link on https://reactrouter.com/docs/en/v6 for FAQ. This should fix unless FAQ should be under getting started.

Fix docs link

---

docs/getting-started/installation.md

History is now a direct dependency and should not be manually installed. See https://github.com/remix-run/react-router/blob/bcd5511c4df1413776d22556066602a53f961a28/docs/upgrading/v5.md?plain=1#L150

Remove `history@5` from installation examples

---

FAQ.md
contributors.yml
docs/faq.md

This fixes two minor typos:
```
docs/faq.md:215: accont ==> account
./FAQ.md:115: acccess ==> access
```

fix: typos in FAQ files

---

contributors.yml
docs/api.md

I ran into an issue (documented in https://github.com/remix-run/react-router/issues/8360) with the `<Link>` component and I think this would help future travellers. Love the project! Thanks.

Add link to props reference for TouchableHighlight

---

contributors.yml
docs/api.md

Interface `NavigateOptions` in `/packages/react-router/index.tsx` 
```ts
export interface NavigateOptions {
replace?: boolean;
state?: any;
}
```
Changed NavigateFunction in `docs/api.md`
`options?: { replace?: boolean; state?: State }` to `options?: { replace?: boolean; state?: any }`

Fix type of NavigateFunction in api.md

---

contributors.yml
docs/upgrading/v5.md

Guess that this PR is self-explainable. While upgrading I think people would benefit on this note, cause it's easy to miss, especially for folks that are not using TS
[v5 logic](https://github.com/remix-run/react-router/blob/78249eb6ce9a28df4691cc61caa0467fed8b7ac0/packages/react-router/modules/Redirect.js#L21)
[v6 logic](https://github.com/remix-run/react-router/blob/6cbb99db85767d752ec8eb3b34ef8f88f067aeb3/packages/react-router/index.tsx#L502)

docs: emphasize v5 and v6 navigation difference

---

contributors.yml
docs/upgrading/v5.md

Many code bases use the `<Prompt>` component from v5 but don't find out that support is currently missing from v6 until after attempting to upgrade.  This adds this information to the upgrade guide so that is more likely that I would be discovered before lots of effort is invested. 
Fixes #8330

Note that `<Prompt>` support is missing from v6

---

packages/react-router/index.tsx
yarn.lock

Improve the type of useParams
According  https://github.com/remix-run/react-router/issues/8200#issuecomment-972680683 comment
The main purpose is to support the declaration of the type of parameter value as a union string

Improve the type of useParams

---

.github/workflows/release.yml
.github/workflows/test.yml
contributors.yml

Other changes:
- Remove matrix as only a single Node version is ever used
- Always check for latest version of Node in version range (14.x)
- Cache Yarn dependencies between runs

Update actions/setup-node to version 2

---

contributors.yml
docs/api.md
docs/contributing.md
docs/faq.md
docs/getting-started/concepts.md
docs/getting-started/installation.md
docs/getting-started/overview.md
docs/getting-started/tutorial.md
docs/upgrading/reach.md
docs/upgrading/v5.md

~Minor: Possessive "its" rather than contracted "it is"~
This grew from the original fix to me doing a sweep of the docs as a whole. I've left some more "stylistic" grammar points as they are, and tried only to fix the ones that are more black and white. Hope they're helpful but feel free to remove any specific changes if they're unhelpful. Thanks!

Fix grammar in docs

---

contributors.yml
docs/api.md
packages/react-router-dom/index.tsx
packages/react-router-native/index.tsx
packages/react-router/__tests__/useOutlet-test.tsx
packages/react-router/index.tsx

accidentally originally opened it against [remix](https://github.com/remix-run/remix/pull/939)

feat: add "context" prop to Outlet

---

contributors.yml
docs/getting-started/concepts.md

Found a couple missing words while reading the ["Definitions" section of the Getting Started docs](https://reactrouter.com/docs/en/v6/getting-started/concepts#definitions). Added them to improve readability.
I didn't see any further guidelines for PR format in the Contributing guide, but please let me know if I need to do something different. Thanks gang! 🤙

fix(docs only): verbiage fixes in Getting Started docs

---

packages/react-router/__tests__/descendant-routes-warning-test.tsx
packages/react-router/index.tsx

This slightly modifies the error message for silly people like me that might see this, which would also be an error:
This would show if you were in the middle of a v5->6 migration and had this:
```jsx
<Routes>
<Route to="/" element={<SomeSectionWithLotsOfNestedRoutes />} />
</Routes>
```
As an aside, it might make sense to do `toMatchInlineSnapshot` checks of the `consoleWarn` in the test to cover both of these cases.

Update descendant routes warning message

---

packages/react-router/__tests__/matchRoutes-test.tsx
packages/react-router/index.tsx

Resolves #8288 
This PR modifies `compilePath`'s non-capturing group to match up to the proceeding `/` so that paths with base64 encoded ids  (e.x.`users/RGFzaGJvYXJkOjE1Nzk=/edit` when using `graphql-relay` globalIds) properly match up to the `/` and not at the word break before the `=` character.

Support base64 encoded ids on nested routes

---

packages/react-router/__tests__/useOutlet-test.tsx
packages/react-router/index.tsx

fix(useOutlet): don't wrap in ContextProvider if no child route

---

contributors.yml
docs/getting-started/tutorial.md

Updated "pathame" to "pathname" type in tutorial docs.

docs: Fixed pathname typo

---

contributors.yml
docs/upgrading/reach.md

Upon going through the source code, I found only `Route` components are allowed inside `Routes`, Hence updated the doc examples as such

doc: updated reach migration guide for Route Components

---

contributors.yml
examples/auth/src/App.tsx

Add `replace={true}` to avoid creating a new entry in the history. Thus, when they click back on the login page, they won't end up on the login page again, but rather on the page they were before trying to access the protected page.

Avoid visiting login page again on back button click

---

docs/getting-started/tutorial.md

Fixing a small typo in the getting started tutorial.

Change extension of 'src/routes/invoice.js' to 'jsx'

---

contributors.yml
docs/faq.md

This fixes the example by using `<Lang lang="…"/>`  instead of `<Lang code="…"/>` (to respect Lang's signature) and by setting the language codes to correspond with the paths.

Fix minor typos in the "Matching generally static values" FAQ example

---

contributors.yml
docs/api.md
packages/react-router-dom/__tests__/nav-link-active-test.tsx
packages/react-router-dom/index.tsx

It seems that there's a type collision between current NavLink interface and NavLink [example](https://reactrouter.com/docs/en/v6/api#navlink) demonstrated on docs.
```
<NavLink
to="tasks"
className={({ isActive }) =>
isActive ? activeClassName : undefined
}
>
Tasks
</NavLink>
// Type 'string | undefined' is not assignable to type 'string'.
```
IMO it looks good to add undefined return type for the classname of NavLink prop instead of modifying an example.
(Existing tests passed, should any further test be required?)

fix: Modify return type of className of NavLinkProps interface

---

.github/workflows/format.yml

this PR enables the format workflow on the `dev` branch allows us to push to the protected branches. I've also updated the email address for "Remix Run Bot" so that commits are properly assigned to it and allows this whole thing to work.
x-ref: https://github.com/remix-run/remix/pull/1455

ci: format dev branch and checkout repo using custom token

---

contributors.yml
docs/api.md

Changes RouteProps.element type in API docs from `React.ReactElement | null` to `React.ReactNode | null`.
The code change being documented was done in #8473

Updates type declaration for RouteProps in API docs

---

contributors.yml
tutorial/index.html
tutorial/src/main.jsx

Fixes #8581 
The documentation in /docs/getting-started uses "root" as the root element id, including in code snippets. So if a learner is following the tutorial documentation, they'll break their app when they copy-paste the tutorial snippets (which use "root") into the template (which was using "app", prior to this PR).
Now the docs and the template both use "root".

fix(tutorial): use "root" as root div id

---

contributors.yml
docs/api.md

Fixed types related to remix-run/history `State` in the docs.
`State` is now unused in the latest code.
Thank you for the nice library!

docs: Fix types related to history State

---

contributors.yml
examples/custom-query-parsing/src/App.tsx

there is an error in example  `custom-query-parsing`
```js
pizza.crust === "deep-dish"
//  not  pizza.crust === "dish-dish"
```

fix(examples): there is an error in example

---

.github/workflows/test.yml
contributors.yml
docs/api.md

docs：Add unstable_HistoryRouter to the api.md document

---

contributors.yml
docs/getting-started/tutorial.md

The due date for the invoice number 1998 (named, "Wide Open Spaces") was "01/27/2998". It should probably have been "01/27/1998" as for all other invoices, invoice number is equal to the year of the due date.

Correct a due date in `src/data.js`

---

contributors.yml
docs/api.md

Making the typescript example consistent with the associated `ContextType`:
`type ContextType = { user: User | null };`

docs: Fix useOutletContext typescript example

---

contributors.yml
packages/react-router/README.md

when click "react-router" of `react-router/packages/react-router/README.md` file it comes 404 error !
>`packages/react-router-dom` and `packages/react-router-native` doesn't come error
I updateed it like other packages README.md

docs: Fix react-router/README.md's link

---

contributors.yml
docs/api.md

I added an import for the `useOutletContext` hook API documentation example to be consistent with other examples. Also based on [this SO question](https://stackoverflow.com/questions/71165826/failing-to-access-outlet-context-in-react) the absence of the import has caused some confusion.

Add import statement to useOutletContext example

---

contributors.yml
docs/getting-started/tutorial.md

It would make the UI more consistent if we pass the query string to navigation function route after deleting and item.

Persist query string when navigating

---

contributors.yml
packages/react-router-dom/index.tsx
packages/react-router-native/index.tsx
packages/react-router/index.tsx

feat: export NavigationType enum as value.

---

contributors.yml
packages/react-router/__tests__/path-matching-test.tsx
packages/react-router/index.tsx

As no member confirm or refuse my issue #8458.
Here a PR that fix the bug for me.
Not sure if this is the best place to call normalizePathname, though.
Do not hesitate to comment, I will gladly change my PR.
----- Commit message -----
Motivation:
When matching with "*", the `pathnameBase` had a trailing slash `/`.
Modifications:
* Call normalizePathname for pathnameBase
Result:
We can use an element that call useRoutes to define another alternative router for matching with "*".
Closes: #8458

fix: Normalize pathnameBase when matching

---

contributors.yml
packages/react-router/__tests__/descendant-routes-splat-matching-test.tsx
packages/react-router/__tests__/layout-routes-test.tsx
packages/react-router/index.tsx

closes #8525 and #8561
Fixes route matching to allow valid, but non-word-boundary characters(`.`, `-`, `~`) and url-encoded entities to appear at the beginning of a nested `*` route.
I pulled this character set from [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt), section 2.3 Unreserved Characters:
> 2.3.  Unreserved Characters
> 
>    Characters that are allowed in a URI but do not have a reserved
>    purpose are called unreserved.  These include uppercase and lowercase
>    letters, decimal digits, hyphen, period, underscore, and tilde.
> 
>       unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
I extended this to include url-encoded entities (ie `%20`), but I am not 100% confident I made the character range wide enough. ([0-7][0-9A-F]). It is probably safe to expand this to any …

Fix: allow nested splat routes to begin with "special" url-safe characters

---

package.json
packages/history/.eslintrc
packages/history/README.md
packages/history/__tests__/.eslintrc
packages/history/__tests__/TestSequences/EncodedReservedCharacters.ts
packages/history/__tests__/TestSequences/GoBack.ts
packages/history/__tests__/TestSequences/GoForward.ts
packages/history/__tests__/TestSequences/InitialLocationDefaultKey.ts
packages/history/__tests__/TestSequences/InitialLocationHasKey.ts
packages/history/__tests__/TestSequences/Listen.ts
packages/history/__tests__/TestSequences/ListenPopOnly.ts
packages/history/__tests__/TestSequences/PushMissingPathname.ts
packages/history/__tests__/TestSequences/PushNewLocation.ts
packages/history/__tests__/TestSequences/PushRelativePathname.ts
packages/history/__tests__/TestSequences/PushRelativePathnameWarning.ts
packages/history/__tests__/TestSequences/PushSamePath.ts
packages/history/__tests__/TestSequences/PushState.ts
packages/history/__tests__/TestSequences/ReplaceNewLocation.ts
packages/history/__tests__/TestSequences/ReplaceSamePath.ts
packages/history/__tests__/TestSequences/ReplaceState.ts
packages/history/__tests__/memory-test.ts
packages/history/index.ts
packages/history/jest.config.js
packages/history/node-main.js
packages/history/package.json
packages/history/tsconfig.json
rollup.config.js
tsconfig.json

* Adds `packages/history`
* Implements `createMemoryHistory`
* Leverages the same test suite + sequences from https://github.com/remix-run/history, simplified down based on the new API

feat: add history package and createMemoryHistory implementation

---

contributors.yml
docs/getting-started/concepts.md

`history.listen` accepts two parameters in the preceding document: `location` and `action`. 
However, I discovered the type declaration below while reading the [docs of `history`](https://github.com/remix-run/history/blob/dev/docs/api-reference.md#historylistenlistener-listener). Instead of two parameters, `history.listen` allows one parameter with two properties.
```
interface Listener {
(update: Update): void;
}
interface Update {
action: Action;
location: Location;
}
```

docs: fix the usage of history.listen

---

contributors.yml
docs/getting-started/concepts.md

The opening tag in the anti-example for layout routes should be `Route` instead of `Routes`
The closing tag is correct.

fixed small typo

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
contributors.yml
docs/getting-started/concepts.md
docs/getting-started/tutorial.md
packages/react-router-dom/index.tsx

#8719
This is a simple PR to allow children on navlink to be optional so a NavLink can be used in type script projects without requiring the children attribute to be set on the NavLink.  Currently it's impossible to use a NavLink in typescript projects on version 6.2 as you can't set jsx children as an attribute, and you can't use NavLink without doing so...

Fix: change children prop on navlink props to be optional

---

contributors.yml
docs/getting-started/tutorial.md

Simple typo, missing `s` on `it render`. Should say `it renders ....`.

Docs: Typo in tutorial.md

---

contributors.yml
docs/api.md

There is an unwanted ")" in Navlink sample code which throws syntax error

Removing unwanted ")" from Navlink sample code

---

contributors.yml
docs/upgrading/reach.md

I think this line was originally meant to be in the "Install React Router v6" section, but there's already an `npm install` command shown there.

docs: Remove misplaced `npm install`

---

contributors.yml
docs/getting-started/concepts.md
docs/getting-started/installation.md
docs/getting-started/overview.md
docs/getting-started/tutorial.md

to avoid user copy and get the warning from react 18.
>**Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot.**

update documentation to match react 18

---

docs/getting-started/installation.md
docs/getting-started/tutorial.md

After changing the format of the doc. The code line highlight is messed up.

fix: documentation code lines highlight

---

contributors.yml
docs/api.md
docs/getting-started/concepts.md
docs/upgrading/v5.md

• `it's` -> `its`
• `behaviour` -> `behavior` (to be in line with the rest of its uses in the docs)

Fix some typos in docs

---

packages/react-router/modules/Router.js
packages/react-router/modules/__tests__/Router-test.js

Fixes #7870.
In React 18, Strict Mode [attempts to detect unexpected side effects](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects) that might happen when rendering in concurrent mode. For class components, it intentionally double-invokes the constructor, `render()`, and `shouldComponentUpdate()`. It also double-invokes both layout and passive effects by mounting, unmounting, and then remounting.
Router in v5 was not compatible with this primarily because the main history subscription was created in the component constructor. Here is a simplified outline of the component lifecycle in StrictMode in v5.3.1:
- constructor &mdash; listen (this instance is not used)
- constructor &mdash; listen
- render
- render
- componentDidMount
- componentWillUnmount &mdash; …

Fix: make v5 Router compatible with v18 StrictMode

---

contributors.yml
docs/getting-started/tutorial.md

The very last example in the tutorial is highlighting the wrong lines of code.
The last time this file was touched in the tutorial, it looked like this:
Then, when you get to the next place `invoices.jsx` is edited, the diff highlights are incorrect. Note:
- 👍 The import diffs is right
- 👎 Lines 9 and 10 (`useNavigate()` and `useLocation()`) were added but not highlighted as additions
- 👎 Lines 20-29 are highlighted, but line 20 was already there and line 30 was added (but not highlighted).
So this request makes it so the actual code differences are highlighted correctly. Current vs. proposed:

fix: highlight code diff for invoice.jsx

---

packages/react-router/lib/router.ts

It's awesome, that `generatePath` can help you to know what params you need to supply for interpolation.
However it currently breaks, if the param isn't immediately following the slash, i.e. `path/item-:param`, although this is technically valid in react router (and with good use cases).
This PR fixes this.
Before:
After:

Fix: prefixed params

---

examples/custom-link/src/App.tsx
packages/react-router-dom/__tests__/nav-link-active-test.tsx
packages/react-router-dom/index.tsx

Adds `isPending` logic to `NavLink` for styling links during navigations.  This also adds the internal refactor for `isActive` discussed in https://github.com/remix-run/react-router/pull/8567#issuecomment-1054471899

feat: add pending logic to NavLink

---

contributors.yml
packages/react-router/__tests__/descendant-routes-splat-matching-test.tsx
packages/react-router/__tests__/layout-routes-test.tsx
packages/react-router/lib/router.ts

Fixes bug #8699 
When a route is nested within a layout route, it wont render routes starting with an '@' symbol:
```
<Routes>
<Route element={<Layout />}>
<Route path=":id" element={<Chat />} />
</Route>
</Routes>
```
Note that the router works correctly when the parent is NOT a layout route (i.e. has a path defined), or is at the root level:
```
<Router>
<Routes>
<Route path=":id" element={'works with /@tom'}/>
<Route path="nested">
<Route path=":id" element={'works with /nested/@tom'}/>
</Route>
</Routes>
</Router>
```

Allow routes starting with @ in layout routes

---

contributors.yml
docs/upgrading/v5.md

Added to migration guide v5 -> v6:
- information about changes to `matchPath` function

docs: Add info about changes in matchPath() to upgrading/v5 guide

---

contributors.yml
docs/upgrading/reach.md
docs/upgrading/v5.md
packages/react-router/__tests__/resolveTo-test.tsx
packages/react-router/lib/router.ts

fix #8175
The following assignment
https://github.com/remix-run/react-router/blob/0f9435a8134b2b5dddfd716a18d17aefe4461fe1/packages/react-router/lib/router.ts#L575
leads to the mutation of the provided `toArg` and the original `pathname` is _accidentally_ replaced: `../../../myPath` will always be `myPath`.

fix: resolveTo should not mutate the provided pathname

---

docs/routers/data-browser-router.md
docs/routers/data-hash-router.md
docs/routers/data-memory-router.md
package.json
packages/react-router-dom/__tests__/nav-link-active-test.tsx
packages/react-router-dom/index.tsx
packages/react-router/__tests__/DataMemoryRouter-test.tsx
packages/react-router/lib/components.tsx
packages/react-router/package.json
packages/router/README.md
packages/router/__tests__/router-test.ts
packages/router/router.ts
yarn.lock

Minor updates + cleanup in preparation for `6.4.0-pre.3`
* Removes stale/unused `use-sync-external-store` dependency in `package.json`
* Change `fallbackElement` type to `ReactNode` for more flexible typing (REM-1146)
* Make `fallbackElement` optional for SSR use-case and to match what the docs currently show (#8896)
* Pass fetcher `actionResult` through to shouldRevalidate on fetcher submissions (REM-1159)
* Brings `packages/router/README.md` up to date
Closes: #8896

fix: Minor updates for 6.4.0-pre.2 reports

---

contributors.yml
packages/react-router-dom/index.tsx

`style` can be `React.CSSProperties` or `undefined`, so I think it should be able to return these values when using a function as well.

fix(react-router-dom): allow returning `undefined` in `NavLink`'s `style` prop

---

packages/react-router-dom/__tests__/DataBrowserRouter-test.tsx
packages/react-router-dom/index.tsx
packages/router/__tests__/router-test.ts
packages/router/router.ts

Errors from `useFetcher()` should propagate upwards from the Route in which they were used and use the closest error boundary

fix: Capture fetcher errors at contextual route error boundaries

---

packages/router/index.ts
packages/router/utils.ts

chore: export ActionFunctionArgs/LoaderFunctionArgs types

---

packages/react-router/__tests__/navigate-test.tsx
packages/react-router/lib/hooks.tsx

fix: Fix navigate bug from nested index routes

---

packages/react-router/__tests__/DataMemoryRouter-test.tsx
packages/react-router/lib/hooks.tsx

No code changes, just reworked some tests to ensure the return value of `undefined` for `useRouteLoaderData('not-found-route-id')`

ci: add tests for useRouteLoaderData with a missing routeId

---

.eslintignore
packages/react-router-dom/index.tsx
packages/react-router-native/index.tsx
packages/react-router/index.ts

* Forgot to export `ActionFunctionArgs`/`LoaderFunctionArgs` up through `react-router*` packages in https://github.com/remix-run/react-router/pull/8947.  
* Also noticed that the new `dist/` directories weren't added to `.eslintignore`
Closes #8942

ci: Update exports and fix linting

---

contributors.yml
docs/hooks/use-navigate.md

When reading the v6 doc I noticed there were no mention of what "replace" is used for on the "useNavigate" page. This PR fixes this issue.

Add hint about "replace" in "useNavigate" documentation

---

.changeset/brave-shirts-sneeze.md
packages/router/__tests__/router-test.ts
packages/router/router.ts
packages/router/utils.ts

Do not manually specify the `Content-Type` in our `Request` creation, the browser will do that automatically based on the `FormData` contents.
Closes #8982

fix: handle multipart/form-data submissions

---

packages/router/__tests__/router-test.ts

No functionality changes, adds unit tests for the scenario fixed in Remix via https://github.com/remix-run/remix/pull/3460 (Bug https://github.com/remix-run/remix/issues/3302)

ci: Add tests for chained redirect cases

---

packages/react-router-dom/__tests__/trailing-slashes-test.tsx

We had parallel PRs for relative navigation (#8985) and trailing slashes (#8861), and these trailing slash tests relied on the previously broken relative nav behavior.  This fixes them.

Fix broken tests from conflicting PRs

---

.changeset/odd-yaks-kneel.md
packages/react-router-dom/__tests__/DataBrowserRouter-test.tsx
packages/react-router-dom/index.tsx
packages/router/__tests__/router-test.ts
packages/router/router.ts

We are currently defaulting `<Form method="post">` to be a `REPLACE` navigation by default, but this is a bit aggressive because if the action redirects, then we lose the starting location. 
For example, without a redirect, the following is correct:
* User is on `/`
* Navigates to `/form`
* Submits to `/form` _and does not redirect_
* The submission should REPLACE so that POP does not re-play the post and goes back to `/`
However, if the action is redirecting, they're already handling the `REPLACE` and we should stay with `PUSH` so the user can back-navigate to the form:
* User is on `/`
* Navigates to `/form`
* Submits to `/form` _and redirects to `/results`_
* The submission should PUSH so that POP goes back to `/form`
This PR removes the push/replace logic from `useSubmitImpl` and lets …

fix: do not REPLACE if action redirected

---

contributors.yml
docs/utils/generate-path.md

as explained in this issue: https://github.com/remix-run/react-router/issues/9007 generatePath expects strings for params but are ints in the docs

chore: updated param of generate-path so its a string instead of int

---

contributors.yml
docs/hooks/use-revalidator.md

fix docs typo which uses `revalidate` instead of `revalidator`

fix docs typo

---

.changeset/strong-bees-pay.md
package.json
packages/router/.eslintrc
packages/router/history.ts
packages/router/jest.config.js
packages/router/node-main.js
packages/router/package.json
packages/router/rollup.config.js
packages/router/router.ts

Simplify the `@remix-run/router` build down to remove all the various builds and just ship source code + ESM/CJS/d.ts files
```
package.json
index.ts         # TS source code for deno
dist/
index.d.ts     ## Types for IDEs
router.js      ## ESM build
router.cjs.js  ## CJS build
```
To test, you can do the following:
```bash
cd packages/router
rm -rf dist
npx rollup -c
npm pack
tar -xzf remix-run-router-0.2.0-pre.3.tgz
ls package/
rm -rf package/
rm remix-run-router-0.2.0-pre.3.tgz
```

ci: Simplify router rollup build and dist directory

---

contributors.yml
docs/components/link-native.md

<Link> Tag needs <Text> in React Native for usage, otherwise throws Errors

 Need <Text> Tag in <Link> for React Native

---

.changeset/four-lobsters-crash.md
.github/workflows/test.yml

prevent duplicate runs for Pull Requests
the real fix here was specifying which branches should trigger the "push" event, but also normalizing the action between react-router and remix

ci: prevent duplicate runs for Pull Requests

---

.eslintrc
package.json
packages/react-router-dom/__tests__/DataBrowserRouter-test.tsx
packages/react-router-dom/__tests__/trailing-slashes-test.tsx
packages/router/__tests__/browser-test.ts
packages/router/__tests__/hash-test.ts
packages/router/__tests__/memory-test.ts
packages/router/__tests__/router-test.ts
yarn.lock

Adds [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest) to the codebase, primarily to error on focused tests.  But the recommended set of rules exposed a few other things we can cleanup

ci: add eslint-plugin-jest

---

contributors.yml
docs/getting-started/concepts.md

When I click `History Object` in the nav bar, the scroll position is as the screenshot above.
When I click `History Object` in the nav bar, the scroll position is on the title of History Object.
I change the `id` of `History` in Chapter Definitions to `history`, which ensures that there is just one `#history` and one `#history-object` on the current page.

docs: fix scroll position of History Object

---

contributors.yml
docs/getting-started/overview.md

Outlet and Route docs moved to the components subdirectory.

docs(getting-started): fix component links

---

.changeset/ninety-spoons-suffer.md
docs/hooks/use-route-loader-data.md
docs/routers/data-static-router.md
examples/scroll-restoration/src/App.tsx
examples/ssr-data-router/README.md
examples/ssr-data-router/index.html
examples/ssr-data-router/server.js
examples/ssr-data-router/src/entry.client.tsx
examples/ssr-data-router/src/entry.server.tsx
package.json
packages/react-router-dom/__tests__/data-browser-router-test.tsx
packages/react-router-dom/__tests__/data-static-router-test.tsx
packages/react-router-dom/__tests__/nav-link-active-test.tsx
packages/react-router-dom/index.tsx
packages/react-router-dom/server.tsx
packages/react-router-native/index.tsx
packages/react-router/__tests__/data-memory-router-test.tsx
packages/react-router/index.ts
packages/react-router/lib/components.tsx
packages/react-router/lib/context.ts
packages/react-router/lib/hooks.tsx
packages/router/__tests__/router-test.ts
packages/router/index.ts
packages/router/router.ts
packages/router/utils.ts

Follow up changes to #9013 based on issues encountered while integrating this into Remix as well as API reviews

SSR API Updates
