contributors.yml, docs/hooks/use-match.md, docs/utils/generate-path.md, packages/router/utils.ts
This PR improves the `params` type of `generatePath`'s argument.
```ts
type Star = "*"
type PathParam<
Path extends string
> = Path extends `:${infer Param}/${infer Rest}`
? Param | PathParam<Rest>
: Path extends `:${infer Param}`
? Param
: Path extends `${any}/:${infer Param}`
? PathParam<`:${Param}`>
: Path extends `${any}/${Star}`
? Star
: Path extends Star
? Star 
: never
export function generatePath<Path extends string>(path: Path, params: {
[key in PathParam<Path>]: string
} = {} as any): string {
return ""
}
generatePath("a", {}) // {}
//^?
generatePath(":a", {})// {"a": string;}
//^?
generatePath("/:a", {})// {"a": string;}
//^?
generatePath("/:a/b", {})// {"a": string;}
//^?
generatePath("/:a/:b", {})// {"a": string; "b": string;}
//^?
generatePath("/a/:b", {})// {"b": string;} …
```
=> feat: improve generatePath arg type

.changeset/eighty-horses-leave.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/dom.ts
Do not overwrite input values if a submitting button has the same name (same fix from https://github.com/remix-run/remix/pull/3611)
=> fix: do not overwrite input value from button with same name

.changeset/cuddly-dingos-tickle.md, packages/react-router/__tests__/navigate-test.tsx, packages/react-router/lib/components.tsx
Prevent `<Navigate>` from kicking off duplicate `navigate()` calls when inside inside a data router.
Closes #9122
=> fix: avoid navigation loops in <Navigate> re-renders

.changeset/lucky-olives-wonder.md, package.json, packages/react-router-dom/index.tsx, packages/router/__tests__/router-test.ts, packages/router/router.ts
Fixes some bugs with redirect history management and aligns on the navigation semantics of "replace is determined by the origin".  See https://github.com/remix-run/react-router/pull/9117#issuecomment-1209674666 and https://github.com/remix-run/react-router/pull/9117#issuecomment-1209688276 for rationale.
=> fix: fix up default history push behavior on redirects

packages/react-router-dom/__tests__/link-href-test.tsx
Follow up to the discussion in https://github.com/remix-run/react-router/pull/8985#discussion_r898024544 to strengthen the existing `..` navigation tests
=> ci: strengthen relative navigation via .. tests

.changeset/yellow-cherries-tell.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/index.tsx
Follow up to correct a small misunderstanding on https://github.com/remix-run/react-router/pull/9060 after chatting through with Chance and Ryan a bit more.
=> fix: useFormAction should not include pathless splat portion

contributors.yml, docs/components/link-native.md
I've found this typo while reading the docs.
=> fixed react-native link typo

.changeset/afraid-games-laugh.md, packages/react-router/__tests__/data-memory-router-test.tsx, packages/router/router.ts
Now that `loaderData` is stable across `defer` resolutions we don't need to `updateState` and can jut let the re-render happen at the Suspense boundary
=> fix: avoid uneccesary re-renders on defer resolution

.changeset/wise-scissors-hug.md, docs/components/form.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
This default behavior allows users to back-button from the error page back to the form
=> fix: use a push navigation on submission errors

.changeset/sweet-eggs-hug.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Fixes a bug where revalidating fetchers triggered by a separate submitting fetcher would temporarily have their `data` messed up, and due to the wrong key usage it would reflect the submitting fetcher action data.
=> fix: fetcher submission revalidating fetchers using wrong key

.changeset/beige-buckets-lick.md, examples/scroll-restoration/src/routes.tsx, packages/react-router-dom/index.tsx, packages/react-router/lib/context.ts, packages/react-router/lib/hooks.tsx, packages/router/router.ts
`<ScrollRestoration getKey>` should get the "public" matches from `useMatches` instead of the internal router matches objects
=> fix: pass useMatches objects to ScrollRestoration getKey

packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/index.tsx, packages/react-router/__tests__/data-memory-router-test.tsx, packages/react-router/lib/components.tsx
Move the `fallbackElement` down into the contexts so users can leverage hooks/components inside the fallback
=> fix: move fallbackElement into router context

.changeset/big-bags-report.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/__tests__/link-href-test.tsx, packages/react-router-dom/dom.ts, packages/react-router-dom/index.tsx, packages/react-router-native/index.tsx, packages/react-router/__tests__/navigate-test.tsx, packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/context.ts, packages/react-router/lib/hooks.tsx, packages/router/utils.ts
Adds a `relative=path` option to navigation aspects to allow users to opt-into paths behaving relative to the _current URL_ instead of the _current route hierarchy_.  This is useful if you're sharing route patterns in a non-nested for UI reasons:
```jsx
// Contact and EditContact do not share additional UI layout
<Route path="/" element={<Layout />}>
<Route path="contacts/:id" element={<Contact />} />
<Route path="contacts:id/edit" element={<EditContact />} />
</Route>
function EditContact() {
// ...
return <Link to=".." relative="path">Cancel</Link>
}
```
Without this, a `..` link would navigate up to `Layout` so the user would need to reconstruct the `contacts/:id` url using `useParams` and either hardcoding the `/contacts` prefix or parsing it from `useLocation` 😕 
This applies to all …
=> feat: add relative=path option for url-relative routing

contributors.yml, docs/getting-started/tutorial.md
The stylesheet references the id as `zero-state`, but the code gave the id `index`
=> docs(tutorial): fix styles for Index route

.changeset/wet-readers-mate.md, docs/guides/deferred.md, package.json, packages/router/__tests__/router-test.ts, packages/router/router.ts
I was a bit naive in the "is revalidating" check to determine when to `await` all deferred values.  We need to distinguish current `loaderData` for the same route _and the same params_ versus same route but _different_ params since we do want to fallback by default in the latter case (i.e., navigating /invoices/1 -> /invoices/2`).
Closes #8914
=> fix: Await should fallback on route params navigations

.changeset/young-pumas-destroy.md, package.json, packages/router/__tests__/router-test.ts, packages/router/index.ts, packages/router/router.ts, packages/router/utils.ts
fix: tracked promises should resolve/reject with the value instead of swallowing it
=> fix: proxy defer resolve/reject values through tracked promises

docs/getting-started/tutorial.md
The useEffect from the previous step isn't reflected, which is confusing.
=> Add missing code to tutorial

docs/route/action.md
This page is about `action`, so the explanation of `params` should specify `action`.
=> fix: params explanation should say action

.changeset/shy-guests-tickle.md, package.json, packages/react-router/__tests__/data-memory-router-test.tsx, packages/react-router/lib/components.tsx, packages/router/__tests__/router-test.ts, packages/router/utils.ts
We need to send the `AbortedDeferredError` through the `TrackedPromise` in `_error` so `Await` can throw a never-resolving promise to `Suspense` to freeze the UI.  Otherwise, we end up throwing an already-rejected promise to `Suspense`, which sends it right back down to `Await`.  React does break out of this loop as soon as the next load or navigation finishes, but it's busted _during_ the transition
=> fix: prevent aborted defer values from starting a suspense render loop

packages/router/__tests__/router-test.ts, packages/router/router.ts, packages/router/utils.ts
For static handler `query()` calls, we propagate out the `headers` from any returned `Response` instances for eventual use in the SSR response (`getDocumentHeaders` in Remix).  This PR ensures we also capture those on error flows (i.e., `throw new Response`)
=> fix: expose loader/action headers on error responses in static handler

packages/router/router.ts
Now that the `router` singleton is managed in user land, user's technically have access to these APIs - but they should not be using them directly and should always be using the react-router abstractions
=> chore: mark router APIs as @internal

contributors.yml, package.json, packages/react-router/__tests__/generatePath-test.tsx, packages/router/utils.ts
Fix for #8883, a bit changed the logic of `generatePath` function, added handling of this particular edge case.
=> fix: generating path when passed only slash and star

docs/elements.md, docs/hooks/use-matches.md, docs/route/action.md, docs/route/error-element.md, docs/route/route.md
Provide links to `createBrowserRouter` to help clarify what a "data router" is
=> docs: update references to data router for clarity

contributors.yml, packages/react-router-dom/README.md, packages/react-router-native/README.md
👋 At the moment, the getting started tutorial links on the package `README.md` are pointing to a `docs/getting-started/` directory that no longer exists. As a result, users viewing the package on NPM will be pointed to a broken getting started link. 
I have changed it to point to `docs/start/`. 
Question, previously the `react-router-dom` and `react-router-native` pointed to the same tutorial, should this still be the case?
=> Fixed broken getting started links on README

contributors.yml, docs/start/overview.md
Fixed a code example for the Route loader on the Feature Overview page.
closes #9244
=> fix: route loader code example in docs

contributors.yml, docs/elements.md, docs/hooks/use-matches.md, docs/route/action.md, docs/route/error-element.md, docs/route/route.md
Hi, you have some dead links in your documentation. Links pointing to `createbrowserrouter` point to 'https://reactrouter.com/en/main/routers/create-browser-router.md' which returns a 404.
Pages with broken links: (search for "createbrowserrouter")
* https://reactrouter.com/en/main/route/error-element
* https://reactrouter.com/en/main/hooks/use-matches
* https://reactrouter.com/en/main/route/action
* https://reactrouter.com/en/main/route/error-element
* https://reactrouter.com/en/main/route/route
// related 44736e9ae5fcab17e37b7c551499ac19a1a692c5
=> docs: fix broken link

contributors.yml, docs/start/overview.md
The Suspense with deferred data code example reuses the `history` variable.
This tiny PR renames the one from the render prop to better highlight the fact that the outer one is in fact a promise, while the inner one is a resolved data.
closes #9245
=> feat: improved suspense code example in docs

README.md, contributors.yml
[The getting started guide](https://github.com/remix-run/react-router/blob/main/docs/getting-started/installation.md) is no longer available, I changed the link to direct users to the tutorial instead.
=> docs: fix deadlink in readme

contributors.yml, docs/components/scroll-restoration.md
Removed unnecessary argument destructuring on `getKey` callback.
https://github.com/remix-run/react-router/blob/4d915e3305df5b01f51abdeb1c01bf442453522e/packages/router/router.ts#L321-L329
=> docs: fix ScrollRestoration getKey example

.changeset/heavy-waves-pump.md, packages/react-router-dom/index.tsx, packages/react-router-native/index.tsx, packages/react-router/__tests__/useLocation-test.tsx, packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/router/__tests__/memory-test.ts, packages/router/history.ts
=> fix: preserve state from initialEntries

contributors.yml, docs/start/tutorial.md
the Edit function is imported in the next step by a different name (Edit -> EditContact).
=> fix small error in tutorial documentation

.changeset/pretty-ravens-film.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/router/__tests__/router-test.ts, packages/router/router.ts
Fetcher GET submissions need to preserve the `?index` param instead of replacing it as GET submissions do by default.
Same fix as https://github.com/remix-run/remix/pull/4238 in remix
=> fix: properly handle ?index on fetcher get submissions

.changeset/nasty-bugs-promise.md, docs/components/form.md, docs/components/scroll-restoration.md, docs/hooks/use-fetcher.md, docs/hooks/use-fetchers.md, docs/hooks/use-matches.md, docs/hooks/use-navigation.md, docs/hooks/use-revalidator.md, docs/hooks/use-route-error.md, docs/hooks/use-route-loader-data.md, docs/hooks/use-submit.md, docs/route/action.md, docs/route/error-element.md, docs/route/should-revalidate.md, packages/react-router-dom/index.tsx, packages/react-router/lib/hooks.tsx
A few folks have messaged in discord trying to use `ScrollRestoration` and other data-router-only hooks inside `BrowserRouter` so I went though the new hooks and added the `<docs-warning>` to them with a link to "Picking a Router".
I left out a few hooks like `useLoaderData`, `useActionData` since they seemed self-explanatory?
I also updated the implementation to leverage internal private `useDataRouterContext` and `useDataRouterState` hooks that will print a better error message if called in `BrowserRouter`:
For example:
```
useMatches must be used within a data router.  See https://reactrouter.com/en/main/routers/picking-a-router.
```
=> docs: add better docs and console errors for data router features

.changeset/short-hats-peel.md, contributors.yml, packages/router/__tests__/router-test.ts, packages/router/router.ts
This pull request is a fix for issue #9333 
It removes the action data after a redirect from action.
=> fix: reset actionData state on redirection from an action

.changeset/sweet-chicken-suffer.md, packages/react-router-dom/__tests__/nav-link-active-test.tsx, packages/react-router/__tests__/matchPath-test.tsx, packages/router/utils.ts
Would like to get @mjackson's eyes on this since he wrote the original path matching logic.
I think this was a previously undiscovered bug that's been exposed now that we updated `NavLink` to leverage `useMatch` to follow along with our own recommendation in `examples/custom-link/`.  We had tests to assert that `matchPath({ path: "/users", end: false }, "/users2")` would be null, but we did not have any tests against `/users-2` which is incorrectly matching currently.  
Closes #9279
=> fix: update matchPath to avoid false positives on dash-separated segments

.changeset/hip-colts-serve.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/index.tsx
=> fix: respect basename in useFormAction

contributors.yml, docs/hooks/use-search-params-rn.md
remove `.md` extension on `use-search-params` endpoint
There is some error with the url on [useSearchParams (RN)](https://reactrouter.com/en/main/hooks/use-search-params-rn) that point to [useSearchParams](https://reactrouter.com/en/main/hooks/use-search-params.md) instead [useSearchParams](https://reactrouter.com/en/main/hooks/use-search-params)
Here's the current behavior 
https://user-images.githubusercontent.com/43630681/193406038-7a8b4e67-6ab0-4424-84e0-ee363ebd3d2f.mp4
=> fix: update invalid url for use-search-params

packages/react-router/modules/createContext.js, packages/react-router/modules/createNamedContext.js, packages/react-router/modules/miniCreateReactContext.js, packages/react-router/package.json, yarn.lock
This PR inlines the `mini-create-react-context` dependency, a polyfill for older versions of React that is no longer maintained. This should have no meaningful impact, but it will remove a needless peer dependency version warning for users on React 18.
It could potentially (slightly) increase the bundle size for legacy users where the dependency is already bundled, but it shouldn't be significant enough to ease the concern for users on React 18+ IMO.
=> [v5] Inline `mini-create-react-context` dependency

.changeset/calm-insects-obey.md, packages/react-router/lib/context.ts
Fixes a types typo from https://github.com/remix-run/react-router/pull/9366#discussion_r984815951
=> fix: make hasErrorelement optional on types

contributors.yml, docs/route/error-element.md
The name of the constant in the abstractions section is named `response` but the following references use `res`
=> (fix) fix wrong var name usage in abstractions

contributors.yml, docs/routers/picking-a-router.md
While going through the documentation, I came across a confusing grammatical error in https://reactrouter.com/en/main/routers/picking-a-router. Opening a PR to fix a simple typo in picking-a-router.
=> update picking-a-router confusing typo

contributors.yml, docs/start/tutorial.md
The "Access and render the data" section on the tutorial page is highlighting one line short in the code preview. This PR corrects this to highlight the full snippet.
=> docs: fix highlighted lines on tutorials page

contributors.yml, packages/router/router.ts
Closes https://github.com/remix-run/react-router/issues/9417
=> fix: respect basename in loaders and actions redirects

contributors.yml, docs/hooks/use-route-loader-data.md
Tiny fix in docs for missing url for picking a router in `use-route-loader-data.md`
=> Fix missing url in use-route-loader-data.md

packages/react-router-dom-v5-compat/package.json
Fixes a type in the `unpkg` file, leading https://unpkg.com/react-router-dom-v5-compat to 404 currently
=> fix: update unpkg file for react-router-dom-v5-compat

contributors.yml, packages/react-router-dom/index.tsx
Closes https://github.com/remix-run/react-router/issues/9450
=> fix: respect relative prop in NavLink for isActive

contributors.yml, docs/routers/picking-a-router.md
When migrating from `<MemoryRouter>` to `createMemoryRouter`, some of my project's tests started to fail due to `fetch` not being polyfilled in the `jest` environment.
The error itself is really unclear, so IMO, at least docs should inform about this requirement.
Please let me know if better wording or suggestion should be used here.
=> docs: add fetch polyfill disclaimer to testing section

.changeset/weak-lizards-occur.md, packages/react-router-dom-v5-compat/rollup.config.js, packages/react-router-dom/rollup.config.js, packages/react-router/rollup.config.js, packages/router/package.json, packages/router/rollup.config.js
Adds a UMD build for `@remix-run/router` since that's needed for unpkg/UMD usage of `react-router`/`react-router-dom` 
Closes #9240
=> fix: add router UMD build for unpkg

.changeset/moody-bulldogs-enjoy.md, package.json, packages/router/__tests__/router-test.ts, packages/router/router.ts, packages/router/utils.ts
Submissions should ignore pathless layout routes when looking for the action to call
Closes #9284
=> fix: submissions should ignore pathless layout routes

.changeset/metal-drinks-melt.md, package.json, packages/router/__tests__/router-test.ts, packages/router/router.ts
Updates to `createStaticHandler` to better normalize the return values of `query`/`queryRoute` for use in Remix
=> fix: update thrown/returned Response handling in staticHandler

.changeset/hot-badgers-grow.md, package.json, packages/react-router-dom/__tests__/navigate-encode-params-test.tsx, packages/react-router-dom/__tests__/special-characters-test.tsx, packages/router/history.ts, packages/router/router.ts, packages/router/utils.ts
**tl;dr;**
Replaces #9458 with a fairly comprehensive test suite to ensure that we can handle paths with special characters, match against them, and received properly encoded values from `useLocation` that match what `window.location` would report.
**Background**
In 6.3 and prior we were always in a _reactive_ mode to `window.history` so for example, we would `history.pushState` and then call the listeners with the value from `window.location`.  This flow meant that we inherited the built-in URL encoding performed by `window.location`.  Therefore, if you clicked `<Link to="/✅">` you got `{ pathname: "/%E2%9C%85", ... }` from `useLocation()`.
In 6.4, we go through the new `@remix-run/router` first and do all of our data fetching and `updateState` _before_ `history.pushState` - so we …
=> fix: fix encoding/matching issues with special chars

.changeset/funny-shirts-admire.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Minor updates to `query`/`queryRoute` behavior for Remix usage (see https://github.com/remix-run/remix/pull/4385)
=> Updates to createStaticHandler for Remix consumption

.changeset/cyan-poems-clean.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router/lib/hooks.tsx, packages/router/index.ts, packages/router/utils.ts
While not a super common pattern, this was causing `Form` and `useSubmit` to use incorrect default actions when used in an index route with a path (more commonly generated from remix conventional routes):
```jsx
<Route path="/">
<Route path="foo" index={true} element={<Comp />} />
</Route>
```
A call to `useFormAction` inside `Comp` would incorrectly trim the `foo` route in `getPathContributingMatches` because it was an `index` route, and then it would generate a form action of `/?index` instead of `/foo?index`
=> fix: properly support index routes with a path in useResolvedPath

package.json, packages/router/__tests__/router-test.ts, packages/router/router.ts
=> preserve search/hash in processed redirects

contributors.yml, docs/route/loader.md
There was a typo at the `docs/route/loader.md` doc. One of the `of` word appears twice in a row. So I am considering deleting one of them.
from :
> Since the return value of of `fetch` is a Response...
To :
> Since the return value of `fetch` is a Response...
=> Fixed typo in the route/loader.md doc

.changeset/ninety-countries-cheat.md, packages/react-router-dom/__tests__/special-characters-test.tsx, packages/router/history.ts, packages/router/router.ts, packages/router/utils.ts
Forgot about this callout in the special character encoding PR: https://github.com/remix-run/react-router/pull/9477#discussion_r998722415
We do not want to automatically encode incoming `router.navigate()` locations when using memory routers, so we introduce a `history.encodeLocation` method so encoding can be history aware.
Decoding proves to a be a bit trickier, since we decode in `matchRoutes` which is not history-aware, but since memory locations should never be encoded in the first place, I think it's safe to decode all the time in there, since `decodeURI('/path') === '/path'`
=> fix: make url-encoding history-aware

contributors.yml, packages/router/router.ts
`window.location.origin` is `"null"` (the literal string value) in Firefox under certain conditions: https://bugzilla.mozilla.org/show_bug.cgi?id=878297 
This leads to a broken app in Firefox when you build for production and try to use it from the local file system in an HTML file.
I added an additional check in createURL() in router.ts to respect that case.
=> fixed createURL() for Firefox

.changeset/odd-kids-buy.md, packages/react-router/index.ts
=> fix: fix initialEntries type in createMemoryRouter

contributors.yml, tutorial/README.md
The link in this [page](https://github.com/remix-run/react-router/tree/main/tutorial) is broken
=> Fix the tutorial link

contributors.yml, docs/hooks/use-outlet-context.md
Green lines are marking not important lines, I selected the important parts that involve the useOutletContext hook.
=> Fix docs/hooks/use-outlet-context.md green lines

contributors.yml, docs/guides/deferred.md
The `defer` and `useAsyncValue` links presumably linked to old urls. I believe these are the correct locations.
=> Fix broken links in the deferred data guide

contributors.yml, examples/notes/README.md
The link referenced the old *remixing* branch before the data features were merged into *dev*.
Fixes https://github.com/remix-run/react-router/discussions/9594
=> doc: Update StackBlitz link

contributors.yml, docs/route/should-revalidate.md
This PR fixes the link to `useSubmit` that's currently broken on the page https://reactrouter.com/en/main/route/should-revalidate.
=> docs: Fix link in `shouldRevalidate` docs

contributors.yml, docs/guides/deferred.md
"useAsyncValue" hook alternative example code was missing its highlights.
I tried my best to keep it consistent with the other examples but please review!
=> docs(guide/deferred): Fixed code highlights in details element

contributors.yml, packages/react-router/lib/hooks.tsx
Fixing `useMatch` description as the current one does not reflect the hook's signature
=> chore(react-router): fix `useMatch`'s description

.changeset/funny-oranges-arrive.md, package.json, packages/react-router-dom/__tests__/data-static-router-test.tsx, packages/react-router-dom/__tests__/static-link-test.tsx, packages/react-router-dom/server.tsx, packages/router/__tests__/router-test.ts, packages/router/router.ts
Adds support for `basename` to static data routers.  We accept it up front in `createStaticHandler`, and then persist it through `createStaticRouter`/`StaticRouterPRovider`
Sample usage:
```jsx
let { query } = createStaticHandler(routes, { basename: '/base '});
let context = await query(request);
let router = createStaticRouter(routes, context);
return ReactDOMServer.renderToString(
<StaticRouterProvider router={router} context={context} />
);
```
=> fix: support basename in static routers

.changeset/blue-cycles-check.md, package.json, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/__tests__/data-static-router-test.tsx, packages/react-router-dom/index.tsx, packages/react-router-dom/server.tsx
Handles serialization/deserialization of `ErrorResponse` objects as mentioned in #9537
=> fix: properly serialize/deserialize ErrorResponse instances

.changeset/flat-trainers-speak.md, package.json, packages/router/__tests__/router-test.ts, packages/router/router.ts, packages/router/utils.ts
Properly handle external redirects from actions and loaders:
```js
function loader() {
if (condition) {
return redirect("https://otherdomain.com/path");
}
...
}
```
Client-side we detect and process these via `window.location.replace` like we do in Remix currently.  In SSR scenarios we return the redirect location untouched.
This fixes an issue discovered while testing the "Remix on React Router 6.4" work (https://github.com/remix-run/remix/issues/4570)
=> fix: properly handle external redirects

.changeset/stale-coats-smoke.md, package.json, packages/router/__tests__/router-test.ts, packages/router/router.ts, packages/router/utils.ts
Per the spec, [307](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307) and [308](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308) redirects should preserve the HTTP method and request body and re-submit to the new location.  The spec is ambiguous for 301/302/303 so those will still always redirect using `GET`.
Closes https://github.com/remix-run/remix/issues/4356
=> fix: preserve method on 307/308 redirects

contributors.yml, docs/routers/create-hash-router.md
Currently the highlighting on https://reactrouter.com/en/dev/routers/create-hash-router does not make sense to me:
I think that it would be better to highlight line 4 instead of 3 and 7.
I wasn't able to figure out how to build the docs portal to verify my changes.
I hope my contribution would be helpful.  Thank you for considering it.
=> docs(routers/create-hash-router): fix highlighting 

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, contributors.yml, packages/react-router/lib/components.tsx, packages/react-router/lib/hooks.tsx, packages/router/utils.ts
**Previous behavior**
* Links on the issue and feature request templates errored with a `404`
* Links on the JS docs on certain components, hooks and utils errored with a `404`
**New behavior**
* Updated links to up-to-date ones, mainly a change from `v6` to `main` as provided in https://reactrouter.com/en/main
=> fix: update url links on templates and JS docs

.changeset/hungry-eyes-cheat.md, packages/react-router-dom/index.tsx, packages/react-router/lib/context.ts, packages/react-router/lib/hooks.tsx
This type change from #9589 should have been optional.  In normal flows we'll always have it, but for direct `Router` usage (i.e., Remix) and potential `unstable_HistoryRouter` usages we should make it optional
=> Ensure backwards-compatibility with navigator.encodeLocation

.changeset/itchy-phones-rush.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Fixes a bug in `6.4.4-pre.1` where redirects were always replacing and causing incorrect back button behavior
* Start at `/`
* Click to `/a`
* Click to `/b`
* `/b` `loader` returns `redirect('https://google.com')`
* Land on Google
* Back button should return you to `/a`
Using `<Link to="/b" replace>` above would cause the back button to go back to `/`
=> Respect replace behavior on external redirects

contributors.yml, docs/route/action.md
Adds missing `request` parameter in [action docs](https://reactrouter.com/en/main/route/action)
=> docs(route/action): Add missing`request` parameter

.changeset/new-taxis-stare.md, contributors.yml, package.json, packages/react-router/__tests__/path-matching-test.tsx, packages/router/utils.ts
Closes: https://github.com/remix-run/react-router/discussions/9550
Allows optional params and optional static segments
`:lang?/about` will get expanded matched with
```
/:lang/about
/about
```
`/multistep/:widget1?/widget2?/widget3?`
Will get expanded matched with:
```
/multistep
/multistep/:widget1
/multistep/:widget1/:widget2
/multistep/:widget1/:widget2/:widget3
```
`/fr?/about` will get expanded and matched with:
```
/about
/fr/about
```
Code was added at the point of `flattenRoutes`
Should we allow intercalated situations? currently:
`/one/:two?/three/four?` gets matched with:
```
/one/:two/three
/one/:two/three/:four
```
=> feat: optional params and static segments

.changeset/pretty-kiwis-study.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Loader revalidation requests after an action were being passed the same request used for the action, which was still a `POST` with `formData`.  Loaders should be receiving a `GET` request without the body
=> Fix loader request method

.changeset/pretty-kiwis-study.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Cherry-picked https://github.com/remix-run/react-router/pull/9660 over for the `@remix-run/router@1.0.5` hotfix.  We're updating how we create `Request`/`URL` to fix https://github.com/remix-run/remix/issues/4740 so it made sense to get this fix in as well since they touch some of the same code.
=> Fix loader request method (#9660)

.changeset/new-kiwis-confess.md, package.json, packages/router/history.ts, packages/router/index.ts, packages/router/router.ts, packages/router/utils.ts
We ran into an issue in Remix 1.8.0 where the static handler was failing to create a `new URL()` in Cloudflare pages.  This is because we ended up trying to share some code to create `URL` instances that should have been client-only in the static handler.  This PR updates our code to prefer creating `URL`s from `Request`s (which will always have origins) where possible via `new URL(request.url)` and makes it more explicit where we need to create client-side `URL`/`Request` instances.
Closes https://github.com/remix-run/remix/issues/4740
=> fix(router): fix URL creation in Cloudflare Pages

.changeset/curvy-hairs-deliver.md, packages/router/router.ts
When using `@remix-run/router` for server-side data fetching, we seem to get different `Response` instances from a `return fetch(...)` in a `loader`/`action`.  ~~I'm not entirely sure _why_ yet since we polyfill all `fetch`/`Request`/`Response` globals, but the `instanceof Response` checks were failing.  Copied the same `isResponse` method used in Remix and replaced all checks with that.~~
I think the underlying cause here is that our `loader` is built via ESM and uses the ESM version of the fetch polyfills, but `@remix-run/server-runtime` + `@remix-run/router` are runningin node and therefore using the CJS versions of the fetch polyfills.  Hence the `instanceof` failing.
Closes https://github.com/remix-run/remix/issues/4741
=> Remove instanceof Response checks in favor of isResponse

.changeset/afraid-snakes-cough.md, packages/router/__tests__/router-test.ts, packages/router/router.ts, packages/router/utils.ts
Support a `requestContext` in the static handler similar to `getLoadContext` in Remix
Route loaders/actions accept a `context` for SSR uses only as of now:
```js
let routes = [{
path: '/',
async loader({ request, params, context }) {
let profile = await getUserProfile(context.user);
return json({ profile });
}
}
```
This is provided via the `query`/`queryRoute` methods on the server.  Went with `requestContext` since it's request-specific on the server and because we already return a static handler "context" from `query`.
```js
// entry-server.js
let requestContext = { user: getUser(req); }
let { query, queryRoute } = createStaticHandler(routes);
let context = query('/', { requestContext });
// or
let response = queryRoute('/', { routeId: 'root', requestContext });
```
Closes …
=> Add requestContext to staticHandler query/queryRoute

contributors.yml, docs/start/tutorial.md
The `action` function on line 607, as it is, is throwing the following error:
_You defined an action for route "0" but didn't return anything from your `action` function. Please return a value or `null`._ 
Returning a `contact` (as does the similar `loader` function) seems to solve the issue.
=> Fix: action function throws an error, asking for something to return

packages/react-router/__tests__/path-matching-test.tsx, packages/router/utils.ts
#9650 added support for matching routes with optional path segments, but did not work for nested routes.
This PR fixes that.
It also refactors the approach to explicitly "explode" a path with optional path segments into the equivalent set of valid combinations of paths without optional segments (see `explodeOptionalSegments` jsdoc for an example). The paths are "exploded" prior to creating the route metadata, which means that when the route metadata gets initialized its already correct. Previously, we needed to surgically modify route metadata for a branch (which we were only handling correctly for unnested routes).
=> fix: explode optional segments for relative paths in nested routes

.changeset/violet-rules-rest.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Pointed to `main` just for now, need to check on timing of the next minor or if this should go as a patch
Closes https://github.com/remix-run/remix/issues/4791
=> Fix error boundary tracking for multiple errors bubbling to the same boundary

.changeset/kind-dodos-shop.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Follow up to #9660 to ensure we proxy the `request.headers` from the action request.  For document requests during SSR we also persist the method since it's a single `POST` `request`, unlike during CSR when the revalidations are separate GET requests.  This matches Remix behavior in 1.7.6 but going to confirm.
Remix PR: https://github.com/remix-run/remix/pull/4829
=> Fix loader request on document POST requests

contributors.yml, docs/route/route.md
Adds missing `handle` prop in <Route> documentation with a link to already-existing documentation at docs/hooks/use-matches.md.
Resolves #9724
=> docs(route/route): Add missing `handle` prop

.changeset/slow-drinks-cheer.md, packages/react-router/__tests__/path-matching-test.tsx, packages/router/utils.ts
Found an issue with >2 optional nested segments due to the ordering in which we recombined the exploded paths.
The setup causing this was:
```jsx
<Route path="dashboard">
<Route path=":widget1?"> 
<Route path=":widget2?">
<Route path=":widget3?">
```
When we had 2 levels of nesting (which we have tests for) everythings fine.  But once you get a third level and we get another level of recursion, we were incorrectly combining the results such that child routes interspersed prior to parent routes and we got `/dashboard/:widget2` coming _before_ `/dashboard/:widget1`
=> fix bug with nested optional segments

.changeset/kind-gifts-reflect.md, docs/components/form.md, package.json, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/router/__tests__/router-test.ts, packages/router/router.ts
Bug fixes for PUSH/REPLACE logic for action submissions.  The goal here is to be smart _only when the user doesn't explicitly provide a `replace` value_.  Currently we were missing respecting `replace:false` in the non-redirect scenario, so that is fixed in this PR.
Furthermore, the new default logic is based on the location _after_ the submission.  If that location (be it from the `formAction` or from a `redirect`) is the same as the current location, then we'll `REPLACE`, otherwise we'll `PUSH`
=> Update replace logic for form submissions/redirects

.changeset/fifty-kiwis-sniff.md, package.json, packages/router/__tests__/router-test.ts, packages/router/router.ts
Closes issue reported in Discord with Remix `1.10.0-pre.1`
=> Send submission to shouldRevalidate on action redirects

.changeset/new-news-remember.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Closes #9333
The tl;dr; is that there was a fix a long time ago to differentiate between action redirects and action reloads, but it gave false negatives if you redirected to the same location.  We have a `state._isRedirect` flag now that allows us to avoid this
=> Fix: reset actionData on action redirect to current location

.changeset/swift-bottles-cheat.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Fixes a misunderstanding in #9777.  Went back and checked Remix and it does not keep the submission around on fetch action redirects
=> Fix shouldRevalidate on fetcher action redirect

contributors.yml, packages/react-router/__tests__/useNavigate-test.tsx
I was tracking down a bug and to make sure it wasn't a bug in `react-router` I looked for tests of `useNavigate`.
I saw there is no test of `useNavigate` that expects `navigate` to clear the query string.
That's it. This PR just add a single test.
=> test(useNavigate): navigate with an defined and empty query string

.changeset/three-ladybugs-clap.md, packages/react-router-dom/index.tsx, packages/react-router-dom/server.tsx, packages/react-router-native/index.tsx, packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/context.ts, packages/react-router/lib/hooks.tsx
We found a useId mismatch when testing Remix `1.10.0-pre.5`.  It came down to 2 separate issues:
* The presence of an additional `<DataStaticRouterContext>` during SSR.  This has now been collapsed into an optional `staticContext` field on `<DataRouterContext>`
* An extra fragment and `<script>`/`null` in `StaticRouterProvider` that were not reflected in `RouterProvider`
=> Ensure consistent component tree for useId

docs/route/error-element.md
Assuming `home` isn't meant to be a Promise
=> Add missing `await` in errorElement example code in docs

packages/react-router/docs/api/history.md
Since v5 of RR is using `history` package version 4, I think it can be best to link directly to that branch for users to easily navigate.
Although this is written in the README of the `history` package, I think people might be confused in finding it :)
Thanks!
=> docs: link directly to v4 of `history` package from v5 docs

contributors.yml, docs/components/await.md
This PR fixes a small typo in the last example.
=> docs(components/await): fix typo

.changeset/slow-trees-notice.md, contributors.yml, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/__tests__/polyfills/SubmitEvent.submitter.ts, packages/react-router-dom/__tests__/setup.ts
Work around the [submitter bug](https://github.com/jsdom/jsdom/issues/3117) in just one place, and link to my [jsdom PR](https://github.com/jsdom/jsdom/pull/3481) which will fix it, so that the workaround can be removed sooner rather than later 🤞
This workaround refactor also establishes a pattern for other jsdom bug polyfills which will be landing in forthcoming RR PRs (the bugs aren't relevant in the current test suite, but will be in the PRs 😅)
=> test(react-router-dom): streamline jsdom submitter bug workaround

.changeset/happy-ladybugs-occur.md, packages/react-router/__tests__/generatePath-test.tsx, packages/router/utils.ts
=> Fix up generatePath when optional params are present

contributors.yml, packages/router/__tests__/router-test.ts, packages/router/router.ts
This solves the issue remix-run/remix#5002.
With this change, we are able to redirect to URI's like `mailto:mail@example.com` before this change it was not possible because it was interpreted as a relative path.
The regex comes from https://stackoverflow.com/a/31991870 and should match all common absolute URLs and URIs including string starting with `//`.
I tested it with in my own project and it worked like a charm!
=> Improved absolute redirect url detection in actions/loaders

contributors.yml, docs/start/tutorial.md
If we use `<a>` tag, we need to add a slash, ortherwise we got /contacts/contacts/2
=> docs(start/tutorial): fix links

.changeset/scroll-restoration-action-redirect.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
This Pull request fix issue #9577
=> Fix scroll restoration when redirecting in an action

README.md, contributors.yml
I noticed that the README says "when v6 is stable" and... v6 is stable!
=> docs(README): v6 is stable, link to its documentation

contributors.yml, docs/components/form.md
=> docs(components/form): Fix method case in action

.changeset/real-panthers-hear.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Fixes a regression in Remix 1.10.0 for CORS requests.  Remix used to reject `OPTIONS` on data requests but allow them on resource requests.  Since we don't distinguish these in `createStaticHandler.queryRoute`, this PR allows `OPTIONS` requests for any usage of `queryRoute`
Closes: https://github.com/remix-run/remix/issues/5093
=> Support OPTIONS requests in staticHandler.queryRoute

README.md, contributors.yml, packages/react-router-dom/README.md, packages/react-router-native/README.md, tutorial/README.md
The raw MarkDown is less styled and has broken image files. The documents are intended to be read on https://reactrouter.com/ so link there to be more friendly to newcomers.
Fixes #9607
=> Link to the tutorial on https://reactrouter.com/

.changeset/rare-dancers-shave.md, packages/router/__tests__/router-memory-test.ts, packages/router/__tests__/router-test.ts, packages/router/router.ts
Fixes a small 1.10.0 regression in same-origin absolute redirects
Former Remix logic: https://github.com/remix-run/remix/blob/%40remix-run/serve%401.7.6/packages/remix-react/routes.tsx#L227
Closes: https://github.com/remix-run/remix/issues/5117
=> Fix 404 bug with same-origin absolute redirects

.changeset/spicy-nails-compete.md, package.json, packages/react-router-dom/index.tsx
Add an unstable version of `usePrompt`.  Behavior gets _very_ weird (and in some cases very wrong across browsers) if users click additional back/forward navigations while a prompt is open and there's nothing we can do about it, but this provides a simpler path than building a custom `useBlocker` modal/inline-prompt.
=> Add unstable_usePrompt

.changeset/silent-oranges-pay.md, package.json, packages/react-router-dom/__tests__/link-href-test.tsx, packages/react-router-dom/index.tsx
complimentary work for https://github.com/remix-run/remix/issues/5016
=> feat: allow Link's "to" prop to accept external urls

contributors.yml, packages/react-router-dom-v5-compat/__tests__/compat-router-test.tsx, packages/react-router-dom-v5-compat/lib/components.tsx
Currently when using `react-router-dom-v5-compat`'s `CompatRouter` with SSR, you get this fun React warning in your console:
This is something my team has ignored, but it's pretty obnoxious. Additionally, [even Ryan](https://twitter.com/ryanflorence/status/1610499820502011911) believes this warning is unnecessary.
This PR simply adds a fix [previous React core team member Bri implemented](https://github.com/bvaughn/react-resizable-panels/blob/main/packages/react-resizable-panels/src/hooks/useIsomorphicEffect.ts), as well as a test to verify that warning does not show up in a jest node environment
=> Fix React SRR useLayoutEffect console.error when using CompatRouter

contributors.yml, docs/router-components/browser-router.md
React V18 synthax correction (cause I had the following error in my Chrome console : "Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot"). I hope this will helps.
=> docs(Browser-router.md): Update for React 18.0

.changeset/small-squids-wash.md, contributors.yml, packages/react-router-dom/index.tsx
`pagehide` seems to be a better cross-browser way of detecting the unload of a page.  And in the case of scroll restoration there's no need to ever prompt the user so `pagehide` seems a better option anyway.
From https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event#usage_notes:
> If you're specifically trying to detect page unload events, the pagehide event is the best option.
Closes #9463
=> Change useScrollRestoration to use pagehide event

.changeset/chilly-stingrays-rhyme.md, docs/components/form.md, docs/components/scroll-restoration.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Closes #9961, https://github.com/remix-run/remix/issues/3145
=> Respect preventScrollReset on fetcher.Form

.changeset/orange-insects-complain.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
=> Do not short circuit on hash change only mutation submissions

.changeset/little-taxis-bake.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
This PR fixes underlying some bugs with `fetcher.load` `shouldRevalidate` behavior.  In an oversight in initial implementation we passed the _fetcher.load()_ url to both the `currentUrl`/`nextUrl` parameters and also deciphered the `currentParams`/`nextParams` from the fetcher load match, not the navigation locations.  This is wrong since fetchers revalidate due to _navigation_ events and we need to provide information about the navigation that triggered the revalidation (and indeed the `form*` submission fields we provide come from the navigation).
This PR makes the following updates:
* fetcher `shouldRevalidate` now receives `currentUrl`/`currentParams`/`nextUrl`/`nextParams` fields from the navigation locations to align with the submissions info
* I also realized that we are …
=> Fix fetcher shouldRevalidate parameters

.changeset/afraid-ducks-know.md, packages/react-router-dom/__tests__/search-params-test.tsx, packages/react-router-dom/dom.ts, packages/react-router-dom/index.tsx, packages/react-router-native/__tests__/__snapshots__/search-params-test.tsx.snap, packages/react-router-native/__tests__/search-params-test.tsx, packages/react-router-native/index.tsx
If a user provides an initial set of search params with `useSearchParams({ key: 'initial' })` we only want to leverage that value initially, but not once they've applied new params via a `setSearchParams` call  
Closes #9668
=> Fix bug with search params removal

.changeset/six-tigers-fold.md, packages/router/history.ts, packages/router/router.ts
=> Fix navigation for hash routers on manual URL changes

contributors.yml, docs/start/tutorial.md
Changed to match the name used throughout the rest of the tutorial
=> docs(start/tutorial): fix EditContact component typo

contributors.yml, docs/hooks/use-matches.md
Route of the crumb should be /messages instead of /message
=> docs(hooks/use-matches): Fix crumb route

.changeset/afraid-scissors-rhyme.md, packages/react-router-dom/__tests__/link-href-test.tsx, packages/react-router-dom/index.tsx
This merge request improves the detection of absolute URLs in the `<Link to=".." />` component.
`<Link to="mailto:remix@example.com" />` will not solve to the correct url because its detected as a relative url.
`<Link to="mailto:remix@example.com" />` will solve to the correct url and opens the mail app depending on the browser.
This uses the same regex as in #9829
=> Added better detection for absolute urls in link component

docs/start/tutorial.md
Fixes the current highlighting which covers some things that don't change and is missing the </Form> which does:
=> docs(start/tutorial) fix: highlighting for changing `<form>` to `<Form>`

.changeset/thirty-frogs-wave.md, packages/router/router.ts
=> Only check for differing origin on absolute URL redirects

.github/workflows/release-comments.yml, .github/workflows/release.yml, scripts/release/comment.ts, scripts/release/constants.ts, scripts/release/find-release-from-changeset.js, scripts/release/github.ts
sync with remix https://github.com/remix-run/remix/pull/5342
=> ci: use current branch when gathering PRs for stable releases

.changeset/violet-apes-pay.md, packages/react-router-dom/__tests__/link-click-test.tsx, packages/react-router-dom/__tests__/link-href-test.tsx, packages/react-router-dom/index.tsx
Absolute URL detection in `<Link to>` missed a case where the object form of `to` was used without a pathname, and resulted in the loss of the active pathname
Closes #10007
=> Fix partial object (search or hash only) pathnames losing current path

.changeset/healthy-moons-compete.md, packages/react-router/lib/hooks.tsx, packages/router/router.ts
Fixes an invalid boolean condition on our `warning` and also removes the `activeBlocker` internal state variable since it was not actually correct in strict mode.
Closes #9998
=> Remove inaccurate console warning for POP navigations

DEVELOPMENT.md, package.json, scripts/publish.js, scripts/version.js
Updates for experimental releases
=> Updates to manual publish scripts

DEVELOPMENT.md
Note: most of the change in here are adding a trailing `.` ;)
Sibling to https://github.com/remix-run/remix/pull/5388
=> Sync up release docs with react router

.changeset/long-jokes-wait.md, packages/react-router-dom/server.tsx
=> Fix useBlocker to return IDLE_BLOCKER during SSR

contributors.yml, docs/route/route.md
When Outlet was moved to the components section (out of route section), the old link was never deleted in `route.md`.
=> docs: Fix link to Outlet component

.changeset/nasty-carrots-breathe.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Fixes the following issue:
When a Remix document request involves a loader which defer()s with specific response headers and/or status code, those are not at all respected.
Fixes issue: https://github.com/remix-run/remix/issues/5345
=> fix(defer): respect headers and status

contributors.yml, docs/start/tutorial.md
Remove severely out of date and high vuln dependency sort-by, which goes seemingly unused.
Closes #10092
=> docs(start/tutorial): remove unnecessary dependency

.changeset/wet-dogs-check.md, contributors.yml, package.json, packages/router/__tests__/router-test.ts, packages/router/router.ts
Fix for #10052 
Checks whether the redirect location contains the basename (if set) and redirect as an external url if the basename is not present in the redirect location.
Also related: #9859
=> fix(router): "hard" redirect to different paths on the same origin if redirect location does not contain basename

contributors.yml, docs/start/tutorial.md
In this tutorial, within route `/contact/:contactId/edit ` 
- We forgot destructuring  contact data before render it on UI. 
Before fix: 
After fixed:
=> docs(tutorial): Fix logic loader data in edit route

.changeset/big-olives-doubt.md, package.json, packages/react-router-dom/__tests__/link-click-test.tsx, packages/react-router-dom/__tests__/link-push-test.tsx, packages/react-router-dom/index.tsx
=> fix: treat absolute/same-origin/different-basename <Link to> values as external

contributors.yml, docs/start/concepts.md
When I tried to create a layout, I was thoroughly confused because the lines above say it will be rendered like this:
```jsx
<PageLayout>
<Privacy />
</PageLayout>
```
So I assumed that inside PageLayout, I could just render the children with `{children}` and that's where `<Privacy />` would go. To my surprise, nothing showed up, and the documentation felt confusing. I found the answer on [stack overflow](https://stackoverflow.com/questions/69982197/page-layout-broken-in-react-router-v6), but felt a little note here would helpful to anyone brand new to using React router.
=> Specifiy that layouts require an <Outlet> to work

contributors.yml, docs/start/tutorial.md
When editing any contact the form is always empty. It's because the loader wraps the contact in an object, so it has to be destructured in the component call to be loaded properly.
=> docs(start/tutorial): fix EditContact loaded data

.changeset/old-camels-accept.md, contributors.yml, packages/react-router/__tests__/generatePath-test.tsx, packages/react-router/__tests__/matchPath-test.tsx, packages/router/utils.ts
generatePath was doing multiple passes on the `path` using string replace, the first two passes were applying parameters, the third pass was doing a cleanup and the fourth path was applying the `splat`. It was possible to get incorrect results while applying `splat` when the last parameter value ended with `*`:
```ts
const path = generatePath("/route/:name", {
name: encodeURIComponent("includes *asterisk at the end*"),
})
```
```
Expected: "/route/includes *asterisk at the end*"
Received: "/route/includes *asterisk at the end"
```
results of the first two passes return the value of `/route/*asterisk at the end*` which was later treated as path with the splat resulting in the last asterisk removed.
it was also possible to inject the splat value unintentionally
```ts …
```
=> fix: generatePath incorrectly applying parameters #9051

contributors.yml, docs/hooks/use-submit.md
Change "let's" (contraction of "let us") to "lets" (singular of "let")
=> docs(hooks/use-submit): Fix typo

contributors.yml, docs/guides/deferred.md
After explaining how React Router uses response objects to replicate web standard behavior, it can be confusing why this suddenly stops working just by adding "defer" to the loader's return value. Thinking it through yields the answer (deferred data isn't handled by the response returning the HTML), but it seems like it would reduce the friction to add a little explanation.
=> docs(guides/deferred): add FAQ about using `Response` objects with `defer`

contributors.yml, docs/routers/create-memory-router.md
Found a couple of typos in create-memory-router.md file. Fixed them as best as I could.
=> docs(routers/create-memory-router): fix typos

.changeset/tricky-walls-eat.md, contributors.yml, packages/react-router-dom/__tests__/data-static-router-test.tsx, packages/react-router-dom/server.tsx
Check for presence of new `ErrorBoundary` property was missing.
=> fix(react-router-dom): fix `detectErrorBoundary` function

packages/react-router-dom/__tests__/data-browser-router-test.tsx
Update `data-browser-router-test.ts` to use `createBrowserRouter`/`createHashRouter`/`<RouterProvider>` directly instead of the utility `<TestDataRouter>` element which was leftover from the original `<DataBrowserRouter>`/`<DataHashRouter>` API design
=> Remove wrapper API from data browser router tests

.changeset/proud-kings-cough.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/router/__tests__/router-test.ts, packages/router/router.ts
Run `lazy()` via `startNavigation` in `router.inititialize()` so we can properly bubble `lazy()` errors to boundaries.
Closes #10194
=> Properly handle lazy errors during router initialization

.changeset/fix-fragments-ids.md, packages/react-router/__tests__/createRoutesFromChildren-test.tsx, packages/react-router/lib/components.tsx
=> Fix route ID generation when using Fragments in createRoutesFromElements

.changeset/fetcher-submission-revalidation.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
=> Provide fetcher submission to shouldRevalidate if fetcher action redirects

packages/router/__tests__/router-test.ts, packages/router/router.ts
Follow up to #10208 to ensure we only hand the submission to `shouldRevalidate` but we don't put it on the loading `navigation`
=> fix: don't include fetcher submission on navigation in fetch action redirect

contributors.yml, docs/start/concepts.md
The <Outlet> is being treated as markup by the mdx, and is being rendered as a tag on the page resulting in :
```html
<docs-warning>
Don't forget to add an `
<outlet>` 
to your layout where you would like child route elements to be rendered. Using `children` will not work as expected.
</outlet>
</docs-warning>
```
instead of
```html
<docs-warning>
Don't forget to add an <code>`<outlet>`</code> to your layout where you would like child route elements to be rendered. Using <code>`{children}`</code> will not work as expected.
</docs-warning>
```
=> docs(start/concepts): fix warning

docs/hooks/use-location.md
Fixes #10241
We use `any` now. This doc needs updating.
=> Match location.state type to code

.changeset/rotten-waves-fold.md, package.json, packages/router/router.ts
Closes https://github.com/remix-run/blues-stack/issues/151
=> Remove instanceof check for DeferredData

contributors.yml, docs/start/concepts.md
Added the missing word "the" in the documentation.
=> docs(start/concepts): fix typo

contributors.yml, packages/react-router/README.md
These links work on github, but don't work correctly on https://www.npmjs.com/package/react-router
=> docs(readme): Change links to full path

contributors.yml, docs/routers/create-browser-router.md
Changed the link to Route object instead of Route APIs
The link is used here:
`
routes
An array of [Route][route] objects with nested routes on the children property.
`
=> docs(create-browser-router.md): correct link

contributors.yml, docs/hooks/use-navigate.md
restored the line since despite #8991 got merged into main, 854f4a41780089ad114fecef1a25111830f5cc0b was nowhere to be seen in commit history.
=> docs(use-navigate.md): restore hint for `replace`

docs/components/link.md, docs/components/nav-link.md
I see this is documented above, but I didn't realize it was an option until I was reading the source and saw it in the type of the props
=> Add docs section in Link/Navlink for `reloadDocument`

.changeset/fix-fetcher-revalidation.md, package.json, packages/router/__tests__/router-test.ts, packages/router/router.ts
- Fetchers no longer revalidate on search param changes or when routing to the same URL
- Also fixed a semi-related bug where fetcher.load redirects wouldn't be marked as done on the completion of the redirect
=> Fix fetcher revalidation logic

.changeset/fetcher-404.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Add a proper 404 `ErrorResponse` for a `fetcher.load` to a route without a loader, instead of a raw `Error`
=> Add proper 404 error for missing loader

.changeset/fetcher-basename-copy.md, .changeset/fetcher-basename.md, .changeset/stable-navigate-submit.md, package.json, packages/react-router-dom-v5-compat/index.ts, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/dom.ts, packages/react-router-dom/index.tsx, packages/react-router-dom/server.tsx, packages/react-router-native/index.tsx, packages/react-router/__tests__/data-memory-router-test.tsx, packages/react-router/__tests__/navigate-test.tsx, packages/react-router/__tests__/useNavigate-test.tsx, packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/context.ts, packages/react-router/lib/hooks.tsx, packages/router/README.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
This work closes a handful of things:
* Stabilizes `useNavigate` across `location` changes: https://github.com/remix-run/react-router/issues/7634#issuecomment-1306650156
* Stabilizes `useSubmit` and `fetcher.submit` across location changes: https://github.com/remix-run/react-router/issues/9739
* Forked off from https://github.com/remix-run/react-router/discussions/9737
* It does this by moving the relative routing logic into `@remix-run/router` (when using a `RouterProvider`): https://github.com/remix-run/react-router/discussions/9588
* We also get `basename` handling for fetchers with this: https://github.com/remix-run/react-router/issues/9711
=> Stabilize useNavigate/useSubmit/fetcher.submit for data routers

contributors.yml, docs/components/routes.md
Fixes a link that currently 404s on the `<Routes>` component page.
- From: https://reactrouter.com/en/main/hook/location (404s)
- To: https://reactrouter.com/en/main/hooks/use-location
=> Update routes.md fixing broken link

contributors.yml, docs/hooks/use-search-params.md
The link directs to content that is out-of-date. Fixed!
=> update useState URL to current

.changeset/raw-payload-submission-router.md, .changeset/raw-payload-submission.md, docs/hooks/use-fetcher.md, docs/hooks/use-navigation.md, docs/hooks/use-submit.md, docs/route/action.md, docs/route/should-revalidate.md, package.json, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/dom.ts, packages/react-router-dom/index.tsx, packages/router/__tests__/router-test.ts, packages/router/router.ts, packages/router/utils.ts
~~Depends on #10336~~
Closes part of #10324 (does not yet handle call-site/override actions - that will be a separate PR):
* Adds support for `useSubmit()(obj, { encType: null })` to opt out of serialization for raw payloads.  These are then passed to the `action` via the `payload` parameter.  Same goes for `fetcher.submit`.
* Add support for opt-in serialization of payloads for `encType:application/json` and `encType:text/plain`
See the changesets for examples.
=> Add better control over submission serialization 

.changeset/invalid-link-to.md, packages/react-router-dom/__tests__/link-href-test.tsx, packages/react-router-dom/index.tsx
Closes https://github.com/remix-run/remix/issues/5440
=> Fail gracefully on invalid Link to values

.changeset/revalidate-error-boundary.md, package.json, packages/react-router/__tests__/data-memory-router-test.tsx, packages/react-router/lib/hooks.tsx, packages/router/router.ts
=> Allow useRevalidate to resolve a loader-driven error boundary UI

.changeset/descendant-routes-data-errors.md, package.json, packages/react-router-dom/server.tsx, packages/react-router/__tests__/data-memory-router-test.tsx, packages/react-router/lib/components.tsx, packages/react-router/lib/hooks.tsx
Fix descendant `<Routes>` rendering inside a `RouterProvider` when data routes errors exist
Closes #10317
=> Fix descendant Routes rendering alongside RouterProvider errors

packages/react-router/lib/components.tsx, packages/react-router/lib/hooks.tsx
Quick follow up to https://github.com/remix-run/react-router/pull/10374 to avoid relying on implicit detection of being inside a `RouterProvider` and move to an explicit param passed to a new internal `useRoutesImpl` hook.
=> refactor(react-router): clean up `useRoutes`' `RouterProvider` detection

.changeset/navigate-in-effect.md, package.json, packages/react-router/__tests__/useNavigate-test.tsx, packages/react-router/lib/hooks.tsx
Continuation of #8929
Closes #8809
=> Allow useNavigate to be called from child component effects

.github/workflows/format.yml, .github/workflows/release.yml, .github/workflows/test.yml
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
- https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency
- > The fully-formed ref of the branch or tag that triggered the workflow run. For workflows triggered by `push`, this is the branch or tag ref that was pushed. For workflows triggered by `pull_request`, this is the pull request merge branch. For workflows triggered by `release`, this is the release tag created. For other triggers, this is the branch or tag ref that triggered the workflow run. This is only set if a branch or tag is available for the event type. The ref given is fully-formed, meaning that for branches the format is `refs/heads/<branch_name>`, for pull requests it is …
=> chore: remove `styfle/cancel-workflow-action` usage

.changeset/soft-moons-sneeze.md, packages/react-router-dom/server.tsx
Fix SSR warnings about `useLayoutEffect` on the server since we were missing the `static` prop inside `StaticRouterProvider` (which is what `useIsomorphicLayoutEffect` relies on)
=> Add missing static propr for StaticRouterProvider

.changeset/same-hash-links.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Closes https://github.com/remix-run/remix/issues/5898
=> Fix up same-hash link short circuiting logic

.changeset/silent-stingrays-boil.md, contributors.yml, packages/react-router/lib/components.tsx
Rebased #10400 onto the `release-next` branch for inclusion in 6.11 since this fixes an issue in Remix apps on React 17.
=> Avoid unnecessary router subscribes

.changeset/descendant-routes-component.md, docs/route/route.md, packages/react-router/__tests__/Route-test.tsx, packages/react-router/lib/hooks.tsx
=> Fix usage of Component API within descendant routes

.changeset/empty-path-basename-navigation.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
=> Fix pathless relative routing with a basename

.changeset/navigate-from-routes.md, packages/react-router/__tests__/useNavigate-test.tsx, packages/react-router/lib/context.ts, packages/react-router/lib/hooks.tsx
=> Fix useNavigate when called from <Routes> inside a <RouterProvider>

.changeset/navigate-strict-mode.md, package.json, packages/react-router/__tests__/navigate-test.tsx, packages/react-router/lib/components.tsx
=> Fix usage of Navigate in strict mode when using a data router

contributors.yml, docs/start/concepts.md
This commit fixes a grammatical error in the React Router documentation. The word "an" was added to the sentence that originally read "you'll most likely want index route to fill the space when the user hasn't clicked one of the items yet."
=> fix: grammatical error in documentation

docs/components/nav-link.md
Changed "NavLinks's" to "NavLink's" to correct a grammatical mistake and improve the clarity of the sentence.
This change applies to the latest version of React Router. No potential issues or side effects are expected from this change.
Thanks for taking the time to review this pull request!
=> Corrected a grammatical mistake in a sentence

.changeset/fix-basename-duplication.md, packages/react-router/__tests__/useNavigate-test.tsx, packages/react-router/lib/hooks.tsx
* In `BrowserRouter`, `useNavigateUnstable` will handle resolving the relative path and prepending the basename
* In `RouterProvider`, the `router.navigate` will handle resolving relative paths and prepending the basename
However, If you use `RouterProvider` and include some descendant `<Routes>` inside the tree, then that needs to use `useNavigateUnstable` to resolve relative paths but it _should not_ also prepend the basename since navigation will still go through `router.navigate`
Closes #10467
=> Fix basename duplication in RouterProvider descendant routes

docs/components/routes.md, docs/upgrading/v5.md, docs/upgrading/v6-data.md
I've seen a lot of confusion recently around the compatibility of `<Routes>` and `<RouterProvider>` so I wanted to start u pa new doc where we could clearly explain how we envision apps migrating.
Related issues/discussions:
* https://github.com/remix-run/react-router/issues/10021
* https://github.com/remix-run/react-router/issues/10317
* https://github.com/remix-run/react-router/discussions/10373
=> Add docs on migrating from BrowserRouter to RouterProvider

.changeset/non-serializable-state.md, packages/router/__tests__/TestSequences/PushStateInvalid.ts, packages/router/__tests__/browser-test.ts, packages/router/__tests__/hash-test.ts, packages/router/history.ts
=> throw on non-serializable state PUSH navigation

.changeset/revalidate-with-hash.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
=> Ensure revalidations happen when hash is present

.changeset/delete-submit-fetcher.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Do not abort revalidations if the submitting fetcher is deleted right after it's action completes
Closes https://github.com/remix-run/remix/issues/6458
=> Allow revalidations to complete if submitting fetcher is deleted

.changeset/young-glasses-smoke.md, package.json, packages/react-router/lib/components.tsx
Now that's we're using `startTransition` we can't look directly at `router.state` in `RouterProvider`
=> Use react concurrent mode state in RouterProvider

.changeset/big-vans-act.md, contributors.yml, packages/router/router.ts
=> Update window.history before setting updated React state on navigations

packages/react-router/docs/api/history.md
The link to history.block documentation was pointing to v5 of the history package, the version used in react-router v5 is v4
=> Updated history.md  : Corrected link to history.block documentation

.changeset/strip-basename-getkey.md, package.json, packages/react-router-dom/__tests__/scroll-restoration-test.tsx, packages/react-router-dom/index.tsx, packages/router/__tests__/router-test.ts, packages/router/router.ts
Fixes issue raised in https://github.com/remix-run/react-router/discussions/9565#discussioncomment-6053841
We were calling `getKey` inconsistently.  From the `usePageHide` hook it was the `useLocation` value (not including `basename`) but from inside the router it was the `router.state.location` (including `basename`).  Now it's always the user-land version without the `basename`
=> Strip basename from location provided to getKey

.changeset/silly-eagles-divide.md, packages/react-router-dom/index.tsx, packages/react-router/lib/components.tsx
I'm not quite sure why the current feature detection approach wasn't sufficient 😕 .  It works fine in `vite` but apparently has issues in `webpack`.  the react team doesn't do anything funny like this in their [`useSyncExternalStore` shim package](https://github.com/facebook/react/blob/main/packages/use-sync-external-store/src/useSyncExternalStoreShim.js#L13) and I can't imagine that has issues on `webpack` and React 17.
Either way, moving to a constant seems to fix the webpack compilation issue.
Closes #10566
=> Fix feature detection of React.startTransition

.changeset/blocker-key-strict-mode.md, .changeset/strip-blocker-basename.md, examples/navigation-blocking/src/app.tsx, package.json, packages/react-router-dom/__tests__/use-blocker-test.tsx, packages/react-router/lib/hooks.tsx, packages/router/router.ts
Fix issues with internal blocker `key` generation in `StrictMode`
Closes #10073
Closes #10144
Also strips the `basename` (if present) from the `currentLocation`/`nextLocation` we expose out to the user to match `useLocation` behavior.  This was discovered as part of https://github.com/remix-run/react-router/pull/10550#issuecomment-1574091175
=> Fix unstable_useBlocker key issues in strict mode

yarn.lock
Did this by running `npx yarn-deduplicate && rm -rf ./node_modules && yarn` (just like I did in https://github.com/remix-run/remix/pull/6108 & https://github.com/remix-run/examples/pull/247)
- https://github.com/scinos/yarn-deduplicate
- https://npm.im/yarn-deduplicate
=> chore: dedupe `yarn.lock`

.changeset/start-transition-minification.md, packages/react-router-dom/index.tsx, packages/react-router/lib/components.tsx
This fixes the `webpack`/`terser` production build minification issue discovered in #10579 where in production mode the code would minify down such that the first half of the following ternary wouldn't actually be called:
```js
// React Router source code
// In module scope
const START_TRANSITION = "startTransition";
// Inside BrowserRouter/etc.
let setState = React.useCallback((newState) => {
START_TRANSITION in React
? React[START_TRANSITION](() => setStateImpl(newState))
: setStateImpl(newState);
},
[setStateImpl]
);
```
This would minify down to the following using `webpack`, where `const _ = "startTransition"` and `f` is `setStateImpl`:
```js
// Minified production webpack build
p=o.useCallback((e=>{_ in(r||(r=n.t(o,2)))||f(e)}),[f]);
```
Which expands to:
```js
p = …
```
=> Fix webpack/terser startTransition minification bug in production mode

.changeset/v7-start-transition.md, docs/guides/api-development-strategy.md, package.json, packages/react-router-dom/__tests__/concurrent-mode-navigations-test.tsx, packages/react-router-dom/__tests__/exports-test.tsx, packages/react-router-dom/index.tsx, packages/react-router-native/__tests__/exports-test.tsx, packages/react-router/__tests__/navigate-test.tsx, packages/react-router/__tests__/useNavigate-test.tsx, packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/polyfills/start-transition.ts
=> Add future.v7_startTransition flag

.changeset/purple-islands-cough.md, packages/react-router/__tests__/generatePath-test.tsx, packages/router/utils.ts
=> Fix generatePath when passed a zero value param

.changeset/skip-fetcher-revalidate.md, package.json, packages/router/__tests__/router-test.ts, packages/router/router.ts
If an initial `fetcher.load` is interrupted by a navigation, we should not try to call `shouldRevalidate` for the interrupted fetcher since it still performing the initial load and therefore it's not a revalidation.  This is specifically crucial in Remix apps where the "load" also encompasses loading the JS route module, so until the first one completes we don't even have a `shouldRevalidate` implementation to call.
Also ensures we properly abort in-progress `fetcher.load` calls that are re-loaded in this manner.
Closes #10473
=> Avoid calling shouldRevalidate on interrupted initial load fetchers

packages/router/__tests__/router-test.ts, packages/router/router.ts
Quick follow up to https://github.com/remix-run/react-router/pull/10413 for submitting `null` or `""`
=> fix empty submissions

.changeset/brave-mails-relate.md, package.json, packages/react-router-dom/__tests__/setup.ts, packages/react-router-dom/dom.ts, packages/react-router/__tests__/setup.ts
The existing check had some false positives
```js
new FormData(undefined, 0); 
// throws: Uncaught TypeError: Failed to construct 'FormData': parameter 1 is not of type 'HTMLFormElement'.
```
=> fix FormData submitter check

contributors.yml, docs/hooks/use-submit.md
"This behavior will likely change in the future when React Router releases v7, so it's best to make any JSON object submissions explicit with either encType: "application/x-www-form-urlencoded" or encType: "application/json" to ease your eventual v7 migration path." https://github.com/remix-run/remix/releases/tag/remix%401.18.0
=> docs(use-submit): explicit encType

.changeset/fix-blocker-loop.md, packages/react-router-dom/__tests__/use-blocker-test.tsx, packages/react-router/lib/hooks.tsx
Closes https://github.com/remix-run/remix/issues/6704
=> Fix loop in unstable_useBlocker when used with an unstable blocker function

.changeset/fix-reused-blocker.md, package.json, packages/react-router-dom/__tests__/use-blocker-test.tsx, packages/react-router/lib/hooks.tsx, packages/router/router.ts
Our approach for clearing blockers after a successful navigation was incorrect for blockers that were reused in a layout route.
Closes #10649
=> Fix issue with reused blockers on subsequent navigations

.changeset/route-lazy-type.md, packages/react-router/lib/context.ts, packages/router/utils.ts
=> Enhance route.lazy return type

packages/react-router/lib/context.ts
Quick follow up to https://github.com/remix-run/react-router/pull/10634 which was only allowing agnostic properties to be returned from `lazy`
=> Fix lazy typings

contributors.yml, docs/hooks/use-outlet-context.md
In previous version when you change type of a user in `useState` or just pass wrong data in the context you wouldn't get a typescript error. In other words only context consumer uses `ContextType` but not producer, which is wrong bcs as I said when you change type of data in the producer(without changing ContexrType) => the consumer would still assume the old data is passed.
This commit adds better typescript support, so that when you change data passed into context you will get ts error if the data does not satisfy ContextType and you will be forced to update context related stuff everywhere where it is needed(bcs typescript will show you)
=> docs(hooks/use-outlet-context): update typings

.changeset/fetcher-redirect-interrupt.md, package.json, packages/router/__tests__/router-test.ts, packages/router/router.ts
If a fetcher loader/action is in-flight, and a new navigation is started, and then the loader/action completes with a redirect, we should be ignoring the redirect since the navigation came after it.
Closes https://github.com/remix-run/remix/issues/6695
=> Properly handle fetcher redirects interrupted by normal navigations

.changeset/decode-hash-scroll.md, .changeset/dirty-coats-warn.md, contributors.yml, packages/react-router-dom/index.tsx
Supersedes https://github.com/remix-run/react-router/pull/10642
Closes #10641
=> Properly decode element id when emulating hash scrolling

.changeset/defer-resolve-undefined.md, package.json, packages/router/__tests__/router-test.ts, packages/router/utils.ts
Alternate fix for https://github.com/remix-run/remix/pull/6793
=> Better handling of deferred promises that resolve/reject with undefined

.changeset/initial-load-fetcher.md, packages/router/__tests__/router-test.ts, packages/router/router.ts
Follow up to https://github.com/remix-run/react-router/pull/10623 which inadvertently started revalidating initial-load fetchers on GET navigations, when it should only revalidate (without calling `shouldRevalidate`) on explicit revalidations (submissions, `useRevalidate`, etc.).  
Discord thread in which this was raised: https://discord.com/channels/770287896669978684/1128075241579614208/1128080680417501215
=> Initial-load fetchers should not automatically revalidate on GET navigations

.changeset/prompt-effect-order.md, contributors.yml, packages/react-router-dom/__tests__/use-prompt-test.tsx, packages/react-router-dom/index.tsx
PR for #10489.
This pull request fixes the `usePrompt` invalid blocker state transition invariant exception.
Essentially, when navigating, if we should block navigation, we update the blocker for the derived blocker key so that it's in a "blocked" state. In the proceed function for this blocker, we then update the blocker so that it's in a "proceeding" state. In the reset function for this blocker, we reset the blocker to the `IDLE_BLOCKER` (which results in an "unblocked" state). 
In the `updateBlocker` function, we receive the blocker key as a parameter and update it. What was happening here is that by the time we came to proceed the blocker, it was in a "proceeding" state, causing the invariant to throw an exception according to the state-machine-like logic (logically, as this makes no …
=> fix(react-router-dom): Fix `usePrompt` invalid blocker state transition

contributors.yml, docs/hooks/use-outlet-context.md
Note: documentation only change.
Lines that were intended to be highlighted are not. The array used to define the lines to highlight does not allow for spaces.
Remove the spaces in the line number array.
=> Fix syntax highlighting in docs for useOutletContext

contributors.yml, examples/auth-router-provider/.gitignore, examples/auth-router-provider/.stackblitzrc, examples/auth-router-provider/README.md, examples/auth-router-provider/index.html, examples/auth-router-provider/package-lock.json, examples/auth-router-provider/package.json, examples/auth-router-provider/src/App.tsx, examples/auth-router-provider/src/auth.ts, examples/auth-router-provider/src/index.css, examples/auth-router-provider/src/main.tsx, examples/auth-router-provider/src/vite-env.d.ts, examples/auth-router-provider/tsconfig.json, examples/auth-router-provider/vite.config.ts, packages/router/router.ts
Fix typo during check in isQueryRouteResponse
=> Fix isQueryRouteResponse

.changeset/stable-use-revalidator.md, packages/react-router-dom/__tests__/concurrent-mode-navigations-test.tsx, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/__tests__/scroll-restoration-test.tsx, packages/react-router/__tests__/data-memory-router-test.tsx, packages/react-router/__tests__/navigate-test.tsx, packages/react-router/__tests__/use-revalidator-test.tsx, packages/react-router/__tests__/utils/MemoryNavigate.tsx, packages/react-router/__tests__/utils/getHtml.ts, packages/react-router/__tests__/utils/tick.ts, packages/react-router/lib/hooks.tsx, packages/router/__tests__/router-test.ts, packages/router/__tests__/utils/createDeferred.ts
Closes https://github.com/remix-run/react-router/issues/10706
I also restructured some unit tests in 28d8eed9004e730b14bbe646706c224097006798.  Began with pulling out `useRevalidator` tests from the larger `data-memory-router-test` and then that led to moving some utils to standalone files and leveraging them instead of copy/pasting them across test suites.
=> Stabilize useRevalidator

.changeset/prompt-add-back-settimeout.md, packages/react-router-dom/index.tsx
Add back in the `setTimeout` that was removed in #10687 since it causes issues with `navigate(-1)`.  This wasn't specifically removed to fix anything in the original bug.  
I wasn't able to get a unit test exposing this though because it seems to be some sort of race between `window.history` and `window.confirm` where the `window.history` revert operation doesn't land until after the `window.confirm`.  This doesn't happen in a unit test with a mocked `window.confirm`.
Closes #10714
=> Add setTimeout back to unstable_usePrompt

contributors.yml, docs/routers/create-browser-router.md, docs/routers/router-provider.md
- Fixes #10725
- Before
- ![image](https://github.com/remix-run/react-router/assets/1915925/b765631a-d519-4999-8958-f8386fbeb61e)
- After
- ![image](https://github.com/remix-run/react-router/assets/1915925/76fa77b5-54f0-44ca-bd0c-e11793873c63)
=> docs(routers/create-browser-router): fix docs-info links

contributors.yml, examples/auth-router-provider/README.md
I think it should be `protected`
=> docs(examples/auth-router-provider): fix typo

.changeset/hash-leading-slash.md, packages/router/__tests__/hash-test.ts, packages/router/history.ts
Closes https://github.com/remix-run/react-router/issues/8638
=> Add defensiveless for malformed hash urls without a leading slash

docs/components/nav-link.md, packages/react-router-dom/__tests__/nav-link-active-test.tsx
Clear up `NavLink` docs confusion on root (`/`) links and the `end` prop from https://github.com/remix-run/react-router/issues/9261#issuecomment-1636704328.  I think the docs were always wrong since before 6.4 this was the behavior, it briefly changed in `6.4.0->6.4.2` until we reverted the underlying change to `NavLink`'s internals.  
See https://github.com/remix-run/react-router/pull/9497#discussion_r1003705842
=> Fix docs on NavLink w.r.t. links to the root route and the end prop

.changeset/x-remix-reload-document.md, contributors.yml, docs/fetch/redirectDocument.md, package.json, packages/react-router-dom-v5-compat/index.ts, packages/react-router-dom/index.tsx, packages/react-router-native/index.tsx, packages/react-router/index.ts, packages/router/__tests__/router-test.ts, packages/router/index.ts, packages/router/router.ts, packages/router/utils.ts
Sometimes we want to force a document reload when redirecting on the same origin. This PR adds support for a custom header (`X-Remix-Reload-Document`), which, when present, tells the router to trigger a document reload when handling a redirect in the browser.
My use-case for this behavior is using remix as an OAuth login app, sharing the same origin with other apps, each served on a separate basename (behind a reverse proxy). On the final stage of the login flow, the response may either fail or succeed. In the case of failure, we return an error message without a page reload and remain within the remix app. In the case of success, we redirect to the target application. Since the result is dynamic, we cannot set `reloadDocument` in the request form. Since the target application is served …
=> Add support to force reload on redirect with `X-Remix-Reload-Document` header

.changeset/form-action-hash.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/index.tsx
Do not include the hash in `useFormAction(undefined)` since it's unavailable on the server and causes a hydration error if included.  The original [issue](https://github.com/remix-run/remix/issues/927) this code was added to fix was only referring to the search params not being included, we shouldn't have added the hash then.  Users can still get a hash by including it in their `action` if needed and can manage hydration issues accordingly.
Closes https://github.com/remix-run/remix/issues/6976
=> Do not include hash in useFormAction() for unspecified actions

.changeset/should-revalidate-action-result-type.md, docs/route/should-revalidate.md, packages/router/__tests__/router-test.ts, packages/router/router.ts, packages/router/utils.ts
Fixes https://github.com/remix-run/remix/issues/5759.
This type issue was picked up if I added type annotations to the args objects in the test suite, so I've also added those as part of this fix.
=> Fix actionResult type on shouldRevalidate args

.changeset/aborted-query-error-message.md, packages/router/__tests__/hash-test.ts, packages/router/__tests__/router-test.ts, packages/router/router.ts
Enhance error messages so folks know which routes they are happening on
=> Add method and URL to aborted query/queryRoute error message

.changeset/export-should-revalidate-args.md, .changeset/short-rocks-buy.md, contributors.yml, packages/react-router-dom-v5-compat/index.ts, packages/react-router-dom/index.tsx, packages/react-router-native/index.tsx, packages/react-router/index.ts, packages/router/index.ts
export `ShouldRevalidateFunctionArgs` so that it can be later exported also in `@remix-run/react`.
This would allow to export `shouldRevalidate` as a non arrow function in Remix
```ts
import type {ShouldRevalidateFunctionArgs} from '@remix-run/react'
export function shouldRevalidate(args: ShouldRevalidateFunctionArgs) {...}
```
=> Export ShouldRevalidateFunctionArgs interface

.changeset/error-response-type.md, packages/react-router-dom/index.tsx, packages/router/index.ts
🤦 Moved too fast and merged https://github.com/remix-run/react-router/pull/10811 without realizing I hadn't pushed up my final tweaked commit.
=> Addendum to ErrorResponse type export

.changeset/remix-v2-prep.md, package.json, packages/router/__tests__/router-test.ts, packages/router/router.ts
Removing some internals needed for the Remix v1 back-compat layer that can be removed in Remix v2.
Current experimental: `0.0.0-experimental-f728258d`
Replaces https://github.com/remix-run/react-router/pull/10211
=> Prepare for Remix v2

.changeset/align-types.md, package.json, packages/react-router-dom-v5-compat/index.ts, packages/react-router-dom/index.tsx, packages/react-router-native/index.tsx, packages/react-router/index.ts, packages/react-router/lib/hooks.tsx, packages/router/history.ts, packages/router/index.ts, packages/router/router.ts, packages/router/utils.ts
Adding TS generics to support https://github.com/remix-run/remix/pull/7319
=> Add generics for Remix type enhancements

.changeset/gold-ghosts-draw.md, packages/router/history.ts, packages/router/utils.ts
Follow-up of @brophdawg11's #10843 for the reasons mentioned in my remark (see https://github.com/remix-run/react-router/pull/10843#pullrequestreview-1611895961)
> In the light of named tuple elements, I've seen something passing by to do the same for generic elements as well, so I think it would be better to have long names instead
> 
> https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#named-and-anonymous-tuple-elements
=> chore(router): update generic names

.changeset/soft-forks-cough.md, contributors.yml, packages/react-router-dom/__tests__/scroll-restoration-test.tsx, packages/react-router-dom/index.tsx
As discussed in #10842
This writes a descriptive warning to the console if `sessionStorage` is unavailable for any reason, but allows the scroll saving/resetting to continue working as much as possible (until the user leaves the page we still have the scroll positions in a global variable)
It also retro-fits a "happy-path" test for `ScrollRestoration` to confirm the scroll position is correctly reset and no warnings are printed.
Interestingly, writing the test turned up a behaviour quirk where the default `getKey` implementation fails to save the scroll position for the first page viewed (since its `location.key` is `default` on the first visit). I haven't attempted to fix this; I'm not even sure if it's a real issue outside the test environment.
=> Handle case when session storage is blocked

.changeset/error-response-type.md, contributors.yml, packages/router/utils.ts
There is problem in current declaration of `ErrorResponse`: the private field leaks to the public contract. So `ErrorResponse` type behaves very strange on usage (see [playground](https://www.typescriptlang.org/play?noUncheckedIndexedAccess=true&exactOptionalPropertyTypes=true&ts=5.1.6#code/JYWwDg9gTgLgBAbwKJStASgUwM6QHbaYC+cAZmiHAEQACUmIwAHgLRQCueA9GuzJlCoAoEQGMIBePVwTCALjgo0ULDIKY4AXkRC4euNhgBDGO2wKALACYANLv2GTZgCqYmMBVX6Gqd-XAATEyMFBCIhIiA)).
I propose to simplify the declaration of `ErrorResponse` and declare it's public interface obviously.
=> Specify `ErrorResponse` as interface to provide obvious contract

contributors.yml, docs/route/action.md, docs/route/error-element.md
Related issue: #10905 
The vast majority of the warnings use `<docs-warning>` so I went with that.
=> [Docs]: Use consistent feature warnings

.changeset/support-optional-path-segments-in-match-path.md, contributors.yml, package.json, packages/react-router/__tests__/matchPath-test.tsx, packages/router/utils.ts
Adds support for optional path segments in `matchPath`. Resolves #9862
=> Support optional path segments in `matchPath`

.changeset/splat-form-action.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/index.tsx
Reverting because this had some unintended impacts on `useFormAction` behavior from a layout route when using dynamic params.  Will re-open a new PR with a proper fix.
This reverts #10933 (commit 908a40a25382612b869638664e19a4aa7a977e53)
Reopens: #10922
=> Revert "Ensure Form contains splat portion of pathname when no action is specified (#10933)"

.changeset/fetcher-key.md, .changeset/fix-get-delete-fetcher-types.md, .changeset/form-navigate-false.md, docs/components/form.md, docs/hooks/use-fetcher.md, docs/hooks/use-submit.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/dom.ts, packages/react-router-dom/index.tsx, packages/router/__tests__/utils/utils.ts, packages/router/router.ts
Add `useFetcher({ key })` and `<Form navigate={false} fetcherKey={key}>` APIs
* Implements the updated version of https://github.com/remix-run/remix/discussions/7698
* 1st of 3 PRs to supersede https://github.com/remix-run/react-router/pull/10945
=> Add useFetcher(key) and <Form navigate={false}>

.changeset/fetcher-cleanup.md, .changeset/fix-router-future-prop.md, docs/guides/api-development-strategy.md, examples/data-router/src/app.tsx, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/index.tsx, packages/react-router/lib/components.tsx, packages/router/router.ts
Dependent on https://github.com/remix-run/react-router/pull/10961
Implemented the new fetcher persist/cleanup behavior behind a new `future.v7_fetcherPersist` flag in the router.
* Implements the updated version of https://github.com/remix-run/remix/discussions/7698
* 3rd and final PR to supersede https://github.com/remix-run/react-router/pull/10945
=> Add future.v7_fetcherPersist flag

.changeset/fetcher-cleanup.md, .changeset/fetcher-ref-count.md, .changeset/fix-router-future-prop.md, package.json, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/index.tsx, packages/react-router-dom/server.tsx, packages/router/__tests__/view-transition-test.ts, packages/router/router.ts
When `v7_fetcherPersist` is enabled we open up some new code flows for fetcher result processing that we need to consider.
* Previously, when fetchers were aborted on unmount, we would end up ignoring all results from those unmounted fetchers via `if (request.signal.aborted)`
* Now that we don't abort the fetchers immediately (when the flag is enabled) we need to determine if we should process the fetcher result or not
We do this by lifting the ref counting up into the router so it knows if any instances of a given fetcher key are still mounted in the UI. 
* If no instances are mounted at the time the fetcher completes, we don't process the result - like same as before when we aborted on unmount
* If _some_ instances are still mounted (meaning some other new component picked up the …
=> Updates for v7_fetcherPersist post-processing logic

.changeset/fix-resolve-path.md, .changeset/splat-form-action.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/__tests__/link-href-test.tsx, packages/react-router-dom/index.tsx, packages/react-router/__tests__/useResolvedPath-test.tsx, packages/react-router/lib/hooks.tsx
Second shot at a fix for #10922
Originally fixed in #10933 and reverted in #10965 due to issues.
The main issue seems to boil down to `useResolvedPath`'s longstanding behavior of using `pathnameBase` to construct the current route hierarchy.  `pathnameBase` never contains the splat - but `pathname` does.
This breaks a few existing uni tests that rely on the existing behavior - need to review with @mjackson.
=> Fix issues with useFormAction/useResolvedPath for dot paths in param/splat routes

.changeset/flush-sync-router.md, .changeset/flush-sync.md, docs/hooks/use-fetcher.md, docs/hooks/use-navigate.md, docs/hooks/use-submit.md, package.json, packages/react-router-dom/__tests__/flush-sync-navigations-test.tsx, packages/react-router-dom/dom.ts, packages/react-router-dom/index.tsx, packages/react-router/lib/context.ts, packages/router/__tests__/flush-sync-test.ts, packages/router/__tests__/utils/data-router-setup.ts, packages/router/router.ts
Closes https://github.com/remix-run/react-router/issues/11003
**Todo:**
=> Add unstable_flushSync option

.changeset/fix-relative-path.md, package.json, packages/router/__tests__/path-resolution-test.ts, packages/router/router.ts, packages/router/utils.ts
=> Fix relative=path issue

.changeset/changing-fetcher-key.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/index.tsx
=> Fix bug with changing fetcher key in a mounted component

.changeset/fix-action-data.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router/__tests__/data-memory-router-test.tsx, packages/react-router/lib/hooks.tsx
Closes #11022 
This has been a bug since the move from TransitionManager (https://github.com/remix-run/remix/blob/%40remix-run/vercel%401.7.6/packages/remix-react/components.tsx#L1421).  `useActionData` should behave the same as `useLoaderData` in this regard.
=> Fix useActionData so it only returns the contextual route action data

.changeset/form-action-index.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/index.tsx
=> Fix useFormAction inheriting ?index param from child route action submission

.changeset/resolve-to-splat.md, package.json, packages/react-router/lib/components.tsx, packages/react-router/lib/hooks.tsx, packages/router/__tests__/path-resolution-test.ts, packages/router/index.ts, packages/router/router.ts, packages/router/utils.ts
Follow up to #10983 to handle other code paths calling `getPathContributingMatches`/`resolveTo`
Closes #11038
=> Fix other code paths for resolveTo from a splat route

.changeset/catch-unwrap-error.md, packages/router/__tests__/navigation-test.ts, packages/router/router.ts
=> Catch errors when trying to unwrap responses

.changeset/handle-falsy-errors.md, packages/react-router/__tests__/data-memory-router-test.tsx, packages/react-router/lib/hooks.tsx
=> Properly handle falsy error values in ErrorBoundary's

.changeset/relative-splat-path.md, docs/components/form.md, docs/components/link.md, docs/guides/api-development-strategy.md, docs/hooks/use-href.md, docs/hooks/use-navigate.md, docs/hooks/use-resolved-path.md, docs/hooks/use-submit.md, package.json, packages/react-router-dom-v5-compat/index.ts, packages/react-router-dom/index.tsx, packages/react-router-dom/server.tsx, packages/react-router-native/index.tsx, packages/react-router/__tests__/useResolvedPath-test.tsx, packages/react-router/lib/components.tsx, packages/react-router/lib/context.ts, packages/react-router/lib/hooks.tsx, packages/router/index.ts, packages/router/router.ts, packages/router/utils.ts
Re-implement the bug fix from #10983 behind a `future.v7_relativeSplatPath` flag because we determined that a lot of folks were relying on the buggy behavior (see #11052 and #11078).
Usage:
```js
/**** Data router ****/
let router = createBrowserRouter(routes, { 
future: { v7_relativeSplatPath: true }
});
<RouterProvider router={router} />
/**** Non-Data Router ****/
<BrowserRouter future={{ v7_relativeSplatPath: true }}>
/**** Data Router SSR ****/
let { query, dataRoutes } = createStaticHandler(routes, {
future: { v7_relativeSplatPath: true },
});
let router = createStaticRouter(dataRoutes, context, {
future: { v7_relativeSplatPath: true },
});
<StaticRouterProvider router={router} context={context} />
/**** Non-Data Router SSR ****/
<StaticRouter future={{ v7_relativeSplatPath: true …
```
=> Add future.v7_relativeSplatPath flag

.changeset/silver-teachers-doubt.md, package.json, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/router/__tests__/fetchers-test.ts, packages/router/__tests__/utils/data-router-setup.ts, packages/router/router.ts
=> Allow persisted fetchers unmounted during submit to revalidate

contributors.yml, docs/route/error-element.md
This PR applies minor grammatical changes to the docs for `errorElement`(https://reactrouter.com/en/main/route/error-element).
=> docs: Add minor grammatical changes to `errorElement` docs for better readability

contributors.yml, docs/hooks/use-view-transition-state.md
edited the `unstable_useViewTransitionState` document page for better correctness (correcting missing href and idx) of code and align closer with the examples under Components -> link -> unstable_viewtransition
link document referring to: https://remix.run/docs/en/main/components/link#unstable_viewtransition
somewhat new to open source contribution, let me know if I have done anything incorrectly
=> doc edited for unstable_useViewTransitionState

.changeset/lazy-partial-hydration.md, packages/react-router-dom/__tests__/partial-hydration-test.tsx, packages/react-router/lib/hooks.tsx, packages/router/__tests__/lazy-test.ts, packages/router/router.ts
=> Fix issues with partial hydration combined with route.lazy

contributors.yml, docs/route/loader.md
hyperlink on the text "Server-Side Rendering" is redirecting to not found page. Removing .md from the link redirects to the correct route.
=> documentation fix: "Server-Side Rendering" link in loader.md redirecting to 404

.changeset/dynamic-param-dash.md, packages/react-router/__tests__/generatePath-test.tsx, packages/react-router/__tests__/path-matching-test.tsx, packages/router/utils.ts
Fix bug where dashes were not picked up as part of the dynamic parameter name:
```js
// A URL `/whatever` should match with `useParams()["foo-bar"] === "whatever"`
let routes = { path: ":foo-bar" };
```
Without this, the portion after the dash was being incorrectly scored/counted as a static segment, and we only support dynamic parameters as the full URL (https://github.com/remix-run/react-router/pull/9506)
Closes #11159
=> Pick up dashes in dynamic parameter names

.changeset/fetcher-key-useid.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/index.tsx
Still digging but for some reason the `setState` during render of `useFetcher` to assign the internal unique incrementing `key` causes `useId` to return unstable values on client and server.  The "proper" fix for React 18 is to use `useId` to generate fetcher keys and avoid the incrementing key hack, but we need to support React 17 in React Router as well. 
We can feature detect `useId` and use it when available, and fall back on the current approach for React 17 and below.
Closes https://github.com/remix-run/remix/issues/8393
=> Leverage useId for internal fetcher keys when available

.changeset/unlucky-planets-repeat.md, packages/router/__tests__/navigation-test.ts, packages/router/router.ts
=> Do not attempt to deserialize empty json responses

.changeset/brave-pillows-juggle.md, packages/react-router-dom/__tests__/nav-link-active-test.tsx, packages/react-router-dom/index.tsx
=> Fix NavLink isPending with a basename

.changeset/static-context-error-status-code.md, packages/router/__tests__/ssr-test.ts, packages/router/router.ts, yarn.lock
This will allow us to respect status codes from thrown `Response`'s in Remix `entry.server`
=> Respect the ErrorResponse status code if passed to getStaticContextFromError

contributors.yml, docs/guides/ssr.md, examples/ssr-data-router/server.js, examples/ssr-data-router/src/entry.server.tsx
=> docs: listen for close event on response, not request

contributors.yml, docs/hooks/use-outlet-context.md
Docs: Update context provider link in useOutletContext section
This change updates the markdown link for the context provider reference to point directly to the `createContext` documentation on React's new site, ensuring users have access to the latest information.
Let me know if you prefer an update to another of theirs URL, I felt that the createContext was more direct connected to what the docs meant, but it could also be https://react.dev/learn/passing-data-deeply-with-context if you prefer to go to a more generic context page.
=> Update context provider link to point to React's new documentation site

.changeset/partial-hydration-errors.md, packages/react-router-dom/__tests__/partial-hydration-test.tsx, packages/router/router.ts
Closes https://github.com/remix-run/remix/issues/8889
=> Preserve hydrated errors during partial hydration

.changeset/partial-hydration-bubbled-error.md, packages/router/__tests__/route-fallback-test.ts, packages/router/router.ts
Came across this during the single fetch work, where if a child loader threw on SSR and bubbled to the parent, we'd see that the child route had a loader and no `loaderData`/`errors` on the client and think we needed to re-run it
=> Don't run loaders below the boundary during partial hydration

contributors.yml, docs/hooks/use-navigate.md
the top of the code block specifies
```js
// Assume the current URL is https://remix.run/docs/en/main/start/quickstart
```
but the expected output is based on the current URL being `https://remix.run/docs/en/main/start/future-flags`.
=> docs: Fix use-navigate.md example output in section on using useLocation with the URL constructor

docs/start/changelog.md
Just like the Remix docs have a changelog, now so will the react router docs!
Note: this is just a placeholder, [we'll render the actual CHANGELOG file](https://github.com/remix-run/react-router-website/issues/94)
=> docs:add changelog doc

.changeset/funny-tips-beg.md, .changeset/slow-flies-help.md, .changeset/static-query-flags.md, CHANGELOG.md, package.json, packages/router/__tests__/ssr-test.ts, packages/router/router.ts
We can implement this behavior in Remix's `dataStrategy` implementation now that it's request specific
=> Remove flags

integration/action-test.ts, integration/catch-boundary-data-test.ts, integration/catch-boundary-test.ts, integration/client-data-test.ts, integration/defer-loader-test.ts, integration/defer-test.ts, integration/error-boundary-test.ts, integration/error-boundary-v2-test.ts, integration/error-data-request-test.ts, integration/error-sanitization-test.ts, integration/fetcher-layout-test.ts, integration/fetcher-test.ts, integration/file-uploads-test.ts, integration/form-data-test.ts, integration/form-test.ts, integration/loader-test.ts, integration/navigation-state-test.ts, integration/playwright.config.ts, integration/redirects-test.ts, integration/revalidate-test.ts, integration/set-cookie-revalidation-test.ts
I've opted to skip multi-fetch tests for now rather than deleting them to keep the git diff to a minimum while we're still migrating.
This PR:
- Skips 301 additional tests.
- Speeds up the integration tests in CI by ~2m30s.
- Fixes some flakiness with `client-data-test`.
=> Skip multi-fetch tests, enable passing tests

integration/playwright.config.ts, packages/react-router-dom/index.tsx, packages/react-router-dom/ssr/errors.ts
Turns out the logic differed slightly between `react-router-dom` and `@remix-run/react` and that Remix serializes stack traces in development mode, so we need to ensure that stack traces are picked up when deserializing errors.
=> Fix `error-sanitization-test`

integration/playwright.config.ts, integration/vite-css-test.ts
Vanilla Extract internally has checks for the `remix` Vite plugin. Until that's updated, we need to manually enable the `emitCssInSsr` option which is normally enabled internally when the `remix` plugin is detected. Once Vanilla Extract is patched, we can update to the latest version and remove the `emitCssInSsr` option since it's now the default behaviour and no longer configurable.
=> Fix `vite-css-test`

packages/react-router-dom/index.tsx, packages/react-router-dom/ssr/errors.ts
Revert the `process.env` check from https://github.com/remix-run/react-router/pull/11420 since we don't 100% handle those in our current build configs and just use the Remix implementation directly for the Remix codepath.  Eventually I hope the Remix implementation goes away in a single-fetch only world...
=> Update error sanitization logic

package.json, packages/react-router-dom-v5-compat/rollup.config.js, packages/react-router-dom/rollup.config.js, packages/react-router-native/rollup.config.js, packages/react-router/rollup.config.js, packages/remix-dev/rollup.config.js, packages/remix-express/rollup.config.js, packages/remix-node/rollup.config.js, packages/remix-serve/rollup.config.js, packages/remix-server-runtime/rollup.config.js, packages/remix-testing/rollup.config.js, packages/router/rollup.config.js, pnpm-lock.yaml, rollup.utils.js
This addresses a couple of issues in the Rollup build on Windows:
- `rollup-plugin-extensions` doesn't resolve paths correctly on Windows, so we need to replace it with `@rollup/plugin-node-resolve`.
- `rollup-plugin-copy` doesn't support absolute paths on Windows.
=> Fix Windows Rollup build

packages/react-router-dom-v5-compat/rollup.config.js, packages/react-router-dom/rollup.config.js, packages/react-router-native/rollup.config.js, packages/react-router/rollup.config.js, packages/remix-dev/rollup.config.js, packages/remix-express/rollup.config.js, packages/remix-node/rollup.config.js, packages/remix-serve/rollup.config.js, packages/remix-server-runtime/rollup.config.js, packages/remix-testing/rollup.config.js, packages/router/rollup.config.js, rollup.utils.js
When running `pnpm watch`, the Rollup process exits whenever there's a syntax or type error. Turns out this is due to the TypeScript plugin's `noEmitOnError` option being enabled. We still want this enabled when running `pnpm build`, so I'm using the Rollup's `ROLLUP_WATCH` environment variable to disable `noEmitOnError` whenever we're in watch mode.
=> Handle TypeScript errors in watch mode

packages/react-router-dom/index.tsx
The `router` prop was still being marked as required.
=> Fix `router` prop type on `RouterProvider`

.github/workflows/test.yml, integration/helpers/cf-template/tsconfig.json, integration/helpers/node-template/package.json, integration/helpers/node-template/tsconfig.json, integration/helpers/vite-cloudflare-template/package.json, integration/helpers/vite-cloudflare-template/tsconfig.json, integration/helpers/vite-template/package.json, integration/helpers/vite-template/tsconfig.json, integration/package.json, package.json, packages/remix-dev/package.json, pnpm-lock.yaml
This ensures tests, test helpers and playgrounds are type checked since we're currently only checking types during the Rollup build for code in `packages`.
=> Add new `typecheck` script to `test` workflow

.changeset/create-remix-router.md, integration/vite-css-test.ts, integration/vite-spa-mode-test.ts, packages/react-router-dom/__tests__/ssr/components-test.tsx, packages/react-router-dom/index.tsx, packages/react-router-dom/ssr/browser.tsx, packages/remix-dev/config/defaults/entry.client.tsx, playground/compiler-express/app/entry.client.tsx, playground/compiler-spa/app/entry.client.tsx, playground/compiler/app/entry.client.tsx
Avoid bundle bloat by reversing our idea of just doing all the auto-hydration in `RouterProvider`, since that means folks using `RouterProvider` in a RR SPA are paying the cost for all the Remix hydration code.  Instead this is now effectively going back to the RemixBrowser approach and calling it `HydratedRouter` (name not final 😉 )
=> Extract remix logic out of RouterProvider into HydratedRouter

integration/error-boundary-v2-test.ts, integration/vite-dot-server-test.ts, integration/vite-spa-mode-test.ts, packages/remix-dev/CHANGELOG.md, packages/remix-dev/vite/plugin.ts, packages/remix-dev/vite/styles.ts, packages/remix-express/CHANGELOG.md, packages/remix-node/CHANGELOG.md, packages/remix-serve/CHANGELOG.md, packages/remix-server-runtime/CHANGELOG.md, packages/remix-server-runtime/routeModules.ts, packages/remix-server-runtime/routes.ts, packages/remix-server-runtime/single-fetch.ts, packages/remix-testing/CHANGELOG.md
We originally migrated remix packages to the `v7` as of `remix@2.9.0-pre.0`.  Now that `2.9.0` is released and merged into `dev` this brings over all subsequent changes up to the merge commit of `release-next -> dev` (SHA 470bb1c2e4e6e15cbcddc689b857f19cdd03bca8).
Patches generated via (on the `dev` branch):
```sh
git format-patch remix@2.9.0-pre.0..HEAD -o ~/Desktop/patches integration packages/remix-dev packages/remix-express packages/remix-node packages/remix-serve packages/remix-server-runtime packages/remix-testing ':!*/package.json'
```
And applied via:
```sh
git am ~/Desktop/patches/*.patch
```
A few patches required manual intervention:
**Vite critical CSS resolution**
I made this change manually in this branch.
Fix Vite critical CSS resolution for route files with absolute paths …
=> Apply patches from remix 2.9.0

packages/remix-dev/vite/plugin.ts
Replay of https://github.com/remix-run/remix/pull/9301.
=> Only add RR packages to `ssr.external` in RR repo

contributors.yml, docs/upgrading/v6-data.md
In the docs, examples were using `createBrowserRouter` with the `component` prop, which looks to be incorrect. If I'm not mistaken, it should be `element`.
=> Fix v6 data API migration guideline docs

packages/remix-dev/vite/plugin.ts
Replay of https://github.com/remix-run/remix/pull/9305.
=> Fix `dest already exists` error during Vite build

.changeset/little-ghosts-give.md, packages/react-router-dom/server.tsx, packages/react-router-dom/tsconfig.json
=> Fix react-router-dom/server index.ts import from pnpm migration

integration/vite-route-added-test.ts
This test is consistently failing in Safari due to its aggressive caching causing it to hold onto an outdated browser manifest. This test was already flaky and for some reason seems to have gotten worse. I tried rolling back to a previously working state and I'm still seeing the same issue. Until we figure out how to fix this, I'm skipping this test in Safari so that it doesn't hold up CI.
=> Skip `vite-route-added-test` in Safari

.changeset/clever-pumas-arrive.md, packages/router/__tests__/ssr-test.ts, packages/router/router.ts
Needed so we can make `response` non-optional for resource routes in https://github.com/remix-run/remix/issues/9314
=> Support unstable_dataStrategy on staticHandler.queryRoute

.changeset/smooth-sloths-exist.md, contributors.yml, packages/react-router-dom-v5-compat/lib/components.tsx, packages/react-router-dom/__tests__/static-location-test.tsx, packages/react-router-dom/server.tsx
Fixes https://github.com/remix-run/react-router/issues/11448
I fixed location's state property value like this.
```ts
let location: Location = {
pathname: locationProp.pathname || "/",
search: locationProp.search || "",
hash: locationProp.hash || "",
state: locationProp.state ?? null, // fixed
key: locationProp.key || "default",
};
```
Now, useLocation receive 0 instead of null when state is set to 0.
=> Fix useLocation to receive 0 instead of null when state is set to 0

packages/remix-dev/vite/plugin.ts
Replay of https://github.com/remix-run/remix/pull/9395.
=> Clean redundant `?client-route=1` usage in dev

.changeset/good-donkeys-kiss.md, contributors.yml, packages/react-router-dom/index.tsx
Cherry picked from https://github.com/remix-run/react-router/pull/11528 for release-next
=> Add defensive window.document check when checking for startViewTransition

contributors.yml, docs/routers/create-browser-router.md
Replaced a small typo I noticed while copy pasting the example.
=> docs: Replace `.` typo with `;`

integration/vite-prerender-test.ts
The order of the array returned by `fs.readdirSync` differs on Windows, so we need to sort it before asserting its contents.
=> Fix prerender test on Windows

.changeset/remove-manifest-option.md, .changeset/vite-manifest-location.md, integration/vite-manifests-test.ts, integration/vite-prerender-test.ts, integration/vite-presets-test.ts, integration/vite-server-bundles-test.ts, integration/vite-spa-mode-test.ts, packages/remix-dev/config.ts, packages/remix-dev/vite/build.ts
This simplifies the build output and makes it closer to your standard Vite output by making a couple of changes:
1) We now leave Vite manifests in their default location, e.g. `build/client/.vite/manifest.json` and `build/server/.vite/manifest.json` instead of `build/.vite/client-manifest.json` and `build/.vite/server-manifest.json`. Note that these Vite manifests are deleted unless consumers explicitly enable them via `build: { manifest: true }` in their Vite config. This means that the build output is now much closer to what you'd expect from a typical Vite project.
2) We no longer have a `manifest` option to write a React Router build manifest to disk under `build/.react-router/manifest.json`. This option was originally added in Remix for Vercel so that they could enable it in their …
=> Clean build manifest output

.changeset/remove-build-end-public-path.md, integration/vite-presets-test.ts, packages/remix-dev/config.ts, packages/remix-dev/vite/plugin.ts
The resolved `reactRouterConfig` object passed to the `buildEnd` hook should only contain properties present on the user-provided React Router config object, whereas the `publicPath` property is a Vite concern. This is just a minor tidy up to keep this API scoped to React Router. If anyone needs the public path in the build end hook, we should instead be passing in the resolved Vite config rather than individual properties.
=> Remove `publicPath` from resolved config

contributors.yml, docs/start/tutorial.md
An unfortunate truth is that several people read the documentation sparsely and will copy/paste what is given to them -- myself included! This small change, inspired from...
- https://github.com/remix-run/react-router/discussions/9808
- https://github.com/remix-run/react-router/issues/11099
- https://github.com/remix-run/react-router/pull/11428
... will help clarify to users that react-router-dom _does not depend on_ these dependencies, which have known vulnerabilities.
=> Clarify necessary dependencies in tutorial

contributors.yml, docs/routers/picking-a-router.md
the useBlocker hook only works with a data route, so the hook should be present in this list.
=> docs: added useBlocker to the data apis

contributors.yml, docs/start/concepts.md
In the entry app, Rendering section (lines 513-536) <Contact /> component is used. But on the line 571, <ContactForm /> component is used, for the same path. It is a typo, so i have changed it to <Contact />
=> Fixed a typo in concepts.md

contributors.yml, docs/start/overview.md
Hi! I think we don't need highlight in line 42:
=> fix diff highlight

.changeset/gorgeous-geese-sit.md, packages/react-router-dom/dom.ts, packages/react-router-dom/index.tsx, packages/router/__tests__/navigation-test.ts
Fixes type issue from https://github.com/remix-run/react-router/issues/11627
=> Fix fetcher.submit types

contributors.yml, docs/route/route.md
In the docs, the type of `RouteObject.children` appears to be incorrect [based on the TS definition](https://github.com/remix-run/react-router/blob/5d66dbdbc8edf1d9c3a4d9c9d84073d046b5785b/packages/react-router/lib/context.ts#L49). This fixes that.
=> Fix type definition of `Route.children`

.changeset/six-pianos-serve.md, contributors.yml, packages/react-router-dom/index.tsx
Documentation tells us we can use callbacks to utilize various NavLink states
```js
import { NavLink } from "react-router-dom";
<NavLink
to="/messages"
className={({ isActive, isPending }) =>
isPending ? "pending" : isActive ? "active" : ""
}
>
Messages
</NavLink>;
```
But then restricts us by not letting use type annotation for it
```js
import { NavLink } from 'react-router-dom';
import { useCallback } from 'react';
export const Header = () => {
const navLinkClassName = useCallback(
({ isActive, isPending }: NavLinkRenderProps) => // this is impossible right now because type is not exported
isPending ? 'text-gray-500' : isActive ? 'text-orange-800' : '',
[],
);
return (
<>
<header className='h-10 w-full bg-amber-100'>
<nav className='p-2'>
<ul className='flex items-center gap-5'>
<li> …
```
=> feat: export type NavLinkRenderProps

.changeset/fluffy-ducks-try.md, packages/react-router/__tests__/router/router-test.ts, packages/react-router/__tests__/router/ssr-test.ts, packages/react-router/lib/router/router.ts
I didn't touch `DataFunctionReturnValue` which currently rules out returning `undefined` since that should all be removed once we land the new `defineRoute` stuff @pcattori  is working on
=> Allow returning undefined from actions and loaders

.changeset/thin-nails-turn.md, packages/react-router/__tests__/data-memory-router-test.tsx, packages/react-router/__tests__/data-router-no-dom-test.tsx, packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/dom/lib.tsx, packages/react-router/lib/router/router.ts
We used to have 2 of these since we kept DOM-specifics in `react-router-dom` (`document.startViewTransition`, `ReactDOM.flushSync`) but now we just need the one and it can be defensive against the lack of `window`/`document`
=> Remove duplicate RouterProvider implementations

packages/react-router/index.ts, packages/react-router/lib/router/define-route.ts
All types for parent route matches have been type cases under-the-hood. Previous attempts let you provide types for `matches` array, but then you'd have to pluck out a specific item from that and do more type casts. So instead, now `matches` is a wide type (array of matches each with `unknown` data) and we provide `Match` and `MetaMatch` type helpers to narrow down the type once you've found the match you wanted.
```ts
import { defineRoute, MetaMatch } from "react-router"
import type blahRoute from "./blah"
export default defineRoute({
meta({ matches }) {
let match = matches.find(id === "routes/blah") as MetaMatch<typeof blahRoute>
console.log(match.data)
//                ^? types inferred from `routes/blah`'s loader
}
})
```
=> defineRoute: type helpers for `meta({matches})` and `useMatches`

.github/workflows/test.yml, package.json, pnpm-lock.yaml
This check as it stands is not helpful in the new v7 state of RR since our minified UMD bundles are much larger now that they incorporate the router, the DOM APIs, the Remix APIs etc.  This is just a barrier to merging v7 PRs at the moment.
Once v7 stabilizes a bit more we can consider looking into re-adding a check of this type, but it should not be simply a minified file size check but instead be some form of check against a bundled/treeshaken application.
=> Remove bundle size check

.changeset/fair-cheetahs-hope.md, packages/react-router-dom/index.ts, packages/react-router/__tests__/router/fetchers-test.ts, packages/react-router/__tests__/router/navigation-test.ts, packages/react-router/__tests__/router/revalidate-test.ts, packages/react-router/__tests__/router/router-test.ts, packages/react-router/__tests__/router/should-revalidate-test.ts, packages/react-router/__tests__/router/submission-test.ts, packages/react-router/__tests__/router/utils/data-router-setup.ts, packages/react-router/index.ts, packages/react-router/lib/dom/dom.ts, packages/react-router/lib/dom/server.tsx, packages/react-router/lib/dom/ssr/browser.tsx, packages/react-router/lib/router/index.ts, packages/react-router/lib/router/router.ts, packages/react-router/lib/router/utils.ts
=> Remove future.v7_normalizeFormMethod

integration/fog-of-war-test.ts, integration/link-test.ts, integration/prefetch-test.ts, packages/react-router/__tests__/dom/data-browser-router-test.tsx, packages/react-router/__tests__/dom/data-static-router-test.tsx, packages/react-router/__tests__/dom/link-push-test.tsx, packages/react-router/__tests__/dom/special-characters-test.tsx, packages/react-router/__tests__/dom/trailing-slashes-test.tsx, packages/react-router/lib/dom/lib.tsx, packages/react-router/lib/dom/ssr/browser.tsx, packages/react-router/lib/dom/ssr/components.tsx, packages/react-router/lib/dom/ssr/fog-of-war.ts, packages/react-router/lib/dom/ssr/routes.tsx, packages/react-router/lib/server-runtime/server.ts
=> Migrate Fog of War from Remix 2.10.0

playground/compiler-express/package.json, playground/compiler-spa/package.json, playground/compiler/package.json, scripts/playground.js
Our playgrounds aren't currently getting the binaries without a specific `pnpm install react-router` step so added that  as an up-front `setup` command
=> Fix playgrounds not installing binaries

packages/react-router-dev/bin.js, packages/react-router-dev/package.json, packages/react-router-dev/rollup.config.js, packages/react-router-serve/bin.js, packages/react-router-serve/package.json, packages/react-router-serve/rollup.config.js, playground/compiler-express/package.json, playground/compiler-spa/package.json, playground/compiler/package.json, rollup.utils.js, scripts/playground.js
Reverts https://github.com/remix-run/react-router/pull/11747.
When running `pnpm install` within this repo for the first time, you see multiple variations of the following error:
```
 WARN  Failed to create bin at /path/to/react-router/playground/compiler/node_modules/.bin/react-router. ENOENT: no such file or directory, open '/path/to/react-router/packages/react-router-dev/dist/cli.js'
```
 
 This is because pnpm is trying to set up package bins before the build step has been run, so the configured bin files don't exist yet.
 
 One way to fix this is to run the build step in the `postinstall` hook, but this is pretty heavy handed and will slow down CI runs. It'll also incorrectly mark Rollup build errors as a failed install step.
 
Instead, the leaner alternative in this PR is to provide …
=> Fix local package bins

integration/helpers/node-template/package.json, integration/helpers/vite-template/package.json
This is a minor test clean up in light of https://github.com/remix-run/react-router/pull/11763. Since package bins are always linked, we no longer need to reach into packages to use their bin scripts.
=> Use linked package bins in test templates

packages/react-router-dev/config.ts, packages/react-router-dev/package.json, packages/react-router-dev/vite/plugin.ts, pnpm-lock.yaml
This gives us lower level control over the terminal output compared to using `ssrLoadModule`.
=> Execute routes.ts with vite-node

.changeset/clever-emus-leave.md, packages/router/__tests__/lazy-discovery-test.ts, packages/router/router.ts
=> Fix bubbling of errors thrown from unstable_patchRoutesOnMiss

.changeset/big-trainers-cough.md, packages/react-router-dom/__tests__/special-characters-test.tsx, packages/react-router/lib/hooks.tsx, packages/router/index.ts, packages/router/utils.ts
Closes https://github.com/remix-run/react-router/issues/11777
=> Fix useMatch undecoded params

.changeset/gold-snakes-build.md, docs/route/should-revalidate.md, docs/routers/create-browser-router.md, docs/upgrading/future.md, packages/react-router-dom/server.tsx, packages/router/__tests__/fetchers-test.ts, packages/router/__tests__/should-revalidate-test.ts, packages/router/router.ts, packages/router/utils.ts
Stabilize the RR `unstable_skipActionErrorRevalidation` flag.  This is used by single fetch but it's functionality is independent of single fetch and fairly straightforward so I don't see any reason to delay stabilizing it until single fetch stabilizes.
Functionally, when this is enabled, actions that return/throw with a 4xx/5xx don't automatically trigger revalidation - see https://remix.run/docs/en/main/guides/single-fetch#revalidations
=> Stabilize future.unstable_skipActionErrorRevalidation

.changeset/five-bottles-press.md, contributors.yml, packages/router/router.ts, packages/router/utils.ts
This PR adds the ability to `REPLACE` the current history entry rather than always using `POP` when redirecting in route loaders.
This is useful for how we manage navigation in [Spacedrive](https://github.com/spacedriveapp/spacedrive):
- Our desktop app supports having multiple tabs, with each tab being its own `MemoryRouter` instance and history stack
- `index` routes contain loaders for going from `/` to `/{libraryId}` to `/{libraryId}/{defaultSegment}`, where `libraryId` is loaded asynchronously and `defaultSegment` is determined based on the result of another asynchronous operation
- loaders are used so we can rely on `Suspense` to show the current tab until the new tab's redirects are complete, since loaders + their redirects all run in a single transition
- The traversal of those …
=> feat: add replace option to loader redirect function

.changeset/sour-dryers-walk.md, package.json, packages/react-router-dom/__tests__/partial-hydration-test.tsx, packages/react-router/lib/hooks.tsx, packages/router/__tests__/lazy-discovery-test.ts, packages/router/router.ts
Closes https://github.com/remix-run/react-router/issues/11812
=> Fix hydration behavior of patchRoutesOnMiss when v7_partialHydration is enabled

contributors.yml, docs/start/tutorial.md
Fixing typo in the docs from `it's` to the possessive form `its`.
=> docs: fix typo

packages/react-router-dev/package.json, packages/react-router-dev/vite/remove-exports-test.ts, packages/react-router-dev/vite/remove-exports.ts, pnpm-lock.yaml
This migrates to @pcattori's awesome [babel-dead-code-elimination](https://github.com/pcattori/babel-dead-code-elimination) library. This means that our code no longer needs to deal with any dead code elimination, and instead only needs to focus on removing exports.
While migrating, I noticed a number of scenarios we didn't have tests for, so I've fleshed out the test suite a bit more.
I also noticed that we didn't handle removal of destructured exports (e.g. `export { loader } = { loader: () => { ... } }`, but since it's an edge case that's not trivial to support, and since the current behaviour is that they're not removed, it's better for us to simply throw an error if any exports to be removed are destructured.
=> Migrate to babel-dead-code-elimination

.changeset/cyan-bobcats-notice.md, packages/router/__tests__/lazy-discovery-test.ts, packages/router/router.ts
This PR updates the fog of war implementation to treat dynamic-param (slug) routes the same way we treat splat routes and call `unstable_patchRotuesOnMiss` if we match a slug route just in case there exists a higher-scoring static route we don't yet know about.
TODO: 
* going to do this in a separate PR
Closes https://github.com/remix-run/remix/issues/9799
=> Call patchRoutesOnMiss when matching slug routes in case there exist higher scoring static routes

.changeset/silver-coats-work.md, docs/routers/create-browser-router.md, packages/react-router-dom/__tests__/partial-hydration-test.tsx, packages/react-router-dom/index.tsx, packages/react-router/index.ts, packages/react-router/lib/hooks.tsx, packages/router/__tests__/lazy-discovery-test.ts, packages/router/index.ts, packages/router/router.ts, packages/router/utils.ts
Renamed for clarity because this is no longer only called on misses
=> Rename patchRoutesOnMiss to patchRoutesOnNavigation

packages/react-router-dev/vite/plugin.ts
client dep optimization pass for local dev
in that case, the module graph is treated like a client-module graph without any transforms, so we need to disable the `.server` detection during deps discovery
in the future, it would be better to have separate module graphs for client and server without requiring transforms so that this all works with Vite out-of-the-box and server dependencies are not optimized for use by the client
See https://github.com/remix-run/remix/pull/9921
=> `ssr` field will be omitted and `scan` will be `true` when vite does its

packages/react-router-dev/vite/plugin.ts, packages/react-router-dev/vite/route-chunks.ts
Since caching was based on IDs which also included route chunk query strings (e.g. `?route-chunk=clientLoader`) there was a lot of wasted work that couldn't be cached across route chunks. This refactor ensures that only the desired route chunk is generated based on the query string value.
=> Route chunks: Improve chunk generation performance

packages/react-router/lib/dom/ssr/components.tsx, packages/react-router/lib/dom/ssr/links.ts
Attempting to add this was more difficult than expected due to some duplication in the code, so I fixed that while I was here. There's now a single source of truth for calculating the preload links.
=> Route chunks: Add modules preloads

packages/react-router-dev/vite/plugin.ts
to make it easier to read transformed modules in dev
once we switch to better interop with `vite-plugin-react` this may become obsolete, but until then its nice to have
see the newly added `[BEGIN]` & `[END]` comment boundaries below
```ts
import { createHotContext as __vite__createHotContext } from "/@vite/client";import.meta.hot = __vite__createHotContext("/app/routes/_index.tsx");
// [BEGIN] REACT REFRESH HEADER ------------------------------------------------
import RefreshRuntime from "/@id/__x00__virtual:react-router/hmr-runtime";
const inWebWorker = typeof WorkerGlobalScope !== 'undefined' && self instanceof WorkerGlobalScope;
let prevRefreshReg;
let prevRefreshSig;
if (import.meta.hot && !inWebWorker) {
if (!window.__vite_plugin_react_preamble_installed__) {
throw new Error( …
```
=> comment boundaries for react refresh transforms

integration/single-fetch-test.ts, packages/react-router/lib/dom/ssr/single-fetch.tsx, packages/react-router/lib/server-runtime/single-fetch.ts, packages/react-router/package.json, pnpm-lock.yaml
1. serialize class instances via `Object.fromEntries(Object.entries(obj))` to omit methods
2. serilaize anything that would otherwise be unserializable as `undefined`
(1) is important as TS can't distinguish between plain objects and class instances, so both of those need to be handled the same way if we want good type safety
(2) is important so that we never get runtime errors from returning "unserializable" data from loaders/actions
This was implemented in Remix in this PR: https://github.com/remix-run/remix/pull/9893
=> robust single fetch serialization

.changeset/unlucky-keys-collect.md, docs/routers/create-browser-router.md, packages/router/__tests__/lazy-discovery-test.ts, packages/router/router.ts
Removed this fifo queue because it was a bit overly restrictive and prevents use cases such as the one described in https://github.com/remix-run/react-router/discussions/11947.  This can be implemented in user land if required (as [Remix does](https://github.com/remix-run/remix/blob/main/packages/remix-react/fog-of-war.ts#L22)).
=> Remove internal discoverRoutes queue and make patch idempotent

package.json, pnpm-lock.yaml
Specifically, we want the new `hoist-workspace-packages` default as of v8.14 (https://github.com/pnpm/pnpm/releases/tag/v8.14.0) so that local `workspace:*` deps are canonically hoisted into `node_modules/.pnpm/node_modules`. This fixes potential TS plugin resolution issues
pnpm automatically upgraded our lockfile to the latest format, which mostly means quoted package names in the lockfile
=> upgrade pnpm to latest (v9.10)

.changeset/stabilize-flush-sync.md, .changeset/stabilize-view-transitions.md, docs/components/form.md, docs/components/link.md, docs/components/nav-link.md, docs/hooks/use-fetcher.md, docs/hooks/use-navigate.md, docs/hooks/use-submit.md, docs/hooks/use-view-transition-state.md, docs/routers/picking-a-router.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/__tests__/flush-sync-navigations-test.tsx, packages/react-router-dom/dom.ts, packages/react-router-dom/index.tsx, packages/react-router/lib/context.ts, packages/router/__tests__/flush-sync-test.ts, packages/router/__tests__/view-transition-test.ts, packages/router/router.ts
For replaying in v7:
```
for F in $(find . -type f -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./examples/*" -not -path "./.changeset/*" -not -name "CHANGELOG.md" -not -name "*.png" -not -name "*.jpeg" -not -name "*.ico"); do
sed -i '' 's/unstable_viewTransition/viewTransition/g' $F;  
sed -i '' 's/unstable_useViewTransition/useViewTransition/g' $F;  
sed -i '' 's/unstable_flushSync/flushSync/g' $F;  
done
```
=> Stabilize viewTransiton and flushSync options

packages/react-router/__tests__/data-router-no-dom-test.tsx, packages/react-router/__tests__/dom/data-browser-router-test.tsx, packages/react-router/__tests__/dom/flush-sync-navigations-test.tsx, packages/react-router/__tests__/router/flush-sync-test.ts, packages/react-router/__tests__/router/view-transition-test.ts, packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/context.ts, packages/react-router/lib/dom/dom.ts, packages/react-router/lib/dom/lib.tsx, packages/react-router/lib/router/router.ts
v7 sibling of https://github.com/remix-run/react-router/pull/11989
=> Stabilize viewTransition and flushSync APIs

packages/react-router-dev/vite/route-chunks-test.ts, packages/react-router-dev/vite/route-chunks.ts
Previously, an import statement that is depended on by multiple exports could easily lead to a de-opt of the route chunks optimisation, even if the individual identifiers that are imported are not shared between exports. This is because the chunking algorithm only operated on top-level statements, so we could only ever omit or retain the entire import statement within each chunk.
This PR fixes this by treating import statements as a special case where we now track the usage of the individual identifiers across all exports. This allows us to remove unused imports for each chunk and greatly increase the chances of successfully optimising a route.
As a minimal example, this previously would have caused a de-opt resulting in all route code in a single chunk:
```tsx
// import statement …
```
=> Route chunks: Optimize import statements

.changeset/calm-wombats-design.md, packages/react-router-dom/__tests__/data-browser-router-test.tsx, packages/react-router-dom/index.tsx, packages/router/router.ts
Closes https://github.com/remix-run/remix/issues/8923
=> Fix issues with contextual routing and index params

.github/workflows/shared-integration.yml, docs/guides/prerendering.md, integration/vite-prerender-test.ts, package.json, packages/react-router-dev/vite/config.ts, packages/react-router-dev/vite/plugin.ts
In simple "true static" sites, React Router can determine all of the static paths so there's no reason to require the app to tell us about the static paths via an array/function.  This PR adds support for `prerender: true` which will walk your route tree and automatically prerender any paths that don't have dynamic/splat params.
We also expose this internal logic to the function API so you can just add your own dynamic paths on top of the known static paths:
```js
export default defineConfig({
plugins: [
reactRouter({
async prerender({ getStaticPaths }) {
let slugs = await getBlogSlugsFromCms();
return [
...getStaticPaths(),
...slugs.map((s) => `/blog/${s}`),
];
},
}),
],
});
```
In a `routes.ts` landscape this will be nice to avoid needing to add a route in 3 places - FS, `routes.ts`, …
=> Add support for prerender:true

packages/router/__tests__/lazy-discovery-test.ts, packages/router/router.ts
Fixes a sibling pathless layouts route bug in the `uniqueChildren` logic from https://github.com/remix-run/react-router/pull/11977.  That hasn't been released yet so no need for a changeset in this PR
=> Fix idempotent patchRoutes for sibling pathless layout routes

packages/react-router-dev/vite/route-chunks-test.ts, packages/react-router-dev/vite/route-chunks.ts
Expanding support for different export types so that multiple variable declarations in a single export (`export const foo = ..., bar = ...`) are handled correctly.
=> Route chunks: Split exported variable declarations

contributors.yml, docs/start/tutorial.md
The sentence said "farther along" instead of "further along" which is grammatically wrong.
The docs have a grammatical error. It says "farther along" instead of "further along" This is grammatically incorrect.
A reference for extra support is here [here](https://www.dictionary.com/e/farther-vs-further/#:~:text=The%20widely%20accepted%20rule%20is%20to%20use%20farther%20when%20being%20literal%20and%20discussing%20a%20physical%20distance%2C%20as%20in%20%E2%80%9CHe%20went%20farther%20down%20the%20road.%E2%80%9D%C2%A0Further%20is%20used%20when%20discussing%20a%20more%20symbolic%20distance%20or%20to%20discuss%20a%20degree%20or%20extent%2C%20as%20in%C2%A0%E2%80%9CI%20wanted%20to%20discuss%20it%20further%2C%20but%20we%20didn%E2%80%99t%20have%20time.%E2%80%9D) . …
=> fix:Grammatical error

packages/react-router-dev/typescript/typegen.ts
Note, this is a PR to https://github.com/remix-run/react-router/pull/12019.
Within the context of the TS plugin running within my editor, the root directory of the vite-node server was `"/"` rather than the project directory.
It looks like this is because it was defaulting to the current working directory, which is different in a TS plugin context compared to regular Vite / CLI usage. If I log `process.cwd()` within the TS plugin, I get `"/"`.
The fix was to explicitly pass our resolved root directory to vite-node rather than relying on cwd by default.
=> Typesafety: Fix vite-node resolution in TS plugin

packages/react-router-dev/vite/plugin.ts
Previously, the props HOCs were only applied when `ssr: false`, so it would work when HMR'ing an existing route to start using props like `loaderData`. That was causing errors as the initial SSR render did not have the HOCs applied, so all the props were `undefined`. Now the props HOCs always get applied.
=> Fix route export props

.changeset/itchy-shoes-sort.md, packages/router/router.ts
=> Avoid unnecessary console error on fetcher abort due to back-to-back revalidation calls

.changeset/gold-frogs-pump.md, docs/components/form.md, docs/components/link.md, docs/components/nav-link.md, docs/hooks/use-fetcher.md, docs/hooks/use-navigate.md, docs/hooks/use-submit.md, docs/routers/create-browser-router.md, packages/router/__tests__/lazy-discovery-test.ts, packages/router/router.ts
Closes https://github.com/remix-run/react-router/issues/12012
=> Remove internal cache from patchRoutesOnNavigation

.changeset/red-feet-shop.md, integration/error-boundary-test.ts, integration/single-fetch-test.ts, packages/react-router/__tests__/router/revalidate-test.ts, packages/react-router/lib/dom-export/hydrated-router.tsx, packages/react-router/lib/dom/ssr/server.tsx, packages/react-router/lib/hooks.tsx, packages/react-router/lib/router/router.ts, packages/react-router/lib/server-runtime/data.ts, packages/react-router/lib/server-runtime/headers.ts, packages/react-router/lib/server-runtime/routes.ts, packages/react-router/lib/server-runtime/single-fetch.ts
Follow up to https://github.com/remix-run/react-router/pull/11680 which missed some of the Remix codepath checks.
=> Allow returning undefined from loaders/actions (part 2)

.changeset/purple-poems-laugh.md, integration/defer-loader-test.ts, packages/react-router/lib/server-runtime/data.ts
=> Fix redirects returned from loader using data

.changeset/gold-suns-march.md, .changeset/silly-papayas-trade.md, packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/dom-export/hydrated-router.tsx, packages/react-router/lib/dom/global.ts, packages/react-router/lib/dom/lib.tsx, packages/react-router/lib/dom/server.tsx, packages/react-router/lib/dom/ssr/errors.ts, packages/react-router/lib/dom/ssr/fog-of-war.ts, packages/react-router/lib/dom/ssr/single-fetch.tsx, packages/react-router/lib/hooks.tsx
Remove the (hopefully) last "remix" wording from the codebase
=> Rename RemixRouter -> DataRouter

templates/basic/app/app.css, templates/basic/app/routes/home.tsx, templates/basic/package.json, templates/basic/postcss.config.js, templates/basic/tailwind.config.ts, templates/basic/vite.config.ts
Unfortunately [tailwind v4 doesn't work on Stackblitz quite yet](https://github.com/tailwindlabs/tailwindcss/issues/13133) so we're going back to 3 for now since so many people use Stackblitz to send us repos
I'm so sorry @alexanderson1993
=> Revert template to tailwind v3

docs/start/overview.md
Added a Search Params section to the Feature Overview in the documentation. It includes a simple description with references, along with an example showing the main concepts.
=> docs(start/overview): add `Search Params` section

docs/start/overview.md
Change the highlighted line from 16 to 20 in the last example. @brookslybrand is familiar with this section
=> docs(start/overview): fix a typo in Search Params section

integration/helpers/vite.ts, integration/route-chunks-test.ts, packages/react-router-dev/vite/config.ts, packages/react-router-dev/vite/plugin.ts, packages/react-router-dev/vite/route-chunks.ts
This allows more performance sensitive consumers to ensure that a de-opt never occurs and that client loaders/actions never end up in the same chunk as the rest of the route module exports.
=> Route chunks: Add "enforce" option

.changeset/shy-chicken-talk.md, packages/router/__tests__/lazy-discovery-test.ts, packages/router/router.ts
This was raised as [feedback](https://github.com/remix-run/react-router/issues/11775#issuecomment-2227793201) and makes sense to avoid RR doing any intermediary processing/wrapping on an error thrown in user code.  The internal `ErrorResponse` errors should be limited to true internal routing errors.  We should expose user-thrown errors directly like we do for loaders/actions
=> Expose patchRoutesOnNavigation errors directly

packages/react-router-dev/__tests__/route-config-test.ts
This is needed to ensure the tests can run on Windows. This was picked up when porting `routes.ts` support to Remix since the unit tests are run on Windows in that repo.
=> Clean paths in relative route helper snapshots

docs/start/overview.md
Added a **missing "Location State" section** to the documentation. 
Provided a clear explanation, along with examples demonstrating how to read and modify the location state using `useLocation`, `Link` and `useNavigate`.
=> docs(start/overview): add `Location State` section

docs/misc/file-route-conventions.md, docs/misc/resource-routes.md
- Copy/Pastes the docs from Remix
- replaces references to Remix with React Router
- adds a section on Turbo Stream
- adds a section on Client Loader/Action in Resource Routes
- moves the section on escaping URLs to the file-based routing docs
=> docs(misc/resource-routes): add new page

docs/upgrading/remix.md, packages/react-router/lib/types.ts
* Remove optional `context` from `Route.ClientLoaderArgs`/`Route.ClientActionArgs`
* Make `context` non-optional in `Route.LoaderArgs`/`Route.ActionArgs`
* Add docs to the Remix v2 upgrade guide on how to use module augmentation to properly type `LoaderFunctionArgs`/`ActionFunctionArgs` for the migration
=> Fix contxt types for Route.LoaderArgs, add upgrade docs

integration/single-fetch-test.ts, packages/react-router/lib/dom/ssr/links.ts, packages/react-router/lib/dom/ssr/routes.tsx
v7 version of https://github.com/remix-run/remix/pull/10139
=> Fix defaultShouldRevalidate when using single fetch (Remix PR 10139)

.changeset/long-peas-doubt.md, packages/react-router/lib/components.tsx, packages/react-router/lib/dom/lib.tsx, packages/react-router/lib/dom/ssr/components.tsx, packages/react-router/lib/dom/ssr/routeModules.ts, packages/react-router/lib/hooks.tsx, packages/react-router/lib/types.ts
Stacked on https://github.com/remix-run/react-router/pull/12177
Handles bringing over Remix generics for:
* `useLoaderData`/`useActionData`
* `useFetcher`
* `useRouteLoaderData`
* `meta()`
* `Await`
* `serverLoader`/`serverAction`
Am I missing anything else?
Available for testing in `0.0.0-experimental-7c6c0664d`
=> Add generics for loader data, action data, and fetchers

.changeset/serious-beds-approve.md, packages/react-router-dev/cli/commands.ts, packages/react-router-dev/tsup.config.ts, packages/react-router-dev/vite/config.ts, packages/react-router-dev/vite/plugin.ts, packages/react-router/tsup.config.ts
Build output is bundled now so things are collapsed to the root of the dist directory. We now need to resolve the config dir relative to the root, not the input file structure.
=> fix: resolve config directory relative to flat output file structure

docs/start/testing.md
=> Docs: update testing docs imports

contributors.yml, packages/router/utils.ts
- update description about isRouteErrorResponse, it has nothing to do with status code.
related: https://github.com/remix-run/remix/issues/10016
=> chore: update isRouteErrorResponse description

contributors.yml, packages/react-router-dev/typescript/typegen.ts
This PR fixes [#12162](https://github.com/remix-run/react-router/issues/12162) by modify the type generation logic to consider custom `appDirectory` config in the Vite plugin.
> [!NOTE]
> While a recent [change](https://github.com/remix-run/react-router/pull/12203/commits/e392cfc7974ef51f64358014686d8b51599855c0) updated the logic to use `Path.basename(ctx.appDirectory)`, this only captures the base name of the directory (e.g., "app" in "src/app"). This PR modifies the logic to utilize the full relative path provided in the `appDirectory` configuration.
_This change ensures that the types are generated in the correct location, as specified by the `appDirectory` config. It has no impact on existing functionality and simply aligns the type generation with the user's chosen configuration._
=> fix: take the `appDirectory` into account when generating types

package.json
This reintroduces the `watch` npm script on top of the new build script setup.
=> Add `watch` npm script

.changeset/typesafety.md, docs/explanation/type-safety.md, docs/how-to/resource-routes.md, docs/start/actions.md, docs/start/data-loading.md, docs/start/routing.md, packages/react-router-dev/typegen.ts, playground/compiler/app/routes/_index.tsx, playground/compiler/app/routes/product.tsx
By wrapping all the generated route types in a `Route` namespace, we get autoimports for `Route` while still being able to use dot-notation to access the types.
https://github.com/user-attachments/assets/4a08e85b-62ba-4bd8-96d9-20bae0e3270a
Contrast this with exporting a record type where we'd need to use `[]`:
```ts
// `Route` as a record
export Route1 = {
LoaderArgs: any
}
function loader(args: Route1["LoaderArgs"]) {} // gross
// `Route` as a namespace
export namespace Route2 {
export type LoaderArgs: any
}
function loader(args: Route2.LoaderArgs) {} // much nicer
```
Normally, I'd be against introducing TS `namespace`s, but since this is an auto-generated `.d.ts` file, it should never need to be compiled to JS.
=> typegen: autoimport for `Route` types

contributors.yml, docs/upgrading/v6.md
Quick one.. v7_skipActionStatusRevalidation is named v7_skipActionErrorRevalidation, at least in RR 6.27.0.
Is this a typo?
=> v7_skipActionStatusRevalidation -> v7_skipActionErrorRevalidation in Docs

docs/components/form.md
Added an **additional "Registration Form"** example to the **Form Component documentation**.
Demonstrated how to use `Mutation Submissions` in the registration workflow. Showed how to work with returned data from the `action` using `useActionData`.
=> docs(components/form): add `Registration Form` example

contributors.yml, docs/upgrading/future.md
I am seeing warnings like:
```
⚠️ React Router Future Flag Warning: The revalidation behavior after 4xx/5xx `action` responses is changing in v7. You can use the `v7_skipActionErrorRevalidation` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_skipactionerrorrevalidation.
```
in my console, but the https://reactrouter.com/v6/upgrading/future#v7_skipactionerrorrevalidation link does not resolve to a section on the `/v6/upgrading/future` page.
=> chore: change `v7_skipActionStatusRevalidation` to `v7_skipActionErrorRevalidation`

contributors.yml, docs/start/overview.md
I find the expression q?=ryan a bit confusing. This was written two years ago, so I may be mistaken, but I wanted to bring it up just in case.
Thanks for the great documentation!
=> Typo fix: '?' is placed in a wrong position

.changeset/shiny-cameras-try.md, contributors.yml, integration/vite-prerender-test.ts, packages/react-router-dev/vite/plugin.ts, packages/react-router/lib/server-runtime/routes.ts
fix #12160 
- Fixed an issue where builds would fail during static prerendering in React Router v7 when the data passed to the loader contains non-ASCII characters, such as Korean.
- Applied encodeURI to the X-React-Router-Prerender-Data header when making requests to localhost in the loader, and added decodeURI processing on the receiving end.
- Added relevant tests and confirmed that they pass.
Screenshot 1: Attempted static prerendering, which failed.
Screenshot 2: Used `console.log` to inspect the `requestInit` object inside `prerenderRoute` to identify the point where prerendering fails.
Screenshot 3: Confirmed that the non-ASCII data is correctly passed to the loader after applying `encodeURI`/`decodeURI`.
=> fix(react-router): (v7) fix static prerender non-ascii problem

integration/typegen-test.ts, packages/react-router/package.json
and alter tests to fail for `any` types
=> fix package export path for `/route-module`

integration/typegen-test.ts, packages/react-router-dev/typegen/generate.ts, packages/react-router/index.ts, packages/react-router/lib/types/meta-match.ts, packages/react-router/lib/types/route-module.ts, packages/react-router/package.json
For `matches` in `meta`, loop over them and match by something like `id` and then cast it. This is equivalent to the generic we had in Remix but with less boilerplate:
```ts
// Remix v2
import type { ParentLoader } from "./parent-route"
import type { GrandparentLoader } from "./grandparent-route"
export function loader() {}
export function meta({ data, matches }: MetaArgs<
typeof loader,
{
"parent-route": ParentLoader,
"grandparent-route": GrandparentLoader,
} // 👆 giant generic for ancestor routes
>) {
for (let match of matches) {
if (match.id === "parent-route") {
const safeMatch = match as { data: SerializeFrom<ParentLoader> }
// 👆 doing that giant generic didn't really help, we still have to cast it here!
}
}
}
```
```ts
// React Router v7
import { MetaMatch } from "react-router" …
```
=> typegen: meta + links

integration/typegen-test.ts, packages/react-router-dev/typegen/context.ts, packages/react-router-dev/typegen/generate.ts, packages/react-router-dev/typegen/paths.ts, packages/react-router/lib/types/route-module.ts, playground/compiler/app/routes/_index.tsx, playground/compiler/app/routes/product.tsx
The `.` was adding more noise to the import as another special symbol. Plus the `/` makes it easier to see that the thing after `+types/` is just the name of the current route module.
=> typegen: `+types.<route>` -> `+types/<route>`

packages/react-router-dev/typegen/paths.ts, packages/react-router/lib/types/route-module.ts
previously, typegen'd files had a `.d.ts` extension but that means any errors within those typegen'd files would not show up due to `skipLibCheck: true`. so instead, we generate `.ts` files.
this makes sense as the typegen'd files are part of your app's domain, not part of a library.
also fixed a type error in typegen'd files by allowing user-defined exports in the route module type
=> typegen: not ignored by skipLibCheck

templates/basic/app/routes.ts
The template is pointing at the last pre-release so it needs to use the old `routes.ts` API until the next release.
=> Fix template `routes.ts`

contributors.yml, docs/index.md
a small mistake found between "https://reactrouter.com/dev/start/framework/installation" and "https://reactrouter.com/dev/framework/start/installation".
=> fix wrong linking for Get Started link

packages/react-router/lib/dom/ssr/routeModules.ts
Using React Router as a library (not framework) still requires use of these types for now
=> un-deprecate types for library mode

packages/react-router-node/index.ts, packages/react-router-node/package.json, packages/react-router-node/server.ts, pnpm-lock.yaml
This PR adds a `createRequestListener` function to `@react-router/node` using `@mjackson/node-fetch-server` under the hood.
=> Add createRequestListener to @react-router/node

.github/ISSUE_TEMPLATE/bug_report.yml, README.md, contributors.yml
I fixed some broken links, but there are still a few left and I don't know what you want to do with them... I guess the doc isn't written yet :)
But just in case, here they are:
```md
- [Getting Started - Framework](https://reactrouter.com/start/framework/installation)
- [Getting Started - Library](https://reactrouter.com/start/library/installation)
- [Upgrade from v6](https://reactrouter.com/upgrading/v6)
- [Upgrade from Remix](https://reactrouter.com/upgrading/remix)
```
Thanks for maintaining react-route :smile:
=> docs: fix broken links

contributors.yml, docs/index.md
The "Get Started" link in the [React Router as a Library section](https://reactrouter.com/dev/home#react-router-as-a-library) was broken and has been updated to the correct URL.
=> fix broken link in the home page of dev branch

contributors.yml, docs/how-to/error-boundary.md
I noticed this at work earlier while looking at [the docs](https://reactrouter.com/7.0.1/how-to/error-boundary), thought it was funny but presumably not intended. figured I might as well open a PR for it! but feel free to just close this and commit the fix yourself if you'd like rofl
=> docs: correct error-boundary how-to doc

packages/react-router/index.ts, packages/react-router/lib/components.tsx
the auto generated api docs put it in a  weird spot with a weird URL when it’s defined in the index file instead of with the rest of the functions
=> moved for API docs

README.md, contributors.yml
Congrats on the v7 release! 🎉 
Seems the `README.md` links broke in https://github.com/remix-run/react-router/commit/c8fd1384fa23d74d7dd72aad4915f20b00d7f35f.
This PR simply fixes those (also uses monospaced characters but can revert that if undesired)
=> docs(README): fix broken links

contributors.yml, docs/how-to/file-route-conventions.md
This PR addresses an issue in the [React Router documentation](https://reactrouter.com/how-to/file-route-conventions) where certain links point to incorrect sections of the docs. Specifically, links are inconsistently directed to `start/[something] `instead of the correct path `start/framework/[something]`.
Changes:
Updated incorrect links to ensure they point to the intended sections under start/framework/[something].
Why:
The current links lead to unrelated parts of the documentation, causing confusion for readers. This update ensures accuracy and improves the user experience.
=> docs(how-to/file-route-conventions): fix links 

contributors.yml, docs/upgrading/v6.md
The current v6 upgrade docs have a command which applies only for BSD sed (included in macOS or BSD operating systems) and won't work on GNU sed, throwing an error. This PR adds the equivalent command for GNU sed.
=> docs(upgrading/v6): add linux example in `Update imports` section

contributors.yml, docs/start/framework/testing.md
The current code example in the documentation is non-functional due to an unnecessary `)`. Therefore, I'm updating the documentation to remove the unnecessary `)`.
=> docs(start/framework/testing.md): fix sample code

.changeset/curvy-readers-notice.md, packages/react-router/package.json
with the export map before this commit, there’s a react router context mismatch in react-router-dev because the node process from `react-router dev` isn’t started with `—conditions development`, so it required the production build of `react-router` (because it’s used internally in `react-router-dev`.
Then for the server render, “react-router” is already in the cache so if any node_modules have a peer dep on it, it gets the production build too.
After that, app code runs and asks for “react-router” but this import is processed through vite with the “development” condition, so the app gets a different version of react router
Now if a node_module want’s to useLocation inside of the app, it’s got a different copy of that hook and no router context
This is a temporary patch until we can work …
=> temporarily only use one build in export map

contributors.yml, docs/start/framework/route-module.md
As far as I'm aware `Route.ShouldRevalidateArg` is not being generated when calling `typegen` so I'm updating the documentation accordingly to use `ShouldRevalidateFunctionArgs`
=> docs(start/framework/route-module): fix types

.changeset/blue-ears-tie.md, packages/react-router-dev/typegen/generate.ts
=> Support moduleResolution NodeNext and Node16

.changeset/honest-dots-deliver.md, packages/react-router-fs-routes/__tests__/flatRoutes-test.ts, packages/react-router-fs-routes/flatRoutes.ts
The `flatRoutes` function is supposed to throw error if the `routesDir` does not exist. But due to a type, it was checking for `rootRoute` again and throwing error regarding missing `routesDir`. 
Fixed the typo and couple of tests to check for correct error to be thrown in both scenarios.
=> fix(fs-routes): throw error if routes directory is missing

docs/how-to/route-module-type-safety.md
that lets the TypeScript LSP handle `type` auto-imports, which means it works in any modern editor without any additional configuration
as suggested in https://github.com/remix-run/react-router-templates/issues/14
=> docs: prefer `verbatimModuleSyntax` when setting up type-only auto-imports

.changeset/serious-chairs-lie.md, packages/react-router/lib/dom/ssr/components.tsx
=> Remove false positive link prefetch warning

contributors.yml, docs/how-to/resource-routes.md
A small fix to update action arguments type instead of LoaderArgs in Handling different request methods example
=> docs: type of action arguments in Handling different request methods example

contributors.yml, docs/start/framework/testing.md
* Currently the example in `testing.md` doesn't run/requires amendments for followers of the tutorial to execute in their own codebase
* Follows the recommended way of importing from `@testing-library/react` as per their [docs](https://testing-library.com/docs/react-testing-library/example-intro)
* `@testing-library/react` doesn't export `user`, replaced with `@testing-library/user-event`
Would love to see this page will out some more in the future, especially with e2e examples with playwright and something cool with Vitest Browser Mode would go down a treat too @ryanflorence 🔥
=> docs(start/framework/testing): fix code

.changeset/khaki-gifts-grin.md, packages/react-router/lib/router/utils.ts, packages/react-router/lib/types/route-data.ts
=> ignore redirects when inferring loader data types

integration/helpers/create-fixture.ts, integration/playwright.config.ts
Node 22.12 enables `require(esm)` by default.
As part of this, the `module-sync` export condition gets used whereas in 22.11 that export condition gets ignored.
We've setup out package.json exports for `react-router` to use the `module-sync` condition to point to the ESM version so that no matter where you get `react-router` from you always get the same copy. That's a good thing!
So in 22.11, you get a (duplicate) CJS version of `react-router` and in 22.12 you get a (deduplicated) ESM version of `react-router`.
This is all intended behavior, but Node shipped this new default while still logging warnings for `require(esm)` to stderr. Since many of our integration tests check stderr for warnings, those started failing.
Again, everything is working correctly (and better than in 22.11) so …
=> tests: silence `require(esm)` warnings for Node 22.12

contributors.yml, docs/start/framework/routing.md
I had trouble figuring out how to write layout components in v7, turns out I had to use an outlet. This was a bit confusing to me because I was using children for some reason. I added extra instructions to [the layout routes docs](https://reactrouter.com/start/framework/routing#layout-routes) to help stragglers like me.
=> Add layout outlet docs

contributors.yml, docs/start/framework/installation.md, docs/start/library/installation.md, docs/upgrading/remix.md, docs/upgrading/v6.md
This bit me, I started updating and a ways into the update got the `startTransition is not a function` error. Almost on 18, but not yet, so a note on the docs site would have saved some frustration/time.
=> Add prerequisite sections to a few places

CHANGELOG.md, contributors.yml
Spotted and fixed a minor typo in the v7.0.0 changelog:
- Was: `introduce din minor releases`
- Now: `introduced in minor releases`
No functional impact on users.
No testing necessary for this PR change - documentation change only.
=> docs(changelog): fix minor typo in Changelog

contributors.yml, docs/start/framework/installation.md
@brookslybrand and I had a chat on Twitter https://x.com/thomasgauvin/status/1869139471263990106. It'd be nice to feature the deployment templates more apparently in the installation guides (similar to how Vite does it https://vite.dev/guide/#scaffolding-your-first-vite-project)
I opened this PR but I couldn't preview the docs. Not sure if this looks crazy, but I think the idea is in the right direction. The current note of `To get started with a template that deploys to your preferred host, check out [all of our templates](https://github.com/remix-run/react-router-templates).` is too easy to miss, and it requires people to figure out how to create a project from a template ie having to run `npx create-react-router@latest --help` to see the available options, especially for folks may not …
=> docs: improve template instructions in installation docs

.changeset/selfish-pianos-grab.md, contributors.yml, packages/react-router-dev/bin.js, packages/react-router-serve/bin.js
It seems React 19 is a bit more strict with `NODE_ENV` and when it's not set by the user there is currently a mismatch between our code and React's code (similar to the issue in https://github.com/remix-run/react-router/issues/12078)
* We default to [`production`](https://github.com/remix-run/react-router/blob/main/packages/react-router-dev/vite/plugin.ts#L63) when we call `vite.resolveConfig` in in `plugin.ts`
* But React defaults to [`development`](https://www.unpkg.com/react@19.0.0/index.js)
This mismatch causes issues because we end up with mismatched versions of React in the bundle versus the `react-router build` runtime.
This PR updates the `react-router` and `react-router-serve` to set `NODE_ENV` accordingly if it's not already set:
* `react-router dev` defaults to `development`
* …
=> Properly initialize `NODE_ENV` if not already set

contributors.yml, docs/community/contributing.md
=> docs(community/contributing): improvements for docs changes

docs/upgrading/v6.md
Resolves #12563 
Our language was too SSR-focused, so it made it confusing why `HydrateFallback` might be needed if you're using `createBrowserRouter` in a SPA
=> docs(upgrading/v6): clarify `partialHydration`

contributors.yml, packages/react-router-dev/bin.js
Related issue #12606 
Introduced in release v7.1.0 with the changes required to have NODE_ENV correctly set-up for React 19.
In this file the optional args are not necessary but it shouldn't crash if present. The fixe handle that situation by not parsing positional args in this file.
=> fix(@react-router/dev): prevent argv parsing crash when optionnal args are passed to the cli

contributors.yml, docs/how-to/suspense.md
This PR removes the unnecessary rendering of NonCriticalUI when the Await component is used.
Since the Await component handles loading states and delays rendering of its children until the awaited resource is ready, rendering NonCriticalUI is redundant.
=> docs(how-to/suspense): update

contributors.yml, tutorials/address-book/package.json
This PR resolves issue #12642 that would cause npm install to fail during setup of the address-book example code. 
using the fix provided by [dev001hajipro](https://github.com/dev001hajipro)
- changed live 17 from 7.0.2 to 7.1.1
=> Update package.json to fix issue #12642

.changeset/beige-ants-pay.md, packages/react-router/__tests__/dom/data-browser-router-test.tsx, packages/react-router/__tests__/router/fetchers-test.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/router/router.ts
v7 version of https://github.com/remix-run/react-router/pull/12674
=> Fix fetcher data cleanup

.changeset/afraid-jeans-drive.md, contributors.yml, packages/react-router-dev/vite/cloudflare-dev-proxy.ts, packages/react-router-dev/vite/plugin.ts
Configuring `resolve.conditions`/`resolve.externalConditions` in Vite v6 has changed: https://vite.dev/guide/migration.html#default-value-for-resolve-conditions
The configured conditions are no longer added to the default values, they now _replace_ the defaults. This was causing problems with resolving packages like `@prisma/client` during SSR.
This fix adds the missing default values if the default values exist, and they only exist in Vite v6, otherwise it preserves the previous behavior in order to (hopefully) maintain the same behavior with Vite v5.
Fixes #12610.
=> Fix configuring resolve conditions for Vite v6

.changeset/calm-cycles-dress.md, packages/react-router/lib/router/utils.ts, packages/react-router/lib/types/route-data.ts
=> do not rely on `symbol` for filtering out `redirect`s from loader data

.changeset/polite-clocks-shake.md, contributors.yml, packages/react-router-dev/vite/plugin.ts
Resolves #12483
The `react-router:react-refresh-babel` transform was wrapping the code with big chunks of code that completely threw off the source maps. I've changed the wrapping code to use babel to maintain the source maps, and split it off into a new transform step so the source maps from the previous transform flow through.
=> Fix react-refresh source maps

docs/start/framework/routing.md
The use of `config routes` and `file routes` in combination is explained in the [PR](https://github.com/remix-run/react-router/pull/11773) where `routes.ts` was added, but it was missing from the guide.
I added it because I thought it would be more useful and cover the use cases by documenting it in the guide.
=> docs: Added guide on combining `configure routes` and `file routes`

docs/how-to/file-route-conventions.md
`flatRoutes` has two options: `ignoredRouteFiles` and `rootDirectory`.
Currently, there is an explanation for `rootDirectory`, but there is no explanation for `ignoredRouteFiles`. I have added an explanation for it, as it is also a very powerful feature.
=> docs: add explanation of `ignoredRouteFiles` option to guide

packages/react-router/lib/context.ts
These should appear both in VS Code and other IDEs, as well as in the reference docs website.
=> docs: add additional JSDocs to NavigateOptions

docs/how-to/client-data.md, docs/how-to/spa.md, docs/start/framework/data-loading.md
We didn't really have any info on `HydrateFallback` or what `clientLoader.hydrate = true` does, so hopefully this helps fill in the gap
=> docs: add HydrateFallback to the data-loading doc

scripts/publish.js
The `publishBranch` variable was unused, and further down the file there was a `releaseBranch` variable being referenced that was never defined.
=> Fix publish script

docs/how-to/file-uploads.md
the `api/upload-avatar.ts` file in that guide doesn’t handle any uploading (it just serves up avatars that are uploaded by the `pages/user-profile.tsx` action), so i renamed it to `api/avatar.ts`. also, i made the style of importing the `FileUpload` type consistent across all code examples.
=> Rename the resource route file in the file upload guide

contributors.yml, packages/react-router/lib/deprecations.ts
Closes #12250, see https://github.com/remix-run/react-router/issues/12250#issuecomment-2525223753
I prefer to use default settings and as little configuration as possible, so it is good practice to follow generally accepted standards.
I did the same as it was done in [MobX](https://github.com/mobxjs/mobx/blob/9944edcc8450fa8d328ffcc436acddd85b90e803/packages/mobx-react-lite/src/index.ts#L23) and [Antd](https://github.com/ant-design/ant-design/blob/c2efea0b336cf23d5ec74eb8a6e31743f61558a4/components/select/index.tsx#L251).
@brookslybrand
=> Suppress v7 warnings in production build

.changeset/fifty-eagles-love.md, integration/single-fetch-test.ts, packages/react-router/lib/dom/ssr/single-fetch.tsx, packages/react-router/lib/server-runtime/server.ts
Closes https://github.com/remix-run/remix/issues/10328
=> Properly handle empty body response codes in single fetch requests

docs/start/framework/routing.md
Fix syntax error in `routing.md` by removing incorrect assignment operator.
=> docs: fix syntax error in routing.md

.changeset/gentle-carrots-appear.md, contributors.yml, packages/react-router-dev/vite/plugin.ts
TL;DR - [`unstable_optimizeDeps` doesn't work well on Windows due to path resolution issues](https://github.com/remix-run/remix/issues/10156). This fixes it. All credit goes to @sebastien-comeau for https://github.com/remix-run/remix/pull/10258 (which still needs merged for the Windows folks still on Remix v2, btw).
=> fix(dev): resolve optimizeDeps entries properly on Windows

contributors.yml, docs/how-to/status.md, docs/start/framework/actions.md
Noticed while going through the actions tutorial that these weren't needed.
=> docs: Remove redundant awaits from formData examples

.changeset/proud-stingrays-wink.md, packages/router/router.ts
Sibling for https://github.com/remix-run/remix/pull/10424
=> Properly bubble headers when throwing a data result

.changeset/stupid-mirrors-prove.md, packages/react-router/lib/dom/ssr/links.ts, packages/react-router/lib/dom/ssr/routes.tsx
CSS side effects are currently treated as if they were defined as part of a route's `links` function. While this kept things conceptually simple, it meant that we're blocking on the route module being loaded before we begin prefetching these styles on navigation.
We can do better than this since we already know about them up front in the manifest as `route.css` before loading the route module, so this PR hoists the prefetching of CSS side effect links up to run in parallel to the loading of the route module.
=> Improve prefetch perf for CSS side effects

packages/react-router-dev/vite/plugin.ts, playground/framework-spa/package.json, pnpm-lock.yaml
The build config can be streamlined a bit since the client build was already providing the same config as our `vite preview` overrides. This meant that a `resolveBuildOptions` function was no longer needed since it's simple enough to inline the build config fallback now.
I've manually tested this in the `framework-spa` playground to ensure that `vite preview` still works.
=> Remove redundant Vite preview SPA build config

.changeset/witty-birds-fetch.md, packages/react-router/__tests__/router/navigation-test.ts, packages/react-router/lib/router/router.ts
Closes https://github.com/remix-run/react-router/issues/12926
=> Fix hash issue for matchRoutes optimization

.changeset/fast-olives-invent.md, packages/react-router-dev/bin.js
See https://github.com/vercel/arg#permissive
Closes #12606
=> Fix CLI arg parsing to allow usage with no arguments

README.md, contributors.yml
Change npm badge style for consistency.
Before:
After:
=> Change badge style

contributors.yml, tutorials/address-book/app/data.ts
After returning from the contacts/:contactId/edit  page to contacts/:contactId page active link styling will disappear for the contact that has first name and middle name like "Kent C.  + Doods" because the URL will be /contacts/kent c.-doods or /contacts/%20c.-doods.
So, in the /app/data.ts in the last line where ids are added for every contact created I fixed this small issue with the split and join methods on the contact.id so the sidebar NavLink styling is corrected.
=> edit: tutorial/address-book Active Link Styling in sidebar

.changeset/afraid-buses-pay.md, integration/helpers/vite.ts, integration/vite-dotenv-test.ts, packages/react-router-dev/vite/plugin.ts
=> Handle custom `envDir` in Vite config

packages/react-router-dev/vite/plugin.ts
When using the Environment API, a custom SSR build entry should be configured in the SSR environment, not the base `build` config.
=> Fix custom SSR environment build entry

.changeset/late-nails-hear.md, .changeset/rotten-numbers-bathe.md, integration/vite-prerender-test.ts, packages/react-router-dev/vite/plugin.ts
Closes https://github.com/remix-run/react-router/issues/12904
=> Skip action-only resource routes with prerender:true

.changeset/slow-coats-arrive.md, packages/react-router-dev/vite/cloudflare-dev-proxy.ts
Fixes: #12973
This change ensures that the side effect of creating the Cloudflare platform proxy doesn't happen when this plugin is used outside of a dev server context, e.g. our child compiler.
=> Lazy load Cloudflare platform proxy

.changeset/thick-meals-shout.md, contributors.yml, integration/vite-prerender-test.ts, packages/react-router-dev/vite/plugin.ts
Closes #12844 
This is the work from #13035 rebased onto `release-next`
=> fix: prerendering binary files

contributors.yml, packages/react-router-dev/README.md
Right now markdown file suggests installing react-router-dev as a runtime dependency instead of dev dependency
=> fix(react-router-dev): add --save-dev command on md

packages/react-router-dev/vite/plugin.ts, packages/react-router-dev/vite/styles.ts
This is a follow-up to #13008.
This PR makes the following refactors:
- Ensure the helper environment is only used for CSS. This is because the helper environment is Node-based and may differ from the `ssr` environment, e.g. when using vite-plugin-cloudflare. CSS is handled the same regardless of environment so it's safe to load from another environment, but we don't want to be loading arbitrary modules.
- In order to scope the helper environment to CSS, the server manifest is no longer loaded from the module graph during HMR. Instead, we now keep a reference to the current server manifest in memory.
- Hoists the CSS dev helper environment up to site alongside the other environments rather than being added on separately within the plugin.
=> Scope helper environment to only handle CSS

.changeset/new-houses-hug.md, packages/react-router-dev/vite/plugin.ts
We had one remaining usage of `ssrLoadModule` which I've now swapped for `environments.ssr.runner.import` when the Environment API future flag is enabled. This also means we now explicitly handle the case when the `ssr` environment has been defined by another plugin (e.g. vite-plugin-cloudflare) to be a custom `Vite.DevEnvironment` rather than a `Vite.RunnableDevEnvironment`. In this case, our middleware bails out and doesn't attempt to handle the request, assuming that it's going to be handled by the plugin that defined the custom `Vite.DevEnvironment`.
This also better prepares our codebase for future Vite releases where `ssrLoadModule` is not available.
=> Avoid `ssrLoadModule` usage with Vite Environment API

CHANGELOG.md, contributors.yml
The changelog for 7.2.0 has a minor typo. `path path` -> `bad path`
=> docs(CHANGELOG): fix typo

contributors.yml, packages/react-router-express/package.json
`express@5` is out, and is mostly compatible with `express@4` (see [the migration guide](https://expressjs.com/en/guide/migrating-5.html)). At least for React Router usage the differences should be immaterial.
This would allow users to integrate React Router into their existing `express@5` apps, or use `express@5` as a hosting server, without having to fiddle with `--legacy-peer-deps` or similar.
=> feat(express): support Express v5

.changeset/modern-forks-ring.md, integration/vite-spa-mode-test.ts, packages/react-router-dev/vite/plugin.ts
Since we only SSR the root route in SPA mode, we don't need to import any other routes in the server bundle; the bundle is solely used to generate the index.html file, and is subsequently discarded.
This should speed up SPA mode builds and make them less error prone; often times apps use libraries that are not SSR-capable (e.g. referencing window in the module scope). By excluding all other routes (and their deps), we make the index.html render more likely to be successful and less likely to require a bunch of shenanigans in vite.config.js.
cc @brophdawg11 
Closes https://github.com/remix-run/react-router/discussions/12360
=> Only import the root route when SSRing SPA mode's index.html

.changeset/gold-insects-remain.md, packages/react-router-dev/vite/plugin.ts
Fixes https://github.com/remix-run/react-router/issues/13071.
=> Fix support for custom `build.assetsDir`

.changeset/dry-impalas-live.md, integration/vite-prerender-test.ts, packages/react-router-dev/vite/plugin.ts
Fixes https://github.com/remix-run/react-router/issues/13069.
Since the server build virtual module now includes a query string when using the `serverBundles` option (e.g. `virtual:react-router/server-build?route-ids=home,about`), we need to ensure that we factor this into any logic that tries to find this virtual module in the Vite manifest.
Note that this issue actually highlighted a previously hidden issue where the build would have broken if you generate than 1 server bundle when using the `prerender` option. This is now also handled correctly.
=> Fix usage of `prerender` option with `serverBundles`

packages/react-router-dev/vite/plugin.ts, packages/react-router-dev/vite/styles.ts, packages/react-router/lib/dom/global.ts, packages/react-router/lib/dom/ssr/components.tsx, packages/react-router/lib/dom/ssr/entry.ts, packages/react-router/lib/server-runtime/build.ts, packages/react-router/lib/server-runtime/dev.ts, packages/react-router/lib/server-runtime/server.ts, packages/react-router/lib/server-runtime/serverHandoff.ts
Our current mechanism for rendering critical CSS in dev assumes that the SSR environment is running in the same Node process as the Vite dev server. If you're using a plugin that defines a non-Node SSR environment (e.g. vite-plugin-cloudflare) this mechanism fails to work. To fix this, when `future.unstable_viteEnvironmentApi` is enabled, we now manage critical CSS via a dynamic CSS file on the Vite dev server (available via `/@react-router/critical.css?pathname=...`) rather than trying to render the string of CSS inline. This ensures that the logic for calculating the critical CSS is always running within the same context as the Vite dev server.
=> Fix critical CSS with custom `Vite.DevEnvironment`

contributors.yml, docs/start/framework/pending-ui.md
Currently, the Task component has a type mismatch when handling form data. The `isComplete` variable is used as a boolean, but it's being directly assigned a string value from `formData.get()`, which causes inconsistent behavior when comparing states.
Before:
```tsx
isComplete = fetcher.formData.get("status");  // Returns string
```
After:
```tsx
isComplete = fetcher.formData.get("status") === "complete";  // Returns boolean
```
=> docs(pending-ui): optimistic ui type mismatch fix

.changeset/real-adults-protect.md, .changeset/tall-lamps-think.md, packages/react-router/lib/dom/ssr/fog-of-war.ts, packages/react-router/lib/router/router.ts, packages/react-router/lib/router/utils.ts, packages/react-router/lib/server-runtime/server.ts
This adds manifest version mismatch detection and forces a hard reload to get the user session onto the updated deployed version.  Similar concept that we use when we hard reload on a route module asset 404.
Closes #10455 
Closes https://github.com/remix-run/react-router/discussions/12951
=> Detect lazy route discovery manifest version mismatches and trigger reloads

.changeset/afraid-tigers-promise.md, packages/react-router-dev/vite/plugin.ts
Fixes #13091.
With the introduction of `future.unstable_splitRouteModules`, we added our own `build.rollupOptions.output.entryFileNames` config so that route chunk names would end up in the output (e.g. `assets/route-client-loader-HASH.js`). This took precedence over any user provided config.
This PR fixes this so any user-provided value for `build.rollupOptions.output.entryFileNames` takes precedence. It's worth calling out that our config is not required for the app to work, it's simply to make it easier to tell the chunks apart when debugging.
=> Fix custom client `build.rollupOptions.output.entryFileNames`

.changeset/pretty-flies-crash.md, integration/vite-server-bundles-test.ts, packages/react-router-dev/vite/build.ts, packages/react-router-dev/vite/plugin.ts
Fixes https://github.com/remix-run/react-router/issues/13104.
This fixes two issues:
- Since moving to the Vite Environment API, if a custom `build.rollupOptions.input` value was provided in the SSR build, this was not honoured when `serverBundles` were configured. This PR ensures that all SSR builds honour this value.
- Since the custom server entry imports `virtual:react-router/server-build`, this fails to account for the query string used to support `serverBundles` (e.g. `virtual:react-router/server-build?route-ids=foo,bar,baz`. This PR alters the logic for getting the route IDs of a server bundle build so they're no longer encoded in the query string. Instead, the server bundle ID is extracted from the environment name, and this is then used to look up its routes in the React Router …
=> Fix custom SSR build input with `serverBundles`

.changeset/ninety-otters-repeat.md, packages/react-router-dev/config/config.ts, packages/react-router-dev/vite/plugin.ts, packages/react-router-dev/vite/ssr-externals.ts, packages/react-router-dev/vite/vite-node.ts
Fixes https://github.com/remix-run/remix/issues/10324 which is also present in this repo.
See https://github.com/remix-run/remix/pull/10510 for more details.
=> Remove unused Vite file system watcher

contributors.yml, docs/start/library/routing.md
Fix the component name in the dynamic segment documentation.
=> docs(start/library/routing): fix component name

.changeset/yellow-glasses-sort.md, packages/react-router-dev/typegen/index.ts
Given the following file-system routes:
```ls
routes/base._index.tsx
routes/base._layout.tsx
routes/base._layout.child.tsx
```
The current typegen algorithm will create 2 entries for `"base": {}`, 1 each for the index and the layout, which is a type error.
This PR adds a filter to the Params generation to ignore layouts if a corresponding index is defined.
Addresses https://github.com/remix-run/react-router/issues/13059
=> do not typegen params for layout routes with a corresponding index

.changeset/yellow-glasses-sort.md, packages/react-router-dev/typegen/index.ts
Cherry-picking commit from #13131 into `dev` since that PR was (accidentally) merged into `main`
=> Fix duplicated entries in typegen for layout routes and their corresponding index route

.changeset/silver-peas-shop.md, integration/helpers/vite-plugin-cloudflare-template/workers/app.ts, integration/typegen-test.ts, packages/react-router-dev/typegen/index.ts, packages/react-router-dev/vite/plugin.ts, packages/react-router/lib/server-runtime/build.ts, packages/react-router/lib/server-runtime/server.ts, playground/vite-plugin-cloudflare/workers/app.ts
It's invalid to declare a module called `virtual:react-router/server-build` within an npm package, but it's valid within app code. In order to provide types for this virtual module, this PR writes a new file as part of the typegen flow that declares this module.
Shout out to Astro for this. They use a similar approach for their `astro:`-prefixed virtual modules.
=> Generate types for `virtual:react-router/server-build`

.changeset/dull-hotels-battle.md, integration/helpers/vite-plugin-cloudflare-template/package.json, integration/vite-plugin-cloudflare-test.ts, packages/react-router-dev/vite/plugin.ts, pnpm-lock.yaml
This allows plugins that override the default SSR environment (such as @cloudflare/vite-plugin) to be placed before or after the React Router plugin.
=> Support flexible ordering of Vite plugins that override SSR environment

.changeset/eleven-oranges-cheat.md, packages/react-router-dev/vite/plugin.ts
This removes the `configureServer` and `configurePreviewServer` hooks in child compiler plugins to avoid conflicts with the main dev server. In @cloudflare/vite-plugin, for example, this prevents creating an additional Miniflare instance. Removing `configurePreviewServer` isn't strictly necessary but seems worth doing for consistency.
=> Remove Vite server hooks in child compiler plugins

.changeset/few-months-begin.md, packages/react-router/lib/server-runtime/server.ts
=> Fix `RequestHandler` `loadContext` type when middleware is enabled

.changeset/cuddly-dots-hear.md, integration/split-route-modules-test.ts, packages/react-router-dev/vite/plugin.ts
Setting `future.unstable_splitRouteModules` to `"enforce"` breaks the build if the root route contains any exports that are candidates for splitting, even if they're splittable.
The root route is never split into multiple chunks since it's always loaded up-front, so it should be valid regardless of whether the exports are splittable or not. This PR ensures both splittable and unsplittable root route exports are now valid.
=> Fix validation of split route modules for root route

.changeset/three-oranges-sort.md, integration/single-fetch-test.ts, packages/react-router/lib/dom/ssr/single-fetch.tsx
=> Fix shouldRevalidate behavior in clientLoader-only routes

.changeset/plenty-jeans-lie.md, integration/fog-of-war-test.ts, packages/react-router/lib/server-runtime/server.ts
=> Ensure ancestor pathless/index routes are loaded via manifest requests

.changeset/four-ligers-search.md, integration/vite-spa-mode-test.ts, packages/react-router/lib/dom-export/hydrated-router.tsx
=> Fix root loader data on initial load redirects in SPA mode

contributors.yml, docs/hooks/use-blocker.md
Add a warning to inform `useBlocker` can only be used within a Data Router
=> docs(hooks/use-blocker): add warning about data routers

.changeset/clever-waves-drum.md, packages/react-router-dev/vite/plugin.ts
This error message includes `[Object object]` as the path because `path` is actually Node's path module. It should be using `prerenderPath` instead.
=> Fix path in prerender error message

.changeset/honest-moles-brush.md, integration/typegen-test.ts, packages/react-router-dev/typegen/index.ts
Fixes #13265.
I've added a test for this and validated that it fails if the fix hasn't been applied.
=> fix(dev/typegen): Fix virtual module typegen with `moduleDetection: "force"`

.changeset/green-windows-itch.md, packages/react-router/__tests__/router/data-strategy-test.ts, packages/react-router/__tests__/router/lazy-test.ts, packages/react-router/__tests__/router/utils/data-router-setup.ts, packages/react-router/lib/router/router.ts, packages/react-router/lib/router/utils.ts
This PR is in preparation for more granular `route.lazy` support. This updates the existing logic to ensure calls to `route.lazy` are deduped, which is how the more granular object-based API is intended to work. This also means that the tests are now updated to be more flexible in terms of the types for `route.lazy`, rather than testing using the `lazy: true` flag on the `TestRouteObject` type. This will make introducing object-based `route.lazy` tests much easier.
=> Dedupe calls to `route.lazy` functions

.changeset/gentle-gifts-kneel.md, packages/react-router/lib/router/utils.ts, packages/react-router/lib/types/route-module.ts
Closes https://github.com/remix-run/react-router/issues/13274
=> Fix middleware return types

.changeset/six-mugs-scream.md, integration/helpers/vite.ts, integration/vite-css-test.ts, packages/react-router-dev/vite/plugin.ts
=> Handle custom base for critical CSS with Vite Env API

contributors.yml, docs/upgrading/remix.md
In the upgrade guide it specified to use remix plugin, however this is incorrect, the correct plugin to use is reactRouter().
=> Updated the upgrade from remix guide to use the correct vite plugin

contributors.yml, docs/api/hooks/useNavigate.md
I found that the URL for the redirect  in the React Router documentation was incorrect. The original URL was:
https://reactrouter.com/api/Utils/redirect
It has been updated to the correct URL:
https://reactrouter.com/api/utils/redirect
=> fix wrong url in useNavigate.md 

packages/react-router/__tests__/router/data-strategy-test.ts, packages/react-router/__tests__/router/lazy-test.ts, packages/react-router/__tests__/router/utils/data-router-setup.ts
With the introduction of granular `route.lazy`, the patterns used in the tests became a bit inconsistent, but later PRs started landing on better patterns. This PR cleans things up and uses more consistent naming and patterns across all tests. Most notably, we're now avoiding the word `lazy` in variable names unless it refers to a `route.lazy` function.
=> Refactor lazy tests

.changeset/happy-spoons-watch.md, packages/react-router/__tests__/router/lazy-test.ts, packages/react-router/__tests__/router/utils/data-router-setup.ts, packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/dom-export/hydrated-router.tsx, packages/react-router/lib/dom/lib.tsx, packages/react-router/lib/router/router.ts
This PR takes advantage of the new granular `route.lazy` API by skipping unused hydration properties when we're done hydrating.
TODO:
=> Skip `route.lazy` hydration properties after hydration

.changeset/smart-ads-doubt.md, packages/react-router/__tests__/dom/data-static-router-test.tsx, packages/react-router/__tests__/router/lazy-test.ts, packages/react-router/__tests__/router/ssr-test.ts, packages/react-router/__tests__/server-runtime/server-test.ts, packages/react-router/lib/router/router.ts
Do not add `null` to `staticHandler.query()` `loaderData` if routes do not have loaders
This was an implementation detail required in Remix v2 because we used `JSON.stringify()` to serialize the `loaderData` of the client and it would strip `undefined` values which would cause issues for client-side router hydration.  This should have been removed in React Router v7 because Single Fetch does not have the same restrictions but it was missed.
We used to check `loaderData[routeId] !== undefined` to see if a given route already had any data or not.  Once we began allowing loaders to return `undefined`, our check of `loaderData[routeId] !== undefined` was no longer valid and we adjusted to a check of `routeId in loaderData`.  This check can produce false positives if null values are inserted. …
=> Stop inserting null placeholders for non-executed loaders in staticHandler.query

integration/split-route-modules-test.ts
Some of the expectations in these need to be async since the page might not have updated by the time they run. I've also bumped out the timeout waiting for the client loaders to be unblocked.
=> Fix flaky split route modules test

integration/action-test.ts, integration/blocking-test.ts, integration/client-data-test.ts, integration/error-boundary-test.ts, integration/fetch-globals-test.ts, integration/fetcher-test.ts, integration/link-test.ts, integration/multiple-cookies-test.ts, integration/redirects-test.ts, integration/resource-routes-test.ts, integration/revalidate-test.ts, integration/scroll-test.ts, integration/transition-test.ts
Some of our tests have unused imports from React Router that are no longer exported, leftover from the Remix migration. Vite builds with these without any issues, but `rolldown-vite` is more strict. This PR fixes the tests to help ensure `vite-ecosystem-ci` can pass against `vite-rolldown` without having to suppress these errors in Rolldown.
=> Remove missing react-router exports in tests

.changeset/silent-snakes-mix.md, packages/react-router/lib/dom/ssr/single-fetch.tsx, packages/react-router/lib/router/router.ts, packages/react-router/lib/router/utils.ts
Add the `unstable_runClientMiddleware` API to `dataStrategy` to allow users to run middleware inside of custom `dataStrategy` implementations
=> Add `unstable_runClientMiddleware` API for `dataStrategy`

packages/react-router/package.json, pnpm-lock.yaml
Types are includes as of `cookie@1.0.0`, so adding the extra types package is obsolete
References:
- https://github.com/jshttp/cookie/releases/tag/v1.0.0
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70892
---
Re-submission of @abdrahmanrizk's #12640
=> chore(react-router): remove `@types/cookie` dependency

contributors.yml, docs/start/modes.md
The current link: `./library/installation` returns a `404`.
The new link: `./declarative/installation` correctly routes to the installation guide for Declarative Mode.
=> docs: fix install link for Declarative Mode

.changeset/plenty-hounds-heal.md, contributors.yml, docs/api/utils/isSession.md, llm.txt, packages/react-router/__tests__/server-runtime/sessions-test.ts, packages/react-router/lib/server-runtime/sessions.ts
This pull request updates documentation, test cases, and code comments to reflect the transition from Remix to React Router terminology and URLs for session-related features.
=> update session documentation links

contributors.yml, docs/how-to/suspense.md
Mostly copied from the remix docs: https://remix.run/docs/en/main/guides/single-fetch#streaming-timeout
Discussed in an issue: https://github.com/remix-run/react-router/issues/12467
=> Add timeout section to streaming wiki

.changeset/silly-ligers-dress.md, packages/react-router/lib/dom/ssr/fog-of-war.ts
Closes https://github.com/remix-run/react-router/issues/13332
=> Don't trigger error boundary prior to lazy route discovery manifest mismatch reload

.changeset/pink-candles-allow.md, packages/react-router/__tests__/server-runtime/handle-error-test.ts, packages/react-router/lib/server-runtime/server.ts
Closes https://github.com/remix-run/react-router/issues/12704
=> fix handleError params values on dynamic param data calls

.changeset/bright-experts-grab.md, .changeset/cold-seals-count.md, .changeset/forty-ants-teach.md, packages/react-router-dev/cli/commands.ts, packages/react-router-dev/config/config.ts
Fixes #12390
This PR fixes a few issues that were raised by the issue linked above:
- When providing a custom Vite config via the CLI (e.g. `react-router dev --config apps/my-app/vite.config.ts`), the React Router project directory would still be `cwd`. This meant that you'd get an error about a missing root route even if it's present in the directory containing the Vite config. To fix this, if a custom Vite config path is provided, we now default the React Router project root to be the directory containing the custom Vite config.
- The logic for resolving the project root directory was duplicated across different commands. This PR introduces a `resolveRootDirectory` util which is used consistently across all commands. This gives us a central place to implement the fix mentioned above. …
=> Fix root directory resolution logic

packages/react-router/__tests__/server-runtime/handle-error-test.ts
This test was failing because the `routeDiscovery` object wasn't present on the mock server build. Note that TypeScript didn't pick this up in my editor because the `ServerBuild` type hadn't been imported, so I've added that too.
=> Fix handleError test

.changeset/little-cups-deliver.md, packages/react-router-dev/vite/vite-node.ts
Fixes https://github.com/remix-run/react-router/issues/12472.
tl;dr: Adding `css: { postcss: {} }` to our vite-node config is the equivalent of `configFile: false` but for PostCSS config files.
=> Ensure `vite-node` doesn't load PostCSS config

.changeset/rude-cobras-warn.md, packages/react-router-dev/vite/plugin.ts
Fixes https://github.com/remix-run/react-router/issues/13430
When `future.unstable_viteEnvironmentApi` is enabled, we were respecting the value for `environments.client.build.assetsDir` when configuring `build.rollupOptions.output.entryFileNames`, but we weren't falling back to the top-level `build.assetsDir` if it was missing.
This PR updates the logic so that the `assetsDir` value falls back to `build.assetsDir` if `environments.client.build.assetsDir` is not provided, before finally falling back to the default value of `"assets"`.
=> Fix `assetsDir` in `entryFileNames` with Vite Env API

.changeset/fast-planets-matter.md, packages/react-router/__tests__/router/router-test.ts, packages/react-router/lib/router/router.ts
Closes #12995 
Best viewed with whitespace hidden: https://github.com/remix-run/react-router/pull/13500/files?w=1
=> fix initial load 404 scenarios in data mode

.changeset/proud-needles-destroy.md, packages/react-router-dev/vite/plugin.ts, packages/react-router-dev/vite/styles.ts
Fixes https://github.com/remix-run/react-router/issues/13379
When we extract critical CSS during dev, we're currently doing this from the SSR environment, or a custom environment when using Vite's Environment API to support non-Node SSR environments. This seems to cause issues if the SSR environment differs from the client environment in terms of resolving CSS files. In the case of the linked issue above, our critical CSS extraction logic doesn't work for the virtual CSS modules that Pigment CSS introduces.
To fix this issue, we now request the same CSS that the browser does by passing the CSS URL to `viteDevServer.transformRequest`. The only down side of this approach is that it returns a string of JS code with the CSS embedded within it as a string (along with HMR code etc.). To work …
=> Get critical CSS in dev from client env

.changeset/thirty-bugs-jump.md, contributors.yml, packages/react-router/lib/components.tsx, packages/react-router/lib/context.ts, packages/react-router/lib/dom/ssr/errorBoundaries.tsx, packages/react-router/lib/dom/ssr/fallback.tsx, packages/react-router/lib/hooks.tsx
I noticed that the `💿 Hey developer 👋` warning for missing hydrate fallback was rendering on my prod application in addition to my dev environment. From looking in the code base, it looks like there is some precedent for only rendering these in dev. This PR tries to consolidate that and also updates the message to point at RR docs instead of Remix docs.
There are a ton of ways to do this, so curious for feedback! For example, I wasn't quite sure where the best place to consolidate `ENABLE_DEV_WARNINGS` was.
=> feat(react-router): only render dev warnings in dev

.changeset/ninety-snails-shout.md, packages/react-router/__tests__/dom/data-browser-router-test.tsx, packages/react-router/lib/router/history.ts, packages/react-router/lib/router/router.ts
Closes https://github.com/remix-run/react-router/issues/11188
Closes https://github.com/remix-run/react-router/issues/11429
Closes https://github.com/remix-run/react-router/issues/11911
=> Detect and handle leading double slash paths

.changeset/ten-pears-wash.md, packages/react-router-dev/config/config.ts, packages/react-router-dev/vite/build.ts
Fixes https://github.com/remix-run/react-router/issues/13078
We currently load the React Router config before starting the Vite build, but this is only done to load the future flags so we know whether to use the Vite Environment API powered build process or not. However, our config loading logic also evaluates `routes.ts`.
As a slight performance improvement and to keep the order of operations as similar as possible to `react-router dev` and `vite build`, we now skip evaluating `routes.ts` when loading future flags before the Vite build is started.
=> Skip unused `routes.ts` eval before Vite build

.changeset/breezy-pets-hug.md, integration/prefetch-test.ts, packages/react-router/__tests__/dom/dom-export-test.tsx, packages/react-router/tsup.config.ts
=> feat(react-router): don't bundle `react-router` in `react-router/dom` export

.changeset/late-hats-yell.md, packages/react-router/lib/dom/ssr/single-fetch.tsx
Closes https://github.com/remix-run/react-router/issues/12919
=> Preserve status code on clientAction throw data() results

.changeset/twenty-snakes-love.md, integration/single-fetch-test.ts, packages/react-router/__tests__/router/revalidate-test.ts, packages/react-router/lib/router/router.ts
Closes https://github.com/remix-run/react-router/issues/13442
=> Short circuit dataStrategy post processing on aborted requests

.github/workflows/integration-pr-windows-macos.yml, .github/workflows/shared-integration.yml
Attempt to fix timed out jobs such as https://github.com/remix-run/react-router/actions/runs/14783281251/job/41506683463
=> Add longer timeout for windows E2E CI runs

.changeset/eighty-mangos-move.md, packages/react-router-dev/vite/with-props.ts, packages/react-router/__tests__/dom/stub-test.tsx, packages/react-router/lib/dom/ssr/routes-test-stub.tsx
Closes https://github.com/remix-run/react-router/discussions/13032
=> Add component props support to createRoutesStub

packages/react-router/lib/rsc/server.ssr.tsx, packages/react-router/tsup.config.rsc.ts, packages/react-router/tsup.config.ts, playground/rsc-vite/src/ssr/entry.ssr.tsx
Delay decoding of the stream until we are inside of a "render to html" context. This allows React to use async localstorage to collect and flush assets for client components as they are discovered.
Before:
After:
=> fix: better flush assets as they are discovered for a flatter network.

packages/react-router/lib/hooks.tsx
As requested in https://discord.com/channels/770287896669978684/770287896669978687/1367235854757531759
=> feat(react-router): stabilize `useRevalidator`'s `revalidate`

.changeset/tough-dancers-own.md, integration/middleware-test.ts, packages/react-router/lib/dom/ssr/single-fetch.tsx, packages/react-router/lib/router/router.ts
=> Fix middleware error bubbling scenarios

.changeset/gold-socks-attack.md, .changeset/rude-lobsters-design.md, packages/react-router-dev/vite/plugin.ts
We currently log a message during the build when moving assets from the server build to the client, but we weren't logging anything when cleaning server assets that already exist in the client build. This led to some confusion because Vite logs that these files were generated, but after the build has finished the assets are no longer there.
To avoid this confusion, we now log whenever assets are handled in any way, not just when they're moved.
While working on this, I also realised that we don't honour the consumer's `build.ssrEmitAssets` option if they explicitly want to keep these assets, so the logic and logging has also been updated to account for this.
Before:
After:
=> fix(dev): improve server build asset handling

.changeset/tasty-beers-whisper.md, packages/react-router/lib/types/route-module.ts
Probably missed in @brophdawg11's #12941
Closes #13550
=> fix(react-router): fix `ClientDataFunctionArgs`' `context`

.changeset/loud-actors-shop.md, packages/react-router-architect/package.json, pnpm-lock.yaml
Re-submission of https://github.com/remix-run/remix/pull/7207
=> chore(architect): update `@architect/functions`

contributors.yml, docs/start/data/data-loading.md
Added the missing `async` keyword
=> docs(start/data/data-loading): fix typo

.changeset/big-ladybugs-brush.md, packages/react-router/lib/types/route-module.ts
Small miss in the new types that we had in Remix v2: https://github.com/remix-run/remix/pull/6231.  See the changeset for scenarios.
Closes #13541
=> Update Route.MetaArgs to reflect optional data

.changeset/purple-boats-bake.md, integration/fetcher-test.ts, packages/react-router/lib/router/router.ts
Closes https://github.com/remix-run/react-router/issues/13114
=> Avoid fetcher 404 when lazy route discovery is racing against a navigation

packages/react-router-dev/__tests__/route-config-test.ts, pnpm-lock.yaml
This PR fixes the following warnings when running our unit test suite:
```
Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
```
The CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```
=> Fix unit test warnings

packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/rsc/server.rsc.ts, playground/rsc-parcel/src/entry.browser.tsx, playground/rsc-parcel/src/entry.rsc.ts, playground/rsc-parcel/src/entry.ssr.tsx, playground/rsc-parcel/src/routes.ts, playground/rsc-parcel/tsconfig.json
The Parcel RSC playground currently isn't working in the `rsc` branch. To fix this, this PR updates all of the RSC entry code to use the latest APIs. However, this surfaced an issue with our use of client component imports within `react-router/rsc` (importing `UNSAFE_WithRouteComponentProps`, `UNSAFE_WithHydrateFallbackProps` and `UNSAFE_WithErrorBoundaryProps`).
For some reason this doesn't seem to work within this monorepo. The errors seem to indicate that Parcel isn't honouring the `"use client"` directive at the top of our `react-router` entry point when resolved within `react-router/rsc`. Since I already had a feeling this might fail in other scenarios (e.g. unbundled Vite dev server), I've modified the API a bit to handle this.
We now have a single component for wrapping route-level …
=> Fix Parcel RSC playground

.changeset/odd-hounds-ring.md, contributors.yml, packages/react-router-dev/vite/plugin.ts
Fixes https://github.com/remix-run/react-router/issues/13590
`entry.path` on `Dirent` is deprecated since a few versions and removed as of Node version 24 https://github.com/nodejs/node/pull/55548
https://nodejs.org/docs/latest-v23.x/api/fs.html#direntpath
Since RR declares engines as working with any minor/patch version above 20.x.x - I can’t just directly use the `parentPath` which is recommended now. I normalize it so it works also in few minors that have `dirent.path` but don't have `dirent.parentPath`. Also a bit of gymnastics for TS is needed because installed version of types for node doesn’t include the `parentPath`
=> Normalize `dirent` entry path across node versions when generating SRI manifest

.changeset/sweet-parents-hug.md, integration/typegen-test.ts, packages/react-router-dev/typegen/generate.ts
=> fix href optionals

packages/react-router/lib/rsc/server.rsc.ts
The dynamic import from `react-router` within `react-router/rsc` is being used to load the client component that wraps all route-level client components. This works within the context of the playground in this repo, but fails in the context of apps installing the package. Instead, we now statically import from `react-router` to get the fallback value. I've confirmed that this works in both the playground and as an experimental release.
=> Remove dynamic `react-router` import from RSC code

packages/react-router/lib/rsc/server.rsc.ts
The `error` prop passed to the `ErrorBoundary` was accidentally a match rather than the error.
=> Fix RSC ErrorBoundary error prop

.changeset/flat-seas-own.md, packages/react-router/lib/hooks.tsx
Partial revert of #12800/#12882
Closes https://github.com/remix-run/react-router/issues/13118, https://github.com/remix-run/react-router/issues/13159
=> Remove matchRoutes optimization from render pass

contributors.yml, docs/how-to/view-transitions.md
Noticed that there is no documentation around the `viewTransition` option in the `useNavigate` method
Also I arranged the ordering of headers
=> docs(how-to/view-transitions): add programmatic navigation example

contributors.yml, docs/start/framework/route-module.md
=> docs(start/framework/route-module): clarify the behaviour of multiple `meta` functions

.changeset/calm-pants-film.md, integration/prefetch-test.ts, packages/react-router-dev/vite/plugin.ts, packages/react-router-dev/vite/with-props.ts, packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/dom/ssr/routes-test-stub.tsx
This change was initially designed to expose these utils for use in the preview RSC Parcel plugin, but I realised this is a useful change to ship immediately since it results in 1 fewer network requests on page load. It also cleans up the internals quite a bit and removes some duplication between `react-router` and `@react-router/dev`.
Before:
After:
=> fix: move `with-props` runtime logic to core library

integration/helpers/rsc-parcel/src/entry.ssr.tsx, integration/helpers/vite.ts, integration/rsc/rsc-test.ts, integration/vite-css-test.ts
- wait on /favicon for integration test startup
- serve public assets in parcel rsc integration test fixture
- enable rsc error test for parcel
=> Enable rsc error test

integration/rsc/rsc-test.ts, packages/react-router/lib/hooks.tsx, packages/react-router/lib/rsc/browser.tsx, playground/rsc-vite/src/routes/home/home.client.tsx, playground/rsc-vite/src/routes/home/home.tsx
Suppress the internal thrown symbol as best as possible from error logs
=> wire thrown redirects from actions into the transition lifecycle

.changeset/two-needles-sell.md, contributors.yml, packages/react-router-dev/typegen/generate.ts
https://github.com/remix-run/react-router/pull/12440 introduced a fix for tsconfig, however, it broke non-JS routes (like .mdx)
When we have a file `./app/routes/test/index.mdx` which is a route we get the following error:
```
.react-router/types/app/routes/test/+types/index.ts:10:29 - error TS2307: Cannot find module '../index.js' or its corresponding type declarations.
10 type Module = typeof import("../index.js")
~~~~~~~~~~~~~
```
=> fix(dev/typegen): fix non-JS/TS files

.changeset/tasty-peas-retire.md, contributors.yml, packages/react-router-fs-routes/normalizeSlashes.ts, packages/react-router-remix-routes-option-adapter/normalizeSlashes.ts
Splitting and joining is slow and results in garbage collection each time. We can instead use a string `replaceAll` for a small perf gain.
=> perf: use `replaceAll` for slash normalisation

packages/react-router/__tests__/router/fetchers-test.ts
This is a follow-up to https://github.com/remix-run/react-router/pull/13709, adding a unit test that fails in dev but passes with the fix merged into `rsc`.
=> Add pathless fog of war test to fetchers unit tests

integration/helpers/rsc-parcel/src/routes/home.tsx, integration/rsc/rsc-test.ts, packages/react-router/lib/rsc/server.rsc.ts, playground/rsc-parcel/src/routes/about/about.client.tsx, playground/rsc-parcel/src/routes/about/about.tsx, playground/rsc-parcel/src/routes/fetcher/fetcher.client.tsx, playground/rsc-parcel/src/routes/fetcher/fetcher.ts, playground/rsc-parcel/src/routes/home/home.client.tsx, playground/rsc-parcel/src/routes/home/home.tsx, playground/rsc-parcel/src/routes/root/root.client.tsx, playground/rsc-parcel/src/routes/root/root.tsx, playground/rsc-vite/src/routes/about/about.client.tsx, playground/rsc-vite/src/routes/about/about.tsx, playground/rsc-vite/src/routes/child/child.tsx, playground/rsc-vite/src/routes/home/home.tsx, playground/rsc-vite/src/routes/parent-index/parent-index.tsx, playground/rsc-vite/src/routes/parent/parent.tsx, playground/rsc-vite/src/routes/root/root.tsx
This brings it in line with the existing Data Mode API, making `default` more of a Framework Mode opinion.
=> feat(react-router): rename RSC `default` route property to `Component`

integration/package.json, pnpm-lock.yaml
~~This upgrades from `npm-run-all` to `npm-run-all2`. Primarily because the latter is actively maintained, has security updates and a reduced footprint in the dependency tree.~~
~~I'm sure people from the wider @e18e ecosystem cleanup (like @43081j) will be very happy to see these kind of changes as well~~
This package isn't used by any of the code, so it can be removed
=> chore: remove unused `npm-run-all` dependency

.changeset/weak-turkeys-pretend.md, integration/typegen-test.ts, packages/react-router/lib/types/route-data.ts, packages/react-router/lib/types/route-module-annotations.ts
You MUST annotate `clientLoader` with `Route.ClientLoaderArgs` for types to distinguish a client loader from a server loader. See changeset for details.
=> Do not serialize types for `useRouteLoaderData<typeof clientLoader>()`

.github/workflows/deduplicate-lock-file.yml
This way we don't have to do PRs like #13674 manually anymore
=> chore: fix "⚙️ Deduplicate lock file" workflow

.github/workflows/deduplicate-lock-file.yml
Here's the most recent run failure: https://github.com/remix-run/react-router/actions/runs/15478040730/job/43578103541
I'm trying to mirror what the format action does: https://github.com/remix-run/react-router/blob/main/.github/workflows/format.yml#L44-L45
Let's see if this works...
=> Attempt to fix the deduplicate-lock-file action

integration/helpers/rsc-parcel/src/routes/home.tsx, integration/rsc/rsc-test.ts, packages/react-router/lib/rsc/server.rsc.ts, playground/rsc-parcel/src/routes/about/about.client.tsx, playground/rsc-parcel/src/routes/about/about.tsx, playground/rsc-parcel/src/routes/fetcher/fetcher.client.tsx, playground/rsc-parcel/src/routes/fetcher/fetcher.ts, playground/rsc-parcel/src/routes/home/home.client.tsx, playground/rsc-parcel/src/routes/home/home.tsx, playground/rsc-parcel/src/routes/root/root.client.tsx, playground/rsc-parcel/src/routes/root/root.tsx, playground/rsc-vite/src/routes/about/about.client.tsx, playground/rsc-vite/src/routes/home/home.tsx, playground/rsc-vite/src/routes/parent-index/parent-index.tsx, playground/rsc-vite/src/routes/parent/parent.tsx, playground/rsc-vite/src/routes/root/root.tsx
This is a follow-up to https://github.com/remix-run/react-router/pull/13726, adding back support to `default` exports from lazy route modules, but only as a fallback for `Component`. The top-level route property is still `Component` rather than `default`.
=> Support RSC lazy `default` export as `Component` fallback

.changeset/silent-boxes-sell.md, packages/react-router-cloudflare/package.json
I guess this was added by accident in @jacob-ebey's #12136
---
I'm sure people from the wider @e18e ecosystem cleanup (like @43081j & @outslept) will be very happy to see these kind of changes as well
=> fix(cloudflare): remove `tsup` from `peerDependencies`

docs/start/framework/routing.md
clarifies 404 route based on https://github.com/remix-run/react-router/discussions/13701#discussioncomment-13386093
=> docs(start/framework/routing): add 404 route instructions

docs/how-to/file-route-conventions.md
followup to https://github.com/remix-run/react-router/pull/13764 to document 404 with file routing
=> 404 route to file routing doc

packages/react-router/lib/rsc/browser.tsx, packages/react-router/lib/rsc/server.rsc.ts
This is so we can detect whether routes without an element require an RSC render pass to get one. This is used for hydration and during client navigations to routes with client loaders.
=> Add `hasComponent` to RSC route manifest

contributors.yml, docs/how-to/accessibility.md
Add the [accessibility](https://remix.run/docs/en/main/guides/accessibility) docs from Remix as it is useful for people understand what is the scope of React Router regarding accessibility
=> docs: add `how-to/acessibility`

contributors.yml, decisions/0003-data-strategy.md, decisions/0005-remixing-react-router.md
**Description:**  
This pull request makes the following changes:
- Corrects a typo in the word "information" in the `0003-data-strategy.md` decision document.
- Updates the component name from `MyOldCatchBoundary` to `MyOldCatchBoundary` (removes the typo) in the `0005-remixing-react-router.md` decision document for consistency.
These changes improve documentation clarity and maintain consistency in component naming. No functional code changes are included.
=> docs(decisions): fix typos

.changeset/tender-snails-attack.md, packages/react-router-dev/__tests__/route-config-test.ts, packages/react-router-dev/config/routes.ts
=> fix: Add validation for a route's id not being 'root'

.changeset/large-points-arrive.md, contributors.yml, packages/react-router-dev/config/config.ts
Skip `package.json` file checks when a user-supplied entry.server file is present
=> fix(dev/config): skip `package.json` resolution with custom `server.entry`

packages/react-router/index.ts, packages/react-router/lib/dom/ssr/routes.tsx, packages/react-router/lib/rsc/browser.tsx, packages/react-router/lib/rsc/errorBoundaries.tsx, packages/react-router/lib/rsc/server.ssr.tsx
This is exported so that the Parcel plugin can use the Framework Mode style default ErrorBoundary. Our current integration tests depend on this being present.
=> fix(rsc): export default root ErrorBoundary

docs/api/hooks/useBlocker.md
Resolves #12628
- Finishes `Params` section
- Adds `Blocker` section
=> docs(api/hooks/useBlocker): finish doc

.github/workflows/release.yml
Reverts remix-run/react-router#13677
Changesets shipped a regression in 1.5 which caused tags not to push to github: https://github.com/changesets/action/issues/465#issuecomment-2895839548. We had pinned to 1.4 to avoid that (https://github.com/remix-run/react-router/commit/ddf8e164ec4690c7a83ff160012be2bb908d5833) but dependabot noticied and opened a PR to bump us back to 1.5 which re-introduced the tag issue (https://github.com/remix-run/react-router/pull/13677)
=> Revert "Bump changesets/action from 1.4.10 to 1.5.3"

docs/tutorials/quickstart.md
=> docs(tutorials/quickstart): fix grammar + remove duplicate link

docs/api/rsc/RSCHydratedRouter.md, docs/api/rsc/RSCStaticRouter.md, docs/api/rsc/getRSCStream.md, docs/api/rsc/matchRSCServerRequest.md, docs/api/rsc/routeRSCServerRequest.md, docs/start/rsc/installation.md, integration/helpers/rsc-parcel-framework/package.json, integration/helpers/rsc-parcel/src/browser.tsx, integration/helpers/rsc-parcel/src/routes.ts, integration/helpers/rsc-vite/src/entry.browser.tsx, integration/helpers/rsc-vite/src/routes.ts, integration/rsc/rsc-test.ts, packages/react-router/index-react-server.ts, packages/react-router/index.ts, packages/react-router/lib/rsc/browser.tsx, packages/react-router/lib/rsc/html-stream/browser.ts, packages/react-router/lib/rsc/server.rsc.ts, packages/react-router/lib/rsc/server.ssr.tsx, playground/rsc-parcel-framework/package.json, playground/rsc-parcel/src/entry.browser.tsx, playground/rsc-parcel/src/routes.ts, playground/rsc-vite/src/entry.browser.tsx, playground/rsc-vite/src/routes.ts, pnpm-lock.yaml
This also adds a new `RSCRouteConfig` type which mirrors our existing `RouteConfig` type so that route config can be typed with `satisfies RSCRouteConfig`.
=> fix(rsc): rename "server" APIs to use "RSC"

.changeset/polite-fans-rhyme.md, contributors.yml, integration/vite-prerender-test.ts, packages/react-router/lib/server-runtime/server.ts
=> feat(react-router): support unencoded UTF-8 routes in prerender config with `ssr` set to `false`

docs/api/framework-conventions/react-router.config.ts.md, docs/explanation/lazy-route-discovery.md
This is a reworking of the [Remix "fog of war" doc](https://remix.run/docs/en/main/guides/lazy-route-discovery)
I used an LLM to rewrite it, removing "before and after" explanations, and formatting it similarly to other "explanation" docs.
I then edited the content, primarily deleting things and shuffling around sections, making very few additions.
Please let me know if something is wrong or missing!
Resolves #12826
=> docs: add Lazy Route Discovery doc

contributors.yml, docs/api/components/Await.md
Currently, in the documentation at the `docs/api/components/Await.md` section, the sample loader function uses an await in the fetch:  `const book = await fetch("/api/book").then((res) => res.json() );`, however, the function declaration does not have the `async` keyword.  This pull request aims to update the documentation for the loader function by adding the `async` keyword to the function in order to prevent a syntax error if someone inadvertently do a copy and paste.
=> docs: Added async keyword to the loader function in the Await documentation

.changeset/calm-swans-tap.md, packages/react-router-dev/vite/node-adapter.ts
Resubmission of @TrySound's https://github.com/remix-run/remix/pull/10199
> We use https for development at Webstudio.
> While setup we found some requests always have "http" protocol. Turns out origin is not sent with get requests and node-adapter falls back into "http".
>
> Here added https detection based on express internals.
=> fix(dev/vite): properly handle `https` protocol in dev mode

integration/helpers/rsc-parcel-framework/app/entry.browser.tsx, integration/helpers/rsc-parcel-framework/app/entry.rsc.ts, integration/helpers/rsc-parcel-framework/app/index.ts
This decouples our test suite from the higher level conveniences of the Parcel plugin to ensure we're exposed to it as little as possible. Now, we're only testing against the `virtual:react-router/routes` virtual module.
=> test(rsc): provide custom rsc-parcel-framework entries

.changeset/honest-socks-fail.md, packages/react-router/__tests__/router/lazy-discovery-test.ts, packages/react-router/lib/router/router.ts
Cherry-pick'd https://github.com/remix-run/react-router/pull/12899 into v7 since we forgot to do that we we landed it in v6 (fixes v7 regression of https://github.com/remix-run/react-router/issues/12896).
=> fix(react-router): strip search params from FOW path parameter

contributors.yml, docs/upgrading/remix.md
This adds a note about how to use folder based routing convention for folks migrating from Remix v1.
=> Adds Remix v1 route convention usage in Upgrading Remix doc

docs/explanation/backend-for-frontend.md, docs/explanation/code-splitting.md, docs/explanation/concurrency.md, docs/explanation/hot-module-replacement.md, docs/explanation/lazy-route-discovery.md, docs/explanation/progressive-enhancement.md, docs/explanation/state-management.md, docs/explanation/type-safety.md, docs/how-to/accessibility.md, docs/how-to/client-data.md, docs/how-to/error-boundary.md, docs/how-to/error-reporting.md, docs/how-to/fetchers.md, docs/how-to/file-route-conventions.md, docs/how-to/file-uploads.md, docs/how-to/form-validation.md, docs/how-to/headers.md, docs/how-to/navigation-blocking.md, docs/how-to/pre-rendering.md, docs/how-to/presets.md, docs/how-to/resource-routes.md, docs/how-to/route-module-type-safety.md, docs/how-to/security.md, docs/how-to/server-bundles.md, docs/how-to/spa.md, docs/how-to/status.md, docs/how-to/suspense.md, docs/how-to/view-transitions.md
Add's a MODES bar to all docs in the Explanation/How To sections that didn't already have one
=> docs: Add modes to all explanation/how to

.changeset/dirty-dolls-pay.md, packages/react-router-dev/config/config.ts
=> fix: allow .mjs extension for route config file

contributors.yml, packages/react-router/lib/router/router.ts
The way the `BlockerBlocked` interface is defined fails the [unbound-method](https://typescript-eslint.io/rules/unbound-method/) ESLint rule with code like this:
```
const { state, proceed } = useBlocker(hasUnsavedChanges);
useEffect(() => {
if (state === 'blocked') {
dialog('You have unsaved changes. Are you sure you want to leave?', {
onAccept: () => {
proceed();
},
});
}
}, [dialog, state, proceed]);
```
Because the `reset` and `proceed` function aren't methods of a class, it's more precise to type them as arrow functions, i.e., without a `this` variable.
=> fix(react-router): fix `Blocker` type

docs/explanation/form-vs-fetcher.md
Porting over [this Remix doc](https://remix.run/docs/en/main/discussion/form-vs-fetcher) to React Router
If you review, please note any examples that did not get converted correctly, or any explanations that no longer make sense
Resolves #12818
=> docs: add form-vs-fetcher doc

integration/helpers/rsc-parcel-framework/package.json, integration/helpers/rsc-parcel/package.json, integration/helpers/rsc-vite/package.json, pnpm-lock.yaml
These are used when debugging integration tests in the `.tmp/integration` directory, but they're currently not working correctly.
=> test(rsc): fix RSC integration fixture start scripts

.changeset/great-lobsters-raise.md, contributors.yml, packages/react-router-dev/vite/static/refresh-utils.cjs, packages/react-router/__tests__/dom/ssr/components-test.tsx, packages/react-router/lib/dom-export/hydrated-router.tsx, packages/react-router/lib/dom/global.ts
=> fix: clear critical css after initial render in HydratedRouter

.changeset/proud-scissors-tickle.md, contributors.yml, packages/react-router/lib/dom/lib.tsx
Some tooling might pass arbitrary strings in the `window.location.hash`. React Router should not crash if the value is not decodable.
In our case, for example, a user interacted with a URL that Datadog injected some tracking info into and the call turned to:
```ts
decodeURIComponent("targetindividualusers---input-raw%20:9999%20--output-http%20OVERRIDE_TARGET|OVERRIDE_PERCENT%%20--http-rewrite-url%20v5/onboarding:v6/interstitials%20--http-set-header%20X-Datadog-Parent-Id:%20--http-set-header%20X-Datadog-Trace-Id:%20--http-set-header%20X-Datadog-Sampling-Priority:1%20--http-allow-url%20/content/v5/onboarding")
```
...which crashed the view with the following error:
```
Uncaught URIError: malformed URI sequence
```
To avoid this in the future, I would like to suggest that a failure to decode …
=> Do not throw if the url hash is not a valid URI component

.changeset/cyan-bags-thank.md, integration/helpers/vite.ts, integration/vite-css-test.ts, packages/react-router-dev/vite/plugin.ts
Fixes https://github.com/remix-run/react-router/issues/13620
=> fix(dev/vite): Fix missing styles when Vite's `build.cssCodeSplit` is disabled

packages/react-router/lib/rsc/server.rsc.ts
I mistakenly included logic for retrieving errors from child routes and bubbling them up, but this is redundant in this context since the static handler already does this.
=> fix(rsc): remove manual error bubbling

.changeset/fuzzy-bottles-itch.md, packages/react-router/lib/rsc/server.rsc.ts
Always include additional route patches in payload to aid in SPA / "lazy" discovery cases. Remove unnecessary changeset.
=> Always include additional route patches

.changeset/lucky-hotels-complain.md, packages/react-router/lib/dom-export/hydrated-router.tsx, packages/react-router/lib/dom/ssr/components.tsx
Fixes the issue raised in this comment: https://github.com/remix-run/react-router/issues/13589#issuecomment-3064628231
See the comment in the code for more details about the fix.
=> Remove leftover critical CSS on hydration mismatch

CHANGELOG.md, docs/start/modes.md, docs/upgrading/component-routes.md, docs/upgrading/remix.md, docs/upgrading/router-provider.md
**Justification**:
In the context of computer science and programming, the word **"type-safe"** is used as a compound adjective modifying a noun.  This is the prevailing usage of the word, and is **already** used like this in other places in the documentation.  This pull request aims for consistency within the docs, and general English taxonomy.
=> docs: fix grammar

.changeset/neat-jeans-sneeze.md, integration/rsc/rsc-test.ts, packages/react-router/index-react-server-client.ts, packages/react-router/index.ts, packages/react-router/lib/components.tsx, packages/react-router/lib/rsc/browser.tsx, packages/react-router/lib/rsc/server.rsc.ts
We're now wrapping all client route components to ensure that all props match the equivalent values you'd get from the hooks, e.g. `loaderData` will include client loader data, whereas previously this prop would only ever be the server loader data.
=> Inject client route component props during RSC render

contributors.yml, docs/upgrading/v6.md
The **"V6 Migration"** contains a **"Update relative links"** section which shows that the `/` link should be updated to `../`, which I believe isn't correct.
This PR changes that.
=> docs(v6migration): absolute link should not be changed to relative

contributors.yml, scripts/docs.ts
When fixing #14017, and test-generating the markdown files I noticed that all the relative references to local files generated with the slashes swapped. I'm on Windows. This change replaces the `"\"` with `"/"` at the source of generating the relative path on `path.relative()` in the `scripts/docs.ts` file.
No changeset because this is documentation mechanics.
=> fix(jsdoc) Normalize generated path on Windows

.changeset/proud-dingos-nail.md, packages/react-router/lib/rsc/server.rsc.ts
This fixes `Matched leaf route at location "/..." does not have an element or Component` warnings when error boundaries are rendered.
=> Fix RSC outlet fallback warnings on error

.changeset/shiny-owls-glow.md, contributors.yml, packages/react-router/lib/rsc/server.rsc.ts
Fixes #14042 by removing the declaration of the `___reactRouterServerStorage___` variable from the global scope in the TypeScript declaration files. If it's desirable for this to exist in the declaration file, then I can explore other options, but it seems like somewhat of a private variable that doesn't need to be in the declaration files.
=> fix(react-router/rsc): remove dependency on `@types/node` in TypeScript declaration files

integration/client-data-test.ts
The usage of `test.skip` was nested in a way that resulted in more tests being skipped than expected. This meant that the RSC tests weren't running for this test. I've moved the `test.skip` calls down into the next describe block to fix this problem, but this surfaced a failing test. For now we're skipping this with `test.fixme` and will address it in a future PR.
=> Fix RSC client data tests

contributors.yml, docs/explanation/code-splitting.md
👋 Just spotted this misplaced word while reading your docs on code splitting.
=> docs(explanation/code-splitting): fix typo

packages/react-router/lib/components.tsx, packages/react-router/lib/dom-export/hydrated-router.tsx
=> docs(api): add some extra reference links

.changeset/giant-ligers-mix.md, packages/react-router/lib/dom/ssr/components.tsx, packages/react-router/lib/router/links.ts
Closes #14053
CC/ @luzat @outofthisworld
=> feat(react-router): add `nonce` prop to `Links` & `PrefetchPageLinks`

.changeset/good-months-hope.md, contributors.yml, packages/react-router/lib/dom/ssr/fog-of-war.ts
This PR improves the performance of `fetchAndApplyManifestPatches` by avoiding direct mutation of `url.searchParams`, which turns out to be _unbelievably_ slow (the `sort()` is absolutely fine in comparison).
https://issues.chromium.org/issues/331406951
https://github.com/nodejs/node/issues/51518
This resolves [#14075](https://github.com/remix-run/react-router/issues/14075), where this performance bottleneck became noticeable when preloading thousands of paths during fog-of-war route discovery.
As @brophdawg11 notes in the issue, there's definitely room for algorithmic improvements on top of this — but figured it was worth sending this simple (but significant) optimisation initially as it's an easy win.
=> perf: avoid slow searchParams mutation in manifest prefetching

.changeset/cool-pigs-cheer.md, packages/react-router/__tests__/router/context-middleware-test.ts, packages/react-router/lib/router/router.ts, packages/react-router/lib/server-runtime/server.ts
Closes: https://github.com/remix-run/react-router/issues/13936
Supersedes: https://github.com/remix-run/react-router/pull/13962
=> Ensure resource route errors go through handleError w/middleware enabled

.changeset/grumpy-frogs-greet.md, .changeset/neat-dolls-join.md, packages/react-router/__tests__/router/context-middleware-test.ts, packages/react-router/lib/router/router.ts
Closes #13659 as well as an issue raised in #13766
=> Handle middlewares returning responses without calling next

.changeset/rotten-foxes-deliver.md, contributors.yml, packages/react-router/lib/rsc/server.ssr.tsx
This commit addresses webpack module resolution errors that occur when bundling React Router's RSC features in React 18 environments, where React.use does not exist.
**Problem:**
Webpack's static analysis phase occurs before any runtime code executes. When webpack encounters `React.use(getPayload())` in the source code, it attempts to validate that the `use` export exists in the React module during build time. In React 18, this export doesn't exist, causing the build error:
```
export 'use' (imported as 'React5') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, act, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, …
```
=> React 18 "React.use" webpack fix

.changeset/young-beans-sneeze.md, integration/client-data-test.ts, packages/react-router/lib/rsc/server.rsc.ts
This is a follow-up to https://github.com/remix-run/react-router/pull/14060, fixing the test that was skipped with `test.fixme`.
=> Fix RSC bug where outlets replace routes that skip revalidation

integration/helpers/cloudflare-dev-proxy-template/package.json, packages/react-router-cloudflare/package.json, pnpm-lock.yaml
While we're at it, this also gets rid of an install warning
```sh
 WARN  Issues with peer dependencies found
integration/helpers/cloudflare-dev-proxy-template
└─┬ wrangler 4.23.0
└── ✕ unmet peer @cloudflare/workers-types@^4.20250617.0: found 4.20250317.0
```
=> chore(deps): update `@cloudflare/workers-types`

.changeset/purple-papayas-applaud.md, integration/helpers/rsc-vite-framework/tsconfig.json, integration/link-test.ts, integration/vite-hmr-hdr-test.ts, packages/react-router/lib/dom/ssr/components.tsx, packages/react-router/lib/rsc/browser.tsx, packages/react-router/lib/rsc/route-modules.ts, packages/react-router/lib/rsc/server.ssr.tsx
The `meta` and `links` exports are not expected to be on the route object itself, but rather in the `routeModules` object. To fix this, we now manage the minimal set of route module exports for these to work.
=> Handle `meta` and `links` route exports in RSC

docs/api/other-api/dev.md
As a follow-up to https://github.com/remix-run/react-router/pull/14144, this is a port of the [Remix CLI docs](https://github.com/remix-run/remix/blob/6d6caaed5dfc436242962dcb2ff9617757a11e17/docs/other-api/dev.md), with all references to Remix updated, and all irrelevant details removed.
I've also added docs for the `reveal`, `routes` and `typegen` commands as these were missing in the original docs.
=> Add docs for react-router CLI

integration/client-data-test.ts
The client data integration tests are _really_ slow because every test case runs its own build, and each test case is run 2–3 times across Vite 5, Vite 5 + Split Route Modules, and RSC Framework Mode.
This PR makes the test a lot faster by making each test fixture its own set of routes rather than a standalone build. The code obviously isn't as clean, but it's much faster now since only 3 builds are required.
=> Use shared build for client data integration tests

integration/helpers/rsc-vite-framework/package.json, integration/helpers/vite.ts, integration/mdx-test.ts, integration/vite-plugin-order-validation-test.ts, package.json, packages/react-router-dev/vite/build.ts, packages/react-router-dev/vite/dev.ts, packages/react-router-dev/vite/plugin.ts, packages/react-router-dev/vite/plugins/validate-plugin-order.ts, packages/react-router-dev/vite/rsc/plugin.ts, patches/@mdx-js__rollup.patch, playground/rsc-vite-framework/app/root.tsx, playground/rsc-vite-framework/app/routes/mdx/route.mdx, playground/rsc-vite-framework/mdx.d.ts, playground/rsc-vite-framework/package.json, playground/rsc-vite-framework/vite.config.ts, pnpm-lock.yaml
Note that this feature depends on this PR to `@mdx-js/rollup` being published: https://github.com/mdx-js/mdx/pull/2629. For now, this fix is provided as a patch in this PR.
=> Add MDX route support to RSC Framework Mode

contributors.yml, docs/start/data/installation.md
See the note on: https://reactrouter.com/api/data-routers/RouterProvider - The RouterProvider docs says to prefer the import from `react-router/dom` over `react-router`, but the [installation docs on data mode](https://reactrouter.com/start/data/installation#create-a-router-and-render) uses the one from `react-router`.
=> docs: update imports in installation.md

docs/start/data/installation.md
Highlight the correct lines (got broken in #14176).
Broken version:
Before #14176:
=> docs(start/data/installation): fix code highlighting

.changeset/heavy-months-work.md, docs/how-to/middleware.md, packages/react-router/__tests__/router/context-middleware-test.ts, packages/react-router/lib/router/router.ts
https://github.com/remix-run/react-router/issues/13766#issuecomment-3189670498
~~Stacked on https://github.com/remix-run/react-router/pull/14181~~
When throwing from a server `middleware` on a document/data request, only redirects are returned verbatim - anything else thrown will bubble to the error boundary (including `Response`, `data`, `Error`, etc.)
=> Propagate middleware thrown non-redirect responses to the boundary

.changeset/real-rules-compare.md, packages/react-router/__tests__/router/lazy-discovery-test.ts, packages/react-router/lib/router/router.ts
Closes https://github.com/remix-run/react-router/pull/12493
=> Fix TypeError if you throw from patchRoutesOnNavigation when no partial matches exist

.changeset/quiet-cows-build.md, integration/middleware-test.ts, packages/react-router/lib/server-runtime/server.ts, packages/react-router/lib/server-runtime/single-fetch.ts
This dedupes a good bit of code and keeps the middleware chain a bit more consistent between document/data requests since you can now inspect and "see" a redirect in both cases and you don't have to be aware of the implementation detail that is the turbo-stream encoding and the 202 response.  We just wait until right before we send the response before we serialize it via turbo-stream.
```tsx
function middleware() {
let res = await next();
// Currently, `res` would be a 202 response on `.data` requests and you can't easily 
// see the location because it's encoded in the body.
// Now, it's a standard 3xx redirect with a `Location` header on both document 
// and data requests
return res;
}
function loader() {
return redirect('/');
}
```
=> Delay turbo-stream serialization of .data redirects

integration/helpers/rsc-vite-framework/package.json, integration/helpers/vite.ts, integration/vite-css-test.ts, packages/react-router-dev/vite/rsc/virtual-route-modules.ts, packages/react-router/lib/rsc/server.ssr.tsx, pnpm-lock.yaml
The existing `vite-css` integration test wasn't being run against RSC Framework Mode. As part of this PR, I've ensured that these tests are now running against RSC Framework Mode and fail without the fix introduced in this PR.
=> Inject CSS into server-first routes in RSC Framework Mode

integration/helpers/rsc-parcel/src/routes/root.tsx, integration/helpers/rsc-vite-framework/package.json, integration/helpers/rsc-vite/package.json, integration/vite-css-test.ts, packages/react-router-dev/package.json, packages/react-router/lib/rsc/server.ssr.tsx, playground/rsc-vite-framework/package.json, playground/rsc-vite/package.json, pnpm-lock.yaml
This doesn't get us to 100% support, but this solves a number of issues and ensures the tests are passing against the fixes:
- Updated `@vitejs/plugin-rsc` to fix an issue where it was removing link tags that were rendered by our `Links` component.
- Cloned `serverResponse` to detect redirects to fix an issue where CSS was missing on page load in dev when using floated link tags.
- Updated `vite-css-test.ts` so that we're running all passing test cases with comments explaining what's left to fix.
=> Improve CSS HMR in RSC Framework Mode

integration/helpers/rsc-vite-framework/package.json, integration/helpers/rsc-vite/package.json, integration/vite-css-test.ts, packages/react-router-dev/package.json, playground/rsc-vite-framework/package.json, playground/rsc-vite/package.json, pnpm-lock.yaml
This PR updates `@vitejs/plugin-rsc` to v0.4.24 which includes a fix for HMR of CSS `?url` imports. The CSS integration test has been updated so all passing test cases are now enabled.
=> Improve CSS `?url` HMR in RSC Framework Mode

contributors.yml, docs/index.md
Updated the Data mode link in the Getting Started section from `./start/data/custom` to `./start/data/installation`.
- Changed the Data guide link to point to the installation page, matching the pattern used for the Declarative and Framework modes.
- This ensures all Getting Started links consistently point to installation instructions, making the documentation more predictable for users.
Previously, the Data guide link directed to a custom guide, whereas other mode links pointed to installation guides. By aligning all links to installation pages, users can reliably find setup information regardless of mode.
=> docs: fix Data mode link to point to installation guide for consistency

integration/helpers/rsc-vite-framework/package.json, integration/helpers/rsc-vite/package.json, integration/vite-css-test.ts, integration/vite-hmr-hdr-test.ts, packages/react-router-dev/package.json, playground/rsc-vite-framework/package.json, playground/rsc-vite/package.json, pnpm-lock.yaml
This PR updates `@vitejs/plugin-rsc` to v0.4.25 to address HMR issues fixed in this PR: https://github.com/vitejs/vite-plugin-react/pull/788. This allows us to re-enable some of our CSS HMR tests in RSC Framework Mode.
=> Update `@vitejs/plugin-rsc` to fix HMR issues

.changeset/cool-readers-attack.md, integration/helpers/rsc-vite/server.js, integration/rsc/rsc-test.ts, packages/react-router/index-react-server-client.ts, packages/react-router/index-react-server.ts, packages/react-router/index.ts, packages/react-router/lib/context.ts, packages/react-router/lib/rsc/server.rsc.ts
chore: remove compression from integration test server to help streaming tests run smoother
=> fix: react-server Await component

.changeset/stale-rice-learn.md, packages/react-router-dev/config/default-rsc-entries/entry.rsc.tsx, playground/rsc-vite/src/entry.rsc.tsx
This PR adds same suggestion from https://github.com/remix-run/react-router-templates/pull/143. This should only affects how server module change causes re-evaluation of modules in rsc environment. Previously, any change would clear rsc environment module graph entirely (except externalized module which is in node's own module cache). With `import.meta.hot.accept`, this can be minimized to be only the modules from "entry" to "changed module" via import chain.
=> fix(rsc): add `import.meta.hot.accept` to rsc entry

integration/helpers/rsc-vite-framework/vite.config.ts, integration/helpers/vite.ts, integration/vite-plugin-order-validation-test.ts, packages/react-router-dev/package.json, packages/react-router-dev/vite/plugins/validate-plugin-order.ts, packages/react-router-dev/vite/rsc/plugin.ts, playground/rsc-vite-framework/package.json, playground/rsc-vite-framework/vite.config.ts, pnpm-lock.yaml
This changes our strategy from wrapping `@vitejs/plugin-rsc` to expecting it to be a peer dependency when using RSC Framework Mode.
=> Add `@vitejs/plugin-rsc` as optional peer dependency

packages/react-router-dev/vite/has-dependency.ts, packages/react-router-dev/vite/plugin.ts, packages/react-router-dev/vite/rsc/plugin.ts
This makes the following improvements:
- Adds `react-router/internal/react-server-client` to the list of optimised deps. This ensures you don't get a flash when Vite first encounters this import.
- Checks whether `react-router-dom` is an app dependency before adding it to the `resolve.dedupe` list to avoid warnings that this package is missing.
The code has also been refactored to share the `hasDependency` util between both Vite plugins.
=> Improve `optimizeDeps` in RSC Framework Mode

packages/react-router-dev/vite/rsc/plugin.ts
This ensures that changes to the file system result in updated route config, allowing routes to be added and removed while the dev server is running.
=> Handle route config changes in RSC Framework Mode

contributors.yml, docs/api/hooks/useNavigate.md
Description:
This PR fixes broken markdown link formatting in the useNavigate docs.
=> docs(useNavigate): fix broken markdown link to history api

docs/api/framework-conventions/react-router.config.ts.md
This PR fixes the code example of the `buildEnd` hook.
`serverBuildPath` doesn't currently exist.
=> docs: fix code example of buildEnd hook

.changeset/happy-hornets-judge.md, integration/error-boundary-v2-test.ts, integration/error-data-request-test.ts, packages/react-router/__tests__/server-runtime/server-test.ts, packages/react-router/lib/dom/ssr/single-fetch.tsx, packages/react-router/lib/rsc/browser.tsx, packages/react-router/lib/rsc/server.rsc.ts, packages/react-router/lib/rsc/server.ssr.tsx, packages/react-router/lib/server-runtime/server.ts
We lost this logic when we moved to single fetch (previously implemented [here](https://github.com/remix-run/remix/blob/v2/packages/remix-react/data.ts#L19) in v2)
This also removes the unused `X-Remix-Catch` and `X-Remix-Error` headers that are leftover from pre-single-fetch.
Closes: #14363
=> Avoid decoding CDN errors that never reached the origin server

integration/helpers/fixtures.ts, integration/package.json, integration/typegen-test.ts, pnpm-lock.yaml
I'm bringing over the [testing utils I created for react-router-templates](https://github.com/remix-run/react-router-templates/blob/main/.tests/utils.ts) which are mostly [Playwright fixtures](https://playwright.dev/docs/test-fixtures).
The goal is for end-to-end tests to stick as close to real user setups and workflows as possible while making correct, thorough tests ergonomic.
```ts
import getPort from "get-port"
import { test } from "./helpers/fixtures"
test("hello world", async ({ edit, $, page }) => {
await $("pnpm typecheck")
const port = await getPort()
const dev = $(`pnpm dev --port ${port}`)
await serverIsReady(dev, port)
await page.goto(`http://localhost:${port}`, { waitUntil: "networkidle" })
await edit({
"app/routes/_index.tsx": `
export default function HelloWorld() {
return …
```
=> better playwright fixtures: `cwd`, `edit`, `$`

contributors.yml, docs/api/components/Routes.md, packages/react-router/lib/components.tsx
Fix unclosed JSX tag in Route component example.
The Route component was missing the closing `/` which is required in JSX syntax.
=> fix(docs): correct unclosed Route tag in JSX example

.changeset/six-lobsters-think.md, integration/use-route-test.ts, packages/react-router-dev/typegen/generate.ts, packages/react-router/index.ts, packages/react-router/lib/hooks.tsx, packages/react-router/lib/types/register.ts
```tsx
export function AddToCart() {
const productRoute = useRoute("routes/product")
if (productRoute === undefined) throw new Error("Expected to be within product route")
const { loaderData, actionData } = productRoute
//          ^^^^^^^^^^^^^^^ these are now type-safe!
return <div>{/* ... */}</div>
}
```
=> unstable_useRoute
